Updates the covid 19 FSE ; add covid 19 activite partielle ; adds tes…
openfisca/openfisca-france pull request #1442
Opened 2020-09-28 08:30 UTC by pzuldp

…ts for 3 main covid 19 measures

* Évolution du système socio-fiscal | Changement mineur.
* Périodes concernées : jusqu'au 31/12/2020 | à partir du 01/03/2020
* Zones impactées : `openfisca-france/openfisca-france/model/covid19`, `openfisca-france/openfisca-france/parameters/covid19` et `openfisca-france/tests/covid19/`
* Détails :
  - Met à jour les mesures Covid 19 : le dispositif de Fonds de solidarité aux entreprises pour les indépendants / Ajoute l'indemnité d'activité partielle
  - Ajoute des tests pour trois mesures Covid 19 principales (FSE, AP et Aide exceptionnelle)
  - Affine l'éligibilité au FSE (prise en compte de la baisse de CA)

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2020-09-28 09:02 UTC, benjello requested changes
@pzuldp : j'ai fait des remarques de forme.
Je laisse @guillett regarder le fond.

2020-09-28 09:02 UTC, benjello commented on openfisca_france/model/covid19.py
> +        return elig*(delta_ca < 0)*((delta_ca < -plaf)*plaf + (delta_ca> -plaf)*(-delta_ca))
```suggestion
        return elig*(delta_ca < 0) * ((delta_ca < -plaf) * plaf + (delta_ca > -plaf) * (-delta_ca))
```

2020-09-28 09:02 UTC, benjello commented on openfisca_france/model/covid19.py
> +        return elig*(delta_ca < 0)*((delta_ca < -plaf)*plaf + (delta_ca> -plaf)*(-delta_ca))
Il faut gérer l'égalité aussi.

2020-09-28 09:02 UTC, benjello commented on openfisca_france/model/covid19.py
> +        salh = individu('salaire_de_base', period) / heures
Eviter les abréviations non contrôlées. Préférer les noms longs.

2020-10-01 13:49 UTC, pzuldp commented on openfisca_france/model/covid19.py
> +        salh = individu('salaire_de_base', period) / heures
changements effectués !

2020-10-01 13:50 UTC, pzuldp commented on openfisca_france/model/covid19.py
> +        salh = individu('salaire_de_base', period) / heures
cf https://github.com/openfisca/openfisca-france/pull/1442/commits/7d2aa7214f9a87ff86a0f2076e83de2654f7cc40

2020-10-01 14:08 UTC, benjello requested changes

2020-10-01 14:08 UTC, benjello commented on openfisca_france/model/covid19.py
> +        return eligibilite_activite_partielle*indemnite_horaire*heures
```suggestion
        return eligibilite_activite_partielle * indemnite_horaire * heures 
```

2020-10-01 14:17 UTC, benjello commented
@pzuldp : tu veux peut-être aussi ajouter cette aide dans l'agrégat prestations sociales, pour qu'elle se retrouve in fine dans le revenu disponible.

2020-10-01 14:18 UTC, benjello commented
@sandcha @guillett : preneur d'un regard hors de l'IPP pour ne pas être accuser d'unilatéralisme.

2020-10-01 14:20 UTC, guillett commented
Je vais regarder quand tu ne seras plus en « change requested » mais en OK.

2020-10-12 15:58 UTC, benjello approved these changes

2020-10-12 15:58 UTC, benjello commented
@guillett : your turn ?

2020-10-22 15:19 UTC, benjello approved these changes
Cela me paraît bien.

Sur le fond j'imagine que tu as bien vérifié que les auto-entrepreneurs sont bien éligibles à l'iade TPE.

2020-10-22 15:19 UTC, benjello commented on openfisca_france/model/covid19.py
> +        return individu('travailleur_non_salarie', period) * (((chiffre_d_affaire - chiffre_d_affaire_annee_n_1) / chiffre_d_affaire_annee_n_1) < -0.5)
Risque de division par zéro. Remonter le dénominateur.

2020-10-22 15:19 UTC, benjello commented on openfisca_france/model/covid19.py
> +        return max((rsa + ass + (al * af_nbenf)), (rsa_n_1 + ass_n_1 + (al_n_1 * af_nbenf_n_1)))
Comme c'est un "ou" je mettrais un plus plutôt qu'un max.

2020-10-22 15:19 UTC, benjello commented on openfisca_france/model/covid19.py
> +        return eligibilite_fse*(difference_chiffre_d_affaire < 0) * ((difference_chiffre_d_affaire < -plafond_fse) * plafond_fse + (difference_chiffre_d_affaire > -plafond_fse) * (-difference_chiffre
Pour être plus clair, je définirais même perte_chiffre_d_affaire = - min_(chiffre_d_affaire - chiffre_d_affaire_annee_n_1, 0) et j'utiliserai ce dernier dans le return

2020-10-22 15:20 UTC, benjello commented
@guillett : comme tu as initié cela, pourrais-tu jeter un oeil également sur les modifs apportées par @pzuldp. Merci !

2020-10-23 08:02 UTC, guillett reviewed
J'ai fait une première passe. J'ai même commencé des propositions de modifications dans
https://github.com/openfisca/openfisca-france/commit/304532a1b25cb75813cb8296372b491b9e6df27d

Je pense qu'il faut extraire le calcul du CA de référence. Ma version était très optimiste mais celle-là me parait très pessimiste (en ne prenant en compte que les CA N-1).

2020-10-23 08:02 UTC, guillett commented on openfisca_france/parameters/covid19.yaml
> +  plafond:
:warning:  Un tel changement nécessite une montée de version majeure.

2020-10-23 08:02 UTC, guillett commented on openfisca_france/model/covid19.py
> +        return individu('travailleur_non_salarie', period) * (((chiffre_d_affaire - chiffre_d_affaire_annee_n_1) / chiffre_d_affaire_annee_n_1) < -0.5)
L'article 2 du décret fait référence à une perste de 70% et non 50%. D'où vient le 50% dans la formule ?

2020-11-19 14:19 UTC, pzuldp commented on openfisca_france/model/covid19.py
> +        return individu('travailleur_non_salarie', period) * (((chiffre_d_affaire - chiffre_d_affaire_annee_n_1) / chiffre_d_affaire_annee_n_1) < -0.5)
non, l'article 2 du décret a été modifiée 2 jours après la publication de la version initiale, et le critère de perte de CA a été étabi à 50% contre 70% dans la version initiale  https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000041780634

2020-11-19 16:40 UTC, pzuldp commented on openfisca_france/model/covid19.py
> +        indemnite_horaire_nonplancher = parameters(period).covid19.indemnite_ap.taux * salaire_horaire
comme "nonplafonnée", mais avec un plancher plutôt qu'un plafond ?

2020-11-19 21:28 UTC, benjello commented on openfisca_france/model/covid19.py
> +        indemnite_horaire_nonplancher = parameters(period).covid19.indemnite_ap.taux * salaire_horaire
Pour éviter un nom un eu barabare, je propose plutôt ce qui suit 
```
indemnite_ap = parameters(period).covid19.indemnite_ap
indemnite_horaire = max(
    indemnite_horaire_ap.taux * salaire_horaire,
    indemnite_ap.plancher
    )

2020-11-19 21:29 UTC, benjello commented on openfisca_france/parameters/covid19.yaml
> +  plafond:
Mais en même temps c'est plus explicite. Faut-il pour cette raison éviter de renommer ?

2020-12-08 08:57 UTC, pzuldp commented on openfisca_france/model/covid19.py
> +        indemnite_horaire_nonplancher = parameters(period).covid19.indemnite_ap.taux * salaire_horaire
ok !

2020-12-08 08:57 UTC, pzuldp commented on openfisca_france/model/covid19.py
> +        indemnite_horaire_nonplancher = parameters(period).covid19.indemnite_ap.taux * salaire_horaire
je fais ça

2020-12-08 09:17 UTC, pzuldp commented on tests/covid19/fse.yaml
> +    covid_aide_exceptionnelle_tpe_montant : 0
done

2020-12-08 09:17 UTC, pzuldp commented on tests/covid19/aide_exceptionnelle.yaml
> +
done

2020-12-08 09:19 UTC, pzuldp commented on openfisca_france/parameters/covid19.yaml
> +       4.5
done

2020-12-08 09:20 UTC, pzuldp commented on openfisca_france/model/covid19.py
> -
done

2020-12-08 09:22 UTC, pzuldp commented on openfisca_france/model/covid19.py
> +        "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000041983045?r=D4toiqv7co"
done

2020-12-08 09:25 UTC, pzuldp commented
@guillett changements pris en compte merci !
pour les 70%/50% : 2 jours après le décret initial un nouveau décret a été publié qui passe bien le seuil à 50% contre 70% précédemment (https://www.legifrance.gouv.fr/eli/decret/2020/4/2/ECOI2008841D/jo/texte)

2020-12-17 14:34 UTC, bfabre01 commented
@guillett @pzuldp : il faut je pense vraiment merger cette PR. De ce que je comprends, @pzuldp a bien pris en compte toutes les modifs, et tout est ok sur le fond. Donc, on peut merger tel quel. Reste cette histoire de renommage de paramètre. Si cela est vraiment nécessaire, on peut merger en mettant un nouveau numéro de version au 1er niveau, car le nouveau nom du paramètre est beaucoup plus approprié à mon sens.
Est-ce ok pour tout le monde ? Il faudrait qu'on merge demain au plus tard.

2020-12-17 14:45 UTC, guillett commented on openfisca_france/parameters/covid19.yaml
> +  plafond:
Non non mais il faut faire la bonne montée de version.

2020-12-17 14:51 UTC, guillett commented
Je ne suis pas bloquant, c'est d'ailleurs pour ça que j'évite les request changes. Je n'ai pas regardé à nouveau le code en détail mais ça va dans la bonne direction donc ça me va. :)

2021-01-25 15:04 UTC, bfabre01 commented
@pzuldp @guillett @benjello : je viens de repasser sur cette PR et ai un certain nombre de remarques. J'ai fait notamment les modifs suivantes:
(1) corriger les tests qui ne passaient pas;
(2) compléter le calcul de l'aide exceptionnelle (notamment prise en compte des jeunes dans le dispositif); 
(3) inclure la 2ème aide exceptionnelle (celle de novembre);
(4) améliorer le calcul du FSE (sachant qu'on ne calcule ici que la première version du FSE).
Deux remarques à ce stade, avant de merger:
- @guillett : j'ai supprimé la variable `covid_aide_exceptionnelle_famille_eligibilite` , qui était un copié-collé d'une partie de la formule de `covid_aide_exceptionnelle_famille_montant`. Dis-moi si c'est bloquant pour toi.
- pour l'activité partielle, je propose de la supprimer simplement de cette PR. Là, l'activité partielle est calculée en prenant pour argument le nombre d'heures travaillées. Il faudrait un argument spécifique, qui est : quelle est le nombre d'heures pour lesquelles l'activité partielle est demandée. Sinon, on est dans une situation où le salarié perçoit son salaire et son allocation d'activité partielle au titre des mêmes heures. De plus, les écrêtements de CSG-CRDS associés au dispositif ne sont pas codés. Bref, cela demande un travail spécifique, qu'on a déjà fait sur taxipp, mais sur mesure (car exploitant des données via imputations et donc peu généralisables). Ça pourra faire l'objet d'une PR à part.
Etes-vous ok avec ça ? Si pas de retour d'ici demain soir, je merge.

2021-01-27 08:30 UTC, merged