Ajoute une première version des aides pour ESTIME
openfisca/openfisca-france pull request #1445
Opened 2020-10-01 14:48 UTC by guillett

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées :
  - `model/prestations/agepi.py`
  - `model/prestations/complement_aide_au_retour_emploi.py`
* Détails :
  - Ajout de l'aide à la garde d'enfants pour parent isolé (Agepi) au chômage
  - Ajout du complément d'Allocation chômage d'aide au retour à l'emploi (ARE) en cas de reprise d'activité salariée

Je vais faire une passe pour essayer d'ajouter des références :sweat_smile:

2020-12-13 21:13 UTC, benjello requested changes
Merci @guillett pour ces compléments.

Il y a plein de paramètres qui sont codés en dur qui doivent être rassemblés dans un fichier de paramètres.

2020-12-22 10:44 UTC, guillett commented
Merci @benjello pour ce retour. J'ai effecivement fait le choix de ne pas utiliser de fichier de paramètres par simplicité. L'objectif avec cette première version est de montrer que l'ajout de formules est facile. Les fichiers de paramètres me paraissent intéressants à partir du moment où les paramètres sont structurés ou évoluent dans le temps.

Cette première version te parait-elle vraiment non intégrable en l'état ? Merci.

2020-12-22 11:47 UTC, benjello commented
@guillett quelques éléments de réponse:
- @lauradelmas8 devrait rajouter le calcul des allocations chômage donc je pense que cela vaut le coup de structurer les paramètres.
- `temps_travail_semaine` peut me semble-t-il être calculée à partir du nombre d'heures (désolé je n'avais pas vu cela dans la première revue).

2021-03-09 16:07 UTC, guillett commented
@benjello j'ai supprimé le calcul du complément ARE étant donné que cela générerait trop de conflits / coordination avec @lauradelmas8. Est-ce que l'AGEPI te convient en l'état ?
Je voudrais intégrer à master les développements spécifiques de Mes Aides pour faciliter les itérations à venir.

2021-03-09 16:42 UTC, benjello reviewed
A priori ok à une petite remarque près

2021-03-09 16:42 UTC, benjello commented on openfisca_france/model/prestations/agepi.py
> +class agepi_temps_travail_semaine(Variable):
Est-ce nécessaire de calculer cette variable intermédiaire ?

2021-03-15 09:47 UTC, guillett commented on openfisca_france/model/prestations/agepi.py
> +class agepi_temps_travail_semaine(Variable):
Done

2021-03-15 09:49 UTC, benjello approved these changes

2021-03-15 09:49 UTC, merged

2021-03-15 09:51 UTC, benjello commented
Pardon @guillett : j'ai fusionné dans la foulée alors que cela te revenait.

2021-03-15 10:13 UTC, guillett commented
Ça ne va très bien ! Merci beaucoup !