Implémente une première version du dégrèvement de la taxe foncière
openfisca/openfisca-france pull request #1446
Opened 2020-10-01 16:00 UTC by guillett

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées : `model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py`.
* Détails :
  - Implémente une première version du dégrèvement de la taxe foncière

PR par dessus #1445

2021-03-15 11:07 UTC, benjello requested changes

2021-03-15 11:07 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +        return (15 < montant) * montant
Je mettrais ces deux paramètres en dur (.50 et 15) dans un fichier YAML

2021-03-15 11:08 UTC, benjello commented
@bfabre01 connaît le sujet, il est plus à même de te relire @guillett.

2021-03-16 15:46 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +    entity = FoyerFiscal
Pas sûr que cela soit la bonne entité. Une taxe foncière est associée à un logement normalement. A voir comment ça se répartit entre les foyers fiscaux s'il y en a plusieurs. Notamment lié à un de mes commentaires sur le RFR ci-après.

2021-03-16 15:47 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +class taxe_fonciere_degrevement(Variable):
Il faut préciser de quel dégrèvement il s'agit. Il y en a plusieurs.

2021-03-16 15:49 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +        ressources = foyer_fiscal('rfr', period)
Ça doit être le RFR de le l'année N-1. Car en N, on ne connait que celui-là.

2021-03-16 15:51 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +        montant = max_(0, tf_base - ressources * degrevement.pourcentage_reste_a_charge)
Il manque la condition de ressources !! Pour être éligible, il faut avoir des revenus < à un certain seuil. 
Il manque également la condition sur IFI = 0 en N-1 (tout est bien détaillé dans l'art. 1391 B ter du CGI.

2021-03-16 15:54 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +        return (degrevement.minimum < montant) * montant
Le dégrèvement est diminué du montant de la TFPB qui est associé à la hausse des taux depuis 2011. A voir si tu veux ajouter cette fonctionnalité qui peut être un peu compliquée. Si elle n'est pas codée, il faut le préciser dans la docstring.

2021-03-16 15:55 UTC, bfabre01 commented on openfisca_france/parameters/taxation_locale/taxe_fonciere/degrevement.yaml
> +pourcentage_reste_a_charge:
Il manque les références législatives

2021-03-16 15:56 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +    def formula(foyer_fiscal, period, parameters):
Si la première année pour laquelle tu souhaites coder ce dégrèvement est 2018 (première année pour laquelle tu as renseigné les paramètres), il faudrait je pense mettre formula_2018_01_01 partout, pour être explicite sur la période pour laquelle c'est codé.

2021-03-16 15:58 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +class taxe_fonciere_degrevement_montant(Variable):
Je ne comprends pas la signification de cette variable...

2021-03-16 16:02 UTC, bfabre01 commented on openfisca_france/model/prelevements_obligatoires/taxe_fonciere/taxe_fonciere.py
> +    value_type = float
En revanche, peut-être ajouter une variable de TFPB après application du dégrèvement

2021-03-16 16:05 UTC, bfabre01 requested changes
@guillett : mes commentaires sont le long du code.

2021-03-22 07:28 UTC, guillett commented
Merci beaucoup @bfabre01 pour ces retours. Étant donné que le travail restant sur cet ajout est plus important que je l'avais imaginé, je ne vais pas pouvoir m'y atteler tout de suite. Je laisse la PR ouverte pour le moment et j'essayerais d'y revenir courant avril. Encore merci !

2023-01-17 14:25 UTC, bfabre01 commented
@guillett : du coup, je pense qu'on peut fermer.

2023-01-17 14:25 UTC, closed without merging