Pull  msa aah asi
openfisca/openfisca-france pull request #1455
Opened 2020-10-23 14:36 UTC by sandcha

📍 Cette PR intègre les commits MSA de la branche `msa_fork_al_css_v1_7_1` concernant l'AAH et l'ASI.
Elle équivaut à l'intégration des commits suivants à `master` sans autre altération : 2c2978049492478359392d5f31683e31e744c7c5, 7a0f8179590b859dfd37869685452d9a838f1782 et pour l'ASI, 8ac181e14b58667fed545c162cee1f840c15b506.

---

* Évolution du système socio-fiscal.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : 
  - `openfisca_france/model/prestations/minima_sociaux/aah.py`
  - `openfisca_france/parameters/prestations/minima_sociaux/asi/`
  - `openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml`
* Détails :
  - AAH : met à jour la valeur par défaut de `aah_restriction_substantielle_durable_acces_emploi` et complète les tests.
  - ASI : met à jour les paramètres de montants et plafonds.

- - - -

Ces changements : 
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).

2020-10-23 15:53 UTC, benjello requested changes

2020-10-23 15:53 UTC, benjello commented on tests/formulas/aah_eligible.yaml
> +    une estriction substantielle et durable pour l'accès à l'emploi
```suggestion
    une restriction substantielle et durable pour l'accès à l'emploi
```

2020-10-23 15:53 UTC, benjello commented on tests/formulas/aah_eligible.yaml
> +    une estriction substantielle et durable pour l'accès à l'emploi
```suggestion
    une restriction substantielle et durable pour l'accès à l'emploi
```

2020-10-23 15:53 UTC, benjello commented on openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
> +    reference: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000020037365&dateTexte=29990101&categorieLien=cid
```suggestion
    reference: https://www.legifrance.gouv.fr/loda/id/JORFTEXT000041835211/2020-10-13/
```

2020-10-23 15:53 UTC, benjello commented on openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
> +    reference: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000020037365&dateTexte=29990101&categorieLien=cid
Je garderais la référence d'origine. Es-tu ok @guillet ?

2020-10-23 15:53 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
Un peu dangereux de changer une valeur par défaut. l faut uqe cela soit très bien mentionner dans la changelog.

2020-10-30 15:57 UTC, sandcha commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
C'est un changement effectivement non rétro-compatible ; c'est maintenant précisé dans le changelog. 
De plus, même si c'est un sujet plutôt spécifique, il me semble qu'il nécessite un bump majeur de numéro de version. Ok avec ça @benjello @maukoquiroga ?

> En tout cas, le changement de cette valeur par défaut à False me semble logique (les individus n'ayant par défaut pas de restriction d'accès à l'emploi).

2020-10-30 16:12 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
> +    reference: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000020037365&dateTexte=29990101&categorieLien=cid
Effectivement, à l'emploi du [lien proposé](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000020037365&dateTexte=29990101&categorieLien=cid) par @mtifarine, le site `legifrance` redirige vers [ce lien de 2016](https://www.legifrance.gouv.fr/codes/id/LEGIARTI000031781089/2016-01-01/) qui n'est pas adapté à la revalorisation 2020 du montant d'AAH.

L'ancien lien dont tu parles @benjello est plus juste ; voire, celui-ci qui mène directement à l'article : 
```suggestion
    reference: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000041835215
```

2020-10-30 16:34 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
Ok. @bfabre01 @pzuldp notez bien ce changement ...

2020-10-30 16:36 UTC, benjello commented
ok @sandcha on peut fusionner !

2020-11-03 22:04 UTC, maukoquiroga commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
Je n'ai pas d'avis quant à l'aspect métier de la chose, mais c'est effectivement un bump de version majeur :)

2020-11-03 22:05 UTC, maukoquiroga commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
En particulier je ne suis pas à l'aise avec le fait que ce changement se fasse en même temps que les revalorisations qui, elles, sont juste un bump patch.

2020-11-03 22:09 UTC, maukoquiroga requested changes
Hello ! Merci infiniment @sandcha.

Pour respecter au plus possible l'atomicité des changements, je préfère que l'on sépare ef8744553d5fc66bb41015fb38031713b0e5595b du reste, car ce sont deux changements avec des impacts très différents (non rétro-compatible, et juste une valorisation).

2020-11-04 07:09 UTC, guillett commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
Désolé, je ne sais plus pourquoi j'avais fait ce choix. En y repensant un peu, cette variable est principalement utile pour les personnes en situation de handicap et plus précisément les personnes avec un 50% < taux d'incapacité < 80%. Pour ces personnes il faut avoir une RSDAE pour être éligible à l'AAH. Avec cette valeur par défaut, on "facilite" l'éligibilité de cette population à l'AAH.


Cela étant dit, OK pour modifier la valeur par défaut plus habituelle. Je rejoins @maukoquiroga  sur la séparation d'une telle modification si ça avance. Par contre, je suis curieux du message de @benjello 
> @bfabre01 @pzuldp notez bien ce changement ...
Vous utilisez cette valeur par défaut côté IPP ? :) (Les usages IPP, PNDS, MA, etc. sont de bonnes sources d'infos pour évaluer la pertinence de la valeur par défaut).

2020-11-04 16:01 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
@guillett : on n'a pas les données pour savoir si les gens ont une RDSAE. Donc on préfère tous les mettre en RDSAE (l'ancien défaut). Et si la valuer par défaut change il faut en tenir compte en aval côté TAXIPP car sinon o nva avoir une perte d'AHH inexpliquée.

2020-11-04 16:04 UTC, guillett commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
OK, donc la valeur de défaut choisie avait du sens :) Merci

2021-03-25 20:06 UTC, maukoquiroga commented
Hello @sandcha ! Je replonge sur ce _pull request_, est-tu d'accord avec la stratégie proposée de couper la poire en deux ? À disposition si je peux aider.

2021-03-25 21:43 UTC, maukoquiroga commented
Au temps pour moi je n'avais pas vu #1459

2021-06-18 19:58 UTC, sandcha commented
Du temps s'étant écoulé et #1459 ayant été mergée, je vous propose de rebaser afin d'identifier les éléments restants de cette PR (mais ceci perturbera la branche que vous avez en local).

2021-06-22 18:10 UTC, sandcha commented
Rebase en cours.

2021-06-22 18:24 UTC, sandcha commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
@MattiSG La situation évoquée dans la discussion ci-dessus est un autre exemple de choix de modélisation à trancher : choisissons-nous une valeur par défaut de `aah_restriction_substantielle_durable_acces_emploi ` à True afin d'éviter des pertes d'`aah_eligible` ? 
Ce serait probablement la valeur par défaut la plus neutre sachant qu'`aah_restriction_substantielle_durable_acces_emploi` n'a pas d'autre emploi dans le modèle et, de par son nom, elle est contextualisée `AAH`.

2021-06-23 08:19 UTC, MattiSG commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
Merci @sandcha d'attirer mon attention sur ce sujet. J'ajoute la manière de définir des valeurs par défaut à la liste des éléments sur lesquels des lignes directrices seraient bienvenues 🙂

2023-03-01 15:10 UTC, benjello commented
@sandcha : finalement, il ne reste que des tests (et une valeur par défaut qu'il ne faut pas changer à mon avis) à conserver de cette PR semble-t-il ?

Pourrais-tu rebaser et voir si on la conserve telle quelle ?

cc @clallemand @DorineLam

2023-06-27 14:23 UTC, benjello commented on CHANGELOG.md
> +  - `parameters/prestations/minima_sociaux/aah/montant.yaml`
Ne me semble pas être modifié ici.

2023-06-27 14:23 UTC, benjello commented on CHANGELOG.md
> +  - ASI : met à jour les paramètres de montants et plafonds.
Ne me semble pas être fait dans cette PR

2023-10-02 15:16 UTC, robinguill commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
Bonjour, je déterre un sujet pour voir ce qu'on peut faire de cette PR. Du coup une ligne directrice sur les valeurs pour les booléens d'éligibilité comme celui ci  a-t-elle été prise ? 🙂

2023-10-02 15:35 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +    default_value = False
Pour respecter le principe de moindre surprise, il vaut mieux que les valeurs par défaut soit les valeurs par défaut des types. Et il faut que la valeur par défaut soit le cas le plus courant, donc plutôt `True` ici. 

Mais cela reste un simple avis.

2023-10-03 12:56 UTC, robinguill commented
Je ferme la PR et supprime la branche. Le changement de valeur par défaut n'est pas accepté.

2023-10-03 12:56 UTC, closed without merging