Revalorisation des paramètres RLS pour janvier et octobre 2020
openfisca/openfisca-france pull request #1456
Opened 2020-10-23 15:00 UTC by sandcha

📍 Cette PR intègre les commits MSA de la branche `msa_fork_al_css_v1_7_1` concernant le dispositif de réduction de loyer de solidarité (RLS). Elle équivaut à l'intégration du commit 1463766e5cce5df0e6c921b5e5b85f9af334af4d  à `master` sans autre altération.
Noter qu'il s'agit aussi à ce jour du dernier commit (le plus récent) de `msa_fork_al_css_v1_7_1`.

---

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2020.
* Zones impactées : `openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/`.
* Détails :
  - Mise à jour des montants de réduction de loyer de solidarité (RLS) pour janvier et octobre 2020.

- - - -

Ces changements :

- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).

2020-10-23 15:57 UTC, benjello requested changes
Manque les références législatives pour vérifier.

2020-10-27 22:24 UTC, maukoquiroga requested changes
@benjello Voilà

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/couples.yaml
> +    value: 41.13
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 41.13
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
> +    value: 67.46
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 67.46
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
> +    value: 9.78
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 9.78
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
> +    value: 49.50
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 49.50
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
> +    value: 52.79
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 52.79
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
> +    value: 59.40
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 59.40
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
> +    value: 8.65
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 8.65
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
> +    value: 43.14
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 43.14
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
> +    value: 49.01
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 49.01
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
> +    value: 54.95
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 54.95
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
> +    value: 7.87
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 7.87
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml
> +    value: 40.43
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2019/12/31/LOGL1934007A/jo/texte
    value: 40.43
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/personnes_seules.yaml
> +    value: 27.85
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 27.85
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/majoration_par_pac_supp.yaml
> +    value: 5.42
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 5.42
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/famille_1pac.yaml
> +    value: 37.85
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 37.85
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_3/couples.yaml
> +    value: 33.76
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 33.76
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/personnes_seules.yaml
> +    value: 29.72
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 29.72
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/majoration_par_pac_supp.yaml
> +    value: 5.96
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 5.96
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/famille_1pac.yaml
> +    value: 40.92
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 40.92
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_2/couples.yaml
> +    value: 36.37
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 36.37
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/personnes_seules.yaml
> +    value: 34.10
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 34.10
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/majoration_par_pac_supp.yaml
> +    value: 6.74
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 6.74
```

2020-10-27 22:24 UTC, maukoquiroga commented on openfisca_france/parameters/prestations/reduction_loyer_solidarite/montant/par_zone/zone_1/famille_1pac.yaml
> +    value: 46.47
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/9/30/LOGL2020748A/jo/texte
    value: 46.47
```

2020-10-28 10:26 UTC, benjello approved these changes

2020-10-28 10:42 UTC, benjello approved these changes

2020-10-28 10:43 UTC, benjello commented
@maukoquiroga @sandcha : we are good to go !

2020-10-28 12:54 UTC, maukoquiroga approved these changes

2020-10-28 18:05 UTC, sandcha commented
Merci @benjello @maukoquiroga !
@mtifarine @frtomas Merge à `master` en cours.

2020-10-28 18:19 UTC, merged