Met à jour libellés et références de paramètres des AL
openfisca/openfisca-france pull request #1460
Opened 2020-11-05 21:52 UTC by sandcha

Connected to #1451 

📍 Cette PR intègre les commits MSA de la branche `msa_fork_al_css_v1_7_1` concernant les revalorisations de paramètres d'AL. Elle équivaut à l'intégration des commits mettant à jour les paramètres seuls dans le draft de PR #1451. 
Puis, le diff a été fait avec ce qui a été intégré par PR #1451.

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2019.
* Zones impactées : 
  - `parameters/prestations/aides_logement/R0/`
  - `parameters/prestations/aides_logement/al_charge/personne_isolee_ou_menage_seul/`
  - `parameters/prestations/aides_logement/forfait_charges/`
  - `parameters/prestations/aides_logement/loyers_plafond/par_zone/`
  - `parameters/prestations/aides_logement/participation_min/montant_forfaitaire.yaml`
  - `parameters/prestations/al_etudiant/`
  - `parameters/prestations/al_plafonds_logement_foyer/conventionne/`
* Détails :
  - Met à jour libellés et références de paramètres des aides au logement.

- - - -

Ces changements :

- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2020-11-05 21:53 UTC, sandcha commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/personnes_seules.yaml
> +    value: 258.69
```suggestion
    value: 258.69

```

2020-11-05 22:23 UTC, sandcha commented on openfisca_france/parameters/prestations/aides_logement/R0/taux3pac.yaml
> +    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/1/3/LOGL1934006A/jo/article_1
```suggestion
    reference: https://www.legifrance.gouv.fr/eli/arrete/2020/1/3/LOGL1934006A/jo/article_1

```

2020-11-06 13:54 UTC, benjello requested changes
Il manque des références législatives (que je n'ai pas cherchées).
Mais surtout il y a un nouveau fichier de paramètres sans références législatives et je ne sais pas où il sert donc s'il faut l'inclure dans cette PR.

2020-11-06 13:54 UTC, benjello commented on openfisca_france/parameters/prestations/al_assistant_journaliste/abattement.yaml
> +          value: 1195
C'est un nouveau fichier. mais on ne comprend pas si le paramètre débute en 2019 où s'il existait avant. Et pas de référence législative non plus ...

2020-11-06 13:54 UTC, benjello commented on openfisca_france/parameters/prestations/al_etudiant/autres_dont_les_etudiants_en_chambres_rehabilitees_de_residences_universitaires/menages.yaml
> +    value: 263.29
Manque référence législative

2020-11-06 13:54 UTC, benjello commented on openfisca_france/parameters/prestations/al_etudiant/autres_dont_les_etudiants_en_chambres_rehabilitees_de_residences_universitaires/personnes_isolees.yaml
> +    value: 169.41
Manque référence législative

2020-11-06 13:54 UTC, benjello commented on openfisca_france/parameters/prestations/al_etudiant/loyer_considere_comme_paye_par_les_etudiants_logeant_en_residence_universitaire/menages.yaml
> +    value: 130.45
Manque référence législative

2020-11-06 13:54 UTC, benjello commented on openfisca_france/parameters/prestations/al_etudiant/loyer_considere_comme_paye_par_les_etudiants_logeant_en_residence_universitaire/personnes_isolees.yaml
> +    value: 83.79
Manque référence législative

2020-11-30 17:46 UTC, sandcha commented on openfisca_france/parameters/prestations/aides_logement/forfait_charges/cas_general.yaml
> +    value: 53.99
> Le descriptif de ce paramètre me paraît ambigu : `Cas général - isolé ou couple`
En particulier, ce paramètre était-il couvre-t-il bien le cas isolé ? Ou le couvrait-il dans le passé ?

> Si ce n'est pas le cas, il me semble que son descriptif pousse à confusion avec le paramètre `prestations.aides_logement.al_charge.personne_isolee_ou_menage_seul.cas_des_colocataires_ou_des_proprietaires_1` pour lequel nous avons des valeurs toutes aussi anciennes et qui dans la loi cible les `bénéficiaires isolés` (c'est du moins le cas pour 2019 et 2020).

> Ces deux paramètres sont indiqués dans le même tableau en [2019](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000039160757/2019-10-08) et [2020](https://www.legifrance.gouv.fr/loda/id/LEGIARTI000042378438/2020-10-01)

2020-11-30 18:45 UTC, sandcha commented on openfisca_france/parameters/prestations/al_assistant_journaliste/abattement.yaml
> +          value: 1195
Effectivement. Références en cours de recherche ; néanmoins, ces paramètres prendront plus sens s'ils sont conservés dans la PR contenant les formules spécifiques aux assistants journalistes. Je supprime donc ce fichier de cette PR.

> Deux remarques pour plus tard : 
> * Le répertoire semble mal nommé car les paramètres du fichier comprennent aussi le cas de l'assistance maternelle/familiale.
> * Une référence au montant de `1195€` existe dans ce fichier [ecologie.gouv.fr](https://www.ecologie.gouv.fr/sites/default/files/Dossier%20de%20presse%20APL.pdf) qui, page 10, dit : 
> ```
> Assistants familiaux et maternels
> Les assistants familiaux et maternels bénéficient d’un régime d’imposition favorable. Sa prise en compte est maintenue pour le calcul de l’aide au logement.
> Dans le cas où cet abattement n’aurait pas été transmis, un abattement forfaitaire de 1195 € mensuel sera appliqué aux revenus des assistants familiaux et maternels. Ce montant peut être révisé à la suite d'une déclaration spontanée du bénéficiaire.
> ```

2020-11-30 19:03 UTC, sandcha commented on openfisca_france/parameters/prestations/al_etudiant/autres_dont_les_etudiants_en_chambres_rehabilitees_de_residences_universitaires/menages.yaml
> +    value: 263.29
Références ajoutées pour 2019 et 2020.
Toutefois, legifrance n'indique pas d'historique antérieur à 2019 pour cet article alors que les montants et public visé me semblent compatibles. Qu'en penses-tu @benjello ? 
Est-ce le public visé qui a changé ? Est-ce qu'on définit un autre paramètre si c'est le cas ? 🤔

2020-11-30 19:05 UTC, sandcha commented on openfisca_france/parameters/prestations/al_etudiant/autres_dont_les_etudiants_en_chambres_rehabilitees_de_residences_universitaires/personnes_isolees.yaml
> +    value: 169.41
De même : références ajoutées mais sur la base d'un texte qui, dans legifrance, n'a pas d'historique antérieur à 2019.

2020-11-30 19:09 UTC, sandcha commented on openfisca_france/parameters/prestations/al_etudiant/loyer_considere_comme_paye_par_les_etudiants_logeant_en_residence_universitaire/menages.yaml
> +    value: 130.45
De même : ref ajoutées mais même doute sur la correspondance de paramètre dans le temps.

2020-11-30 19:09 UTC, sandcha commented on openfisca_france/parameters/prestations/al_etudiant/loyer_considere_comme_paye_par_les_etudiants_logeant_en_residence_universitaire/personnes_isolees.yaml
> +    value: 83.79
De même : ref ajoutées mais même doute sur la correspondance de paramètre dans le temps.

2021-06-02 19:38 UTC, sandcha commented
Rebase en cours afin de vérifier si cette PR contient encore des éléments après l'intégration de la PR #1451

2021-06-02 19:42 UTC, sandcha commented
PR prête à la re-revue. Elle est nettement amaigrie et contient désormais essentiellement des ajouts de références et des mises à jour de libellés de paramètres. cc @benjello

2021-06-02 19:57 UTC, benjello requested changes

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/al_charge/personne_isolee_ou_menage_seul/cas_des_colocataires_ou_des_proprietaires_1.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378438/2020-10-01
Doublon de référence

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/forfait_charges/majoration_par_enfant.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378438/2020-10-01
Doublon de référence

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/couples.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
Doublon de référence

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/majoration_par_enf_supp.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/personnes_seules.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_1/un_enfant.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/couples.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/participation_min/montant_forfaitaire.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378442
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/un_enfant.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/personnes_seules.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
odem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/majoration_par_enf_supp.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_3/couples.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/un_enfant.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/personnes_seules.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 19:57 UTC, benjello commented on openfisca_france/parameters/prestations/aides_logement/loyers_plafond/par_zone/zone_2/majoration_par_enf_supp.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378448/2021-01-02
idem

2021-06-02 21:41 UTC, sandcha commented on openfisca_france/parameters/prestations/aides_logement/forfait_charges/majoration_par_enfant.yaml
>      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000042378438/2020-10-01
😳 Pardon, corrigé après parcours de tous les fichiers de la PR.
> Le rebase s'était passé sans erreur sur ces fichiers 😅

2021-06-02 21:46 UTC, sandcha commented on openfisca_france/parameters/prestations/al_assistant_journaliste/abattement.yaml
> +          value: 1195
Ces paramètres ont été ajoutés par une autre PR (sans références législatives 😬). 
J'annule la suppression du fichier qui ouvrirait alors un sujet parce que les paramètres sont utilisés par des calculs (comme pour la variable `journaliste` et cette [erreur](https://app.circleci.com/pipelines/github/openfisca/openfisca-france/1056/workflows/49460c10-0102-425f-80ca-8e62127fa92d/jobs/14248) de CI si on le supprimait).

2021-06-02 22:56 UTC, benjello approved these changes

2021-06-02 22:57 UTC, benjello commented
@openfisca/france-contrib-ipp vous avez peut-être un avis.

2021-06-03 16:57 UTC, sandcha commented
Merci ! Intégration en cours.

2021-06-18 19:36 UTC, sandcha commented
Rebase en cours.

2021-06-18 19:48 UTC, merged