Corrige et met à jour des barèmes et formules de prélèvements sociaux
openfisca/openfisca-france pull request #1469
Opened 2020-12-18 13:06 UTC by SophieIPP

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py`, `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py`, `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py`
* Détails :
  - Met à jour, complète et corrige les barèmes de certains prélèvements sociaux : CSG sur revenus de remplacement, cotisation maladie Alsace-Moselle, cotisation famille, cotisation accident (taux faible), seuils de RFR pour taux réduits
  - Corrige les formules de CSG sur revenus de remplacement pour prendre en compte la création d'un taux médian pour la CSG sur pensions de retraite
  - Ajoute la création du taux réduit de cotisation maladie en 2019 (bascule du CICE en baisse de cotisation employeur)

- - - -

Ces changements :

- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).

2020-12-18 13:07 UTC, SophieIPP commented
@benjello je ne suis pas sûre de comment augmenter le numéro de version, d'autant que le changelog, malgré un rebase, n'est pas à jour sur ma branche... Je ne l'ai donc pas modifié. Tu peux m'aider ?

2020-12-18 13:49 UTC, benjello requested changes

2020-12-18 13:49 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions/csg/retraite/imposable/taux_reduit.yaml
> +description: taux de la CSG imposableunit: /1values:  1997-01-01:    value: 0.0
Problème de retour à la ligne.

2020-12-18 13:49 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions/csg/seuils_taux/demi_part_suppl_seuil_1.yaml
> +reference: https://www.ipp.eu/outils/baremes-ipp/unit: currencyvalues:  2015-01-01:    value: 2839.0  2016-01-01:    value: 2850.0  2017-01-01:    value: 2936.0  2018-01-01:    value: 2942.
Problème de retour à la ligne.

2020-12-18 13:49 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions/csg/seuils_taux/demi_part_suppl_seuil_3.yaml
> +reference: https://www.ipp.eu/outils/baremes-ipp/unit: currencyvalues:  2019-01-01:    value: 6028.0  2020-01-01:    value: 6124.0
Problème de retour à la ligne.

2020-12-18 13:49 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions/csg/seuils_taux/seuil_de_rfr_3.yaml
> +reference: https://www.ipp.eu/outils/baremes-ipp/unit: currencyvalues:  2019-01-01:    value: 22580.0  2020-01-01:    value: 22941.0
Problème de retour à la ligne.

2020-12-18 13:49 UTC, benjello commented on tests/formulas/allegement_cotisation_maladie.yaml
> +- period: 2019-01  name: 1xSMIC  relative_error_margin: 0.001  input:    salaire_de_base: 1521.22    # allegement mode necessary when requesting on a 1 month salary :    allegement_cotisation_m
Problème de retour à la ligne.

2020-12-18 13:49 UTC, benjello commented on tests/formulas/chomage_employeur.yaml
> +- period: 2018-01  name: Cotisation de chômage employeur  relative_error_margin: 0.001  input:    salaire_de_base: 1500  output:    chomage_employeur: -0.0405 * 1500
Problème de retour à la ligne.

2020-12-18 13:49 UTC, benjello commented on tests/formulas/csg_remplacement.yaml
> +- name: Retraite Exoneration  period: 2020-01  input:    retraite_brute: 2000.0    rfr:       2018:         10000.0  output:    csg_imposable_retraite: 0*2000    csg_deductible_retraite: 0*2
Problème de retour à la ligne.

2020-12-18 13:50 UTC, benjello commented
@SophieIPP : ce n'est pas un rebase mais un merge que tu as fait.

2020-12-18 13:54 UTC, benjello commented
@SophieIPP : j'ai rebasé ta branche `cotisation-fix` sur `master` dans une branche `cotisation-fix-bis`. Vérifie qu'elle a bien les commits que tu as intégré et je pourrais la force-push sur `cotisation-fix`.

2021-08-03 13:39 UTC, closed without merging

2021-08-03 13:40 UTC, SophieIPP commented
Résolu par la PR !1595