Init single entity parallel axes
openfisca/openfisca-france pull request #1470
Opened 2021-01-11 12:44 UTC by benjello

* Évolution du système socio-fiscal. Changement mineur.
* Périodes concernées : aucune.
* Zones impactées : aucune.
* Détails :
  - Ajout d'un test pour inti_single_entity d'initialisation de scénarios 
- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2021-01-18 08:59 UTC, benjello commented
@sandcha : j'aimerais bien merger cela rapidement ;-)

2021-01-22 19:56 UTC, sandcha commented on tests/test_basics.py
> +def test_init_single_entity_parallel_axes():
Ce test n'est-il pas redondant dans un contexte où nous économisons sur un temps de test déjà conséquent ? Si on le supprime, mettre à jour le changelog en conséquence. 

Quel cas as-tu identifié qui ne soit pas déjà couvert par Core ? 🤔 
S'il s'agit aussi d'expliciter la vérification d`init_single_entity`, le déplacer dans un nouveau fichier `test_scenarios.py` ? 

---

Ce test me semble redondant avec les tests actuels  parce que : 

* Le fonctionnement d'`init_single_entity` est indirectement vérifié dans `tests/test_coefficient.py` et, pour les axes, dans `tests/test_tax_rates.py`.
* Les axes parallèles sont maintenant testés dans Core grâce à openfisca/openfisca-core#968. 🙂 
* Si l'on veut tester la spécificité des axes parallèles appliqués à openfisca-france, cela me semble non applicable parce que la gestion des axes parallèle me paraît être dans `expand_axes` (Core, scenario.py) qui n'est pas appelée par `init_single_entity` (France, scenarios.py) et donc la spécificité des axes parallèles ne me paraît pas sensible au modèle du pays. `expand_axes` est plutôt appelé dans le `new_simulation` de ce test. Alors, le titre de ce test d'intégration est ambigu.

2021-01-22 23:31 UTC, sandcha requested changes

2021-01-22 23:31 UTC, sandcha commented on tests/test_basics.py
> +    indexes = [0, 1]
```suggestion
    indexes = [0, 1, 2]
```

2021-01-22 23:31 UTC, sandcha commented on tests/test_basics.py
> +        parent2 = dict(age = 40),
```suggestion
        parent2 = dict(age = 40),
        enfants = [dict(age = 20)],
```

2021-01-22 23:31 UTC, sandcha commented on tests/test_basics.py
> +    assert simulation.calculate_add('salaire_de_base', year) == pytest.approx([0, 0, 7500, 7500, 15000, 15000])
```suggestion
    assert simulation.calculate_add('salaire_de_base', year) == pytest.approx([0, 0, 0, 7500, 7500, 7500, 15000, 15000, 15000])
```

2021-01-22 23:31 UTC, sandcha commented on tests/test_basics.py
> +def test_init_single_entity_parallel_axes():
Après vérification de la couverture de tests, je te propose d'amender ce test-ci comme proposé plus bas afin qu'il apporte une différence et de l'extraire dans un fichier `test_scenarios.py`.

En effet, en l'état, ce test ne change pas la couverture :

Avec la librairie `coverage` en v`5.3.1`, et après avoir exécuté les commandes suivantes : 
```shell
coverage run -m pytest tests/test_*
coverage report -m | grep openfisca_france/scenarios.py
``` 
(où l'environnement virtuel est configuré pour que le module de pays pris automatiquement soit `openfisca-france`), les branches `master` et celle-ci renvoient ce résultat : 
```
openfisca_france/scenarios.py                            42      3    93%   38-40
```
où 38-40 correspondent aux lignes posant problème.

Après modification du test pour atteindre les lignes 38-40, nous obtienderions ceci : 
```
openfisca_france/scenarios.py                           42      0   100%
```

2021-01-23 10:53 UTC, sandcha commented on CHANGELOG.md
> +  - Ajout d'un test pour l'initialisation de scénarios avec des axes parallèles pour tenir compte de openfisca/openfisca-core#968
@benjello Oubli ou choix de ne pas l'intégrer ?

2021-01-23 14:52 UTC, sandcha approved these changes
Merci @benjello !
~~Merge en cours.~~

2021-01-23 15:01 UTC, sandcha commented
Le merge va attendre un peu plus de temps que prévu : il y a une maintenance en cours sur CircleCI.
➡️ [status](https://status.circleci.com).

2021-01-24 21:25 UTC, merged

2021-01-24 21:25 UTC, benjello commented
@sandcha : je me suis permis de merger.