Ajoute l'éligibilité à l'aide mobili-jeune
openfisca/openfisca-france pull request #1492
Opened 2021-03-22 21:17 UTC by sandcha

* Évolution du système socio-fiscal. 
* Périodes concernées : à partir du 01/07/2012.
* Zones impactées : 
  - `model/base.py`
  - `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/alternance.py` 🆕 
  - `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py`
  - `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py`
  - `model/prestations/mobili_jeune.py` 🆕 
  - `parameters/prestations/mobili_jeune.yaml` 🆕 
* Détails :
  - Ajoute l'éligibilité à l'aide mobile-jeune qui subventionne une partie du loyer pour les jeunes en apprentissage.

- - - -

Informations complémentaires : 

* Principales références : 
  - https://www.actionlogement.fr/l-aide-mobili-jeune
  - https://www.service-public.fr/particuliers/vosdroits/F33173
 
* Simulateur existant : https://mobilijeune.actionlogement.fr/connexion

* Conditions non modélisées : 
  - Non cumul de l'aide
  - Conditions citées en documentation de la variable

- - - -

Ces changements :

- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2021-03-22 21:18 UTC, sandcha commented on openfisca_france/model/base.py
> +    non_agricole = 'Non agricole'
> Un peu cavalier pour les autres activités mais c'est tout ce dont nous avons besoin.

2021-03-22 21:18 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py
> +    reference = "https://www.legifrance.gouv.fr/codes/id/LEGIARTI000031088014/2016-01-01/"
> Lien remplacé parce que KO.

2021-03-22 21:20 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py
> +        rsa = individu.famille('rsa', period)
> Peu rassurant sur l'état de la variable `prefessionnalisation`. A priori, ce serait une input value pour la simulation de mobili-jeune (la formule ne serait pas appelée).

2021-03-22 21:21 UTC, sandcha commented on openfisca_france/model/prestations/mobili_jeune.py
> +    def formula_2012_07(individu, period, parameters):
> Date discutable : déduite de ce [communiqué de presse](http://www.cfau.fr/telecharger-documents/Dossier%20de%20presse%20Mobili-Jeune.pdf).

2021-03-22 21:22 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py
> +class qualifie(Variable):
> Ajoutée afin d'éviter une erreur de variable manquante dans `remuneration_professionnalisation` ci-dessous. De même, peu rassurant sur l'état de la formule de `remuneration_professionnalisation` mais ne devrait pas poser problème pour mobili-jeune qui l'aurait en input variable.

2021-03-22 21:22 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py
> +        qualifie = individu('qualifie', period)
😿

2021-03-22 21:25 UTC, sandcha commented on openfisca_france/model/prestations/mobili_jeune.py
> +                individu("secteur_activite_employeur", period) == TypesSecteurActivite.non_agricole
> `non_agricole`, en tant que valeur d'énuméré, pourrait avoir la vie courte et on pourrait souhaiter de vérifier l'inverse d'`agricole`.

2021-03-22 21:26 UTC, sandcha commented on openfisca_france/model/prestations/mobili_jeune.py
> +            individu("categorie_salarie", period) == TypesCategorieSalarie.prive_non_cadre
> Suppose qu'on ne peut pas être apprenti et [prive_cadre](https://fr.openfisca.org/legislation/categorie_salarie) mais est-ce bien vrai ? 🤔

2021-03-22 21:30 UTC, sandcha commented on openfisca_france/model/prestations/mobili_jeune.py
> +            )
> Inspiré de la phrase de [service-public](https://www.service-public.fr/particuliers/vosdroits/F33173) (semblant plus précise qu'actionlogement.fr) disant : 
"Être en formation en alternance sous **contrat d'apprentissage** ou sous **contrat de professionnalisation** dans une entreprise du secteur privé non agricole"

2021-03-22 21:34 UTC, sandcha commented on openfisca_france/model/prestations/mobili_jeune.py
> +        condition_employeur = secteur_prive_non_agricole * individu("peec_employeur", period)
La condition de PEEC est issue de service-public : 
"Être dans une entreprise cotisant au dispositif dit 1 % logement (c'est le cas de toutes les entreprises de 20 salariés et plus)" mais j'ai vu après qu'elle est absente de la [page d'action logement.fr](https://www.actionlogement.fr/l-aide-mobili-jeune). 
1) La conservons-nous ?
2) Si nous la supprimons, gardons-nous la variable `peec_employeur` dans le modèle ? (on s'attache si vite)

2021-03-22 21:37 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
> +
> Un doute subsiste quant au bon fichier où placer les variables qui suivent.

2021-03-22 21:44 UTC, sandcha commented
Note : Les tests passent en local. Je soupçonne que nous ayons encore un problème de cache CircleCI.

2021-03-23 07:19 UTC, guillett requested changes
Merci beaucoup @sandcha !

J'ai, pour le moment, mis un _request changes_ car je préférerai que la logique soit répartie dans plusieurs variables pour faciliter la relecture et les investigations. La complexité des tests rédigés est aussi, selon moi, un signal d'une trop grosse complexité regroupée au même endroit.

Dans un premier temps, il me semble important de, a minima, extraire la condition liée à l'entreprise et au contrat avec l'entreprise `condition_employeur`. En effet, dans une première version du simulateur, je pense qu'il est préférable de ne pas demander ces informations là et de considérer cette condition remplie. Avec la condition extraite dans une variable, c'est une seule variable à mettre à `True` sans cette condition extraite, il en faut plusieurs.

2021-03-23 07:19 UTC, guillett commented on openfisca_france/model/base.py
> +    __order__ = 'non_renseigne agricole non_agricole'  # Needed to preserve the enum order in Python 2
> # Needed to preserve the enum order in Python 2

OpenFisca est-il encore fonctionnel en Python 2 ?

2021-03-23 07:19 UTC, guillett commented on openfisca_france/model/prestations/mobili_jeune.py
> +        condition_employeur = secteur_prive_non_agricole * individu("peec_employeur", period)
Dans une première version du simulateur, je pense qu'on ne va pas demander les informations associées à l'employeur.

2021-03-23 07:19 UTC, guillett commented on openfisca_france/model/prestations/mobili_jeune.py
> +            )
Existe-t-il d'autres contrats en alternance ? Pole Emploi [ne décrit que](https://www.pole-emploi.fr/employeur/lessentiel-pour-embaucher/alternance--des-infos-pour-se-la/les-contrats-en-alternance--mode.html) c'est deux types là. Cela pourrait simplifié la formule.

2021-03-24 11:04 UTC, guillett commented on openfisca_france/model/prestations/mobili_jeune.py
> +            * individu("remuneration_professionnalisation", period)
Je pense que c'est un `+` qui faudrait à la place.

2021-03-24 11:05 UTC, guillett commented on openfisca_france/model/prestations/mobili_jeune.py
> +            * individu("remuneration_professionnalisation", period)
```suggestion
            + individu("remuneration_professionnalisation", period)
```
:sweat_smile:

2021-03-24 11:07 UTC, guillett commented on openfisca_france/model/prestations/mobili_jeune.py
> +            * individu("remuneration_professionnalisation", period)
De plus je me demande si l'on peut faire confiance à ces variables de rémunération qui sont probablement des minimums et pas des salaires obligatoires.

J'externaliserais le calcul de la rémunération et je ferais plutôt référence au `salaire_brut`.

2021-03-27 12:38 UTC, sandcha commented
Rebase en cours (sachant que le rebase en cours de revue a été évoqué ensemble / slack).

2021-03-27 13:23 UTC, sandcha commented on openfisca_france/model/prestations/mobili_jeune.py
> +            * individu("remuneration_professionnalisation", period)
`salaire_de_base` pris en compte.
En notant que la rémunération des apprentis bénéficie de conditions particulières ([impôts](https://www.service-public.fr/particuliers/vosdroits/F11249) et [cotisations salarié](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038027062/)).

2021-03-30 06:27 UTC, guillett approved these changes
Merci @sandcha pour la nouvelle passe. C'est bon pour moi.

2021-03-30 06:27 UTC, guillett commented on openfisca_france/model/base.py
> +    __order__ = 'non_renseigne agricole non_agricole'  # Needed to preserve the enum order in Python 2
```suggestion
    __order__ = 'non_renseigne agricole non_agricole'
```

2021-03-30 07:11 UTC, guillett commented on openfisca_france/model/base.py
> +    __order__ = 'non_renseigne agricole non_agricole'  # Needed to preserve the enum order in Python 2
```suggestion
```

:thinking:

2021-03-30 20:41 UTC, sandcha commented
Rebase en cours.

2021-03-30 21:08 UTC, merged

2021-04-04 20:33 UTC, MattiSG commented
> Et le montant ? Non modélisé par manque de formule de calcul.

Je comprends de https://www.actionlogement.fr/l-aide-mobili-jeune que l'aide vaut `min(100, loyer + charges_locatives - apl)`, avec un minimum de prise en charge de 10€ :

> Le montant de l’aide MOBILI-JEUNE est calculé :
> - à partir de la quote-part  de loyer (charges comprises)  
> - en tenant compte des diverses aides au logement perçues pour le même logement
> - en fonction des justificatifs transmis
> 
> Calcul du montant de l’aide MOBILI-JEUNE :
> - Pour un loyer de 350 €, si vous percevez 220 € d’APL, l’aide versée sera de 100 €.
> - Pour un loyer de 350 €, si vous percevez 280 € d’APL, l’aide versée sera de 70 €.
> - Pour un loyer de 250 €, si vous percevez 245 € d’APL, vous ne pourrez bénéficier de l’aide. Le reste à charge étant inférieur à 10 €.

2021-04-06 15:46 UTC, sandcha commented
@MattiSG Bien vu pour la formule de calcul :  
`min(100, loyer + charges_locatives - apl)`, avec un minimum de prise en charge de 10€

où il me semble qu'il ne manquerait que la quote-part de loyer mais ok pour que nous la modélisions en l'état (avec 100% du loyer donc).