Ajoute une première version de l'éligibilité aux logements du CROUS
openfisca/openfisca-france pull request #1493
Opened 2021-03-25 12:55 UTC by guillett

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées : `model/crous.py`.
* Détails :
  - Ajoute d'une variable pour l'éligibilité aux logements proposés par le CROUS
- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2021-03-26 10:25 UTC, benjello requested changes
Je t'invite à mettre les variables intermédiaires qui ne sont utilisées qu'une fois dans le calcul de la prestation dans la liste noire du cache `cache_blacklist`.

2021-03-26 10:26 UTC, benjello commented on openfisca_france/model/prestations/bourses_superieur.py
> +        age_ok = individu('bourse_criteres_sociaux_eligibilite_age', period)
```suggestion
        eligibilite_age = individu('bourse_criteres_sociaux_eligibilite_age', period)
```

2021-03-26 10:26 UTC, benjello commented on openfisca_france/model/prestations/bourses_superieur.py
> +        etudes_ok = individu('bourse_criteres_sociaux_eligibilite_etude', period)
```suggestion
        eligibilite_etude = individu('bourse_criteres_sociaux_eligibilite_etude', period)
```

2021-03-26 10:27 UTC, benjello commented on openfisca_france/model/prestations/bourses_superieur.py
> +        return select([etudes_ok * age_ok], [echelon], default = -1)
```suggestion
        return select([eligibilite_age * eligibilite_etude], [echelon], default = -1)
```

2021-03-26 10:40 UTC, guillett commented
Merci beaucoup @benjello tu m'as fait des retours sur la partie #1484  :sweat_smile:  c'est top, je les ai pris en compte sur la bonne PR directement.

2021-04-06 16:11 UTC, MattiSG requested changes
Je n'ai pas revu l'intégralité des calculs car je suis très gêné par le nombre de variables introduites pour le calcul de la bourse sur critères sociaux. J'y vois une approche très pertinente d'un point de vue de génie logiciel, avec de l'encapsulation de fonctions, mais qui me paraît inappropriée pour la modélisation de la loi en code : chacun des éléments apportés n'a pas de sens d'un point de vue législatif, et le nombre de variables introduites dans l'espace de nommage global rend leur utilisation très compliquée.

2021-04-06 16:11 UTC, MattiSG commented on openfisca_france/model/prestations/bourses_superieur.py
> +        return select([eligibilite_age * eligibilite_etude], [echelon], default = -1)
Pourquoi ne pas simplement utiliser un `where` plutôt que de passer par la création de tableaux ?

2021-04-06 16:11 UTC, MattiSG commented on openfisca_france/parameters/bourses_enseignement_superieur/criteres_sociaux/montants.yaml
> +metadata:
Manque une référence.

2021-04-06 16:11 UTC, MattiSG commented on openfisca_france/parameters/bourses_enseignement_superieur/criteres_sociaux/plafond_ressource/echelon_0bis.yaml
> +metadata:
J'appellerais plutôt cela `plafond_ressources` que `plafond_ressource` 🙂

2021-04-06 16:11 UTC, MattiSG commented on openfisca_france/parameters/bourses_enseignement_superieur/criteres_sociaux/seuil_ressources_etudiant_autonome.yaml
> +values:
```suggestion
description: Seuil de ressources pour considérer l'étudiant autonome en pourcentage du SMIC net
unit: /1
values:
```

2021-04-06 16:11 UTC, MattiSG commented on openfisca_france/model/prestations/bourses_superieur.py
> +        age = individu('age', period)
[La condition](https://www.education.gouv.fr/bo/20/Hebdo25/ESRS2013435C.htm) est :

> Être âgé de moins de 28 ans au 1er septembre de l'année d'inscription

Il faut donc calculer l'âge à cette date et non à `period` 🙂

2021-04-06 16:11 UTC, MattiSG commented on openfisca_france/model/prestations/bourses_superieur.py
> +class bourse_criteres_sociaux_echelon_potentiel(Variable):
Sans documentation ni commentaire, je ne comprends pas du tout pourquoi on introduit des variables qui déterminent un échelon « potentiel » à partir de montants de bourse plutôt que de s'appuyer sur un échelon donné pour calculer un montant, par exemple 🙁

2021-04-09 07:36 UTC, guillett commented on openfisca_france/model/prestations/bourses_superieur.py
> +        return echelon >= 0
Bien vu, j'ai corrigé cela en ajoutant les bourses du collège et du lycée dans la formule.

2021-04-09 07:43 UTC, guillett commented on openfisca_france/model/prestations/bourses_superieur.py
> +    def formula_2008(individu, period):
Naïvement, j'ai voulu créer du lien dans le modèle en ajoutant une définition à cette variable qui était jusqu'alors uniquement une _input variable_, sauf que cela a tiré beaucoup de choses. Notamment, dans `tests/reforms/test_landais_piketty_saez.py` qui s'est mis à échouer car les variables appelées ne sont pas définies depuis assez longtemps. C'était aussi le cas de `tests/test_basics.py` (qui ne porte pas forcément le meilleure nom :sweat_smile: ) qui calcule le revenu disponible de 2006 à 2020...

Suite à l'ajout des bourses du collège et du lycée, j'ai indiqué une formule à partir de 2021 uniquement.

2021-04-09 11:38 UTC, guillett commented on openfisca_france/model/prestations/bourses_superieur.py
> +        return famille.nb_persons(Famille.ENFANT)
Comme indiqué sur Slack, pour moi, il y a plusieurs sujets et raisons pour lesquelles j'ai tendance à créer de telles variables _intermédiaires_. La législation définie un nombre d'enfants et ne définit pas que ce nombre d'enfants est le nombre de personnes avec le rôle `enfant` dans OpenFisca. Avec une telle variable, j'explicite le concept de la législation et son interprétation dans OpenFisca.

2021-04-21 14:19 UTC, sandcha commented on openfisca_france/model/crous.py
> +        Tous les étudiants sont éligibles aux logements proposés par le CROUs mais
```suggestion
        Tous les étudiants sont éligibles aux logements proposés par le CROUS mais
```

2021-04-26 12:46 UTC, MattiSG reviewed
### Je suis en défaveur de l'intégration de ce dispositif dans OpenFisca au vu de ce qui en est décrit.

Je ne comprends pas en quoi cette approximation d'une éligibilité, qui ne peut pas être calculée sans données extérieures (nombre de dossiers et nombre de places dans la résidence visée), relève d'un modèle de la législation.

Si cette approximation a un intérêt métier pour une application cliente, elle devrait à mon avis se trouver dans le code de cette application, sur la base du retour du calcul de `bourse_criteres_sociaux_echelon` par OpenFisca.

2021-06-18 07:29 UTC, guillett commented
Merci @MattiSG pour ton retour. Effectivement ce n'est pas idéal mais en le faisant du côté de l'application cliente, on commence à avoir un simili simulateur, surcouche d'OpenFisca. Ça créé un précédent pour coder en dehors d'OpenFisca plutôt qu'en dedans.

On va aller dans cette direction mais, pour moi, ce n'est pas anecdotique :)

2021-06-18 10:04 UTC, closed without merging