Ajoute l'aide à l’obtention du permis de conduire automobile pour les demandeurs d’emploi
openfisca/openfisca-france pull request #1503
Opened 2021-03-29 09:56 UTC by guillett

* Évolution du système socio-fiscal. 
* Périodes concernées : À partir du 11/04/2011.
* Zones impactées : `prestations/aide_permis_demandeur_emploi.py`.
* Détails :
  -  Ajoute l'aide à l’obtention du permis de conduire automobile pour les demandeurs d’emploi.

- - - -

Cette PR repose sur #1502 

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Ajoutent une fonctionnalité (par exemple ajout d'une variable).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2021-03-29 12:21 UTC, MattiSG requested changes
Je ne trouve pas les conditions codées dans les références indiquées.

2021-03-29 12:21 UTC, MattiSG commented on openfisca_france/parameters/allocation_retour_emploi/montant_minimum.yaml
> +    value: 26.66
👏

2021-03-29 12:21 UTC, MattiSG commented on openfisca_france/parameters/allocation_retour_emploi/montant_minimum.yaml
> +values:
Une référence serait bienvenue 🙂

2021-03-29 12:21 UTC, MattiSG commented on openfisca_france/parameters/prestations/transport/aide_permis_demandeur_emploi.yaml
> +montant:
Il s'agit d'un plafond pour couvrir les frais réellement engagés et non d'une aide forfaitaire :

> Cette aide financière est plafonnée à 1 200 euros et est destinée à prendre en charge tout ou partie des frais que le demandeur d’emploi expose dans le cadre de l’apprentissage des règles d’acquisition du permis de conduire automobile.

```suggestion
montant_max:
```

2021-03-29 12:21 UTC, MattiSG commented on openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
> +        "Délibération n°2011/13 du 11 avril 2011",
```suggestion
        "Délibération Pôle Emploi n°2011/13 du 11 avril 2011",
```

2021-03-29 12:21 UTC, MattiSG commented on openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
> +        sans_rsa = individu.famille('rsa', period) <= 0
Pourquoi ne pas simplement utiliser la variable booléenne [`rsa_eligibilite`](https://fr.openfisca.org/legislation/rsa_eligibilite?q=rsa%20eligib) ?

2021-03-29 12:21 UTC, MattiSG commented on openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
> +        sans_aah = individu('aah', period) <= 0
Pourquoi ne pas simplement utiliser la variable booléenne [`aah_eligible`](https://fr.openfisca.org/legislation/aah_eligible) ?

2021-03-29 12:21 UTC, MattiSG commented on openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
> +        return sans_rsa * sans_aah * chomage_minimum
Je ne trouve pas ces conditions dans la référence indiquée.

2021-03-29 12:47 UTC, guillett commented on openfisca_france/parameters/allocation_retour_emploi/montant_minimum.yaml
> +    value: 26.66
Je n'ai fait que reprendre le travail de @lauradelmas8. :sweat_smile:

2021-03-30 06:12 UTC, guillett commented on openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
> +        sans_rsa = individu.famille('rsa', period) <= 0
Car cette variable de vérifie pas tous les critères pour percevoir effectivement le RSA. Notamment les conditions de ressources.

2021-03-30 06:12 UTC, guillett commented on openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
> +        sans_aah = individu('aah', period) <= 0
Même remarque, cette variable ne vérifie pas tous les critères pour percevoir effectivement l'AAH. Notamment les conditions de ressources.

2021-03-30 06:14 UTC, guillett commented on openfisca_france/parameters/allocation_retour_emploi/montant_minimum.yaml
> +values:
J'ai ajouté `https://www.ipp.eu/baremes-ipp/chomage/allocations_assurance_chomage/alloc_base/` mais je peux comprendre que ça ne soit pas satisfaisant. Cela étant dit, OpenFisca manque vraiment de la possibilité d'associer plusieurs revalorisations à la même référence. Le [barème de l'IPP](https://www.ipp.eu/baremes-ipp/chomage/allocations_assurance_chomage/alloc_base/) est en cela intéressant.

2021-03-31 12:27 UTC, MattiSG requested changes
Merci pour l'ajout des références ! 🙂 

Il me semblerait également pertinent de documenter la durée minimale d'inscription (il faut être inscrit à Pôle Emploi depuis plus de 6 mois), même si elle n'est pas modélisée, car il s'agit d'une raison importante de donner des faux positifs.

2021-03-31 12:27 UTC, MattiSG commented on openfisca_france/model/prestations/aide_permis_demandeur_emploi.py
> +        chomage_minimum = individu('chomage_brut', period) <= plafond_chomage
> indemnisé au titre d’une allocation chômage dont le montant **net** (avant prélèvement à la source de l’impôt sur le revenu) est inférieur ou égal à l’allocation d’aide au retour à l’emploi minimale (ARE minimale )

[Source : 1.1.1](http://www.bo-pole-emploi.org/bulletinsofficiels/instruction-pe-n2011-205-du-9-decembre-2011--mise-a-jour-bope-n2020-05.html?type=dossiers/2020/bope-n2020-005-du-17-janvier-2020)

```suggestion
        chomage_minimum = individu('chomage_net', period) <= plafond_chomage
```

2021-03-31 12:45 UTC, MattiSG approved these changes
Non testé localement.

2021-03-31 13:29 UTC, merged