Ajoute l'aide aux personnes inscrites à une formation labellisée par la Grande École du Numérique et ajoute la condition de nationalité aux bourses sur critères sociaux
openfisca/openfisca-france pull request #1521
Opened 2021-04-12 16:05 UTC by MattiSG

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/07/2012.
* Zones impactées :
  * `prestations/enseignement_superieur/bourse_criteres_sociaux.py`
  * `prestations/enseignement_superieur/aide_formation_gen.py`
  * `parameters/bourses_enseignement_superieur/criteres_sociaux/montants.yaml`
  * `parameters/bourses_enseignement_superieur/criteres_sociaux/nationalites_hors_eee.yaml`
* Détails :
  - Ajoute le barème 2015 des bourses sur critères sociaux de l'enseignement supérieur.
  - Ajoute la variable `bourse_criteres_sociaux_eligibilite_nationalite` et ajoute la condition de nationalité à l'éligibilité aux bourses sur critères sociaux de l'enseignement supérieur.
  - Renomme `bourse_criteres_sociaux_distance_domicile_familial` en `distance_domicile_familial`.
  - Renomme `echelon_bourse` en `bourse_criteres_sociaux_echelon`.
  - Ajoute le type de scolarité `grande_ecole_du_numerique`.
  - Ajoute le calcul de l'éligibilité et du montant à l'aide aux personnes inscrites dans les formations labellisées par la Grande Ecole du numérique avec les variables `aide_formation_gen_eligibilite` et `aide_formation_gen`.

- - - -

Ces changements :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

## Modélisé

- Une aide peut être accordée, selon leurs ressources, aux personnes […] qui sont inscrites dans les formations labellisées par la Grande Ecole du numérique.
- Cette aide est accordée en fonction d'un barème national […]. Les règles d'attribution des points de charge sont celles en vigueur à la date de commencement de la formation pour l'attribution des bourses d'enseignement supérieur […].
- Les taux des bourses d'enseignement supérieur […] s'appliquent au montant de l'aide mentionnée à l'article premier du présent décret.
- L'aide n'est pas cumulable avec une bourse d'enseignement supérieur sur critères sociaux.
- Le demandeur doit en outre remplir les mêmes conditions de nationalité que celles fixées en application de l'article D. 821-1 du code de l'éducation par le ministre chargé de l'enseignement supérieur pour bénéficier d'une bourse d'enseignement supérieur sur critères sociaux.

## Non modélisé

Les conditions de non-cumul spécifiques à la formation ne sont pas modélisées car aucune n'est modélisée à ce jour dans OpenFisca et qu'un grand nombre sont arbitraires ou à l'échelon infra-national :

- L'aide n'est pas cumulable avec une aide spécifique versée par le ministre chargé de l'enseignement supérieur ou les établissements publics qui en relèvent.
- Sont exclues du bénéfice de l'aide les personnes inscrites à Pôle Emploi comme demandeurs d'emploi qui perçoivent une aide à l'insertion ou une aide à la formation professionnelle ainsi que les personnes rémunérées sous contrat d'apprentissage ou de professionnalisation et les personnes en congé individuel de formation.
- Sont également exclues du bénéfice de l'aide les personnes percevant une aide du ministère chargé de l'emploi ou d'un conseil régional versée au titre de la formation professionnelle ou de l'insertion professionnelle.

## Points d'attention sur le modèle

- L'exclusivité avec la bourse d'enseignement supérieur est implémentée en introduisant un nouveau type de scolarité : `grande_ecole_du_numerique`. Cela m'a semblé approprié car les formations labellisées GEN ne sont pas nécessairement dispensées par des établissements d'enseignement supérieur. Cela pose néanmoins la question de la définition d'une éventuelle formation labellisée GEN dispensée par un établissement d'enseignement supérieur.
- Les deux renommages de variables qui font de ce jeu de changements un changement majeur ne sont pas totalement nécessaires, mais il me semble pertinent de les effectuer tant que c'est frais et que peu de réutilisateurs ont eu le temps de dépendre de `bourse_criteres_sociaux_distance_domicile_familial`.

## Points d'information importants pour les bénéficiaires

- La décision de refus d'attribution de l'aide doit être motivée.
- L'aide est versée à compter du mois suivant celui où le demandeur a produit l'ensemble des documents nécessaires à l'instruction de sa demande. La mise en paiement est effectuée en début de mois. L'aide est versée pour la durée de la formation. Dans le cadre de cette période, tout mois commencé en formation donne lieu au versement d'une mensualité d'aide. ⇒ Vu la courte durée des formations et la non rétroactivité, il est crucial de déposer le dossier au plus tôt.
- S'il ne remplit pas les conditions générales de scolarité et d'assiduité auxquelles est subordonné le bénéfice de l'aide qui lui a été accordée, il est tenu au reversement des sommes indûment perçues.

2021-04-14 10:28 UTC, guillett requested changes
Ravi de voir que le découpage des règles sur les bourses sur critères sociaux fasse, si vite, l'objet de réutilisation.

En l'état, je ne suis pas favorable aux renommages/suppression de variables et le suivi d'une formation labellisée devrait être sorti de TypeScolarité.

2021-04-14 10:28 UTC, guillett commented on openfisca_france/model/prestations/enseignement_superieur/aide_formation_gen.py
> +        points_de_charge = individu('bourse_criteres_sociaux_points_de_charge', period)
:heart:

2021-04-14 11:06 UTC, MattiSG commented on openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py
> -class bourse_criteres_sociaux_distance_domicile_familial(Variable):
Les règles spécifiques aux bourses concernent l'attribution des points de charge, pas le calcul de la distance entre le domicile familial et le lieu d'études. La variable renommée ne représente que le nombre de kilomètres entre le domicile familial et le lieu d'études.

2021-04-14 11:12 UTC, MattiSG commented on openfisca_france/model/prestations/enseignement_superieur/bourse_criteres_sociaux.py
> -class bourse_criteres_sociaux_distance_domicile_familial(Variable):
Je vais appliquer la demande.

2021-04-14 11:15 UTC, MattiSG commented on openfisca_france/model/prestations/education.py
> +    grande_ecole_du_numerique = "Formation labellisée par la Grande Ecole du numérique"
J'ai personnellement l'impression qu'on va complexifier encore le modèle global en rajoutant une variable booléenne difficile à découvrir et dont la relation avec la formation et le type de scolarité n'est pas clair, et qu'il faudra dans tous les cas refactor avec un changement majeur lorsqu'une hypothétique « bonne représentation des formations continues » arrivera, et qu'en l'état il vaut mieux reconnaître que `TypesScolarite` représente tous les types de scolarité, pas uniquement la formation initiale (ce qui n'est pas documenté).

2021-04-14 11:15 UTC, MattiSG commented on openfisca_france/model/prestations/education.py
> +    grande_ecole_du_numerique = "Formation labellisée par la Grande Ecole du numérique"
Je vais appliquer la demande.

2021-04-14 12:00 UTC, guillett approved these changes

2021-04-14 12:00 UTC, guillett commented on openfisca_france/parameters/bourses_enseignement_superieur/criteres_sociaux/montants.yaml
> +      reference: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000031088328/2015-09-01
> J'ai bien la [représentation des références dans les barèmes IPP][https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml/blob/master/parameters/chomage/allocations_assurance_chomage/alloc_base.yaml) qui évite la répétition de l'information. J'ai tenté d'initier cela dans ce fichier. J'ai aussi tendance à préférer les liens [ELI](https://fr.wikipedia.org/wiki/Identifiant_europ%C3%A9en_de_la_l%C3%A9gislation)

2021-04-26 09:38 UTC, MattiSG commented on openfisca_france/model/prestations/education.py
> +    grande_ecole_du_numerique = "Formation labellisée par la Grande Ecole du numérique"
Comme vu en échange audio la semaine dernière, la complexité consécutive à l'introduction d'un booléen et les zones grises législatives que cela soulève (arbitrage nécessaire sur la priorité à donner entre formation GEN et formation enseignement supérieur) fait pencher le rapport coût / bénéfice en faveur de l'implémentation initiale.

2021-04-26 12:23 UTC, merged