Harmonisation csg crds
openfisca/openfisca-france pull request #1541
Opened 2021-05-24 10:06 UTC by Sasha-Laniece

* Amélioration technique.
* Périodes concernées : toutes. 
* Zones impactées : toutes
* Détails : Harmonisation du dossier parameters:
  -- Arborescence selon le modèle IPP
  -- Nouveau formatage des fichiers .yaml
  -- Mise à jour des valeurs et des références (et ajout de nouveaux paramètres) d'après l'IPP
- - - -
Ces changements 
- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

2021-05-24 10:14 UTC, Sasha-Laniece commented
Pour la CSG du Capital : 
parameters.prelevements_sociaux.contributions_sociales.csg.capital --> parameters.taxation_capital.prelevements_sociaux.csg

Pour capital.py (l326), on décide de garder l'ancien fichier  (glob.yaml) car l'harmonisation demande de changer la formule (et de faire la distinction entre revenus du patrimoine et produits de placement, ce qui n'est pas le cas dans la vieille formule) 

Il faudra faire cette distinction dans la mise à jour de la formule, mais pour l'instant j'ai pris le parti de ne pas changer les résultats des calculs actuels

2021-05-24 16:14 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
> +            base_avec_abattement=chomage_brut,
Dans openfisca on met des espaces autour des signes "=" même pour passer des arguments pour faciliter la lecture.
Par ailleurs on utilise cette convention pour les parenthèses (et équivalents) fermantes:
```python
my_list = [
    1, 2, 3,
    4, 5, 6,
    ]
result = some_function_that_takes_arguments(
    'a', 'b', 'c',
    'd', 'e', 'f',
    )
```

@sandcha @maukoquiroga : je n'ai trouvé cela nulle part dans  la doc. Peut-être devrions nous l'indiquer.
Peut-être même juste dans celle de openfisca-france ...

2021-05-24 16:23 UTC, benjello requested changes
Merci @Sasha-Laniece !
-  j'ai repéré des problèmes de forme que j'ai signalé de façon générique. Je te laisse les corriger.
- Si tu veux que je les signale tous (ou que je t'aide à les corriger), n'hésite pas à me le signaler.

2021-05-24 16:27 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
> +            base_avec_abattement=chomage_brut,
Hello ! Merci pour tes conseils, malheureusement j'ai utilisé un fix automatique (black) qui n'a pas les mêmes conventions que vous. Ça a changé tout le fichier pour le pire ...

Je m'occupe de tout ça demain !

2021-05-24 16:27 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/activite/taux.yaml
> +documentation:
Champ vide

2021-05-24 16:27 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/retraite/index.yaml
> +description: CRDS sur les Retraites et pensions d'invalidité
```suggestion
description: CRDS sur les retraites et pensions d'invalidité
```

2021-05-24 16:30 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/retraite/taux.yaml
> +  reference:
Il y a pas mal de champs vides. Cela semble à dessein. Pourrais-tu nous éclairer @Sasha-Laniece ?

2021-05-24 16:30 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/index.yaml
> +  description_en: Social contributions
```suggestion
  description_en: Social contributions

```

2021-05-24 16:30 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  description_en: Social contributions
```suggestion
  description_en: Social contributions

```

2021-05-24 16:31 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/deductible/taux_plein.yaml
> +  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.
```suggestion
  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.

```

2021-05-24 16:31 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/deductible/taux_reduit.yaml
> +  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.
```suggestion
  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.

```

2021-05-24 16:31 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/imposable/taux.yaml
> +  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.
```suggestion
  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.

```

2021-05-24 16:31 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/chomage/taux_global.yaml
> +  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.
```suggestion
  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.

```

2021-05-24 16:32 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/indemnites_journalieres/deductible/taux.yaml
> +  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.
```suggestion
  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.

```

2021-05-24 16:32 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/indemnites_journalieres/imposable/taux.yaml
> +  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.
```suggestion
  La loi 96-1181 du 30/12/1996 (LF pour 1997) a créé l'art. 154 quinquies (M) du Code général des impôts (CGI) qui régit les dispositions relatives à la CSG depuis 1997.

```

2021-05-24 16:32 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/retraite/taux.yaml
> +  reference:
Salut ! Pour l'instant on a fait le choix de garder les champs vides, pour que les contributeurs métiers qui ne connaissent pas OpenFisca puissent remplir facilement ces fichiers

2021-05-24 16:33 UTC, benjello requested changes
@Sasha-Laniece : il y a beaucoup de fichiers sans retour à la ligne en fin de fichier. Je te conseille de réglr ton éditeur pour qu'il gère cela.

2021-05-25 12:10 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return -assiette_csg_revenus_capital * P.taxation_capital.prelevements_sociaux.csg.glob
Merci @Sasha-Laniece .

@clallemand @bfabre01 @pzuldp : cette PR est un début d'harmonisation barèmes openfisca / barèmes IPP.
On veut virer la csg sur le capital présente dans openfisca.
Il semble que l'on ne gère pas bien la différence placement/patrimoine.
Je propose de migrer le commentaire suivant trouvés dans le fichier de paramètre openfisca dans la formule de la csg sur les revenus du capital.
```
# Pour les revenus du patrimoine, le changement de CSG se fait à partir des revenus de 2017, mais le taux de CSG déductible se fait à partir des revenus 2018. Pour les revenus de placement, le timing est différent, et reste à être pris en compte ici : cf. II.B de l'art. 67 de loi 2017-1837 et 3° et 4° du V.A de l'art. 8 de loi 2017-1836
````

Est-ce que cela vous va ?

2021-05-25 12:11 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return -assiette_csg_revenus_capital * P.taxation_capital.prelevements_sociaux.csg.glob
Et bien sûr d'utiliser la csg des revenus du patrimoine venant des barèmes IPP  dans openfisca (ce qui semble être l'existant)/

2021-05-25 14:53 UTC, Sasha-Laniece commented
Petite question de la Team UI pour @benjello : dans les parametres.yaml, on a :

metadata:
  reference:
      2017-01-01:
        title: Décret 2014-1531 du 17/12/2014, art. 4
        href: https://www.legifrance.gouv.fr/affichTexteArticle.do/sdfa45w45w4
      2016-01-01:
        title: Décret 2014-1531 du 17/12/2014, art. 4
        href: https://www.legifrance.gouv.fr/affichTexteArticle.do/34w54d5e
      2015-01-01:
        title: Décret 2014-1531 du 17/12/2014, art. 4
        href: https://www.legifrance.gouv.fr/affichTexteArticle.do/434564r
   date_parution_jo:
      2017-01-01: 2014-12-19
      2016-01-01: 2014-12-19
      2015-01-01: 2014-12-19
     
  Pourrait-on envisager de merger ces informations par date (cf. ci-dessous)? **Quels problèmes cela poserait-il côté IPP ? Et OpenFisca ?**

metadata:
  reference:
      2017-01-01:
        title: Décret 2014-1531 du 17/12/2014, art. 4
        href: https://www.legifrance.gouv.fr/affichTexteArticle.do/sdfa45w45w4
        date_parution_jo: 2014-12-19
      2016-01-01:
        title: Décret 2014-1531 du 17/12/2014, art. 4
        href: https://www.legifrance.gouv.fr/affichTexteArticle.do/34w54d5e
        date_parution_jo: 2014-12-19
      2015-01-01:
        title: Décret 2014-1531 du 17/12/2014, art. 4
        href: https://www.legifrance.gouv.fr/affichTexteArticle.do/434564r
        date_parution_jo: 2014-12-19

2021-05-26 08:05 UTC, pzuldp commented
> 
> 
> @Sasha-Laniece : je pense qu'en effet ce serait plus approprié. Mais je ne sais pas quel impact cela aura côté IPP.
> Donc je serais plutôt dans une posture attentiste sachant qu'il ne doit pas être très compliqué de faire un script qui déploie les parution au JO au niveau des paramètres.

@benjello en termes d'info je ne crois pas que ça change quelque chose côté IPP, le niveau auquel l'information est rentré reste le même ? c'est "juste" une question de manière de contribuer à l'avenir (et d'écluser le passé ?) - on peut éditer le manuel et faire passer le mot ?

2021-05-26 09:38 UTC, Sasha-Laniece commented
> > > @Sasha-Laniece : je pense qu'en effet ce serait plus approprié. Mais je ne sais pas quel impact cela aura côté IPP.
> > > Donc je serais plutôt dans une posture attentiste sachant qu'il ne doit pas être très compliqué de faire un script qui déploie les parution au JO au niveau des paramètres.
> > 
> > 
> > @benjello en termes d'info je ne crois pas que ça change quelque chose côté IPP, le niveau auquel l'information est rentré reste le même ? c'est "juste" une question de manière de contribuer à l'avenir (et d'écluser le passé ?) - on peut éditer le manuel et faire passer le mot ?
> 
> C'est la génération des tables qui m'inquiète.

Pour l'instant je ne fais rien alors. Si vous pensez que le changement est faisable de votre côté, je vous laisse revenir vers moi.

2021-05-26 09:42 UTC, Sasha-Laniece commented
Côté clefs: description & ux_name , nous avons pris des décisions que je vais implémenter, et qu'il faudra expliciter dans le guide de contribution. Je mets ça ici pour l'instant:
- la description doit faire une phrase dans le meilleur français possible tout en restant succinct, qui décrit le paramètre/dossier depuis la racine de l'arbre
- le ux_name est un ensemble de quelques mots qui permet de comprendre clairement le paramètre/dossier s'il est affiché avec l'arbre qui le précède. Il ne doit pas décrire des paramètres/dossiers sous son niveau de noeud. Il doit rester succinct pour pouvoir être affiché dans un tableau, un graphe, etc...

2021-05-26 12:03 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return -assiette_csg_revenus_capital * P.taxation_capital.prelevements_sociaux.csg.glob
Fait !

2021-05-27 09:25 UTC, benjello commented
Je pense qu'il y a des fichiers redondants et que l'on peut donc les supprimer (et corriger le code s'il y lieu):
- taxation_capital.prelevements_sociaux.csg.deductible.deduc.yaml
- taxation_capital.prelevements_sociaux.csg.glob.yaml

Je le fais directement sur ta branche ou préfères-tu que je liste les problèmes sur la PR ?

2021-05-27 09:30 UTC, Sasha-Laniece commented
> Je pense qu'il y a des fichiers redondants et que l'on peut donc les supprimer (et corriger le code s'il y lieu):
> 
> * taxation_capital.prelevements_sociaux.csg.deductible.deduc.yaml
> * taxation_capital.prelevements_sociaux.csg.glob.yaml
> 
> Je le fais directement sur ta branche ou préfères-tu que je liste les problèmes sur la PR ?

Hello ! Ils sont redondants en effet, à supprimer une fois que les formules de csg du capital sont mises à jour suite à l'issue que j'avais soulevée. Mais je ne crois pas que ce soit le cas ?

Le pb en question : les nouveaux parametres CSG du capital qui séparent revenus du patrimoine et produits de placement, ce qui n’était pas le cas avant. Je ne sais pas si je dois changer les formules ? J’ai peur de faire une erreur métier

2021-05-27 09:49 UTC, benjello commented
@Sasha-Laniece : je vais le faire si tu veux bien.

2021-05-27 09:51 UTC, Sasha-Laniece commented
@benjello carrément ! Merci !
Et du coup on met un warning quelque part pour dire aux gens qui utilisaient la formule qu'elle va changer?

2021-05-27 09:55 UTC, benjello commented
Normalement elle ne changera pas car on prendra les bons paramètres.

2021-05-27 11:03 UTC, sandcha commented
Pour ce qui est du principe du regroupement de `date_parution_jo` sous `metadata`/`reference`/**date**, je pense que c'est ok pour openfisca.
> Ceci dans le sens où cela ne change rien d'un point de vue technique (c'est libre sous `metadata`) et rien de particulier d'un point de vue usage tant que c'est sous `metadata`/`reference` (même si `metadata` est libre, `reference` est souvent utilisé ; exemple : dans le [country-template](https://github.com/openfisca/country-template/blob/master/openfisca_country_template/parameters/benefits/basic_income.yaml)).

Néanmoins, par cohérence, je mettrais un nom de clef en anglais. 
Ce pourrait être construit sur la base de ces termes : date of issue in official journal (l'acronyme `OJ` est [utilisé pour l'UE](https://eur-lex.europa.eu/oj/direct-access.html)).

2021-05-27 13:48 UTC, Sasha-Laniece reviewed
Je vois que tu as trouvé le problème...
Faut-il changer les tests ? Mais alors qu'est-ce que ça veut dire pour les gens qui voulaient ces résultats-là ? (Même s'ils sont faux en théorie)

2021-05-27 14:04 UTC, benjello commented
@Sasha-Laniece : il y a potentiellement une erreur. J'ai demandé aux [experts](https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml/-/issues/101)  .

2021-05-28 08:18 UTC, pzuldp commented
> 
> 
> @Sasha-Laniece : il y a potentiellement une erreur. J'ai demandé aux [experts](https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml/-/issues/101) .

Salut @benjello @Sasha-Laniece pour autant que je puisse en juger il y a effectivement une erreur côté openfisca. 
En général les changements de taux de csg et csg déductible associés à un texte en vigueur en début d'année N s'appliquent en N aux revenus de placement (art 136-7 CSS), et N-1 aux revenus du patrimoine (art 136-6 CSS) : cf. [note (4) en bas du barème IPP avec un exemple](https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml/-/blob/master/parameters/taxation_capital/prelevements_sociaux/csg.yaml).

Pour l'exemple sur la LFSS 2018 
cf les 3° et 4° du V A 

> 3° A compter de l'imposition des revenus de l'année 2017, en ce qu'ils concernent la contribution mentionnée à l'article L. 136-6 du code de la sécurité sociale, sous réserve du II de l'article 34 de la loi n° 2016-1918 du 29 décembre 2016 de finances rectificative pour 2016 ;

> 4° Dans les conditions et sous les réserves définies par le présent V, aux faits générateurs intervenant à compter du 1er janvier 2018, en ce qu'ils concernent la contribution mentionnée à l'article L. 136-7 du code de la sécurité sociale.

2021-05-28 09:07 UTC, benjello commented
Un résumé du problème:
- on ne distingue pas les revenus du patrimoine des revenus de placement pour les prélèvements sociaux
- on avait des valeurs incohérentes pour la CSG totale et pour la CSG déductible (une fois on traitait les revenus des capitaux comme des revenus de patrimoine et une autre fois comme des revenus de placement) 
-  on a désormais au moins un test qui foire sur les rvcm de 2018

On peut garder le fait que l'on traite tout comme des revenus du patrimoine et corriger le test car les rcvm sont des revenus du patrimoine (en espérant que l'on n'aura pas à corriger trop d'autres choses.  

@bfabre01 @claireleroy @clallemand @pzuldp cela vous convient-il ?

2021-05-28 11:44 UTC, pzuldp commented
> 
> 
> Un résumé du problème:
> 
>     * on ne distingue pas les revenus du patrimoine des revenus de placement pour les prélèvements sociaux
> 
>     * on avait des valeurs incohérentes pour la CSG totale et pour la CSG déductible (une fois on traitait les revenus des capitaux comme des revenus de patrimoine et une autre fois comme des revenus de placement)
> 
>     * on a désormais au moins un test qui foire sur les rvcm de 2018
> 
> 
> On peut garder le fait que l'on traite tout comme des revenus du patrimoine et corriger le test car les rcvm sont des revenus du patrimoine (en espérant que l'on n'aura pas à corriger trop d'autres choses.
> 
> @bfabre01 @claireleroy @clallemand @pzuldp cela vous convient-il ?

ça me paraît une bonne option (ce d'autant plus que plusieurs types de revenus de placement sont exonérés de toute façon, donc en attendant de compléter l'erreur ne sera pas si grande ?).

2021-05-28 11:57 UTC, benjello commented
Autres tests qui plantent

```
================================================================================================ FAILURES =================================================================================================
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/pv_pfu.yaml:
  Test 'Application du PFU aux plus-values':
    prelevements_sociaux_revenus_capital@2019: [-8250.] differs from -8600.0 with an absolute margin [350.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/pv_pfu.yaml:
  Test 'Cas d'un foyer fiscal sujet à la fois au PFU sur plus-values et à des taxations hors barème et hors PFU sur plus-values':
    prelevements_sociaux_revenus_capital@2019: [-9900.] differs from -10320.0 with an absolute margin [420.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/pv_pfu.yaml:
  Test 'Cas d'imposition hors barème de plus-values non imposable au PFU':
    prelevements_sociaux_revenus_capital@2018: [-8250.] differs from -8600.0 with an absolute margin [350.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/rpns_pv.yaml:
  Test 'Imposition des plus-values des revenus de professions non-salariées - régime microBA':
    prelevements_sociaux_revenus_capital@2019: [-6600.] differs from -6880.0 with an absolute margin [280.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/rpns_pv.yaml:
  Test 'Imposition des plus-values des revenus de professions non-salariées - Régime du bénéfice réel':
    prelevements_sociaux_revenus_capital@2019: [-4125.] differs from -4300.0 with an absolute margin [175.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/rpns_pv.yaml:
  Test 'Imposition des plus-values des revenus de professions non-salariées - Régime Micro BIC':
    prelevements_sociaux_revenus_capital@2019: [-3300.] differs from -3440.0 with an absolute margin [140.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/rpns_pv.yaml:
  Test 'Imposition des plus-values des revenus de professions non-salariées - Régime RIC pro bénéfice réel':
    prelevements_sociaux_revenus_capital@2019: [-3300.] differs from -3440.0 with an absolute margin [140.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/rpns_pv.yaml:
  Test 'Imposition des plus-values des revenus de professions non-salariées - Régime RIC non pro micro':
    prelevements_sociaux_revenus_capital@2019: [-3300.] differs from -3440.0 with an absolute margin [140.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/rvcm.yaml:
  Test 'Application du PFU aux revenus de capitaux mobiliers (hors assurance-vie et exceptions)':
    prelevements_sociaux_revenus_capital@2018: [-13365.] differs from -13932.0 with an absolute margin [567.] > 1
______________________________________________________________________________________________ test session _______________________________________________________________________________________________
/home/benjello/openfisca/openfisca-france/tests/calculateur_impots/yaml/rvcm.yaml:
  Test 'Application du PFU aux produits des bons et contrats de capitalisation et d'assurance-vie':
    prelevements_sociaux_revenus_capital@2018: [-13365.] differs from -13932.0 with an absolute margin [567.] > 1
========================================================================================= short test summary info =========================================================================================
FAILED tests/calculateur_impots/yaml/pv_pfu.yaml::
FAILED tests/calculateur_impots/yaml/pv_pfu.yaml::
FAILED tests/calculateur_impots/yaml/pv_pfu.yaml::
FAILED tests/calculateur_impots/yaml/rpns_pv.yaml::
FAILED tests/calculateur_impots/yaml/rpns_pv.yaml::
FAILED tests/calculateur_impots/yaml/rpns_pv.yaml::
FAILED tests/calculateur_impots/yaml/rpns_pv.yaml::
FAILED tests/calculateur_impots/yaml/rpns_pv.yaml::
FAILED tests/calculateur_impots/yaml/rvcm.yaml::
FAILED tests/calculateur_impots/yaml/rvcm.yaml::
```

2021-05-28 14:19 UTC, benjello approved these changes

2021-05-28 14:20 UTC, benjello commented
@Sasha-Laniece : LGTM

2021-05-31 06:37 UTC, merged

2021-06-01 17:05 UTC, sandcha commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/activite/taux.yaml
> +  notes:
@Sasha-Laniece Pardon, il y a deux éléments qui ont été perdus durant la revue et qui concernent les paramètres de façon générale. 
Dans une autre PR, il me semble qu'il faudrait amender : 
* `date_parution_jo` afin que ce soit en anglais comme indiqué dans [ce commentaire](https://github.com/openfisca/openfisca-france/pull/1541#issuecomment-849541276). 
* et n'avions-nous pas dit que nous n'indiquerions pas les clefs sans valeur qui sont source d'erreur ? 🤔 Si je ne fais pas erreur à ce sujet, sur l'exemple ci-dessus, nous pourrions ainsi supprimer `reference` et `notes`.