Revalorisation des prestations familiales et l'ASPA
openfisca/openfisca-france pull request #1542
Opened 2021-05-25 16:12 UTC by mtifarine

* Changement mineur.
* Périodes concernées : à partir du 01/01/2021.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - 
  -

2021-06-17 17:16 UTC, sandcha requested changes
Merci @mtifarine pour toutes ces revalorisations !
Il ne manque qu'une référence législative et d'autres sont indiquées en suggestion.
Et selon l'usage que vous faites de la base ressources, le plafond horaire de la sécurité sociale pourrait également être mis à jour 🤔

2021-06-17 17:16 UTC, sandcha commented on openfisca_france/parameters/prestations/aides_logement/autres/nr_seuil.yaml
> +    value: 24.0
Ajouter la référence législative ou la remonter au niveau supérieur du paramètre si le taux reste invarié à 0,68% ? 
```suggestion
  2021-01-01:
    value: 24.0  # 0.68% du plafond mensuel de sécurité sociale arrondi à l'euro supérieur
    reference: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000035671411/2017-10-01
```

2021-06-17 17:16 UTC, sandcha commented on openfisca_france/parameters/prestations/majconj_plaf/plafond_des_ressources_personnelles_du_conjoint_pour_beneficier_de_la_majoration_pour_personne_a_charge.yaml
> +    value: 10271.95
Ajouter une référence législative ? 🤔

2021-06-22 18:37 UTC, sandcha commented on openfisca_france/parameters/cotsoc/gen/plafond_securite_sociale.yaml
> +    value: 3428.0
Précision complémentaire au commentaire de revue : 
Mettre également à jour `openfisca_france/parameters/cotsoc/gen/plafond_securite_sociale_horaire.yaml` ? 🤔 Celui-ci intervient principalement dans les gratifications de stage. Cela dépend donc des valeurs d'entrée employées pour alimenter la base de ressources `asi_aspa_base_ressources_individu`.

2021-08-24 07:23 UTC, mtifarine commented
Merci @sandcha de votre retour!
J'ai pris en compte les retours, pourriez-vous vérifier si c'est bon ?

2021-09-27 07:18 UTC, sandcha commented
Rebase en cours, comme évoqué en réunion, en raison du nombre de `conflicting files` détecté et du temps écoulé.

2021-09-27 07:20 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/aah/montant.yaml
> +    reference: https://www.legifrance.gouv.fr/eli/decret/2021/4/29/SSAA2110847D/jo/article_1
> Référence la plus proche du montant choisie : référence du décret complet supprimée au bénéfice de la référence de l'article (ce comportement a été choisi tout au long du rebase).

2021-09-27 07:21 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/caah/garantie_ressources.yaml
> +    reference: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000019505277/
⚠️ Incohérence détectée au rebase : le paramètre est-il supprimé comme l'indique le `null` ou prolongé ? 🤔 
> À analyser au regard de la formule de calcul ?

2021-09-27 07:22 UTC, sandcha commented on openfisca_france/parameters/prestations/majconj_plaf/plafond_des_ressources_personnelles_du_conjoint_pour_beneficier_de_la_majoration_pour_personne_a_charge.yaml
> +  2021-04-01:
> Ecart détecté au rebase.

2021-09-27 07:23 UTC, sandcha commented on openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1.yaml
> +      https://www.legifrance.gouv.fr/eli/arrete/2018/12/21/SSAS1835267A/jo/article_1
Ces deux références législatives détectées au rebase n'indiquent pas les mêmes montants de plafond. De même pour la tranche_2 🤔

2021-09-27 08:43 UTC, mtifarine commented on openfisca_france/parameters/prestations/majconj_plaf/plafond_des_ressources_personnelles_du_conjoint_pour_beneficier_de_la_majoration_pour_personne_a_charge.yaml
> +  2021-04-01:
Oui je confirme c'est pour le 2021-01-01

2021-09-27 08:59 UTC, mtifarine commented on openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_2.yaml
> +      https://www.legifrance.gouv.fr/eli/arrete/2018/12/21/SSAS1835267A/jo/article_1
La référence
 la plus proche c'est: https://www.legifrance.gouv.fr/eli/arrete/2019/12/20/SSAS1934813A/jo/article_1

2021-09-27 09:01 UTC, mtifarine commented on openfisca_france/parameters/prestations/prestations_familiales/af/modulation/plafond_tranche_1.yaml
> +      https://www.legifrance.gouv.fr/eli/arrete/2018/12/21/SSAS1835267A/jo/article_1
La référence la proche: https://www.legifrance.gouv.fr/eli/arrete/2019/12/20/SSAS1934813A/jo/article_1

2021-09-28 13:43 UTC, mtifarine commented on openfisca_france/parameters/prestations/minima_sociaux/caah/garantie_ressources.yaml
> +    reference: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000019505277/
j'ai vérifié avec @tomy-isabelle , le paramètre est supprimé (pas de reval pour la garantie ressource)

2021-09-28 14:45 UTC, bfabre01 commented on tests/formulas/rsa.yaml
> +  period: 2021-01
@mtifarine : je ne comprends pas le but de ce changement.

2021-09-28 14:56 UTC, bfabre01 commented
@mtifarine : en fait, on a déjà introduit côté IPP les revalorisations qui était l'objet de cette PR, qui date de mai. Voir les PR #1673 et #1668. D'où forcément les problèmes de rebase... Il faut donc changer le titre de cette PR ainsi que son descriptif, car elle n'catualise plus ce qu'elle était censée actualiser à la base. Et bien vérifier ce que cette PR modifie à l'issue du rebase. Car du coup, la proba d'erreur dans le rebase est relativement importante.
Pour les revalorisations, il est important je pense de ne pas laisser une PR non-mergée aussi longtemps. Sinon, ça fait doublon.
cc @sandcha

2021-09-28 15:29 UTC, bfabre01 commented on openfisca_france/parameters/prelevements_sociaux/pss/plafond_de_la_securite_sociale_mensuel.yaml
> +reference: https://www.ipp.eu/outils/baremes-ipp/
@mtifarine @sandcha Ce fichier (`plafond_de_la_securite_sociale_mensuel.yaml`) semble être un doublon d'un fichier déjà existant et situé au même endroit (`plafond_securite_sociale_mensuel.yaml`). Une erreur dans le rebase peut-être. Il faut supprimer ce fichier en tout cas.

2021-10-05 08:58 UTC, frtomas commented on openfisca_france/parameters/prestations/aides_logement/autres/nr_seuil.yaml
> +    reference: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000035671411/2021-08-19/
la mention concernant ce changement sur le seuil de non recouvrement est en fait la suivante :
Les caisses d'allocations familiales et les caisses de mutualité sociale agricole sont autorisées à abandonner la mise en recouvrement des indus d'allocation lorsque leur montant est inférieur à une somme égale à 0,68 % du plafond mentionné à l'article L. 241-3 du code de la sécurité sociale, arrondie à l'euro supérieur.

Il s'agit d'un montant calculé, le calcul n'a pas changé lui même mais le plafond en question si, d'où l'évolution du montant

2021-10-05 09:01 UTC, frtomas commented on tests/formulas/rsa.yaml
> +  period: 2021-01
Cette date etait originellement une erreur, elle avait été positionnée trop loin, ce décalage est une correction

2021-10-05 12:26 UTC, bfabre01 commented on openfisca_france/parameters/prestations/aides_logement/autres/nr_seuil.yaml
> +    reference: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000035671411/2021-08-19/
Ok merci @frtomas. Ce plafond, c'est le PSS ? Ou bien autre chose ? Si ce plafond est présent dans les paramètres, il faudrait peut-être avoir, non pas 24, mais le 0,68% dans les paramètres. Comme ça, ce seuil évoluerait tout seul avec le plafond. Car ici, grosse proba d'oublier de le changer dans le futur.

Par contre, le texte en question est abrogé. Il faudrait la nouvelle référence, si ce montant minimum est toujours en vigueur.

2021-10-05 12:27 UTC, bfabre01 commented on tests/formulas/rsa.yaml
> +  period: 2021-01
Ok merci !

2021-10-06 08:08 UTC, frtomas commented on openfisca_france/parameters/prestations/aides_logement/autres/nr_seuil.yaml
> +    reference: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000035671411/2021-08-19/
@bfabre01 concernant le plafond présent ou non dans les paramètres, il me semble pas l'avoir trouvé dans OpenFisca et ce seuil de versement existe depuis relativement longtemps dans OF. Effectivement, peut-être qu'à terme il sera amené a disparaitre au profit du plafond en lui même et être effectivement calculé.

Pour ce qui est de la référence, je vais essayer de trouver ça.

2021-10-06 08:27 UTC, frtomas commented on openfisca_france/parameters/prestations/aides_logement/autres/nr_seuil.yaml
> +    reference: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000035671411/2021-08-19/
Il me semble que la meilleur référence possible concernant ce point serait celle-ci :
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038929179

Si tout le monde est d'accord, nous allons remplacé celle utilisé actuellement.

2021-12-10 11:23 UTC, tomy-isabelle commented
bonjour @benjello , @sandcha , @mtifarine , @frtomas
dans la mesure où il n'y a plus de discussion sur cette PR
est il possible de la merger s'il vous plait ?
merci

2023-06-28 11:59 UTC, benjello commented
@robinguill @sandcha : est-ce encore à merger dans master ? 
Merci de fermer si ce n'est plus le cas.

2023-06-29 12:46 UTC, robinguill commented
@benjello nous sommes en train de revoir toutes les PR ouvertes non merge ou close, celle ci revalorise le seuil de non recouvrement sur l'AL avec une nouvelle valeur pour 2021 pas encore présente sur le master et me semble donc encore d'actualité. Par contre ne l'ayant pas ouverte je ne peux modifier le message de la PR.

2023-06-29 13:29 UTC, benjello commented
@robinguill est-ce que je peux me permettre de rebaser cette branche car le bug qui apparaît dans les tests semble avoir été résolu sur Core.

2023-07-03 09:23 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/autres/nr_seuil.yaml
> +description: Seuil de non recouvrement - seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur.
Je mettrai plutôt cette remarque dans le champ documentation des metadata

2023-07-12 07:26 UTC, robinguill commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/autres/nr_seuil.yaml
> +description: Seuil de non recouvrement - seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur.
Remarque déplacée

2023-10-24 07:22 UTC, frtomas commented
Reste-t-il des points à discuter sur cette PRs ?
Il reste une review déjà prise en compte mais non marquée à résolu @sandcha 
mais en dehors de ça, tout semble ok ?

2023-10-24 09:20 UTC, benjello approved these changes
Petite suggestion mais je ne veux pas bloquer.

2023-10-24 09:20 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/autres/nr_seuil.yaml
> +  Notes: Seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur.
```suggestion
  Seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur.
```

2023-10-24 09:20 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/autres/nr_seuil.yaml
> +  Notes: Seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur.
Une petite précision pourrait être utile (% du PSS ou autre).

2023-10-24 13:37 UTC, frtomas commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/autres/nr_seuil.yaml
> +  Notes: Seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur.
[Code de la sécurité sociale : Chapitre 3 : Recouvrement des cotisations, versement e](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038929179/2022-06-17)
sur cet article je trouve ceci qui semblerait être le % en question :

_Le montant visé à l'article [L. 133-3 ](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006740147&dateTexte=&categorieLien=cid)en deçà duquel les organismes chargés du versement des prestations de sécurité sociale sont autorisés à abandonner la mise en recouvrement des indus de prestations de sécurité sociale versés à leurs assurés ou constatés à l'égard de tiers est fixé à **0,68 % du plafond mensuel de sécurité sociale** en vigueur, arrondi à l'euro supérieur._

```suggestion
  Seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur (0,68% du plafond).
```

2023-10-24 13:44 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/autres/nr_seuil.yaml
> +  Notes: Seuil calculé au regard du plafond de la sécurité sociale mensuel et arrondi à l'euro supérieur.
Super !
Si on connaît la date de ce changement, on peut le mettre en note à l'année considérée.
Voici un [exemple](openfisca_france/parameters/impot_revenu/calcul_impot_revenu/pv/actifs_numeriques/taux.yaml)

2026-04-22 07:37 UTC, closed without merging