Ajoute les nouvelles données pour la prise en compte de l'aide AdeFIP…
openfisca/openfisca-france pull request #1544
Opened 2021-05-27 09:48 UTC by mtifarine

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées : `model/revenus/activite/salarie.py`.
* Détails :
  - Crée les variables:
    - cer_ou_ppae
    - formation
    - duree_contrat_ou_formation
    - creation_ou_reprise_entreprise

2021-08-30 14:45 UTC, sandcha requested changes
Merci ! Demande de changement principale : séparer les variables "doubles" ? Cela nécessitera effectivement une mise à jour du côté de la formule AdéFip.

2021-08-30 14:45 UTC, sandcha commented on openfisca_france/model/revenus/activite/salarie.py
> +class cer_ou_ppae(Variable):
Découper les variables `a_ou_b` en deux variables quand elles représentent deux concepts distincts comme ici pour `cer` et `ppae` ?

2021-08-30 22:19 UTC, benjello commented on openfisca_france/model/revenus/activite/salarie.py
> +class cer_ou_ppae(Variable):
Si cette dichotomie n'est pas pertinente ailleurs, je ne pense pas qu'il soit nécessaire de les séparer.

2021-09-23 14:51 UTC, tomy-isabelle commented
PNDS - prise en compte des deux variables distinctes à partir 25/10/21 + France-local.

2021-12-10 10:48 UTC, tomy-isabelle commented
bonjour @sandcha @benjello ,  @mtifarine , @frtomas 
cette PR étant ouverte depuis longtemps, 
nous vous proposons de la merger en l'état,
lorsque la pertinence de la séparation de la variable CER/PPAE sera avéré, alors nous ré-ouvrirons une autre PR pour prise en compte dans OF-France et OF-France-local.
nota : cela nous permettra de merger également la [Integration de l'Adefip et des tests associés #84](https://github.com/openfisca/openfisca-france-local/pull/84). 
merci pour votre retour

2021-12-10 10:58 UTC, benjello commented
@tomy-isabelle : ne vaut-il pas mieux mettre ces variables dans openfisca-france-local comme des variables nationales utilisées seulement dans openfisca-france-local car elles risquent de perturber les utilisateurs de openfisca-france ?

Qu'en pensez vous  @sandcha @mtifarine @frtomas @guillett  ?

2022-10-13 05:34 UTC, guillett commented
Je te rejoins tout à fait @benjello sur le déplacement de cette variable vers https://github.com/openfisca/openfisca-france-local/pull/84

2023-06-27 14:25 UTC, robinguill commented
Je ferme cette PR, la feature se trouve ici : https://github.com/openfisca/openfisca-france-local/pull/84

2023-06-27 14:25 UTC, closed without merging