Harmonisation reduction cotisations sociales
openfisca/openfisca-france pull request #1549
Opened 2021-06-01 15:27 UTC by Sasha-Laniece

* Changement majeur.
* Amélioration technique.
* Périodes concernées : toutes. 
* Zones impactées : toutes
* Détails : Harmonisation du dossier parameters:
  -- Mise à jour de parameters.prelevements_sociaux.reductions_cotisations_sociales
  -- Mise à jour des valeurs et des références (et ajout de nouveaux paramètres) d'après l'IPP

- - - -
- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

2021-06-22 11:44 UTC, sandcha requested changes
Merci @Sasha-Laniece pour toutes ces réductions 😁 
La demande de modification concerne principalement : 
* l'absence du répertoire CITS de l'IPP
* une hétérogénéité du format des références (à vérifier avec les parties prenantes)
* et, plus secondaire, un commentaire sur le CICE qui me semble prêter à confusion.

> Le revue s'est faite par vérification des différences apportées par ces commits via par exemple `git diff --diff-filter=DAR --name-only a3c3f93bf614e26267cb0e96f6b72f29735a650b 235939d4eae783540d1ddd2a24e2445add57d933`), un parcours rapide des fichiers et une comparaison des répertoires de premier niveau avec les barèmes IPP.

2021-06-22 11:44 UTC, sandcha commented on openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/alleg_gen/dispositifs_de_reductions_des_cotisations_famille_1993_1996/0_1_1_smic.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000554907
Appliquer le choix fait pour les références à tous les YAML de la PR ?

2021-06-22 11:44 UTC, sandcha commented on CHANGELOG.md
> +    - Ajoute de nouvelles clefs aux metadata: date_of_issue_oj, description_en, last_review, notes, ux_name
```suggestion
    - Ajoute de nouvelles clefs aux metadata: `official_journal_date`, `description_en`, `last_review`, `notes`, `ux_name`
```

2021-06-22 11:44 UTC, sandcha commented on CHANGELOG.md
> +    - Déplace le contenu de parameters/prelevements_sociaux/
```suggestion
    - Ajoute `parameters/prelevements_sociaux/reductions_cotisations_sociales/`
    - Déplace le contenu de `parameters/prelevements_sociaux/` 
```
Mais ces deux actions sont-elles décorellées ou est-ce purement un déplacement du contenu d'un répertoire vers un autre ? On peut se demander, au-delà de la modification technique, est-ce que l'harmonisation apporte des nouveautés du point de vue métier ? N'apporte-t-elle pas par exemple les paramètres de l'allègement Robien etc. ? Préciser l'apport métier en quelques mots ?

2021-06-22 11:44 UTC, sandcha commented on openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/index.yaml
> +description: Réductions sur les cotisations de Sécurité sociale (SS)
À [ce niveau](https://github.com/openfisca/openfisca-france/tree/235939d4eae783540d1ddd2a24e2445add57d933/openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales), ne nous manque-t-il pas le [répertoire CITS](https://www.ipp.eu/baremes-ipp/prelevements-sociaux/1/reductions_cotisations_sociales/cits/) des barèmes IPP ? 🕵️

2021-06-22 18:46 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
> +        credit_impot_competitivite_emploi = taux_cice * assiette_allegement  # En updatant la formule (>2019) il faudra passer le parametre à null
À mon avis ces questions demandent la création d'une issue qui peut etre reliée à la PR, et sur laquelle il faudra s'appuyer lors de la vérification des formules de cette branche

2021-06-22 18:47 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/alleg_gen/dispositifs_de_reductions_des_cotisations_famille_1993_1996/1_1_1_2_smic.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006657219&cidTexte=JORFTEXT000000529278
Je propose d'en discuter avec @eraviart et pourquoi pas faire une passe sur tous les parametres apres l'harmonisation ?

2021-06-22 18:47 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/index.yaml
> +description: Réductions sur les cotisations de Sécurité sociale (SS)
C'est corrigé !

2021-06-23 08:57 UTC, sandcha commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/activite/taux.yaml
> +  date_of_issue_in_oj:
Mettre à jour vers la dernière version du nom utilisé ailleurs dans cette PR ? 😊 
```suggestion
  official_journal_date:
```

2021-06-23 08:57 UTC, sandcha commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/retraite/taux.yaml
> +  date_of_issue_in_oj:
```suggestion
  official_journal_date:
```

2021-06-23 08:57 UTC, sandcha commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/taux_global.yaml
> +  date_of_issue_in_oj:
```suggestion
  official_journal_date:
```

2021-06-23 08:58 UTC, sandcha commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/crds/taux_global.yaml
> +  date_of_issue_in_oj:
De même s'il existe d'autres occurrences ?

2021-07-08 06:45 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py
> +        credit_impot_competitivite_emploi = taux_cice * assiette_allegement  # En updatant la formule (>2019) il faudra passer le parametre à null
Chose faite, ici : https://github.com/openfisca/openfisca-france/issues/1574

2021-07-08 10:08 UTC, eraviart approved these changes

2021-07-08 10:18 UTC, merged