Harmonisation cotsoc
openfisca/openfisca-france pull request #1553
Opened 2021-06-14 11:27 UTC by Sasha-Laniece

Cette PR fait partie de la série de travaux créant une structure commune de paramètres entre les barèmes IPP et openfisca-france. Ces travaux font le rapprochement de paramètres thème par thème. 

Il s'agit ici d'effectuer ce rapprochement pour les cotisations sociales que ce soit les cotisations salariées (aka `sal`) ou patronales (aka `pat`). Toutefois, nous faisons face à un cas particulier car les paramètres YAML des cotisations sociales sont pré-processés : 
* les paramètres initiaux sont dans le répertoire : [/parameters/cotsoc](https://github.com/openfisca/openfisca-france/tree/363d4f6800c81c5999ad8287033c45b5abbf756a/openfisca_france/parameters/cotsoc)
* le script qui charge en mémoire les paramètres YAML et retravaille leur aborescence pour leur emploi dans les formules python est [preprocessing.py](https://github.com/openfisca/openfisca-france/blob/363d4f6800c81c5999ad8287033c45b5abbf756a/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py)

---

**🚧 TODO**

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

2021-06-14 11:27 UTC, Sasha-Laniece commented
[ Idées : méthode de travail ]

- [ ] Créer un script print_pat_and_sal.py qui va sauvegarder les "parameter_node" actuels (pour référence)
- [ ] Créer une sauvegarde de pat_preprocessed et sal_preprocessed en yaml
- [ ] Faire un test qui vérifiera que le pat et le sal générés par le processing.py (quand on travaillera dessus) sont bien égaux aux pat & sal d'avant modifications
- [ ] Faire un build_pat_v2.py  et build_sal_v2.py qui créent les nouveaux pat et sal qui pointent vers les fichiers parameters au format yaml déjà harmonisés (Avant ET Apres processing.py ?)

2021-07-21 08:00 UTC, sandcha commented
@Sasha-Laniece Voici le fichier qui me sert à la revue et compare avant PR / PR / barèmes IPP : [harmonisation_cotsoc_vers_prelevements_sociaux.pdf](https://github.com/openfisca/openfisca-france/files/6853815/harmonisation_cotsoc_vers_prelevements_sociaux.pdf)

2021-07-21 16:23 UTC, sandcha commented on openfisca_france/parameters/cotsoc/index.yaml
> -description: Cotisations sociales
J'indique ici les `index.yaml` manquants identifiés dans les nouveaux répertoires (à défaut de pouvoir mettre un commentaire GitHub sur les actions de renommage) : 
* prelevements_sociaux/cotisations_secteur_public
  * cnral (ou renommé : cnracl)
  * ircantec
  * ircantec/employeur
  *  mmid
  * mmid/colloc
  * mmid/etat
  * rafp
  * rafp/employeur
  * retraite
  * retraite/ati
  * retraite/pension/employeur

Ajouter ces YAML dans chacun des (sous)répertoires listés ?

2021-07-21 18:55 UTC, sandcha requested changes
Voici également quelques retours concernant la réorganisation des cotisations salarié.

2021-07-21 18:55 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['arti'].children.update(indep.retraite.arti.children)  # À harmoniser ! + Créer params depuis IPP
> On passe aux cotiz de la retraite après le décès ! 😛

2021-07-21 18:55 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    # Microsocial
```suggestion

    # Microsocial
```

2021-07-21 18:55 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['cadre'].children.update(retraites.salarie.cadre.children)
> En réaction aux commentaires présents sur des noeuds où l'on dit qu'il faudra ajouter des paramètres IPP : ne serait-ce pas le cas ici aussi ou est-ce que les paramètres du fichier IPP [agirc_arrco_cet_ceg.yaml](https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml/-/blob/master/parameters/prelevements_sociaux/regimes_complementaires_retraite_secteur_prive/agirc_arrco_cet_ceg.yaml) qui n'a pas son équivalent direct dans notre répertoire `regimes_complementaires_retraite_secteur_prive` mais semble dédié aux cadres sont déjà dans le modèle ? 🤔

2021-07-21 18:55 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    # Microsocial
Comme pour les cotisations patronales, ajouter à tous les répertoires des cotisations salariales les `index.yaml` (même à description vide) correspondants ?
C'est le cas par exemple pour le répertoire de microsocial : 
* `prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur`
Et : 
* les sous-répertoires sur plusieurs niveaux de `cotisations_taxes_independants_artisans_commercants/`
* `cotisations_secteur_public` (déjà évoqué pour les cotisations patronales)
* `cotisations_regime_assurance_chomage` (déjà évoqué pour les cotisations patronales)
* deux niveaux de `regimes_complementaires_retraite_secteur_prive`
> `cotisations_securite_sociale_regime_general` semble ok sur les zones de cette PR.

2021-07-21 18:59 UTC, sandcha commented on openfisca_france/parameters/cotsoc/index.yaml
> -description: Cotisations sociales
De même pour les cotisations patronales et salariales de : 
* `cotisations_secteur_public`
* `cotisations_regime_assurance_chomage`
* deux niveaux de `regimes_complementaires_retraite_secteur_prive`
> `cotisations_securite_sociale_regime_general` semble ok sur les zones de cette PR.

2021-07-25 09:13 UTC, sandcha requested changes
👏 @Sasha-Laniece pour cette harmonisation ! 
La principale demande de vérification pour cette dernière portion de revue concerne un paramètre `seuil` qui apparaît plusieurs fois dans la hiérarchie obtenue.

2021-07-25 09:13 UTC, sandcha commented on CHANGELOG.md
> +* Détails :
Certains paramètres harmonisés ont des longueurs de chemin à la limite de la longueur maximale (164 mais, vérifier si cette longueur de référence doit ou ne doit pas inclure `parameters/` ^^').
Par exemple, ces paramètres ont des paths avec `parameters/` de 169, 168, 167 : 
```
parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/contribution_supplementaire_apprentissage/moins_2000_moins_1pc_alternants.yaml
parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/contribution_supplementaire_apprentissage/multiplicateur_alsace_moselle.yaml
parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/apprentissage/contribution_supplementaire_apprentissage/plus_2000_moins_1pc_alternants.yaml
```

2021-07-26 06:43 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    commun.children['seuil'] = autres.construction.children['seuil']
Bien vu, je l'enlève

2021-07-26 06:44 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    commun.children['apprentissage'] = autres.apprentissage.children['apprentissage']
Enlevé

2021-07-26 06:44 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +from openfisca_core.parameters import ParameterNode
Changé

2021-07-26 06:45 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    chom = node_json.prelevements_sociaux.cotisations_regime_assurance_chomage
Done

2021-07-26 06:54 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    commun.children.update(cotiz.penibilite.bareme.children)  # À harmoniser !
Je suis d'accord avec ta remarque, mais on a beaucoup de paramètres dans ce cas-là -i.e. qui ne sont des cotisations que patronale ou que salariale,- et dans ce cas on n'a pas toujours de distinction dans le chemin de fichier (exemple: prelevements_sociaux/cotisations_securite_sociale_regime_general/css_chom, ou prelevements_sociaux/cotisations_securite_sociale_regime_general/indemnite_fin_contrat, ...). Mais effectivement il semble que parfois ce soit le cas, comme prelevements_sociaux/cotisations_securite_sociale_regime_general/accidents 
Dans ce cas, est-ce qu'on décide d'ajouter cette information partout dans les chemins de fichiers ?
Un risque serait de voir 'employeur' et de penser qu'il manque le paramètre version 'salarié' alors qu'il n'existe pas

2021-07-26 07:05 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    pat.children['fonc'].children['etat'].children.update(public.retraite.pension.employeur.children)
Done

2021-07-26 07:11 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    # Etat
Il me semble qu'il y a avait la volonté de créer des copies temporaires, probablement pour avoir une sauvegarde avant de les retirer de 'fonc' l54:
for var in ['etat', 'colloc', 'contract']:
        del pat.children['fonc'].children[var]
        
Mais comme ce nouveau pat.['fonc'] n'est pas utilisé ailleurs, je pense que c'est oubli ? Il suffirait alors de faire le del en fin de script et on se passe de ces _t

2021-07-26 07:25 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    cotiz = node_json.prelevements_sociaux.cotisations_securite_sociale_regime_general
Changed !

2021-07-26 07:46 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    pat.children['fonc'].children['colloc'].children['hospitaliere'] = public.cnral.employeur.hospitaliere
Done

2021-07-26 08:42 UTC, Sasha-Laniece commented on openfisca_france/parameters/cotsoc/index.yaml
> -description: Cotisations sociales
Ajoutés: les index pour :
- cotisations_secteur_public
- cotisations_regime_assurance_chomage
- regimes_complementaires_retraite_secteur_prive (tous les niveaux)
- autres_taxes_participations_assises_salaires

Même si ces index seront modifiés lors de l'harmonisation (avec ajout des infos côté IPP)

En revanche, pas d'index dans les dossiers /bareme/ car ceux-ci sont voués à disparaître lors de l'harmonisation

2021-07-26 08:42 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    cotiz = node_json.prelevements_sociaux.cotisations_securite_sociale_regime_general
Done

2021-07-26 08:43 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.add_child('noncadre', noncadre)
Effectivement il y a pas mal de doublons. Ils sont voués à disparaître lors de l'harmonisation !

2021-07-26 08:43 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['fonc'].children['colloc'].children.update(public.cnral.salarie.children)
Done

2021-07-26 08:44 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['fonc'].children['commun'].children.update(public.fds.children)  # À harmoniser ! + Créer params depuis IPP
Je ne suis pas contre, mais alors on applique ce principe à tous les paramètres ? (cf. commentaire plus haut)

2021-07-26 08:48 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    # Microsocial
Fait pour:
- cotisations_taxes_independants_artisans_commercants au niveau 1. Au niveau 2 il faudra updater ces index avec les infos issues de l'IPP lors de l'harmonisation
- cotisations_taxes_professions_liberales : idem, niveau 2 à faire lors de l'harmonisation

2021-07-26 09:05 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    # ON GENERE LE DOSSIER COTSOC
Done

2021-07-26 09:06 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    cotsoc.taxes_sal.children.update(autres.taxsal.bareme.children)  # À harmoniser
Oui, c'est confirmé par ton pdf

2021-07-26 09:14 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    chom = node_json.prelevements_sociaux.cotisations_regime_assurance_chomage
Done

2021-07-26 09:16 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['fonc'].children['contract'] = public.ircantec.salarie
Non, on ne peut pas le mettre à jour car on crée le répertoire à ce moment

2021-07-26 09:21 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['cadre'].children.update(retraites.salarie.cadre.children)
Oui, ce sera fait lors de l'harmonisation!

2021-07-26 09:23 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal = build_sal(parameters)
Je ne vois pas (dans ton PDF) où tu vois un même parametre seuil en sixtuple ?

2021-07-26 09:25 UTC, Sasha-Laniece commented on CHANGELOG.md
> +* Détails :
Après vérification :
python openfisca_france/scripts/check_longueur_chemins.py
On est bons !

2021-07-26 09:26 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    commun.children.update(cotiz.mmid.bareme.employeur.children)  # À harmoniser ! + Créer params depuis IPP
Ils sont voués à disparaitre lors de l'harmonisation

2021-07-27 06:04 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    # Etat
Mis en commentaire. Cela pourrait bénéficier d'un travail de lean un jour

2021-07-27 06:06 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['fonc'].children['commun'].children.update(public.fds.children)  # À harmoniser ! + Créer params depuis IPP
Décision: le faire pour fds qui est effectivement le vilain petit canard de son répertoire. Pour les autres dossiers, c'est une question qui pourrait se poser si un jour on décide de se passer de l'arbre virtuel des Cotsoc et de construire les barèmes directement à partir des paramètres

2021-07-27 06:50 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal = build_sal(parameters)
C'est corrigé !

2021-07-27 12:30 UTC, eraviart approved these changes

2021-07-27 15:42 UTC, merged