Harmonisation_pss Plafond de la Sécurité Sociale
openfisca/openfisca-france pull request #1610
Opened 2021-07-28 07:46 UTC by Sasha-Laniece

* Amélioration technique.
* Périodes concernées : toutes. 
* Zones impactées : toutes
* Détails : Harmonisation du dossier parameters.prelevements_sociaux.pss :
  -- Arborescence selon le modèle IPP
  -- Nouveau formatage des fichiers .yaml
  -- Mise à jour des valeurs et des références (et ajout de nouveaux paramètres) d'après l'IPP
  -- Supprime plafond_de_la_securite_sociale.yaml qui est un doublon de plafond_securite_sociale_mensuel
- - - -
Ces changements 
- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

2021-07-29 13:17 UTC, pzuldp reviewed
ça me paraît bien. 

je reste un peu perturbé par cette histoire de preprocessing donc j'espère que ça ne va pas tout casser, mais ça a l'air d'être correctement pris en compte.

je demande quand même l'avis de @clallemand :)

2021-07-29 13:41 UTC, clallemand requested changes
Je pense que tout est OK ! (Sauf les dates de fin dans la description en anglais qu'il faut enlever je pense)

2021-07-29 13:41 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_mensuel.yaml
> +  description_en: Social security ceiling (1930-2016)
Je ne crois pas qu'il y ait une date de fin
```suggestion
  description_en: Social security ceiling
```

2021-07-29 13:41 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_horaire.yaml
> +  description_en: Social security ceiling (1930-2016)
```suggestion
  description_en: Social security ceiling
```

2021-07-29 13:41 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_mensuel.yaml
> +  description_en: Social security ceiling (1930-2016)
```suggestion
  description_en: Social security ceiling
```

2021-07-29 16:21 UTC, pzuldp approved these changes
il y a des ":" dédoublés dans les dates de parution JO

2021-07-29 16:21 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_mensuel.yaml
> +  official_journal_date::
```suggestion
  official_journal_date:
```

2021-07-29 16:21 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_horaire.yaml
> +  official_journal_date::
```suggestion
  official_journal_date:
```

2021-07-29 16:21 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/pss/plafond_securite_sociale_annuel.yaml
> +  official_journal_date::
```suggestion
  official_journal_date:
```

2021-08-02 13:08 UTC, clallemand approved these changes

2021-08-04 13:28 UTC, bfabre01 commented
@Sasha-Laniece : il me semble que cette PR est ok aussi. Peut-on merger ?

2021-08-04 21:26 UTC, Sasha-Laniece commented
Le git rebase master est fait, il reste à faire le git push origin harmonisation_regime_assurance_chomage --force-with-lease pour qui veut demain matin.

2021-08-05 08:23 UTC, SophieIPP approved these changes
Ca me parait tout bon.

2021-08-05 08:36 UTC, merged