Configure variables mensuelles (suite)
openfisca/openfisca-france pull request #1620
Opened 2021-08-02 14:38 UTC by DorineLam

* Changement mineur.
* Périodes concernées : toutes
* Zones impactées : `openfisca_france/model/revenus/activite/salarie.py `.
* Détails :
Ajoute un champ set_input à toutes les variables dont la 'definition_period = MONTH'

2021-08-04 16:47 UTC, DorineLam commented
Bonjour @HAEKADI , j'ai poursuivi l'ajout des set_input dans cette PR, est-ce que je peux me permettre de mettre en review ? Merci beaucoup !

2021-08-05 09:28 UTC, HAEKADI approved these changes

2021-08-05 09:29 UTC, HAEKADI commented
Super, merci @DorineLam 👍 
J'ai exécuté les tests et j'ai lancé l'API, et tout a l'air bon.
Je rajoute juste la liste des zones impactées :

- `model/caracteristiques_socio_demographiques/demographie.py`
- `model/caracteristiques_socio_demographiques/logement.py`
- `model/covid19/activite.py`
- `model/covid19/familles.py`
- `model/covid19/jeunes.py`
- `model/divers/gratuite_musees_monuments.py`
- `model/patrimoine/livret_epargne_populaire.py`
- `model/prelevements_obligatoires/impot_revenu/ir.py`
- `model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py`
- `model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py`
- `model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/versement_transport.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/allegements.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/apprentissage.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/contrat_professionnalisation.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/stage.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique.py`
- `model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py`
- `model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py`
- `model/prestations/agepi.py`
- `model/prestations/aide_permis_demandeur_emploi.py`
- `model/prestations/aides_logement.py`
- `model/prestations/alimentation.py`
- `model/prestations/autonomie.py`
- `model/prestations/cheque_energie.py`
- `model/prestations/depart1825.py`
- `model/prestations/education.py`
- `model/prestations/enseignement_superieur/aide_formation_gen.py`
- `model/prestations/enseignement_superieur/aide_mobilite_internationale.py`
- `model/prestations/enseignement_superieur/bourse_criteres_sociaux.py`
- `model/prestations/jeunes/aides_specifiques.py`
- `model/prestations/jeunes/garantie_jeunes.py`
- `model/prestations/jeunes/garantie_pret_etudiant.py`
- `model/prestations/jeunes/mobili_jeune.py`
- `model/prestations/locapass.py`
- `model/prestations/logement_social.py`
- `model/prestations/minima_sociaux/aah.py`
- `model/prestations/minima_sociaux/ada.py`
- `model/prestations/minima_sociaux/anciens_ms.py`
- `model/prestations/minima_sociaux/asi_aspa.py`
- `model/prestations/minima_sociaux/ass.py`
- `model/prestations/minima_sociaux/cs/acs.py`
- `model/prestations/minima_sociaux/cs/cmu.py`
- `model/prestations/minima_sociaux/cs/css.py`
- `model/prestations/minima_sociaux/cs/eligibilite.py`
- `model/prestations/minima_sociaux/cs/ressources.py`
- `model/prestations/minima_sociaux/ppa.py`
- `model/prestations/minima_sociaux/rsa.py`
- `model/prestations/pass_culture.py`
- `model/prestations/prestations_familiales/af.py`
- `model/prestations/prestations_familiales/asf.py`
- `model/prestations/prestations_familiales/base_ressource.py`
- `model/prestations/prestations_familiales/cf.py`
- `model/prestations/prestations_familiales/paje.py`
- `model/prestations/reduction_loyer_solidarite.py`
- `model/prestations/sante_psy/etudiant.py`
- `model/prestations/transport.py`
- `model/prestations/visale.py`
- `model/revenus/activite/non_salarie.py`
- `model/revenus/remplacement/chomage.py`
- `model/revenus/remplacement/indemnites_journalieres_securite_sociale.py`
- `model/revenus/remplacement/rente_accident_travail.py`
- `model/revenus/remplacement/retraite.py`

2021-08-05 10:17 UTC, DorineLam commented
Merci @HAEKADI Je n'ai donc plus qu'à changer la version et merger ?

2021-08-05 10:39 UTC, DorineLam commented
@HAEKADI J'ai essayé de mettre à jour le changelog, mais je ne comprends pas l'erreur que signale la CI :
J'ai ajouté une version mineure au numéri 66.0.1, mais elle semble m'indiquer que le 66.0.0 est déjà pris, ce qui est vrai mais je n'ai pas utilisé ce numéro ! 🤔

J'ai également effectuée une résolution de conflits : https://github.com/openfisca/openfisca-france/pull/1620/commits/26828c72a44ef3011bdf48ee9bcf6a02852a2b9d
Je veux bien que tu jettes un oeil pour vérifier que j'ai réalisé le merge correctement :)

2021-08-05 11:48 UTC, HAEKADI requested changes

2021-08-05 11:48 UTC, HAEKADI commented on CHANGELOG.md
> +  - Ajoute un champ `set_input` à toutes les variables dont la `definition_period = MONTH`
Il faut garder les changements introduits par master (# 66.0.0 et 65.0.0) 😄 C'est la source de l'erreur.

2021-08-05 11:48 UTC, HAEKADI commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +
C'est laligne qui introduit l'erreur du linting. Il faut la supprimer 😃 
```suggestion
```

2021-08-05 11:48 UTC, HAEKADI commented on CHANGELOG.md
> +  - Ajoute un champ `set_input` à toutes les variables dont la `definition_period = MONTH`
Changer la formulation pour correspondre à la PR précédente ?
```suggestion
  - Configure les variables par mois pour qu'elles fonctionnent avec un input annuel.
```

2021-08-05 11:48 UTC, HAEKADI commented on CHANGELOG.md
> +`openfisca-france/openfisca_france/model/` (liste des fichiers détaillée dans la PR)
Ne pas mentionner explicitement la PR vu qu'elle est déjà mentionnée dans le titre ?
```suggestion
`openfisca-france/openfisca_france/model/`
```

2021-08-05 11:54 UTC, DorineLam commented on CHANGELOG.md
> +  - Ajoute un champ `set_input` à toutes les variables dont la `definition_period = MONTH`
Merci @HAEKADI, j'ai passé en revue toutes les autres remarques mais je bloque sur celle-ci ... Faut il que j'ajoute moi-même quelque chose dans le change.log ?

2021-08-05 12:03 UTC, HAEKADI commented on CHANGELOG.md
> +  - Ajoute un champ `set_input` à toutes les variables dont la `definition_period = MONTH`
En fait ici le fichier change.log n'intègre pas les versions # 66.0.0 et #65.0.0 (tu les as supprimé) qui ont été rajoutées à la branche master. Par conséquent, tu passe de la version ### 64.0.1 directement à la version ### 66.0.1. D'où l'erreur.
Je les ai rajoutées 😄

2021-08-05 12:11 UTC, HAEKADI commented on CHANGELOG.md
> +  - Ajoute un champ `set_input` à toutes les variables dont la `definition_period = MONTH`
Il faut aussi faire l'update du fichier setup.py aussi (c'est la source de l'erreur ^^)

2021-08-05 12:12 UTC, HAEKADI commented on CHANGELOG.md
> +  - Ajoute un champ `set_input` à toutes les variables dont la `definition_period = MONTH`
Je me suis permis de mettre la PR en draft jusqu'à ce qu'on résoud ce problème 😃

2021-08-05 12:21 UTC, HAEKADI approved these changes

2021-08-05 12:49 UTC, merged

2021-08-05 12:50 UTC, DorineLam commented
Merci @HAEKADI il me semble mieux comprendre ce qui doit être fait pour le change.log !