Vérifie une partie des cotisations employeurs de la fonction publique
openfisca/openfisca-france pull request #1622
Opened 2021-08-03 17:13 UTC by bfabre01

* Évolution du système socio-fiscal. | Amélioration technique.
* Périodes concernées : toutes.
* Zones impactées : 
  - `prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_fonction_publique`.
* Détails :
  - Vérifie les formules des cotisations employeurs fonctions publiques présentes dans travail_fonction_publique.py, à l'excpetion de `contribution_exceptionnelle_solidarite`. N'a pas été vérifié non plus les cotisations employeurs de la fonction publique hors de ce fichier, car renvoyant à une formule commune avec les autres secteurs (ex : `mmid_employeur`).
- Renomme plusieurs variables:
   - `allocations_temporaires_invalidite` renommé par `cotisation_ati_atiacl`
   - `fonds_emploi_hospitalier` renommée par `cotisation_fonds_emploi_hospitalier`
   - `pension_civile_salarie` renommée par `cotisation_retraite_base_public_salarie` (qui maintenant inclut les militaires)
   - `pension_civile_employeur` renommée par `cotisation_retraite_base_public_employeur` (qui maintenant inclut les militaires)

2021-08-03 20:37 UTC, pzuldp approved these changes
Looks good to me ! 
FYI : j'ai testé l'API web depuis ma machine en faisant `openfisca serve`, et tout semble fonctionner correctement. Je valide donc également côté API

2021-08-04 06:17 UTC, benjello commented
Pour info, on avait essayé d'omettre le préfixe cotisation pour éviter d'utiliser des acronymes dans le reste du nom de la variable sachant que le nature de cotisation de la variable est assez claire au vu de sa localisation dans la sous arborescence `cotisations_sociales`.

Si on devait changer cela, je pense qu'il faudrait mieux le faire globalement (et éventuellement de le consigner quelque part) et en dehors d'une PR.

2021-08-04 06:27 UTC, pzuldp commented
> Pour info, on avait essayé d'omettre le préfixe cotisation pour éviter d'utiliser des acronymes dans le reste du nom de la variable sachant que le nature de cotisation de la variable est assez claire au vu de sa localisation dans la sous arborescence `cotisations_sociales`.
> 
> Si on devait changer cela, je pense qu'il faudrait mieux le faire globalement (et éventuellement de le consigner quelque part) et en dehors d'une PR.

Je ne savais pas ! (et ce commentaire me concerne, vu ma PR en préparation...) Dans le cas des cotisations chomage ou retraite, est-ce que ça n'introduit pas une confusion possible ? "chomage_salarie" par exemple ?

2021-08-04 07:44 UTC, pzuldp requested changes
Je change ma revue vu le rappel de @Sasha-Laniece ; je n'avais pas pensé à vérifier, mais dans  `parameters.prelevements_sociaux.cotisations_sociales` il y a l'air d'y avoir des doublons non ?

2021-08-04 07:55 UTC, benjello commented
> > Pour info, on avait essayé d'omettre le préfixe cotisation pour éviter d'utiliser des acronymes dans le reste du nom de la variable sachant que le nature de cotisation de la variable est assez claire au vu de sa localisation dans la sous arborescence `cotisations_sociales`.
> > Si on devait changer cela, je pense qu'il faudrait mieux le faire globalement (et éventuellement de le consigner quelque part) et en dehors d'une PR.
> 
> Je ne savais pas ! (et ce commentaire me concerne, vu ma PR en préparation...) Dans le cas des cotisations chomage ou retraite, est-ce que ça n'introduit pas une confusion possible ? "chomage_salarie" par exemple ?

Je ne sais pas quel est la "meilleure" solution. Celle suivie jusqu'ici, pas forcément uniformément d'ailleurs, a des avantages et des inconvénients. Mon point est que si on pense qu'il faut une autre notation je pense qu'il faut mieux le faire en connaissance de cause après analyse mais pas en même temps qu'autre chose.

2021-08-04 09:20 UTC, bfabre01 commented
@pzuldp @benjello : merci !
@pzuldp : j'ai enlevé des doublons en effets. Il n'y a plus de doublons normalement concernant les paramètres des cotisations du champ de cette PR. Après, cette PR n'est pas une PR d'harmonisation. Mais tu as raison, autant virer les doublons direct !
@benjello : ok, ça marche, je suis donc revenu à la convention que tu mentionnes ! Avec quand même des renommages, notamment `pension_civil_salarie` et `pension_civil_employeur` : j'enlève la mention `civil` car ça couvre maintenant les militaires. Et aussi, `allocations_temporaires_invalidite` en `ati_atiacl`. Car l'ancien nom prête trop à confusion (nom de l'allocation qui est financée par les cotisations ATI et ATIACL). Je préfère avoir les acronymes vraiment associés au nom des cotisations (même si le premier est celui de l'alloc aussi :).

2021-08-04 09:28 UTC, benjello commented
@bfabre01 : je ne savais pas que l'on avait aussi l'allocation dans le code.
Peut-être pour être plus clair, on peut ajouter un suffixe (ou même un préfixe) cotisation car j'ai peu

2021-08-04 09:29 UTC, benjello commented
@bfabre01 @pzuldp : pardon pour la fausse manip d'ouverture / fermeture de la PR

2021-08-04 09:51 UTC, pzuldp approved these changes
d'acc

2021-08-04 10:17 UTC, merged