Ajoute une condition d'éligibilité sur l'âge pour le repas à un euro du crous
openfisca/openfisca-france pull request #1636
Opened 2021-08-06 09:30 UTC by Kout95

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2021.
* Zones impactées :
 - `model/prestations/alimentation.py`
 - `parameters/crous_repas_un_euro.yaml`.
* Détails :
  - Ajoute une condition d'éligibilité sur l'âge pour l'aide `crous_repas_un_euro_eligibilite`.

- - - -
- Corrigent ou améliorent un calcul déjà existant.
- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [x] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [x] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2021-08-09 14:47 UTC, guillett requested changes
Merci !

Je trouve qu'une partie de la logique pourrait être déplacée dans variable nouvelle variable booléenne, par exemple `detention_carte_des_metiers` et faire reposer `crous_repas_un_euro_eligibilite` sur cette nouvelle variable.


Les références législatives sont :
- [Article L6325-6-2 - Code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000024410525/2011-07-30/)
- [Article L6325-1 - Code du travail](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031088014/)

2021-08-09 14:47 UTC, guillett commented on openfisca_france/model/prestations/alimentation.py
> +        return eligibilite_scolarite + eligibilite_alternant
J'ai l'impression qu'il ne se passe pas la bonne chose pour un alternant de l'enseignement supérieur de plus de 26 ans.

2021-08-10 10:18 UTC, Kout95 commented on openfisca_france/model/prestations/alimentation.py
> +        return eligibilite_scolarite + eligibilite_alternant
Je viens de corriger ça :)

2021-08-24 09:05 UTC, Kout95 commented
Changelog:
```
## 69.1.0 [#1636](https://github.com/openfisca/openfisca-france/pull/1636)

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2021.
* Zones impactées :
  - `model/prestations/alimentation.py`
  - `parameters/crous_repas_un_euro.yaml`.
* Détails :
  - Ajoute une condition d'éligibilité sur l'âge des alternants pour l'aide `crous_repas_un_euro_eligibilite`.
```

2021-09-09 07:14 UTC, guillett approved these changes
Merci beaucoup @Kout95 !

2021-09-09 07:14 UTC, guillett commented on openfisca_france/parameters/prestations/carte_des_metiers.yaml
> +
Il y a une ligne en trop.

2021-09-09 07:18 UTC, Kout95 commented on openfisca_france/parameters/prestations/carte_des_metiers.yaml
> +
Merci Thomas je corrige ça !

2021-09-09 07:38 UTC, merged