Modification de la zone 2 en 1 pour la ville Trilport
openfisca/openfisca-france pull request #1651
Opened 2021-08-18 14:30 UTC by mtifarine

* Changement mineur.
* Périodes concernées : toutes.
* Zones impactées : `openfisca_france/assets/apl/20110914_zonage.csv`.
* Détails :
  - Modification de la zone 2 en 1 pour la ville Trilport.

2021-08-18 17:16 UTC, benjello commented
@mtifarine : le changement de zone est-il récent ?

2021-08-18 17:19 UTC, benjello commented
Par ailleurs pour les tests ne pourrait-on élargir la période testée (en datant les output si c'est possible @sandcha ?) plutôt qu'en restreignant de facto les tests ?

2021-08-19 18:25 UTC, sandcha reviewed
> Par ailleurs pour les tests ne pourrait-on élargir la période testée (en datant les output si c'est possible @sandcha ?) plutôt qu'en restreignant de facto les tests ?

Par élargissement de la période je comprends qu'il s'agirait de conserver la vérification des outputs en 2021-04 (supprimée pour le moment) et d'y ajouter 2021-01 (nouveauté de cette PR). Est-ce bien ce que tu proposes @benjello ? Et est-ce pour ne pas perdre une date de vérification récente ? 

Si c'est techniquement possible en ajoutant les dates vérifiées aux outputs et en élargissant la période de validité des inputs (avec par exemple `aide_logement: month:2020-10:7: 120 * 7` au dernier test apprenti de `tests/formulas/rsa.yaml`), il me semble que nous perdrions en lisibilité et en précision du calcul. En parallèle, comme `montant_de_base_du_rsa` est revalorisé dans cette PR en avril 2021 et employé dans les bases ressources, il me semble qu'il serait plus intéressant de garder les dates initiales des tests apprenti, c'est à dire, avril 2021.

2021-08-19 18:26 UTC, sandcha commented
> le changement de zone est-il récent ?
Le changement ne serait-il pas lié à l'action en justice évoquée dans [cet article](https://www.leparisien.fr/seine-et-marne-77/logements-sociaux-excede-le-maire-de-trilport-attaque-l-etat-en-justice-18-11-2019-8195505.php) ?

2021-08-19 19:46 UTC, sandcha requested changes, later dismissed
Merci @mtifarine pour la correction de zone et ces revalorisations !
Cette demande de modification concerne une revalorisation qui n'a plus lieu d'être depuis le déplacement d'un paramètre et quelques références qui sont proposées à l'ajout.

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/majconj_plaf/plafond_des_ressources_personnelles_du_conjoint_pour_beneficier_de_la_majoration_pour_personne_a_charge.yaml
> +    value: 10271.95
À défaut d'un lien plus stable : 
```suggestion
    value: 10271.95
    reference: https://www.legislation.cnav.fr/Documents/circulaire_cnav_2021_01_11012021.pdf
```
> Aussi cité dans les [barèmes cnav](https://www.legislation.cnav.fr/Pages/bareme.aspx?Nom=derniere_valeur_derniere_valeur_bar)

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/aspa/montant_annuel_couple.yaml
> +    value: 16893.94
Pas de décret comme en 2020 ? 🤔 Circulaire CNAV (absente des [barèmes IPP](https://www.ipp.eu/baremes-ipp/prestations-sociales/3/minimum_vieillesse_droits_non_contributifs_de_retraite/aspa/) à ce stade) : 
```suggestion
    value: 16893.94
    reference: https://www.legislation.cnav.fr/Documents/circulaire_cnav_2021_01_11012021.pdf
```

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/aspa/montant_annuel_seul.yaml
> +    value: 10881.75
De même, circulaire CNAV : 
```suggestion
    value: 10881.75
    reference: https://www.legislation.cnav.fr/Documents/circulaire_cnav_2021_01_11012021.pdf
```

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/aspa/plafond_ressources_seul.yaml
> +    value: 10881.75
De même : 
```suggestion
    value: 10881.75
    reference: https://www.legislation.cnav.fr/Documents/circulaire_cnav_2021_01_11012021.pdf
```

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/caah/garantie_ressources.yaml
> +    value: 1082.91
> Nous devrions récupérer les références législatives au travers de l'harmonisation avec les barèmes IPP. Néanmoins, la valeur 2021 y est à ce stade [absente](https://www.ipp.eu/baremes-ipp/prestations-sociales/2/invalidite/caah/). cc @benjello

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/caah/garantie_ressources.yaml
> +    value: 1082.91
👍 pour la valeur aussi citée par [service-public](https://www.service-public.fr/particuliers/vosdroits/F12911) : 
```
(...) le complément de ressources est supprimé depuis le 1er décembre 2019. Toutefois, si vous perceviez cette aide jusqu'à cette date, vous continuez d'en bénéficier pendant 10 ans (...)

Le complément de ressources forme avec l'AAH ce que l'on appelle la garantie de ressources. Le montant du complément de ressources est fixé à 179,31 € ce qui porte la garantie de ressources (AAH + complément de ressources) à 1 082,91 € par mois.
```
où 179,31 € est issu de [cette référence](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000019505277/).

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/prestations_familiales/af/bmaf.yaml
> +    value: 414.81
Ajouter la référence au `Bulletin officiel Santé - Protection sociale - Solidarité n° 2021/5 du 31 mars 2021` (page 138) ?
```suggestion
    value: 414.81
    reference: https://solidarites-sante.gouv.fr/fichiers/bo/2021/2021.5.sante.pdf
```

2021-08-19 19:46 UTC, sandcha commented on openfisca_france/parameters/prestations/minima_sociaux/aspa/plafond_ressources_couple.yaml
> +    value: 16893.94
De même : 
```suggestion
    value: 16893.94
    reference: https://www.legislation.cnav.fr/Documents/circulaire_cnav_2021_01_11012021.pdf
```

2021-08-19 19:46 UTC, sandcha commented on tests/formulas/rsa.yaml
> +  period: 2021-01
Conserver la date d'avril pour les tests puisque le montant_de_base_du_rsa est revalorisé en avril ? 🤔

2021-09-27 06:42 UTC, sandcha reviewed
@mtifarine Il n'y a pas de changement sur cette PR depuis la dernière revue. Auriez-vous des commits en local qui n'auraient pas été poussés en remote ? 🤔

2021-09-27 06:42 UTC, sandcha commented on openfisca_france/parameters/cotsoc/gen/plafond_securite_sociale.yaml
> +    value: 3428.0
Cette conversation ne me semble pas résolue sachant que le paramètre `openfisca_france/parameters/cotsoc/gen/plafond_securite_sociale.yaml` est toujours dans la PR. Il va créer un conflit qui peut être résolu au rebase mais il ne faudra en tout cas pas le merger pour éviter un doublon.

2021-09-27 06:42 UTC, sandcha commented on openfisca_france/parameters/prestations/aides_logement/autres/nr_seuil.yaml
> +    value: 24.0
De même, je ne trouve pas de référence pour la mise à jour de ce paramètre.

2021-09-27 13:09 UTC, frtomas commented
@sandcha les 2 commits qui ne concernaient pas Trilport était une petite erreur sur cette branche, ils font partie de [l'autre PR](https://github.com/openfisca/openfisca-france/pull/1542)

Nous les avons retiré.

2021-12-10 11:19 UTC, tomy-isabelle commented
bonjour @benjello , @sandcha ,  @mtifarine , @frtomas 
dans la mesure où il n'y a plus de discussion sur cette PR 
est il possible de la merger s'il vous plait ?
merci

2023-01-11 09:50 UTC, tomy-isabelle commented
bonjour, ci-joint référence qui justifie l'évolution de zone : 

Source :
La commune de Trilport (77) est reclassée de zone II en zone I à partir du 1 juillet 2020

Texte : [Arrêté du 27 mai 2020 modifiant l'arrêté du 17 mars 1978 modifié relatif au classement des communes par zones géographiques](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000041950513)

2023-06-29 15:23 UTC, sandcha commented
Merci @robinguill @frtomas pour la mise au clair de cette PR 🙌 

La règle de nommage du fichier de zonage n'est pas explicite (cf. cet [ancien commentaire de vérification](https://github.com/openfisca/openfisca-france/pull/1651#discussion_r692357890)) mais je vous propose d'en profiter pour définir une règle et renommer `20110914_zonage.csv` (où 2011 ressemble à l'année des débuts d'openfisca) en `20200701_zonage.csv` où le 1er juillet 2020 correspond à la date d'entrée en application de ce zonage. Seriez-vous d'accord pour faire ça ?

2023-07-11 16:11 UTC, robinguill commented
@sandcha avec le renommage pour traçage de la modification du zonage, peut être pouvons nous approuvé les modifications ?
Ou faut il trouver un meilleur moyen de tracer ces changements ?

2023-10-24 06:47 UTC, frtomas commented
@sandcha @benjello @guillett tout les points de cette PR ayant été reglés, peut-elle effectivement être mergée ?
Quelle type de montée de version conseilleriez vous pour ce type de modification portant sur le zonage, qui a priori ne pose pas de problème de compatibilité mais qui n'est pas anodin ?

2023-10-24 08:12 UTC, benjello commented
Cela peut être vu comme une correction de bug, car le résultat était erroné.

2023-10-24 08:12 UTC, benjello approved these changes

2026-04-22 07:37 UTC, closed without merging