Ajout de l'aide carte scnf eleve apprenti
openfisca/openfisca-france pull request #1682
Opened 2021-09-23 08:38 UTC by QuentinMadura

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2021-09-23 12:29 UTC, Kout95 requested changes

2021-09-23 12:29 UTC, Kout95 commented on openfisca_france/model/prestations/transport.py
> +        return (age_apprenti >= age) * apprenti + (age_etudiant >= age) * etudiant
```suggestion
        return (age_apprenti > age) * apprenti + (age_etudiant > age) * etudiant
```
> étudiant de moins de 26 ans ou apprenti de moins de 23 ans

2021-09-23 12:29 UTC, Kout95 commented on openfisca_france/model/prestations/transport.py
> +        return (age_apprenti >= age) * apprenti + (age_etudiant >= age) * etudiant
Pour une relecture plus simple du résultat, je formulerais plus de cette manière :

```
eligibilite_apprenti = (age_apprenti > age) * individu('apprenti', period)
eligibilite_etudiant = (age_etudiant > age) * individu('etudiant', period)

return eligibilite_apprenti + eligibilite_etudiant
```

2021-09-23 12:29 UTC, Kout95 commented on setup.py
> +    version = "74.1.3",
Étant donné le changement, il s'agit plus d'un changement mineur

2021-09-24 08:03 UTC, Kout95 requested changes

2021-09-24 08:03 UTC, Kout95 commented on openfisca_france/model/prestations/transport.py
> +        return (age_apprenti >= age) * apprenti + (age_etudiant >= age) * etudiant
La condition n'est toujours pas bonne. L'age maximal est de 26 ans **non inclus** et moins de 23 ans **non inclus**
```python
 return (age_apprenti > age) * apprenti + (age_etudiant > age) * etudiant
```

2021-09-24 08:07 UTC, Kout95 commented on CHANGELOG.md
> +* Ajout de l'aide carte sncf pour les élèves et les apprentis
Il faut suivre le format du changelog :
- `##` car c'est une version mineure 
- suivre la structure du changelog ex :
```
* Changement mineur.
* Périodes concernées : jusqu'au 31/12/2018 (inclus) à partir du 21/12/2018 (inclus)
* Zones impactées : model/prelevements_obligatoires/prelevements_sociaux/travail_prive.py.
* Détails :
  - Erreur dans l'end_date de 8 cotisation sociales concernées par la fusion Agirc Arrco (agff, agirc, arrco, cet, employeur et salarié)
  ```

2021-09-24 08:50 UTC, desoindx commented on openfisca_france/model/prestations/transport.py
> +        return (age_apprenti >= age) * apprenti + (age_etudiant >= age) * etudiant
je sais pas ce que j'ai fait... désolé :/

2021-09-24 10:36 UTC, Kout95 approved these changes
Merci ! :)

2021-09-24 10:36 UTC, merged