WIP Complète l'aide à la garde d'enfant (AGEPI) de Pôle Emploi
openfisca/openfisca-france pull request #1711
Opened 2021-11-10 17:33 UTC by TomFavrotSopraSteria

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-01-06 19:35 UTC, sandcha commented
Rebase en cours suite à l'harmonisation des paramètres des prestations sociales et du chômage.

2022-01-10 23:06 UTC, sandcha requested changes
Merci @TomFavrotSopraSteria !
Voici quelques demandes de modification indiquées par portion de code. 
> En grisé comme ici les propositions optionnelles.

2022-01-10 23:06 UTC, sandcha commented on openfisca_france/model/prestations/agepi.py
> +        epsilon = 0.0001
> Encore à vérifier (sachant qu'un epsilon est par exemple également employé par l'[age](https://legislation.fr.openfisca.org/age) pour du timedelta).

2022-01-10 23:06 UTC, sandcha commented on openfisca_france/model/prestations/agepi.py
> +        allocation_minimale_mayotte = parameters(period).chomage.allocation_retour_emploi.montant_minimum_mayotte * mayotte
Factoriser l'appel aux paramètres de la période ? 
```suggestion
        parametres_are = parameters(period).chomage.allocation_retour_emploi
        allocation_minimale_hors_mayotte = parametres_are.montant_minimum_hors_mayotte * hors_mayotte
        allocation_minimale_mayotte = parametres_are.montant_minimum_mayotte * mayotte
```

2022-01-10 23:06 UTC, sandcha commented on openfisca_france/model/prestations/agepi.py
> +        allocation_minimale_mayotte = parameters(period).chomage.allocation_retour_emploi.montant_minimum_mayotte * mayotte
De même pour les autres appels aux paramètres employant une portion commune de chemin. 🙂

2022-01-11 11:34 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/agepi.py
> +                individu('lieu_emploi_formation_saint_martin', period)
En effet, le `select` n'est pas utile dans le cas présent.

2022-01-11 15:10 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/agepi.py
> +class TypesContrat(Enum):
Remplacement de `TypesContratDeTravailDuree`  par `TypesContrat`

2022-01-11 15:27 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/agepi.py
> +    intensite_non_valide = "INTENSITE_NON_VALIDE"
Suppression `intensite_non_valide` dans l'enum

2022-01-11 16:16 UTC, TomFavrotSopraSteria commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/agepi.yaml
> +duree_de_formation_minimum:
Ajout d'une description pour chacun des paramètres.

2022-01-12 18:04 UTC, TomFavrotSopraSteria commented on tests/formulas/agepi.yaml
> +        duree_formation: null
La durée de formation n'a en effet pas lieu d'apparaître lorsque le demandeur d'emploi est sur un type de contrat autre que "formation" (cdi, cdd, ctt).
Suppression des variables d'entrées non pertinentes (null) aux tests.

2022-01-17 09:51 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/agepi.py
> +    france_hors_dom_corse = "France hors DOM et hors Corse"
Cette donnée est utile dans l'aide à la mobilité et est une erreur résiduelle de la séparation de commits entre AGEPI et AMOB.
(Dans l'AMOB, il nous est important de préciser le cas d'une action de reclassement située en France uniquement, donc hors DOM et hors Corse)

2022-01-28 17:55 UTC, sandcha approved these changes
Bravo pour cette première PR @TomFavrotSopraSteria 👏 
Nous avons vu ensemble les derniers commits proposés.
Nous pouvons intégrer cette extension de l'AGEPI 🙌

2022-01-28 18:08 UTC, merged