Harmonisation - Prelevements Sociaux - cotisations_taxes_independants_artisans_commercants (Partie 7)
openfisca/openfisca-france pull request #1761
Opened 2021-12-29 09:40 UTC by Sasha-Laniece

* Amélioration technique. 
* Périodes concernées : toutes.
* Zones impactées : `parameters/prelevements_sociaux/cotisations_securite_sociale_regime_general`.
* Détails :
  - Harmonisation des fichiers avec les barèmes-ipp
  - Tous les chemins sont updatés pour ne pas casser le code

- - - -
Ces changements :

- Modifient l'API publique d'OpenFisca France
- Corrigent ou améliorent un calcul déjà existant.
- - - -

2021-12-29 13:15 UTC, Sasha-Laniece commented
FAMILLE
Pour cette partie, on a des choses à modifier pour etre à jour:
- le taux de cotisation a évolué en 2015 pour un bareme plus progressif : https://www.urssaf.fr/portail/home/independant/mes-cotisations/quelles-cotisations/la-cotisation-allocations-famili/base-et-taux-de-la-cotisation-da.html
- le bareme d'avant (1974-1983) n'est pas codé

Choix fait ici: je laisse  l'ancien bareme comme il est et j'ajoute tous les taux commes parametres simples, mais il faudra ensuite en faire un unique bareme

2022-01-04 09:32 UTC, clallemand requested changes
Je remets ici une remarque que j'ai déjà mise mais qui est valable pour un grand nombre de fichiers dans cette PR et que je n'ai pas remis à chaque fois : certaines références législatives ajoutées dans les paramètres me semblent non pertinentes. Ma compréhension est que dans les barèmes IPP il arrive que plusieurs paramètres soient dans la même feuille. La série de références législatives comprend donc des références pour tous ces paramètres. Le moyen de distinguer à quel paramètre la référence correspond est la date de la référence qui correspond à la date de la modification du paramètre.

2022-01-04 09:32 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['arti'].children.update(indep.mmid.arti.children)
```suggestion
```

2022-01-04 09:32 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['arti'].children.update(indep.mmid.arti.children)
Ces chemins issus du preprocessing ne sont pas utilisés non plus il me semble, on peut donc également les supprimer

2022-01-04 09:32 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
>      # Microsocial
```suggestion
    # Microsocial
```

2022-01-04 09:32 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
>      # Microsocial
Même remarque, ces chemins issus du preprocessing ne sont pas utilisés.

2022-01-04 09:32 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/artisans/sous_pss.yaml
> +    2013-01-01:
Il y a des références pour des dates qui ne correspondent à aucune date de changement de valeur du paramètre. Il me semble qu'il s'agit de références pour d'autres paramètres qui étaient dans la même feuille sur les barèmes IPP mais qui sont dans des feuilles distinctes dans openfisca-france. Je pense qu'il faut garder uniquement les références qui concernent le paramètre en question et dont la date correspond donc à une date dans la série du paramètre. A mon sens les références à ce niveau là servent à documenter le changement dans la série uniquement.

2022-01-04 09:32 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/commercants_industriels/deces.yaml
> +    2015-01-01:
Même remarque que précédemment, les références après 2004 ne semblent pas cohérentes ici puisque le paramètre devient nul à cette date. Ce sont des références qui correspondent à des changements d'autres paramètres et qui ne doivent donc pas apparaître ici à mon sens.

2022-01-04 09:32 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/commercants_industriels/invalidite.yaml
> +    2015-01-01:
Même remarque, références législatives qui ne correspondent pas au bon paramètre

2022-01-04 09:59 UTC, clallemand commented
> FAMILLE Pour cette partie, on a des choses à modifier pour etre à jour:
> 
> * le taux de cotisation a évolué en 2015 pour un bareme plus progressif : https://www.urssaf.fr/portail/home/independant/mes-cotisations/quelles-cotisations/la-cotisation-allocations-famili/base-et-taux-de-la-cotisation-da.html
> * le bareme d'avant (1974-1983) n'est pas codé
> 
> Choix fait ici: je laisse l'ancien bareme comme il est et j'ajoute tous les taux commes parametres simples (dans `famille.famille_ind`), mais il faudra ensuite en faire un unique bareme

J'ai l'impression que le plus gros problème à noter et c'est que les paramètres ne sont pas appelées dans les formules. Les paramètres y sont écrits "en dur".

2022-01-04 15:21 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
> +        categorie_non_salarie = individu('categorie_non_salarie', period)
Hello ! Effectivement on s’est déjà posé la question plusieurs fois, avec @sandcha , @pzuldp et @eraviart .

Au début je supprimais toutes les références qui ne correspondaient pas à une date avec une value

Et en fait on s’est rendu compte que dans certains cas, il y avait des changements de législation qui méritaient d’être indiqués, mais qui ne changeaient pas la value. Et donc on a des références postérieures à la value

Par exemple: si l’article change d’endroit au cours du temps, cela permet de le retrouver et de vérifier qu’entre la création et aujourd’hui, la valeur est bien toujours restée identique


Suite à cela on a décidé que lors de l’harmonisation, à défaut d’avoir le temps d’ouvrir toutes les references à la main pour vérifier à quel parametre elles s’appliquent, on copie tout, et si quelqu’un veut faire un tri, il en a la possibilité ensuite.

2022-01-04 15:43 UTC, bfabre01 commented
@Sasha-Laniece Je suis d'accord avec @clallemand. On ne peut pas laisser pour un paramètre toutes les références présentes dans les fichiers barèmes IPP y compris celles associées à d'autres paramètres qui sont dans la même feuille barème IPP. Cela rendrait l'information non fiable et non-pertinente. Certes, cela alourdit la procédure, mais c'est comme ça. On ne peut pas laisser toutes les références et dire que quelqu'un fera le tri plus tard, comme cela est suggéré... Si le but est d'avoir dans Openfisca des fichiers de paramètres avec la législation correspondante à ce paramètre, alors il faut aller un minimum jusqu'au bout.
Après, il y a surement un moyen d'automatiser ce tri, ou au moins une bonne partie. @eraviart @sandcha , qu'en pensez-vous ? @eraviart, @pzuldp m'a dit que vous en aviez discuté.

2022-01-04 15:46 UTC, Sasha-Laniece commented
> @Sasha-Laniece Je suis d'accord avec @clallemand. On ne peut pas laisser pour un paramètre toutes les références présentes dans les fichiers barèmes IPP y compris celles associées à d'autres paramètres qui sont dans la même feuille barème IPP. Cela rendrait l'information non fiable et non-pertinente. Certes, cela alourdit la procédure, mais c'est comme ça. On ne peut pas laisser toutes les références et dire que quelqu'un fera le tri plus tard, comme cela est suggéré... Si le but est d'avoir dans Openfisca des fichiers de paramètres avec la législation correspondante à ce paramètre, alors il faut aller un minimum jusqu'au bout. Après, il y a surement un moyen d'automatiser ce tri, ou au moins une bonne partie. @eraviart @sandcha , qu'en pensez-vous ? @eraviart, @pzuldp m'a dit que vous en aviez discuté.

Je suis pour une automatisation, mais je vois mal comment vérifier à quel paramètre se rapportent les references... Si on est sur les articles, on pourrait envisager une recherche par montant/value. Mais sur les décrets ça me semble impossible

2022-01-04 16:26 UTC, bfabre01 commented
> 

@Sasha-Laniece : déjà, je pense qu'il serait possible de ne garder que les références associées aux dates des values du paramètre. J’imagine que ceci peut s'automatiser ? Après cette opération, les seuls cas qui resteraient à traiter à la main seraient les cas où pour une même date, il y a plusieurs références (car changements de plusieurs paramètres d'un même fichier yaml de barème IPP). Mais il ne doit pas y avoir beaucoup de cas comme ça.

2022-01-04 16:50 UTC, pzuldp requested changes

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/art_ind_com/montant_du_plafond_rci.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000498711&categorieLien=id
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/art_ind_com/montant_du_plafond_rci.yaml
> +    1985-01-01: 1984-12-02
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/art_ind_com/sous_plafond_rci.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000498711&categorieLien=id
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/art_ind_com/sous_plafond_rci.yaml
> +    1985-01-01: 1984-12-02
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/entre_1_et_4_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000498711&categorieLien=id
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/entre_1_et_4_pss.yaml
> +    1978-01-01: 1978-03-19
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_1_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000498711&categorieLien=id
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_1_pss.yaml
> +    1978-01-01: 1978-03-19
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_3_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006771716&cidTexte=JORFTEXT000000382287
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_3_pss.yaml
> +    1999-01-01: 1997-02-26
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_3_pss.yaml
> +    2004-01-01: Pour les industriels et commerçants, taux de 3,5% sous 3 PSS pour le 1er semestre 2004, et 4,5% sous 3 PSS pour le 2ème semestre 2004
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_4_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000498711&categorieLien=id
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_4_pss.yaml
> +    1978-01-01: 1978-03-19
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_4_pss.yaml
> +    2004-01-01: Pour les industriels et commerçants, taux de 3,5% sous 3 PSS pour le 1er semestre 2004, et 4,5% sous 3 PSS pour le 2ème semestre 2004
```suggestion
```

2022-01-04 16:50 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/industriels_commercants/sous_3_pss.yaml
> +    1978-01-01: 1978-03-19
```suggestion
```

2022-01-04 16:54 UTC, Sasha-Laniece commented
> > 
> 
> @Sasha-Laniece : déjà, je pense qu'il serait possible de ne garder que les références associées aux dates des values du paramètre. J’imagine que ceci peut s'automatiser ? Après cette opération, les seuls cas qui resteraient à traiter à la main seraient les cas où pour une même date, il y a plusieurs références (car changements de plusieurs paramètres d'un même fichier yaml de barème IPP). Mais il ne doit pas y avoir beaucoup de cas comme ça.

Cette méthode n'est pas utilisée pour les raisons expliquées ici: https://github.com/openfisca/openfisca-france/pull/1761#discussion_r778165484

Sinon bien sûr qu'on aurait fait comme ça, trop facile !

2022-01-04 17:17 UTC, bfabre01 commented
> > > 
> > 
> > 
> > @Sasha-Laniece : déjà, je pense qu'il serait possible de ne garder que les références associées aux dates des values du paramètre. J’imagine que ceci peut s'automatiser ? Après cette opération, les seuls cas qui resteraient à traiter à la main seraient les cas où pour une même date, il y a plusieurs références (car changements de plusieurs paramètres d'un même fichier yaml de barème IPP). Mais il ne doit pas y avoir beaucoup de cas comme ça.
> 
> Cette méthode n'est pas utilisée pour les raisons expliquées ici: [#1761 (comment)](https://github.com/openfisca/openfisca-france/pull/1761#discussion_r778165484)
> 
> Sinon bien sûr qu'on aurait fait comme ça, trop facile ! :)




> > > 
> > 
> > 
> > @Sasha-Laniece : déjà, je pense qu'il serait possible de ne garder que les références associées aux dates des values du paramètre. J’imagine que ceci peut s'automatiser ? Après cette opération, les seuls cas qui resteraient à traiter à la main seraient les cas où pour une même date, il y a plusieurs références (car changements de plusieurs paramètres d'un même fichier yaml de barème IPP). Mais il ne doit pas y avoir beaucoup de cas comme ça.
> 
> Cette méthode n'est pas utilisée pour les raisons expliquées ici: [#1761 (comment)](https://github.com/openfisca/openfisca-france/pull/1761#discussion_r778165484)
> 
> Sinon bien sûr qu'on aurait fait comme ça, trop facile ! :)

2022-01-04 17:21 UTC, Sasha-Laniece commented
> @Sasha-Laniece Oui, j'avais vu ce commentaire. Mais normalement, de tels cas évoqués ne sont pas dans les barèmes IPP. Il y a des références législatives seulement au moment du changement d'une valeur, et jamais entre les deux. Alors certes, il y a peut-être quelques rares cas, qui combine à la fois : (1) un déplacement de texte, (2) une mention de ce déplacement car le timing colle avec le changement de valeur d'un autres paramètre de la même feuille, et que les deux paramètres ont subi le même déplacement. Mais cela doit vraiment être très marginal, pas de quoi adopter une stratégie qui remettrait en cause toute la pertinence du contenu d'un fichier de paramètres, avec des références non associées au paramètre. Et quand bien même un déplacement est évoqué dans les barèmes hors du cas évoqué, ça me semble être un effet vraiment très marginal.

Ok alors supprimons les references en trop par moulinette. Et tant pis pour les rares qui seront perdues. De toute façon je crois qu'il va falloir faire un deuil sur l'idée de pouvoir vérifier les valeurs simplement

2022-01-04 19:10 UTC, sandcha commented
@bfabre01 @clallemand est-ce que vous confirmez que vous souhaitez supprimer les références sans valeur dans les barèmes IPP ? Et au-delà de cette PR, que ce serait pour tous les thèmes (comme par exemple pour [smic/nb_heures_travail_mensuel.yaml](https://github.com/openfisca/openfisca-france/blob/db3009d4485bd2a297934a76670c854959724889/openfisca_france/parameters/marche_travail/salaire_minimum/smic/nb_heures_travail_mensuel.yaml) ?

2022-01-05 11:34 UTC, eraviart commented
Pour pouvoir enlever automatiquement les références en trop, il faut commencer par réorganiser automatiquement les paramètres.

Je viens de commettre un brouillon de PR pour en discuter : #1774

Parmi les sujets à creuser, il y a l'ordre des champs dans les YAML (faut-il mettre les values avant ou après les metadata,, etc), l'ordre des dates, etc, sachant qu'une fois qu'on a un script de réorganisation automatique, c'est facile à changer par la suite.

Quand cette PR sera acceptée, j'en ferai une autre pour supprimer les références sans value.

2022-01-05 12:07 UTC, Sasha-Laniece commented
J'ai l'impression que pour le moment, le plus courant est le format suivant:
```
description:
values:
    2021-01-01:
        value: 12.0
metadata:
    ux_name:
    ipp_csv_id:
    unit:
    reference:
    official_journal_date:
    notes:
documentation:
```
Je fais des commentaires séparés en-dessous pour que l'on puisse discuter (et voter 👍  ou 👎) facilement

2022-01-05 12:08 UTC, Sasha-Laniece commented
Je suis assez pour garder la description en 1er, pour savoir de quoi on parle et avoir le contexte

2022-01-05 12:08 UTC, Sasha-Laniece commented
Les `values` en 2e, ça me semble cohérent, car c'est ce qu'on vient chercher dans le paramètre

2022-01-05 12:13 UTC, Sasha-Laniece commented
Ensuite dans les `metadata`, si on doit réorganiser, je le mettrais par ordre d'informations utiles apportées, soit:

1.  le `ux_name` : récap du paramètre
2.  le `unit` : de quoi parle-t-on?
3. le `ipp_csv_id` (qui est une autre forme de recap)
4. les `notes` (ça peut etre pas mal de les remonter car on a souvent des infos utiles qui sont un peu cachées)
5. les `references` (si on fait des recherches specifiques)
6. `official_journal_date` car c'est assez spécifique comme besoin
7. la `documentation` car ce peut etre un paragraphe important qui "cacherait" tout ce qui est dessous

2022-01-05 12:18 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
> +        categorie_non_salarie = individu('categorie_non_salarie', period)
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:19 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/artisans/sous_pss.yaml
> +    2013-01-01:
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:19 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/commercants_industriels/invalidite.yaml
> +    2015-01-01:
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:19 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/commercants_industriels/deces.yaml
> +    2015-01-01:
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:19 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/entre_10_000_frf_et_1_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000332517&categorieLien=id
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/entre_10_000_frf_et_1_pss.yaml
> +    1982-04-01: 1982-03-31
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_4_pss.yaml
> +    2009-01-01: 2007-12-30
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_4_pss.yaml
> +    1978-01-01: 1978-03-19
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/artisans/sous_4_pss.yaml
> +    2004-01-01: Pour les industriels et commerçants, taux de 3,5% sous 3 PSS pour le 1er semestre 2004, et 4,5% sous 3 PSS pour le 2ème semestre 2004
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/industriels_commercants/sous_3_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000498711&categorieLien=id
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/ret_comp_ac/industriels_commercants/sous_3_pss.yaml
> +    1978-01-01: 1978-03-19
Je ferme cette conversation qui dépasse du champ de cette PR et est donc ouverte ici: https://github.com/openfisca/openfisca-france/pull/1774

2022-01-05 12:27 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py
> +        categorie_non_salarie = individu('categorie_non_salarie', period)
Commité!

2022-01-05 12:30 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['arti'].children.update(indep.mmid.arti.children)
Pour moi il sont utilisés via l'appel des différent barèmes du preprocessing, donc ici:
https://github.com/openfisca/openfisca-france/blob/f28f66938fbfe6580a44ff63f67514064be8d911/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py#L263

Est-ce que ça te semble cohérent ?

2022-01-05 12:31 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
>      # Microsocial
De même, pour les MMID je le vois ici:
https://github.com/openfisca/openfisca-france/blob/f28f66938fbfe6580a44ff63f67514064be8d911/openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_non_salarie.py#L141-L165

Est-ce que ça te semble cohérent ?

2022-01-05 12:39 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/preprocessing.py
> +    sal.children['arti'].children.update(indep.mmid.arti.children)
Cf. Commentaire: https://github.com/openfisca/openfisca-france/pull/1761#issuecomment-1005650741

2022-01-05 12:42 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/entre_10_000_frf_et_1_pss.yaml
> +    2015-01-01: "Modulation des taux selon le revenu : si 110 % PSS < revenu d'activité ( r ) < 140 % PSS, taux égal à [(T2 - T1) /(0,3 x PSS)] x (r - 1,1 x PSS) + T1 , où T2 = 5,25 %, T1 = 2,15 %"
Commité ! a6f55691dc034b3

2022-01-05 12:42 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/revenu_professionnel_total.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000718256&categorieLien=id
cf [#1774](https://github.com/openfisca/openfisca-france/pull/1774)

2022-01-05 12:43 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/revenu_professionnel_total.yaml
> +    2018-01-01: 2017-12-31
cf [#1774](https://github.com/openfisca/openfisca-france/pull/1774)

2022-01-05 12:43 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/revenu_professionnel_total.yaml
> +    1982-04-01: Décret 82-292 du 30/03/1982
cf [#1774](https://github.com/openfisca/openfisca-france/pull/1774)

2022-01-05 12:43 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/revenu_professionnel_total.yaml
> +    1991-02-01: 1991-01-24
cf [#1774](https://github.com/openfisca/openfisca-france/pull/1774)

2022-01-05 12:43 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/revenu_professionnel_total.yaml
> +    1982-04-01: 1982-03-31
cf [#1774](https://github.com/openfisca/openfisca-france/pull/1774)

2022-01-05 12:45 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/revenu_professionnel_total.yaml
> +    2015-01-01: "Modulation des taux selon le revenu : si 110 % PSS < revenu d'activité ( r ) < 140 % PSS, taux égal à [(T2 - T1) /(0,3 x PSS)] x (r - 1,1 x PSS) + T1 , où T2 = 5,25 %, T1 = 2,15 %"
Commité 87d88850bd

2022-01-05 12:45 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/si_revenu_d_activite_110_pss.yaml
> +    1982-04-01: 1982-03-31
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/si_revenu_d_activite_140_pss.yaml
> +    1982-04-01: Décret 82-292 du 30/03/1982
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/sous_10_000_frf.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000332517&categorieLien=id
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/sous_pss.yaml
> +      href: https://www.legifrance.gouv.fr/eli/decret/2013/12/27/2013-1290/jo/texte
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/formation_ac/artisans/sous_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000026290023&cidTexte=JORFTEXT000026288927
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/formation_ac/artisans/sous_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006522444&cidTexte=JORFTEXT000000452052
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/formation_ac/commercants_industriels/sous_pss.yaml
> +    2000-01-01: 1999-12-31
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/formation_ac/commercants_industriels/sous_pss.yaml
> +      href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000762233
#1774

2022-01-05 12:46 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/famille/famille_ind/sous_pss.yaml
> +    2014-01-01: 2013-12-31
#1774

2022-01-05 12:48 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/mmid/mmid_ac/assures_actifs/dela_5_pss.yaml
> +    value: null
Bonne question, ça vient de chez vous, je l'ai repris car je me suis dit que vous aviez probablement une bonne raison et je ne voulais rien casser post-harmonisation :)

2022-01-05 12:51 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/mmid/mmid_ac/assures_actifs/index.yaml
> +  - entre_11_5_pss_2
Je crois que l'ordre est utilisé dans les baremes-ipp pour pouvoir sortir le site internet. On nous a demandé de le garder tel quel. Je le place donc à travers la hierarchie d'index de façon à respecter le plus possible l'ordre de vos barmes

2022-01-05 12:53 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/mmid/mmid_ac/assures_actifs/index.yaml
> +  - entre_11_5_pss_2
Je le note dans le commentaire en bas de la PR. On va ouvrir une issue dédiée car on dépasse la simple Harmonisation

2022-01-05 13:13 UTC, Sasha-Laniece commented
La revue a soulevé plusieurs point, donc je fais un récap ici:

1 - @bfabre01 , @clallemand et @pzuldp , vous avez soulevé le problème des références "hors changement de valeur". Après discussion, il a été décidé de les supprimer avec un script automatique. @eraviart a commencé à mettre cela en place [ici #1774](https://github.com/openfisca/openfisca-france/pull/1774) et ce sera donc appliqué postérieurement au merge de cette PR.

2 - @clallemand et @pzuldp vous soulignez que les paramètres des cotisations `famille` et `mmid` des indépendants sont partiellement modélisées, et il y a une amélioration métier à faire. Cela sortant du cadre de l'harmonisation, j'ai ouvert [l'issue ](https://github.com/openfisca/openfisca-france/issues/1775) pour reporter ce problème. Je propose que les modifications du `preprocessing.py` et de `travail_non_salarie.py` soient faites à ce moment-là par la personne qui remodélisera cela (avec ou sans barème).

J'ai ajouté les commentaires qui concernaient directement l'harmonisation.

Est-ce que @pzuldp et @clallemand la PR vous convient en l'état ? Si oui, pourriez-vous mettre à jour votre review ?

2022-01-06 21:04 UTC, clallemand commented
> @bfabre01 @clallemand est-ce que vous confirmez que vous souhaitez supprimer les références indiquées aux dates où il n'y a pas de (nouvelle) valeur dans les barèmes IPP ? Et au-delà de cette PR, que ce serait pour tous les thèmes (comme par exemple pour [smic/nb_heures_travail_mensuel.yaml](https://github.com/openfisca/openfisca-france/blob/db3009d4485bd2a297934a76670c854959724889/openfisca_france/parameters/marche_travail/salaire_minimum/smic/nb_heures_travail_mensuel.yaml)) ?
> 
> Ou est-ce que vous voyez ceci autrement ? Cette question pour vérifier que la suppression ne créera pas d'écart avec les barèmes 🙂

Oui je confirme que dans la très grande majorité des barèmes IPP il y a une référence législative uniquement lorsqu'il y a une nouvelle valeur dans les barèmes donc la suppression peut s'étendre à l'ensemble des thèmes (comme le SMIC)

2022-01-06 21:04 UTC, clallemand commented
> La revue a soulevé plusieurs points, donc je fais un récap ici:
> 
> 1 - @bfabre01 , @clallemand et @pzuldp , vous avez soulevé le problème des références "hors changement de valeur". Après discussion, il a été décidé de les supprimer avec un script automatique. @eraviart a commencé à mettre cela en place [ici #1774](https://github.com/openfisca/openfisca-france/pull/1774) et ce sera donc appliqué postérieurement au merge de cette PR. Vous pouvez d'ailleurs donner votre avis sur le résultat voulu directement sur cette PR.
> 
> 2 - @clallemand et @pzuldp vous soulignez que les cotisations `famille` et `mmid` des indépendants sont partiellement modélisées, et il y a une amélioration métier à faire. Cela sortant du cadre de l'harmonisation, j'ai ouvert [l'issue #1775 ](https://github.com/openfisca/openfisca-france/issues/1775) pour reporter ce problème. Je propose que les modifications du `preprocessing.py` et de `travail_non_salarie.py` soient faites à ce moment-là par la personne qui remodélisera cela (avec ou sans barème).
> 
> J'ai ajouté les commentaires qui concernaient directement l'harmonisation.
> 
> Est-ce que @pzuldp et @clallemand la PR vous convient en l'état ? Si oui, pourriez-vous mettre à jour votre review ?

tout cela me convient !

2022-01-06 21:05 UTC, clallemand approved these changes

2022-01-07 09:34 UTC, pzuldp approved these changes

2022-01-07 10:42 UTC, merged

2022-01-07 11:21 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/mmid/mmid_ac/assures_actifs/dela_5_pss.yaml
> +    value: null
:) on en découvre tous les jours

2022-01-07 11:22 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/mmid/mmid_ac/assures_actifs/index.yaml
> +  - entre_11_5_pss_2
oui bonne idée

2022-01-07 11:22 UTC, pzuldp commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/mmid/mmid_ac/assures_actifs/index.yaml
> +  - entre_11_5_pss_2
merci