Ajoute l'aide à la mobilité de Pôle Emploi
openfisca/openfisca-france pull request #1765
Opened 2021-12-30 15:31 UTC by TomFavrotSopraSteria

* Évolution du système socio-fiscal
* Périodes concernées : à partir du 09/06/2021.
* Zones impactées : `/model/prestations/amob.py`.
* Détails :
  - Créer l'aide à la mobilité de Pôle Emploi.
  - Renomme la variable `contrat_de_travail_duree` en `contrat_de_travail_type` (CDI, CDD, CTT)
  - Créer la variable `contrat_de_travail_duree` (durée du contrat en mois)

- - - -

Ces changements:

- Modifient l'API publique d'OpenFisca France (renommage d'un énuméré et création de variable).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2021-12-30 16:28 UTC, TomFavrotSopraSteria commented
Rebase en cours pour résoudre les conflits suite à l'harmonisation.

2021-12-30 20:51 UTC, Sasha-Laniece commented
> Rebase en cours pour résoudre les conflits suite à l'harmonisation.

Hello Tom ! Bien vu, un gros travail est en cours. J'ai essayé de faire ça pendant les vacances pour que vous n'ayez pas trop de conflits à gérer.

J'ai fini les prélèvements sociaux (quelques PR sont encore en attente de revue), demain je m'attaque aux minimas sociaux. Si vous avez envie de merger des trucs pour éviter les conflits, c'est le moment ! 😅

2022-01-20 08:14 UTC, sandcha requested changes
Merci @TomFavrotSopraSteria pour la modélisation de cette nouvelle aide 🙌 
Voici quelques retours sur la structure. J'ai également poussé des correctifs de linting mineurs (un `git pull` te sera donc utile avant de modifier le code).

2022-01-20 08:14 UTC, sandcha commented on openfisca_france/model/prestations/amob.py
> +        residence_renseignee = not_(lieu_de_residence == TypesLieuResidence.non_renseigne)
👍 Bien vu !

2022-01-20 08:14 UTC, sandcha commented on openfisca_france/model/prestations/amob.py
> +        distance_minimum_hors_metropole = amob_parametres.distance_minimum.hors_metropole
> Ces variable auxiliaires sont-elles nécessaires ? Elles prennent une case mémoire mais ne sont employée qu'une fois et leur nom est comparable en longueur à leur valeur, non ?

2022-01-20 08:14 UTC, sandcha commented on openfisca_france/model/prestations/amob.py
> +                                                    + ((temps_de_trajet > temps_de_trajet_min) * residence_renseignee))
N'est-ce pas un ET vérification du temps de trajet ?

2022-01-20 08:14 UTC, sandcha commented on openfisca_france/model/prestations/amob.py
> +                                                    + ((temps_de_trajet > temps_de_trajet_min) * residence_renseignee))
> En cette ligne et cette étape de l'équation, la résidence n'est-elle pas toujours renseignée ? Le vérifier ?

2022-01-20 08:14 UTC, sandcha commented on openfisca_france/model/prestations/amob.py
> +        duree_de_contrat_3_mois_minimum = individu('contrat_de_travail_duree', period) >= 3
La durée de 3 mois n'est-elle pas un paramètre de l'aide mobilité ? ^^ L'extraire ?

2022-01-21 14:12 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/amob.py
> +    default_value = date(1870, 1, 1)
Modification avec la date du lendemain de la délibération de l'aide mobilité publiée au Bulletin officiel de Pôle emploi.
("Elle s’applique aux demandes d’aide à la mobilité formulées à compter du lendemain de cette publication, quelle que soit la date du fait générateur").

2022-01-21 15:44 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/amob.py
> +class distance_aller_retour_activite_domicile(Variable):
Ce n'est pas simplement la distance domicile-activité mais bien **deux fois** cette distance pour le calcul de l'éligibilité de l'aide à la mobilité :)

2022-01-21 16:11 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/amob.py
> +                                                    + ((temps_de_trajet > temps_de_trajet_min) * residence_renseignee))
Non il s'agit bien d'un OU 
[condition de distance] "ou deux heures de trajet aller‑retour du lieu de résidence du demandeur d’emploi"

2022-01-24 11:37 UTC, TomFavrotSopraSteria commented on openfisca_france/model/prestations/amob.py
> +class aide_mobilite_montant_percu_12_derniers_mois(Variable):
Suppression de la variable `aide_mobilite_montant_percu_12_derniers_mois` et utilisation de : 

`annee_glissante = period.start.period('year').offset(-1)`
`aide_mobilite_12_derniers_mois = individu('aide_mobilite', annee_glissante, options=[ADD])`

D'autres formules laissent apparaître l'année glissante renseignée comme ceci : 
`annee_glissante = period.start.period('year').offset(-1).offset(-1, 'month')`

Je ne comprends pas le `offset(-1, 'month')`

Si je fais une simulation à la période suivante : 2021-12
Je m'attends à avoir une année glissante jusqu'à 2020-12 (avec 12 mois pris de 2021-11 jusqu'à 2020-12 et non pas 2020-11).

2022-01-31 18:36 UTC, sandcha requested changes
Merci pour ces correctifs
> Pour partager le contexte, voici les derniers retours évoqués en réunion et déjà en cours d'application.

2022-01-31 18:36 UTC, sandcha commented on openfisca_france/model/prestations/aide_mobilite.py
> +        ]
```suggestion
    reference = "http://www.bo-pole-emploi.org/bulletinsofficiels/deliberation-n-2021-42-du-8-juin-2021-bope-n2021-43.html?type=dossiers/2021/bope-n-2021-043-du-11-juin-2021"
```

2022-01-31 18:36 UTC, sandcha commented on openfisca_france/model/prestations/aide_mobilite.py
> +    label = "Les différents contextes d'activité pour le calcul de l'aide à la mobilité de Pôle Emploi - AMOB "
N'est-ce pas valable hors AMOB ? Définir un libellé qui désigne le sens d'une valeur unique ?
```suggestion
    label = "Le contexte d'activité au sens de Pôle Emploi"
```

2022-01-31 18:36 UTC, sandcha commented on openfisca_france/model/prestations/aide_mobilite.py
> +    label = "Attribution d'un bon de transport dans un contexte précis - AMOB"
Comment interpréter `dans un contexte précis` en tant que définition ? 🤔 Proposition :
```suggestion
    label = "Eligibilité à un bon de transport, part de l'aide à la mobilité de Pôle emploi (AMOB)"
```

2022-01-31 18:36 UTC, sandcha commented on tests/formulas/aide_mobilite.yaml
> +    allocation_retour_emploi: 29.56
`allocation_retour_emploi` est définie comme une variable mensuelle employée par `chomage_brut` et les bases de ressources comme telle. 
Je vois plusieurs possibilités sachant que l'AMOB et Pôle emploi traitent d'une valeur journalière d'ARE : 
1. Dans l'AMOB (et l'AGEPI, oops 😬), conserver l'utilisation de `allocation_retour_emploi` mais la diviser par un nombre de jours où elle est perçue dans le mois. Question : quel nombre de jours fera fois ?
2. Redéfinir `allocation_retour_emploi` comme valeur journalière comme le fait Pôle emploi dont c'est le coeur de métier et adapter toutes ses réutilisations dans le modèle (via `chomage_brut`) en la multipliant par un nombre de jours afin d'obtenir une valeur mensuelle. Question : quel nombre de jours fera fois ?
3. Considérer qu'il y a deux visions qui cohabitent de l'ARE. La gestion administrative qui calcule l'ARE d'après le salaire journalier de référence (SJR, cf. [service-public pour le salarié du privé](https://www.service-public.fr/particuliers/vosdroits/F14860)) et le demandeur d'emploi + autres administrations évaluant les ressources des individus qui parlent de montant mensuel du chômage. Dans ce cas, la variable `allocation_retour_emploi` peut cohabiter avec une autre variable `allocation_retour_emploi_journaliere` permettant aux réutilisateur d'affecter un nombre de jours applicables adaptés à la situation traitée (et, plus tard, à openfisca-france d'estimer un calcul de jour à mois selon les jours ouvrés ou un autre critère vérifié.

Qu'en dites-vous ? Voyez-vous d'autres options ?

2022-01-31 18:36 UTC, sandcha commented on openfisca_france/model/prestations/aide_mobilite.py
> +    label = "Calcul du montant de l'aide à la mobilité - AMOB"
Tout n'est-il pas calcul par ici ? 😁 
```suggestion
    label = "Montant de l'aide à la mobilité de Pôle emploi - AMOB"
```

2022-01-31 18:37 UTC, sandcha commented on openfisca_france/model/prestations/aide_mobilite.py
> +        #  Le durée de contrat de l'emploi doit être d'au moins 3 mois
```suggestion
        #  La durée de contrat de l'emploi doit être d'au moins 3 mois
```

2022-01-31 18:50 UTC, sandcha commented on tests/formulas/aide_mobilite.yaml
> +    allocation_retour_emploi: 29.56
Option 3 appliquée ici.

2022-01-31 19:15 UTC, sandcha commented on openfisca_france/model/prestations/amob.py
> +class aide_mobilite_montant_percu_12_derniers_mois(Variable):
> Si je fais une simulation à la période suivante : 2021-12
Je m'attends à avoir une année glissante jusqu'à 2020-12 (avec 12 mois pris de 2021-11 jusqu'à 2020-12 et non pas 2020-11).

C'est bien ce qui est fait.

2022-01-31 19:24 UTC, sandcha approved these changes
Merci @TomFavrotSopraSteria pour ces correctifs et cette nouvelle aide pôle emploi !

2022-01-31 19:44 UTC, merged