Correction des Plus-Values de Cession pour les Non-Salariés
openfisca/openfisca-france pull request #1787
Opened 2022-01-17 14:44 UTC by lukas-puschnig

* Changement mineur.
* Périodes concernées : toutes.
* Zones impactées :
  - `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`
  - `openfisca_france/model/prelevements_obligatoires/impot_revenu/prelevements_forfaitaires/ir_prelevement_forfaitaire_unique.py`
  - `openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py`
  - `openfisca_france/parameters/impot_revenu/plus_values.yaml`
  - `tests/calculateur_impots/yaml/regime_benef_reel_agricole_avec_cga.yaml`
  - `tests/calculateur_impots/yaml/rpns_pv.yaml`
* Détails :
  - Correction des taux d'imposition et des formules concernant les plus-values de cession pour les non-salariés (RPNS).
  - Ces PV ne sont pas soumis au PFU mais à un taux forfaitaire qui à été mis au niveau du PFU pour l'instant.

- - - -

Ces changements :

- Corrigent ou améliorent un calcul déjà existant.

2022-01-24 15:31 UTC, clallemand requested changes

2022-01-24 15:31 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return f3vg + f3sg + f3sl + f3va_2014 + f3vz + f3we + rpns_pvce
Si je comprends bien ces modifications (ainsi que les suivantes) tu corrige ici un oubli d'intégration des plus-values professionnelles dans l'assiette de la csg sur les plus-values. Est ce que tu t'appuies sur un texte législatif qui précise cela ?

2022-01-24 15:31 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/plus_values.yaml
> +      title: Loi 2017-1837 du 30/12/2017
Peut être préciser l'article en question dans la loi ?

2022-01-24 15:31 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return f3vg + f3sg + f3sl + f3va_2014 + f3vz + f3we + rpns_pvce
D'autre part il me semble que l'ajout de la variable dans `assiette_csg_plus_values` impacte également la variable `rfr_plus_values_hors_rni` qui se trouve dans `C:\Users\c.lallemand\openfisca-france\openfisca_france\model\prelevements_obligatoires\impot_revenu\ir.py` puisque cela crée des doublons pour les années avant 2018 (alors que ce doublon est bien géré à partir de 2018)

2022-01-25 08:28 UTC, lukas-puschnig commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return f3vg + f3sg + f3sl + f3va_2014 + f3vz + f3we + rpns_pvce
Il y avait en effet une erreur dans ce changement. Je pensais aux PV à court terme qui sont soumises aux cotisations sociales, mais celles-ci ne figurent pas dans la variable `rpns_pvce`, mais dans la variable `rpns_pvct` (fait partie des `rpns_imposables` qui fait elle-même partie dans l'`assiette_csg_crds_non_salarie`, et est donc soumise aux cotisations sociales).

2022-01-25 08:28 UTC, lukas-puschnig commented on openfisca_france/parameters/impot_revenu/plus_values.yaml
> +      title: Loi 2017-1837 du 30/12/2017
done !

2022-01-26 10:54 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return f3vg + f3sg + f3sl + f3va_2014 + f3vz + f3we + rpns_pvce
Pardon je me suis trompée dans mon 2e commentaire, je parlais en fait de doublons dans la variable `plus_values_base_large`

2022-01-26 15:51 UTC, lukas-puschnig commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/capital.py
> +        return f3vg + f3sg + f3sl + f3va_2014 + f3vz + f3we + rpns_pvce
Conclusion pour les plus-values de cession des non-salariés à long terme (`rpns_pvce`) : 

- en général soumises à l'IR, mais avec exonérations (petites entreprises sous condition de chiffre d'affaires, transmissions d'entreprises sous condition de valeur, cessions d'entreprises sous condition de départ à la retraite)
- exonérées des cotisations sociales des indépendants
- mais : soumises aux prélèvements sociaux applicables sur les revenus du patrimoine

Il faut donc ajouter ces plus-values à l'`assiette_csg_plus_values` pour qu'elles soient soumises à la CSG pour toutes les années (jusqu'à maintenant : à partir de 2018), mais par contre il faut enlèver le double-compte dans la variable `plus_values_base_large` pour toutes les années aussi (jusqu'à maintenant : à partir de 2018).

NB : 

- les plus-values à court terme sont toujours imposables
- l'imposition des plus-values des non-salariés diffère de celle des particuliers

2022-01-28 15:42 UTC, clallemand approved these changes
Tout me semble ok !

2022-01-31 09:23 UTC, merged