Ajoute last review dans les allocations familiales
openfisca/openfisca-france pull request #1807
Opened 2022-02-16 14:00 UTC by AhmedZemzami

* Amélioration technique. 

* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails : 
- Ajoute last review 
- Ajoute références vers les valeurs 
- Ajoute des références législatives pour les valeurs concernées 
  
- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-02-18 14:08 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/taux/enf3.yaml
> +      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030680318/
Je ne suis pas sur si c'est le décret qu'il faut mettre, voici le décret : https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000006769086&cidTexte=JORFTEXT000000518125 , Décret 86-150 du 30/01/1986, art. 2 (modif art. D521-1 du CSS)

2022-02-23 08:15 UTC, Sasha-Laniece requested changes
Je te laisse avancer sur les autres: mettre les articles avec la valeur en cours

2022-03-01 09:44 UTC, Sasha-Laniece requested changes

2022-03-01 09:44 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/taux/enf1.yaml
> +    2015-07-01:
! date

2022-03-01 09:44 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/majoration_plafond_par_enfant_supplementaire.yaml
> +    - href: https://www.service-public.fr/particuliers/actualites/A15418
A mettre dans `documentation` a la place des baremes ipp

2022-03-01 09:44 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_1_base.yaml
> +  last_review: "2022-02-24"
```suggestion
  last_review: "2021-12-31"
```

2022-03-01 13:05 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_1.yaml
> +    2018-01-01:
Je pense que c'est bon, le 1 correspond au taux plein mais je suis pas certain

2022-03-01 13:16 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_2.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000036393143/
pareil que le précédent je pense que c'est bon car c'est marqué à taux partiel donc 0,5

2022-03-01 14:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/age3.yaml
> +  2000-01-29:
2003-07-01

2022-03-02 10:44 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/taux/enf1.yaml
> +    2015-07-01:
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030680318/2002-03-02/ lien pour 1998 donc avant 2002 et toujours à jour

2022-03-02 11:13 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/taux/enf2.yaml
>      - href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000030674064
J'ai mis les réf dans 1982 qui étaient valables et qui le sont encore

2022-03-08 14:13 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2_base.yaml
> +  last_review: "2022-02-24"
J'ai modifié la date du last review car fausse et je rajouterai 2022 si je trouve la référence = pareil que pour le paramètre précédent

2022-03-14 08:40 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_2eme_enfant.yaml
> +      title: Article L751-1 di Code de la SS
Non

2022-03-14 08:42 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_2eme_enfant.yaml
> +      title: Article D521-1 du Code de la SS
Non plus

ref ici : 
title:  Article D755-5, I. du Code de la sécurité sociale
href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738575/1998-12-30

2022-03-14 08:54 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/def_pac/age_max_pac_apprentissage_stage_formation_droit_aes.yaml
> +    - title: Article R-512-2 du Code de la SS
Supprimer les refs après 1985

2022-03-15 12:08 UTC, Sasha-Laniece requested changes
C'est bien mieux.
Il y a pas mal de corrections à faire, mais globalement quasiment toutes les infos sont là, pas toujours au bon endroit et pas toujours sous le bon format.

2022-03-15 13:27 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/age_maximum_enfant.yaml
>      - href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000268753
Je vois pas du tout cette réf sur vscode ( peut-être elle a été effacée...)

2022-03-15 13:45 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/age_maximum_enfant.yaml
> +    - title: Article L541-4 1. du Code de la SS
Article L541-4 1. ( 1° Jusqu'au dernier jour du mois civil qui précède l'ouverture du droit à l'allocation aux adultes handicapés lorsque cette prestation lui succède ) c'est égal à 20 ans du coup mais je sais pas si ça justifie

2022-03-15 14:17 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_2.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030055650/2015-01-01/
y a écrit taux partiel et aux plein je pense que taux partiel = 0.5

2022-03-16 06:59 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_2.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030055650/2015-01-01/
Ah non, taux partiel c'est n'importe quoi entre 0 et 1 exclus !

2022-03-16 07:07 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/age_maximum_enfant.yaml
> +    - title: Article L541-4 1. du Code de la SS
Effectivement, ça peut etre ça. Du coup il faudrait mettre la reference pour  l'ouverture du droit à l'allocation aux adultes handicapés.

Mais à mon avis tu peux trouver mieux. En tout cas le L541-1 n'a rien à faire ici donc tu peux l'enlever

2022-03-16 07:07 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/age_maximum_enfant.yaml
>      - href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000268753
As-tu fait un git pull ?

2022-03-18 04:55 UTC, Sasha-Laniece requested changes

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aeeh/age_maximum_enfant.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006750602
Tu es au bon endroit dans la loi, mais à mon avis toutes les références ne sont pas utiles. Je garderai ces 2-là:

- Article R512-2 https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006750602
> Les enfants ouvrent droit aux prestations familiales jusqu'à l'âge de vingt ans

- Article L511-1 https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041979747
>  Les prestations familiales comprennent :
[...]
5°) l'allocation d'éducation de l'enfant handicapé ;
[...]

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_2.yaml
> +  last_review: "2022-02-23"
Il faut changer le last_review si tu n'as pas de reference législative pour l'appuyer.

Attention, la ref en plus dans la `documentation` ne donne pas du tout la valeur de 25%. Vu qu'on ne la trouve nulle part, est-ce que cette valeur est juste? Une piste serait de regarder le tableau I.2 de la circulaire

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress/plafond_tranche_2.yaml
> +  2022-01-01:
Tout n'est pas résolu

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress_ancien/majoration_plafond/couples_biactifs_et_parents_isoles.yaml
> +  last_review: "2006-04-02"
Pourquoi cette valeur ?!

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress_ancien/plafond_de_ressources/0_enfant_couples_monoactifs.yaml
> +    - href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006772271
Cette référence ne nous donne aucune info...

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_maj_1ere_tranche_age.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738575/1998-12-30/
tres bien

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_maj_1ere_tranche_age.yaml
> +    - href: https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000209409&categorieLien=id
En revanche cette référence va dans la clef `1993-01-01` car elle nous informe sur la value
```
1993-01-01:
    value: 0.0674
```

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_6eme_enfant_et_plus.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738572/1992-09-08/
Cf. commentaire ci-apres

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_5eme_enfant.yaml
> +      title: Article D755-5 I. 4. du Code de la sécurité sociale
cf commentaire ci-apres

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_4eme_enfant.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738572/1992-09-08/
cf commentaire ci-apres

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_2eme_enfant.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738572/1992-09-08/
cf commentaire ci-apres

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_3eme_enfant.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738572/1992-09-08/
cf commentaire ci-apres

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_2e_enfant/taux_maj_2eme_tranche_age.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738572/1992-09-08/
cf commentaire precedent

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/majoration_premier_enfant/taux_tranche_1.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006738572/1992-09-08/
cf commentaire ci-apres

2022-03-18 04:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj_dom/nb_enfant_pour_aine_donne_droit_majoration.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000018735853/2008-04-30/
Attention à où tu ranges les references, cf commentaires precedents

2022-03-23 07:03 UTC, Sasha-Laniece approved these changes
Tout est corrigé, bravo !

2022-03-23 09:02 UTC, merged