Ajoute le Contrat d'Engagement Jeune
openfisca/openfisca-france pull request #1827
Opened 2022-03-23 14:28 UTC by Cugniere

* Évolution du système socio-fiscal
* Périodes concernées : à partir du 01/03/2022
* Zones impactées : 
  * `model/prestations/jeunes/contrat_engagement_jeune.py`
  * `parameters/prestations_sociales/aides_jeunes/contrat_engagement_jeune/*`
  * `tests/formulas/contrat_engagement_jeune/*`
* Détails :
  - Ajoute le `Contrat d'Engagement Jeune` en remplacement de la `Garantie Jeunes`

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :
- Ajoutent une fonctionnalité (par exemple ajout d'une variable)
- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-04-19 15:00 UTC, Kout95 requested changes

2022-04-22 07:45 UTC, Cugniere commented on openfisca_france/model/prestations/jeunes/contrat_engagement_jeune.py
> +        not_in_training = no_indemnites_stage * no_revenus_stage_formation_pro
En l'occurence on a le droit de faire un stage en parallèle du contrat d'engagement jeune dès le moment où la rémunération de celui-ci est inférieure à 300€ (cf https://www.service-public.fr/particuliers/actualites/A15503)

2022-04-25 08:19 UTC, Kout95 requested changes

2022-04-25 08:19 UTC, Kout95 commented on openfisca_france/model/prestations/jeunes/contrat_engagement_jeune.py
> +        not_in_training = no_indemnites_stage * no_revenus_stage_formation_pro
Dans ce cas les lignes sont fausses : 
```
no_indemnites_stage = individu('indemnites_stage', period) == 0
no_revenus_stage_formation_pro = individu('revenus_stage_formation_pro', period) == 0
```

2022-04-25 08:19 UTC, Kout95 commented on tests/formulas/contrat_engagement_jeune/contrat_engagement_jeune_montant.yaml
> +- name: Calcul du montant du Contrat d'Engagement Jeune
Je testerais bien un cas = 0

2022-04-25 08:46 UTC, Kout95 commented on tests/formulas/contrat_engagement_jeune/contrat_engagement_jeune_montant.yaml
> +- name: Calcul du montant du Contrat d'Engagement Jeune
Comme discuté par visio le montant ne reflète pas l'éligibilité

2022-04-25 12:56 UTC, Kout95 approved these changes

2022-04-25 13:00 UTC, merged