Corrige la tranche d'imposition et le taux marginal d'imposition
openfisca/openfisca-france pull request #1831
Opened 2022-03-25 13:22 UTC by PiGo86

Cette demande de fusion vise à corriger l'erreur constatée sur la tranche d'imposition (`ir_tranche`) et le taux marginal d'imposition (`ir_taux_marginal`) lorsque le dispositif de plafonnement des effets du quotient familial s'applique (cf. #1820).

Dans le cadre de cette modification, j'ai jugé utile de factoriser la logique de calcul.

Ainsi, le point de savoir si le plafonnement des effets du quotient familial s'applique est déterminé au sein de la variable `ir_tranche` (en comparant les variables `ir_plaf_qf` et `ir_brut`).

Si le plafonnement s'applique, la tranche d'imposition est déterminée sur la base d'une part fiscale (contribuables célibataires ou assimilés) ou de deux parts fiscales (contribuables mariés ou assimilés).

Ensuite, la variable `ir_taux_marginal` est calculée en fonction de la variable `ir_tranche`.

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées : `openfisca_france/model/prelevements_obligatoires/impot_revenu/ir`.
* Détails :
  - Corrige les variables `ir_tranche` et `ir_taux_marginal` : la tranche d'imposition et le taux marginal d'imposition sont erronés lorsque le plafonnement des effets du quotient familial s'applique.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-03-25 16:31 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +                             nbptr)
```suggestion
        nbptr_retenu = where(
            plafonnement_qf,
            (celibataire_ou_divorce_ou_veuf * 1) + (maries_ou_pacses_ou_jeune_veuf * 2),
            nbptr
            )
```

2022-03-25 16:51 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        return (taux_effectif == 0) * array(bareme.rates)[ir_tranche] + taux_effectif
L'idéal serait d'éviter de passer par `array` pour rattraper les taux (ou les seuils d'ailleurs) mais d'avoir méthode de 
 `RateTaxScaleLike` qu se trouve [ici](https://github.com/openfisca/openfisca-core/blob/443bb44c6ae1a48263ee4c25faac7af01f99632d/openfisca_core/taxscales/rate_tax_scale_like.py#L18).

@PiGo86 seriez-vous disposé à proposer des modifications en amont ?

2022-03-25 22:01 UTC, PiGo86 commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        return (taux_effectif == 0) * array(bareme.rates)[ir_tranche] + taux_effectif
Oui bien sûr, je regarde pour faire un pull request sur `openfisca-core`.

2022-03-26 22:02 UTC, PiGo86 commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        return (taux_effectif == 0) * array(bareme.rates)[ir_tranche] + taux_effectif
Comme évoqué, je viens donc de faire un pull request sur `openfisca-core` : openfisca/openfisca-core#1114

2022-03-31 20:56 UTC, PiGo86 commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        return (taux_effectif == 0) * array(bareme.rates)[ir_tranche] + taux_effectif
J'ai modifié cette partie pour utiliser la nouvelle méthode `rate_from_bracket_indice`

2022-04-01 09:43 UTC, benjello requested changes
@PiGo86 : merci beaucoup.

Serait-il possible de ne garder qu'un jeu de tests avec le test des deux variables `ìr_tranche` et `ir_taux__marginal`pour un même cas-type ?
Cela permettrait d'économiser du temps de test.

Désolé j'aurais dû voir cela plus tôt.

2022-04-01 10:10 UTC, PiGo86 commented
Oui bien sûr, je procéderai à la modification sur ce point.

2022-04-01 20:10 UTC, PiGo86 commented
Je viens de passer les modifications : j'ai rassemblé les tests au sein d'un nouveau module `ir_tranche_et_taux_marginal`.

2022-04-01 21:20 UTC, benjello approved these changes

2022-04-08 16:30 UTC, PiGo86 commented
Je suis à votre disposition si des modifications étaient nécessaires avant fusion

2022-04-08 16:35 UTC, benjello commented
@sandcha : pour moi c'est bon. Ok pour fusionner ?

2022-04-19 15:40 UTC, GahMuz commented
Bonjour je suis également intéressé par ce fix y a t il quelque chose que l'on peut faire pour aider a ca mise en prod ?

2022-04-26 12:17 UTC, pzuldp commented
> 

c'est relu @benjello @PiGo86 et ça me paraît juste. merci, bien vu !

2022-04-26 12:56 UTC, benjello commented
@pzuldp : je t'ai ajouté comme reviewer car on a besoin de deux checks avant merge et @sandcha doit être prise ailleurs.

2022-04-26 12:57 UTC, pzuldp approved these changes

2022-04-26 13:54 UTC, sandcha approved these changes
Merci @PiGo86 pour ce correctif ! 👏 
Cela corrige bien l'issue #1820 (testé aussi sur l'API Web).

Afin d'obtenir un historique linéaire des commits, je vous propose de prendre en charge le `rebase` de cette branche maintenant. Ensuite, nous pourrons la merger sur master. 🙌 

--
> Cette page service-public[ "Impôt sur le revenu - Quotient familial d'un parent isolé"](https://www.service-public.fr/particuliers/vosdroits/F35120) a également aidé à la revue ; à date, elle indique en particulier ceci : 
> ```
> Pour savoir si vous êtes concerné par le plafonnement, le service des impôts compare les résultats des 2 calculs suivants :
>
> 1. Impôt calculé sur 1 part, diminué du montant du plafond correspondant aux majorations de quotient familial : Division du revenu imposable en un certain nombre de parts. Ce nombre de parts dépend de la situation du contribuable (célibataire, marié, etc.) et des personnes à sa charge.
> 2. Impôt calculé sur votre nombre de parts réel (en fonction de votre situation et de vos charges de famille)
> 
> Si le 2nd résultat est inférieur au 1er, le plafonnement est applicable. Le montant de l'impôt dû correspond au 1er résultat.
> ```

2022-04-26 13:54 UTC, sandcha commented on CHANGELOG.md
> +- Corrige le calcul du taux marginal d'imposition lorsque le plafonnement du quotient familial s'applique
```suggestion
* Détails :
  - Corrige le calcul de la tranche d'imposition lorsque le plafonnement du quotient familial s'applique
  - Corrige le calcul du taux marginal d'imposition lorsque le plafonnement du quotient familial s'applique
```

2022-04-26 15:11 UTC, merged

2022-04-26 20:29 UTC, sandcha commented
Bonjour @GahMuz, 🙂 
Tout merge sur `master` déclenche une publication automatique du paquet openfisca. 
Ainsi, openfisca-france v116.6.1 intégrant les modifications de cette PR [a été publiée sur pypi](https://pypi.org/project/OpenFisca-France/#history)) quelques minutes après le merge.
Ceci répond-il bien à votre question ?

2022-04-26 22:03 UTC, PiGo86 commented
Bonsoir à tous,

Merci pour l'intégration de cette modification.

 @sandcha : il me semble que le bug référencé comme étant corrigé par la présente proposition de fusion n'est pas la bonne (#1838 au lieu de #1820).

2022-04-27 06:11 UTC, GahMuz commented
Bonjour, merci @sandcha c'est plus que parfait