Vérif_Rsa rsa_cond
openfisca/openfisca-france pull request #1832
Opened 2022-03-28 09:00 UTC by AhmedZemzami

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-03-28 15:03 UTC, AhmedZemzami commented
Bonsoir @fpagnoux, j'aimerais savoir où est-ce que vous avez trouvé le chiffre 0,03 du paramètre parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/patrimoine/taux_interet_forfaitaire_epargne_non_imposable.yaml. Je vous remercie d'avance :) 
Zemzami Ahmed

2022-03-31 08:04 UTC, Sasha-Laniece requested changes
C'est globalement très bien ! Juste 2 points à étudier en détail

2022-03-31 08:04 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/rsa_jeune_en_heure.yaml
> +      title: Article L3122-4 du Code de l'action sociale et des familles
Je ne trouve la valeur dans aucune de ces references

2022-03-31 13:20 UTC, fpagnoux commented
Vu le schéma de nommage, je pense que ces paramètres sont issues de l'importation massive des paramètres venant de l'IPP. 

Mais en regardant la [version à jour de la base de paramètre IPP](https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml/-/tree/master/parameters/prestations_sociales/solidarite_insertion/minima_sociaux), je ne vois pas ce paramètre. @benjello (hi! 👋 ) en sait peut être plus.

2022-03-31 16:22 UTC, pzuldp commented
> @clallemand @lukas-puschnig @pzuldp @bfabre01 savez-vous ?

oui @AhmedZemzami @benjello @fpagnoux 
effectivement cette valeur n'est plus dans les barèmes IPP. 😱 
mais on la retrouve, par exemple ici : https://www.service-public.fr/particuliers/vosdroits/F24585
il s'agit du taux forfaitaire (de 3%) par lequel sont multipliés les capitaux placés, pour l'évaluation des ressources pour l'éligibilité au RSA.

la réf législative "code"
Art R132-1 du CSS
le lien 
https://www.legifrance.gouv.fr/codes/id/LEGISCTA000006178301/

la ref législative "décret"
Article 41 du décret n°54-883 du 2 septembre 1954 portant règlement d'administration publique pour l'application de l'ensemble des dispositions du décret n° 53-1186 du 29 novembre 1953 relatif à la réforme des lois d'assistance.  
le lien
https://www.legifrance.gouv.fr/loda/id/LEGIARTI000006682662/2002-01-01/#LEGIARTI000006682662

2022-03-31 16:31 UTC, lukas-puschnig commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/rsa_jeune_en_heure.yaml
> +      title: Article L3122-4 du Code de l'action sociale et des familles
hello, j'ai pas travaillé dessus mais le paramètre (3214h) peut être trouvé ici : 

https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000022743609/2010-09-01/
fait référence à
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000019356968/2008-08-22/
où sont fixé les 1607h, et il faut les doubler alors on tombe sur 3214.

2022-04-04 08:25 UTC, AhmedZemzami commented
> > @clallemand @lukas-puschnig @pzuldp @bfabre01 savez-vous ?
> 
> oui @AhmedZemzami @benjello @fpagnoux effectivement cette valeur n'est plus dans les barèmes IPP. 😱 mais on la retrouve, par exemple ici : https://www.service-public.fr/particuliers/vosdroits/F24585 il s'agit du taux forfaitaire (de 3%) par lequel sont multipliés les capitaux placés, pour l'évaluation des ressources pour l'éligibilité au RSA.
> 
> la réf législative "code" Art R132-1 du CSS le lien https://www.legifrance.gouv.fr/codes/id/LEGISCTA000006178301/
> 
> la ref législative "décret" Article 41 du décret n°54-883 du 2 septembre 1954 portant règlement d'administration publique pour l'application de l'ensemble des dispositions du décret n° 53-1186 du 29 novembre 1953 relatif à la réforme des lois d'assistance. le lien https://www.legifrance.gouv.fr/loda/id/LEGIARTI000006682662/2002-01-01/#LEGIARTI000006682662

Bonjour @benjello @fpagnoux @pzuldp merci beaucoup de votre aide !

2022-04-04 13:22 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/rsa_jeune_en_heure.yaml
> +      title: Article L3122-4 du Code de l'action sociale et des familles
Bonjour @lukas-puschnig merci beaucoup pour ton aide

2022-04-05 08:42 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/limite_duree_droit_majoration_isolement.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033979137/2017-02-03/
Je pense que c'est bien 18 mois  ---> https://www.mes-allocs.fr/guides/rsa/conditions-rsa/quelles-conditions-toucher-rsa-majore/ ( paragraphe durée du rsa majoré) mais ce n'est pas le cas ici car on parle de 12 mois ---> https://www.aide-sociale.fr/rsa-socle-dossier-calcul/

2022-04-05 08:43 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/limite_duree_droit_majoration_isolement.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033979137/2017-02-03/
J'ai modifié la value de 18 à 12 et les tests passent correctement

2022-04-05 09:05 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/limite_duree_droit_majoration_isolement.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033979137/2017-02-03/
J'ai modifié la value pour limite_duree_droit_majoration_isolement en mettant 1 000 000 et les tests passent bien encore une fois. J'ai ensuite remis la value 12 pour ce paramètre en attendant la confirmation

2022-04-05 12:48 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/limite_duree_droit_majoration_isolement.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033979137/2017-02-03/
> 

C'est bien de dire ce que tu as fait. Pour expliciter ton raisonnement, il faut nous donner les conclusions: en mettant une valeur random (1 000 000) et voyant que les tests passent, qu'est-ce que tu en conclus ?

2022-04-05 13:18 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/limite_duree_droit_majoration_isolement.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033979137/2017-02-03/
Hello, j'en conclus qu'il n'y a pas de tests pour ce paramètre et qu'il serait bien d'en faire un mais je sais pas s'il faudra utiliser 12 ou 18 comme value

2022-04-05 16:13 UTC, lukas-puschnig approved these changes
Hello @AhmedZemzami , j'ai regardé les références est ça me semble être bien. Pour le truc des 12 mois, peut-être que tu veux demander à @Sasha-Laniece si tout est bien à la fin (il me semble que oui, mais c'était votre discussion à vous).

Merci @lukas-puschnig !

2022-04-05 16:28 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_cond/majoration_isolement/limite_duree_droit_majoration_isolement.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033979137/2017-02-03/
Au vu de la Législation c'est 12 mois.

2022-04-05 16:29 UTC, Sasha-Laniece approved these changes

2022-04-05 16:31 UTC, Sasha-Laniece approved these changes
C'est prêt à merger ! Merci de ton travail @AhmedZemzami  !

Merci à toi @Sasha-Laniece pour ton aide et tes conseils !

2022-04-06 09:35 UTC, merged