last review Vérif Rsa_2 pour Rsa_fl Rsa_m Rsa_maj
openfisca/openfisca-france pull request #1833
Opened 2022-03-29 13:08 UTC by AhmedZemzami

* Changement mineur.

 
* Périodes concernées :  à partir du 01/06/2009

 
* Zones impactées : parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_fl ; parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_m ; parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj
* Détails :
  Je rajoute les références législatives aux paramètres et je mets le last_review si c'est possible.

2022-04-06 06:39 UTC, Sasha-Laniece requested changes
Beau travail. 

Il y a 2 paramètres qui demandent une petite fouille, sinon c'est parfait !

2022-04-06 06:39 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +      href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006762725/1985-01-05
Hello ! Plusieurs choses:

- Ce lien date de 1985 : ne faudrait-il pas démarrer la value en 1985 ?
- Ce lien est abrogé fin 1985: est-il encore à jour ? Si cette allocation existe encore, il faudrait trouver une preuve. Peut-être en entrant par Service-Public ou un site spécialisé sur le RSA

2022-04-06 06:39 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux2.yaml
> +      href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006762725/1985-01-05
Cf commentaire ci-dessus

2022-04-06 06:39 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/maj_montant_max/couple_1_enfant_ou_2e_enfant.yaml
> +    - href: https://www.legifrance.gouv.fr/affichTexteArticle.do?idArticle=LEGIARTI000020522717&cidTexte=JORFTEXT000020521930
Tu peux aussi mettre la nouvelle version de l'URL, qui est plus courte: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000020522717/

2022-04-06 10:49 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +      href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006762725/1985-01-05
Bonjour, après avoir fait des recherches je sais que ce paramètre existe encore --> https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044629511. Maintenant il faut que je trouve la valeur de ce paramètre

2022-04-07 07:47 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +      href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006762725/1985-01-05
Hello, j'ai finalement trouvé ! Les taux ont changé depuis 1985 pour ces deux paramètres ---> https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038249358 et https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006743297 alors qu'avant 1985 les taux étaient ceux là ---> https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006762725/1985-01-05

2022-04-07 07:57 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +      href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006762725/1985-01-05
Je me permets donc de rajouter les taux pour la tranche 1 : 28,13% et tranche 2 : 37,5% depuis le 01/04/2018 et toujours à jour

2022-04-07 08:27 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +      href: https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006762725/1985-01-05
J'ai rajouté les values pour 2018 et les tests ne passent pas

2022-04-08 13:16 UTC, Sasha-Laniece requested changes
Des choses à revoir.

Les tests ne sont pas cassés parce que tu as changé les valeurs (du moins pour le moment) mais parce qu'il y a des erreurs de typo.

2022-04-08 13:16 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +  last_review: "2022-04-07"
Plusieurs choses:

- [ ] Il faudrait changer l'unit  '/1' en 'BMAF'
- [ ] La ref de 1985 (ligne 11) est la bonne mais il faut la mettre à la bonne date (1985-12-21) et changer la date de value (ligne 3) qui est  '1985-12-21'
- [ ] Si tu regardes les différentes versions de cet article au cours du temps tu verras que la valeur a changé: entre 2015 et 2016 c'est 0,2476 ' puis 0,2589 etc... jusqu'aux 28,13% de 2018. Il faut donc ajouter :  
1. toutes ces values,
2. toutes les references (versions de cet article) correspondantes

2022-04-08 13:16 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +  last_review: "2022-04-07"
Attention: 
pas de lignes vides !
Et pas de champs vides non plus (notes)

2022-04-08 13:16 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux2.yaml
> +    2018-04-01
Il manque les deux points

2022-04-08 13:16 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux2.yaml
> +    2018-04-01
Sinon les commentaires sont les mêmes qu'au-dessus !

2022-04-11 11:35 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +  last_review: "2022-04-07"
Hello, merci pour tes consignes ! J'ai fait les corrections et les tests ne passent toujours pas. Cette fois ci je pense que c'est dû aux tests

2022-04-12 11:44 UTC, Sasha-Laniece approved these changes

2022-04-12 12:43 UTC, merged