Ajout de valeurs manquantes et de last_review.
openfisca/openfisca-france pull request #1835
Opened 2022-04-05 09:23 UTC by kendrickherz

* Évolution du système socio-fiscal.
* Périodes concernées : à partir de 2021.
* Zones impactées : `openfisca_france/parameters`.
* Détails :
  - 2 petits changements dans les paramètres CIPAV et invalidité décés artisans

2022-04-05 13:19 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_independants_artisans_commercants/deces_ac/artisans/sous_pss.yaml
> +  last_review: 2022-04-04
Si tu mets un last_review, tu dois permettre au reviewer de vérifier que la valeur est juste en 1 clic.

Pour cela il faut donc donner le lien direct vers l'article ou la circulaire.
La plupart du temps le décret ne suffit pas car il peut contenir beaucoup (trop) de liens. Effectivement ici c'est assez simple, mais j'ajouterais "par bonne pratique" le lien vers l'article :
https://www.legifrance.gouv.fr/codes/id/LEGIARTI000029209315/2015-01-01

Et d'ailleurs si on regarde la valeur actuelle de cet article (en cliquant sur "Aujourd'hui" en haut de la page), tu vois que l'article a été modifié ! Ton last_review est donc trompeur car la valeur de 1,3% semble fausse en 2022.

2022-04-08 09:26 UTC, Sasha-Laniece requested changes
Hello ! Beau travail, mais quelques points à revoir:

- une certaine compréhension sur l'utilisation des dates dans les yaml (ta confusion est normale et vient de ce problème : )
- une précision sur le choix des liens vers les articles (en termes de version)
- n'hésite pas à supprimer les references/notes qui sont des résidus mal placés de l'harmonisation

2022-04-08 09:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_hors_alsace_chiffre_affaires.yaml
> +      title: Article L6331-48, 1° du code du travail
Ajoute la ref du CGi (cf ci-dessus)

Comme l'article est long, j'ajouterais: 
Article L6331-48, 2º b) du Code du travail

Tu peux aussi supprimer les notes qui ne concernent pas les artisans et preciser qu'en 2011, la cotisation des Alsaciens fusionne avec le regime general

2022-04-08 09:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_alsace_chiffre_affaires.yaml
> +    - href: https://www.legifrance.gouv.fr/loda/id/LEGIARTI000044794656/2022-01-01/
Tu peux aussi supprimer les notes qui ne concernent pas les artisans et preciser qu'en 2011, la cotisation des Alsaciens fusionne avec le regime general.

Idealement il faudrait noter dans un coin de tes notes pour ton futur boulot sur les independants, qu'à partir de 2018 il faudrait faire une nouvelle formule et un nouveau parametre avec une seule valeur (0,3) pour tout le monde.

2022-04-08 09:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_alsace_chiffre_affaires.yaml
> +      title: Article L6331-48 du code du travail
Comme l'article est long, j'ajouterais: 
Article L6331-48, 2º b) du Code du travail

2022-04-08 09:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/professions_liberales_chiffre_affaires.yaml
> -      title: Décret 2017-1894 du 30/12/2017, art. 1
Ici il faudrait mettre la ref de l'article en 2011-01-01 , car c'est là que la valeur commence:

https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000023382168/2011-01-01/

Comme la valeur n'a pas changé depuis et que l'article non plus, un simple clic permet de verifier que ton last review est bon.

2022-04-08 09:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/formation_pl/sous_pss.yaml
> +      title: Article L6331-48, 1° du code du travail
Il faut la ref l'annee de la modification de value, pour marquer le 'démarrage' : 
https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000026294815/2012-08-18/

Pour l'article, ça suffit car il n'a pas bougé dans le temps

2022-04-08 09:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/ventecom_chiffre_affaires.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044981898/2022-01-01
Attention l'article n'est pas à la bonne date, et la date de la ref non plus

2022-04-08 09:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/servicecom_chiffre_affaires.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044981898/2022-01-01
Il faut l'article de 2011, mis à une date de 2011

2022-04-12 13:57 UTC, kendrickherz commented
Pour artisans_alsace_chiffre_affaires et artisans_hors_alsace_chiffre_affaires:
Depuis le le 1er janvier 2017, la CFP est unifiée pour tous les artisans (en et hors Alsace). Il est donc nécessaire de créer une nouvelle variable qui démarrera en 2017, prenant en compte les 2 ensemble.

Pour sous_pss:
 Depuis 2005, supplément de 0,9 % si leur conjoint a le statut de conjoint collaborateur. Ceci n'est pas pris en compte pour le moment.
  (Sources :  Article article L. 953-1 du Code du travail (depuis 2005), puis article L. 6331-48 du Code du travail (depuis 2008). Lien de l'article en vigueur: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044981898/2022-01-01 )

Pour Professions_liberales_chiffre_affaires ; servicecom_chiffre_affaires ; ventecom_chiffre_affaires:

Les valeurs dans les fichiers yaml sont bon pour les dates du 2009-01-01 et 2011-01-01, mais un changement se fait dans l'article L6331-48 du code du travail, en 2018-01-01.
avant 2018: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000029109045/2015-01-01/
après 2018: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033714298/2018-01-01/
on peut voir que le texte change, au lieu d'avoir 2 contributions possibles de 0,1% et 0,2%, on en a 3 de 0,1% ; 0,2% et 0,3%. Avant 2018 l'article se suffit à lui même, après 2018 l'article se réfère à l'article 50-0 du code général des impôts pour diviser les catégories. 
Je n'arrive pas à lire suffisamment clairement l'article 50-0 du code général des impôts pour comprendre comment fonctionne le changement et si il y a réellement un changement dans nos 3 variables à partir de 2018.

2022-04-18 17:20 UTC, Sasha-Laniece requested changes
On y est presque ! 
Cependant il manque un paramètre, non ? Les professions liberales sous pss devraient avoir leur pendant (au-dessus du PSS), avec 0,34% de cotisation ?

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/cotisations_prestations/cipav.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041918199/2020-05-25
Super d'avoir documenté le déplacement de la ref dans la loi !

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_alsace_chiffre_affaires.yaml
> +      note: lien indisponible
Hello ! Tu ne peux pas mettre de note dans les references. Si tu n'as pas le lien , tu ne le mets pas. Je qu'on n'indiquera pas dans les notes qu'on n'a pas le lien.

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_alsace_chiffre_affaires.yaml
> +      note: lien indisponible
```suggestion
```

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_alsace_chiffre_affaires.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044981898/2022-01-01
De même, c'est super de garder les refs qui bougent au cours du temps !

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/artisans_hors_alsace_chiffre_affaires.yaml
> +      note: lien indisponible
```suggestion
```

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/professions_liberales_chiffre_affaires.yaml
> +      note: lien indisponible
```suggestion
```

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/servicecom_chiffre_affaires.yaml
> +      note: lien indisponible
```suggestion
```

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/ventecom_chiffre_affaires.yaml
> +      note: lien indisponible
```suggestion
```

2022-04-18 17:20 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/formation_pl/sous_pss.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044981898/2022-01-01
Inutile de mettre 2 fois la reference à l'article Article L6331-48  : celle de 2012 suffit car la valeur n'a pas changé depuis et la reference legislative n'a pas bougé non plus.

2022-04-21 22:02 UTC, Sasha-Laniece requested changes
Quelques changements mineurs et c'est bon!

2022-04-21 22:02 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/professions_liberales_chiffre_affaires.yaml
> +  (ii) attention en 2018-01-01, il y a un changement dans l'Article L6331-48 du code du travail qui modifie les régles des valeurs
À préciser. Règles de calcul ? De répartition ? De modalités de versement ?

2022-04-21 22:02 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/servicecom_chiffre_affaires.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044981898/2022-01-01
Idem, pas besoin de repetition

2022-04-21 22:02 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/servicecom_chiffre_affaires.yaml
> +  (ii) attention en 2018-01-01, il y a un changement dans l'Article L6331-48 du code du travail qui modifie les régles des valeurs
idem

2022-04-21 22:02 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/ventecom_chiffre_affaires.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044981898/2022-01-01
Idem

2022-04-21 22:02 UTC, Sasha-Laniece commented on openfisca_france/parameters/prelevements_sociaux/cotisations_taxes_professions_liberales/auto_entrepreneur/formation_professionnelle/ventecom_chiffre_affaires.yaml
> +  (ii) attention en 2018-01-01, il y a un changement dans l'Article L6331-48 du code du travail qui modifie les régles des valeurs
idem

2022-05-13 12:07 UTC, Sasha-Laniece approved these changes
Bravo!

2022-05-13 13:38 UTC, merged