Last review minimas couverture sociale
openfisca/openfisca-france pull request #1840
Opened 2022-04-13 12:39 UTC by AhmedZemzami

Changement mineur.
* Périodes concernées :  à partir du 01/08/2009
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

2022-04-21 11:26 UTC, Sasha-Laniece requested changes

2022-04-21 11:26 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/forfait_logement_al/taux_3p_plus.yaml
> +  2009-06-01:
Il me semble ici que les parametres ne s'eteignent pas lors du passage du RMI au RSA : la formule qui les utilise a bien un changement en 2009_06_01 pour passer au RSA. Cependant, les parametres doivent avoir bougé dans la loi: il faudrait trouver le nouvel article

2022-04-21 13:16 UTC, AhmedZemzami commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/forfait_logement_al/taux_3p_plus.yaml
> +  2009-06-01:
Effectivement après avoir bien fouiller cela semble bizarre. Sommes-nous sur que

2022-05-09 12:03 UTC, AhmedZemzami commented
Les tests passent pas car j'avais rajouté des values

2022-10-28 07:31 UTC, Sasha-Laniece approved these changes

2022-12-13 13:35 UTC, sandcha commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/acs/bareme.yaml
> +      2019-10-01:
Dans la [circulaire 30/2019](https://circulaires.ameli.fr/circulaire/cir-302019) (voir fichier PDF attaché), l'ACS aurait été éteinte au bénéfice de la CMU-C le 1er novembre 2019 : 
```
L’article 52 de la loi de financement de la sécurité sociale pour 2019 opère une réforme profonde de ce 
dispositif d’aide à la couverture complémentaire afin d’améliorer le taux de recours de la population 
aujourd’hui éligible à l’ACS par une simplification des démarches et une amélioration des garanties couvertes.

Cet article supprime ainsi l’ACS pour permettre à ses bénéficiaires d’accéder à la CMU-C moyennant paiement 
d’une participation financière. Ce nouveau dispositif, appelé la « Complémentaire santé solidaire » remplace, à 
compter du 1er novembre, la CMUC et l’ACS.
```

2022-12-13 13:35 UTC, sandcha commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/acs/bareme.yaml
> +      - href: https://www.legifrance.gouv.fr/loda/id/LEGIARTI000037849648/2018-12-24/
> Article abrogeant l'ACS au bénéfice de la CMU-C.

2022-12-13 14:04 UTC, sandcha commented on openfisca_france/model/prestations/minima_sociaux/cs/acs.py
> -            )
Grâce au barème, on met automatiquement à jour les seuils de cette formule 👏

2022-12-13 14:04 UTC, sandcha commented on openfisca_france/model/prestations/minima_sociaux/cs/acs.py
> +        bareme = parameters(period).prestations_sociales.solidarite_insertion.minima_sociaux.cs.acs.bareme
Un seul cas à vérifier : si la personne à charge est un adulte, la formule précédente ne lui attribuait d'ACS que si elle avait 25 ans ou moins. La nouvelle formule, elle, donne un montant d'ACS adulte pour cette personne.

2022-12-13 14:39 UTC, sandcha commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/css/forfait_logement_sans_al/taux_1p.yaml
> +description: Taux forfait logement (en % du RSA) pour une personne non bénéficiaire d'aide personnelle au logement ou logée à titre gratuit
`propriétaire` qui était dans `parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/forfait_logement/index.yaml` semble avoir été perdu des descriptions de forfait logement comme celui-ci. L'ajouter à ces paramètres (ou ne pas dire à qui ça s'applique pour ne pas avoir de liste ambiguë) ?

> https://www.aide-sociale.fr/forfait-logement-caf/#definition indique par exemple : 
> Quiconque se retrouve dans une des situations suivantes peut être soumis au forfait logement :
> Bénéficiaire de l’APL (Aide Personnalisée au Logement)
> bénéficiaire de l’ALF (Allocation de Logement Familiale)
> bénéficiaire de l’ALS (Allocation de Logement Sociale)
> Hébergé à titre gratuit
> Propriétaire de votre logement

2022-12-13 14:39 UTC, sandcha commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/majoration_dom.yaml
> +      href: http://www.mediam.ext.cnamts.fr/ameli/cons/CIRCC/2019/CIR-33-2019.PDF
> Remplacer par ce lien plus stable ?
```suggestion
      href: https://circulaires.ameli.fr/circulaire/cir-332019
```

2022-12-13 14:56 UTC, sandcha commented on openfisca_france/model/prestations/minima_sociaux/cs/cmu.py
> +        P = parameters(period).prestations_sociales.solidarite_insertion.minima_sociaux.cs.css.forfait_logement_sans_al
On passe de paramètres CMU à des paramètres CSS mais la variable est dédiée à la CMU 🙃 
Préciser que ces variable ne sont pas sur la CMU qui a été remplacée par la CSS mais aussi sur le dispositif CSS (dit aussi C2S) plus récent ?

Ceci parce qu'on voit d'après [complementaire-sante-solidaire.fr](https://www.complementaire-sante-solidaire.fr/presentation-complementaire-sante-solidaire-c2s) : 
```
- La CMU-C et l'ACS n'existent plus sous ces noms.
- La CMU-C a été rémplacée par la Complémentaire santé solidaire gratuite (Complémentaire santé solidaire sans participation financière).
- L'ACS a été rémplacée par la Complémentaire santé solidaire payante (Complémentaire santé solidaire avec participation financière).
```
Et que : `css.py` appelle effectivement cette variable CMU dans le modèle : `cmu_forfait_logement_base ` au travers de la variable `cmu_base_ressources`

2022-12-13 15:27 UTC, sandcha commented
Rebase en cours pour débloquer les tests.

2022-12-13 15:32 UTC, sandcha commented on openfisca_france/model/prestations/minima_sociaux/cs/acs.py
> +        bareme = parameters(period).prestations_sociales.solidarite_insertion.minima_sociaux.cs.acs.bareme
Dans les références législatives du barème on ne trouve pas de distinction entre parent et personne à charge. 
Le changement rapprocherait donc la formule de la loi.

2022-12-13 16:02 UTC, sandcha approved these changes
Merci @AhmedZemzami @Sasha-Laniece d'avoir étendu l'historique des paramètres, de les avoir réorganisé et d'avoir mis à jour les last_review 🙌

2022-12-13 17:07 UTC, merged