Last_review Minima action logement
openfisca/openfisca-france pull request #1845
Opened 2022-04-25 09:03 UTC by AhmedZemzami

Changement mineur.
* Périodes concernées :  à partir du 1/1/2016
* Zones impactées : parameters/prestations_sociales/aides_logement/action_logement
* Détails : Je rajoute les références législatives et les last_review pour les paramètres de ce périmètre

2022-04-26 11:31 UTC, benoit-cty reviewed
Ça m'a l'air bon.

2022-05-06 15:12 UTC, Sasha-Laniece requested changes
Il faut trouver le décret qui établi les valeurs pour avoir des références législatives et permanentes

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/delai_max_en_mois_apres_debut_contrat_de_travail.yaml
> +    - href: https://www.service-public.fr/particuliers/actualites/A15044
À mettre en doc. Il faut le decret ;)

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/delai_max_en_mois_apres_entree_logement.yaml
>        href: https://www.actionlogement.fr/aide-mon-job-mon-logement
Idem: le decret

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/delai_max_en_mois_apres_entree_logement.yaml
> +  last_review: "2022-04-25"
Manque une ligne vide

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/jeune_actif/age_maximum.yaml
> +    - href: https://www.actionlogement.fr/aide-mon-job-mon-logement
Idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/jeune_actif/delai_max_en_mois_apres_debut_contrat_de_travail.yaml
> +    - href: https://www.actionlogement.fr/aide-mon-job-mon-logement
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/jeune_actif/pourcentage_minimum_smic.yaml
> +    - href: https://www.actionlogement.fr/aide-mon-job-mon-logement
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/montant.yaml
> +      title: Action logement
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/mon_job_mon_logement/pourcentage_maximum_smic.yaml
> +    - href: https://www.actionlogement.fr/aide-mon-job-mon-logement
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/eligibilite/age_max.yaml
> +    - href: https://www.legifrance.gouv.fr/dossierlegislatif/JORFDOLE000034371004/
C'est mieux mais pas encore ça

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/eligibilite/residence_hors_eee.yaml
> +     - href: https://www.legifrance.gouv.fr/dossierlegislatif/JORFDOLE000034371004/
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/cas_general/hors_ile_de_france.yaml
> +      - href: https://www.senat.fr/questions/base/2018/qSEQ180504798.html
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/cas_general/ile_de_france.yaml
> +        title: Journal officiel Sénat du 13/12/2018
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/etudiant/hors_ile_de_france.yaml
> +    - href: https://www.senat.fr/questions/base/2018/qSEQ180504798.html
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/plafond_loyer/etudiant/ile_de_france.yaml
> -documentation: "Autres refs: https://www.visale.fr/vos-questions/faq-locataires/locataire-de-30-ans-ou-moins-suis-je-eligible/#13"
idem

2022-05-06 15:12 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/action_logement/visale/quote_part_aides_logement.yaml
> +      title: Visale page 7 Allocation logement
idem

2022-06-20 15:17 UTC, Sasha-Laniece approved these changes
Hello ! 
Merci pour ce travail.
J'ai corrigé les erreurs de mise en forme.

Je vois que tu n'as pas trouvé le décret qui doit supposément fixer les valeurs et que tu as décidé de ne pas mettre de last_review. 

Ce choix me paraît pertinent, et avoir toutes les références que tu as ajoutées, c'est déjà un super avancement.

Merci !

2022-06-21 14:20 UTC, merged

2022-06-24 06:59 UTC, sandcha commented
@AhmedZemzami @Sasha-Laniece Sur `master` le [check de test sur windows](https://github.com/openfisca/openfisca-france/runs/6986847197?check_suite_focus=true) a échoué avec l'erreur `AttributeError: 'MarginalRateTaxScale' object has no attribute 'rate_from_bracket_indice'` sur `C:\Miniconda\envs\true\lib\site-packages\openfisca_france\model\prelevements_obligatoires\impot_revenu\ir.py:1116` suite au test `tests/formulas/ir_tranche_et_taux_marginal.yaml`. cc @benoit-cty 
Par votre connaissance de cette PR, identifiez-vous la source de l'erreur ?

2022-06-24 07:04 UTC, sandcha commented
Après vérification de l'historique, l'erreur semble [antérieure à cette PR](https://github.com/openfisca/openfisca-france/actions/runs/2258910415).