Ajout du complément ARE
openfisca/openfisca-france pull request #1849
Opened 2022-05-11 09:06 UTC by LucasDetre

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées : `openfisca_france/model/prestations/complement_are.py`, `tests/formulas/complement_are.yaml`, `openfisca_france/parameters/chomage/complement_are.yaml`.
* Détails :
  - Ajout du calcul du complément ARE au modèle

Ces changements :

- Ajoutent une fonctionnalité (par exemple ajout d'une variable).

2022-05-11 09:18 UTC, LucasDetre commented on openfisca_france/model/prestations/complement_are.py
> +            )
Détermination du nombre de jour dans le mois considéré. Code très largement inspiré de `openfisca_france/model/revenus/activite/salarie.py` _(ligne 800)_

2022-05-11 09:34 UTC, LucasDetre commented on openfisca_france/model/prestations/complement_are.py
> +        return individu('salaire_de_base', period)
Le `gain brut` est le terme utilisé chez Pôle emploi dans le cadre d'une reprise d'activité et d'un calcul de complément ARE. Ce terme renvoie simplement au salaire brut de l'emploi repris suite à une période de chômage.

2022-05-11 10:02 UTC, LucasDetre commented on openfisca_france/model/prestations/complement_are.py
> +        return individu('complement_are_allocation_journaliere', period)
Dans le cadre d'un calcul de complément ARE d'un demandeur soumis à la dégressivité de l'ARE, on distingue :
* l'allocation journalière taux plein (`complement_are_allocation_journaliere_taux_plein`)
* l'allocation journalière taux réduit (`complement_are_allocation_journaliere`)

Dans le cas où aucune valeur n'est définie pour l'allocation journalière taux plein, on considère ces montants égaux et on applique le calcul classique du complément ARE (sans dégressivité)

2022-05-11 10:31 UTC, LucasDetre commented on openfisca_france/parameters/chomage/complement_are.yaml
> +    2021-07-01:
Date à confirmer

2022-05-11 10:34 UTC, LucasDetre commented on tests/formulas/complement_are.yaml
> +    complement_are_deductions_montant_mensuel: 10.08
Met en évidence que des déductions seraient applicables si le nombre de jours indemnisés étaient supérieur à 0. À voir si ce montant ne devrait pas être à 0 dans ce type de cas.

2022-05-18 11:05 UTC, MattiSG commented
Merci @LucasDetre pour cette contribution !

@lauradelmas8 @benjello cette PR rend-elle obsolète https://github.com/openfisca/openfisca-france/pull/1481 ? Qui pourrait la revoir ? 🙂

2022-05-19 08:10 UTC, benjello commented
> Merci @LucasDetre pour cette contribution !
> 
> @lauradelmas8 @benjello cette PR rend-elle obsolète #1481 ? Qui pourrait la revoir ? slightly_smiling_face

Ces deux PR ne traitent pas le même problème.

Par ailleurs, #1481 est en sommeil et ne devrait pas être améliorée à court terme sauf intérêt manifeste notamment de @LucasDetre

2022-05-19 10:00 UTC, benjello reviewed
Je n'ai pas eu le temps de faire une revue complète, mais il y a deux axes de réflexion à approfondir :
- la structure du calcul du complément (éviter d'avoir trop de variables intermédiaires etc)
- son articulation avec le reste de la législation

Dispo pour en parler si besoin.

cc @sandcha @MattiSG

2022-05-19 10:16 UTC, LucasDetre commented on openfisca_france/model/prestations/complement_are.py
> +class complement_are_allocation_journaliere(Variable):
On va donc privilégier la structure du modèle quitte à perdre ou dégrader la notion métier ? C'est ce terme qui est utilisé par les conseillers Pôle emploi (_gain brut_ ou _salaire de reprise d'activité_) mais aussi par les [simulateurs existants](https://candidat.pole-emploi.fr/candidat/simucalcul/repriseemploi) dans le cadre du calcul du complément ARE.

En bref, j'ai essayé de faire un compromis entre cohérence avec le reste du modèle et possibilité d'utiliser le calcul du complément ARE en autonomie vis-à-vis du reste du modèle.

Je n'avais pas vu cette notion de `cache_blacklist`, merci ! N'hésitez pas à me dire quelles variables mériteraient de l'intégrer

2022-05-19 11:22 UTC, benjello commented on openfisca_france/model/prestations/complement_are.py
> +class complement_are_allocation_journaliere(Variable):
Je comprends la volonté de rester précis sur la notion métier. Je ne fais pas de compromis là-dessus.
On peut utiliser une formulation telle que 
```python
gain_brut = individu('salaire_de_base', period)
```
ne me gêne pas du tout.

La règle pratique que j'essaie de suivre c'est de ne créer de variables intermédiaires que si elles sont strictement nécessaires pour utiliser à fond les tests et le débogueur, mais alors il faut les ajouter à la `cache_blacklist`.

Après il y a le point de l'intégration en cohérence avec le reste de l'édifice qui est assez compliqué, surtout parce que 
nous n'avons pas véritable de règles écrites ...

Mais là encore, en pratique, il est utile de se poser la question suivante : comment s'insère le dispositif que je veux ajouter dans le modèle socio-fiscal considéré sachant que celui-ci va du "super-brut" au revenu disponible.

Donc ce cas est-ce que le complément ARE s'insère dans les revenus bruts du chômage. Si oui comment etc ?    

@MattiSG @sandcha, je serais partant pour que l'on essaie de commencer à clarifier tout cela surtout si @LucasDetre nous donne son avis informé de son expérience.

2022-06-08 08:31 UTC, LucasDetre commented on openfisca_france/model/prestations/complement_are.py
> +        return individu('salaire_de_base', period)
Done ! J'ai également basculé une certaine partie des données d'entrée communes à l'ARE et au complément ARE dans le fichier `chomage.py`

2022-08-01 06:40 UTC, sandcha requested changes
Merci @LucasDetre pour ce super ajout !
Tu trouveras quelques questions, en particulier sur la dégressivité et la CSG.

2022-08-01 06:40 UTC, sandcha commented on openfisca_france/model/prestations/complement_are.py
> +                round_(montant_mensuel / allocation_journaliere))
Et à ce stade, si `allocation_journaliere_taux_plein` renvoie l'`allocation_retour_emploi_journaliere`, cette formule renvoie le même résultat, qu'il y ait ou non une dégressivité, non ? L'allocation minimale n'aurait-elle pas à faire référence au plancher d'allocation évoqué par l'Unédic (59€03 / jour) ?

2022-08-01 06:40 UTC, sandcha commented on openfisca_france/parameters/chomage/complement_are.yaml
> +    href: https://www.legifrance.gouv.fr/loda/id/JORFTEXT000038829574?init=true&page=1&query=2019-797&searchField=ALL&tab_selection=all
> Les options du lien ne semblent pas filtrer d'information. Le réduire ?
```suggestion
    href: https://www.legifrance.gouv.fr/loda/id/JORFTEXT000038829574
```

2022-08-01 06:40 UTC, sandcha commented on openfisca_france/model/prestations/complement_are.py
> +        coefficient_assiette_contributions = parameters(period).chomage.complement_are.coefficient_assiette_contributions
En général, regrouper les recherches récurrentes dans l'arborescence des paramètres ? 
Par exemple : 
```suggestion
        parametres_complement_are = parameters(period).chomage.complement_are
        seuil_exoneration_contributions = parametres_complement_are.seuil_exoneration_contributions
        coefficient_assiette_contributions = parametres_complement_are.coefficient_assiette_contributions
```

2022-08-01 09:42 UTC, LucasDetre commented on openfisca_france/model/revenus/remplacement/chomage.py
> +    label = 'Allocation journalière ARE taux plein (en cas de degressivité)'
On a besoin de distinguer ces valeurs lors des calculs en situation de dégressivité (cf `degressivite_are`)

2022-08-02 13:09 UTC, LucasDetre commented on openfisca_france/model/revenus/remplacement/chomage.py
> +    definition_period = MONTH
La dégressivité est un dispositif récent dont la mise en application a été gelée pendant le covid puis réactivée à partir de décembre 2021.

2022-08-02 13:40 UTC, LucasDetre commented on openfisca_france/model/prestations/complement_are.py
> +class complement_are_crds(Variable):
Ajouter le complément ARE dans le [chomage brut](https://legislation.fr.openfisca.org/chomage_brut)

2022-08-02 13:51 UTC, sandcha commented on openfisca_france/parameters/chomage/complement_are.yaml
> +  description: Coefficient de plafond global du complément ARE
Pardon, c'est effectivement un facteur qu'on retrouve dans la [référence Unédic](https://www.unedic.org/indemnisation/fiches-thematiques/cumul-allocation-salaire).

2022-08-08 09:22 UTC, sandcha commented on openfisca_france/parameters/chomage/allocation_retour_emploi/montant_minimum_hors_mayotte.yaml
> +    - href: https://www.ipp.eu/baremes-ipp/chomage/allocations_assurance_chomage/alloc_base/
Nous pourrions ajouter la valeur 2022 seulement ici et améliorer ce paramètre dans une autre PR.
Ceci parce que par exemple, je ne retrouve pas le `29,56`. Est-il bien référencé dans les barèmes ? 🤔 

Et les paramètres openfisca et les barèmes IPP sont en cours de rapprochement (déjà entamé dans [cette PR mergée](https://github.com/openfisca/openfisca-france/pull/1740) pour le chômage ; @Sasha-Laniece celui-ci fait-il partie des paramètres openfisca non mergés ? 🤔) donc l'historique est récupéré à mesure et avec une référence IPP c'est un peu comme si les paramètres se référençaient eux-mêmes. 😅

2022-08-08 09:22 UTC, sandcha commented on openfisca_france/model/prestations/complement_are.py
> +class complement_are_allocation_mensuelle_brute_are(Variable):
@LucasDetre Qu'en est-il de cette question ? Il me semble que nous ne l'avons pas évoquée à l'oral (ou ma mémoire fait défaut...) 🙂

2022-08-08 09:22 UTC, sandcha commented on openfisca_france/model/prestations/complement_are.py
> +    set_input_divide_by_period, round_, max_, min_
> Importer de l'API du modèle quand la fonction y est présente ([ici la source d'origine](https://github.com/openfisca/openfisca-core/blob/e18f23be34b5964e89ee65e33669da1a0996ee73/openfisca_core/model_api.py#L9)) ?
```suggestion
from numpy import busday_count, datetime64, timedelta64, divide, zeros_like

from openfisca_france.model.base import Individu, Variable, MONTH, \
    set_input_divide_by_period, round_, max_, min_, where
```

2022-08-08 14:11 UTC, sandcha commented on openfisca_france/parameters/chomage/complement_are.yaml
> +    2001-07-01:
La convention Unédic ayant lieu tous les 3 ans, les références données se suivent à cette fréquence. 

La date d'entrée en vigueur est aussi indiquée au 1er juillet d'après [le site affaires juridiques](http://affairesjuridiques.aphp.fr/textes/circulaire-dgefp-n-2001-30-du-13-septembre-2001-concernant-lindemnisation-du-chomage-des-agents-du-secteur-public-application-de-la-convention-du-1er-janvier-2001-relative-a-laide-au-retou/) 'qui donne un peu de contexte pour le secteur public).

2022-08-08 15:12 UTC, sandcha commented on openfisca_france/model/prestations/complement_are.py
> +        return individu('complement_are_allocation_journaliere', period)
Le choix a finalement été d'avoir une variable "taux plein" et une variable "taux normal".

2022-08-08 15:18 UTC, sandcha commented on openfisca_france/parameters/chomage/complement_are.yaml
> +    2021-07-01:
D'après l'[arrêté](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000000219946) la date d'entrée en vigueur de décisions du conseil de l'Unédic est au 1er juillet. Par ailleurs, c'est aussi ce qu'indique la référence affaires juridiques donnée plus tôt.

2022-09-01 01:14 UTC, sandcha commented
Push force en cours pour retirer les commits de merge et squasher les fixups.

2022-09-01 02:06 UTC, sandcha commented
Rebase sur `master` en cours.

2022-09-01 02:08 UTC, sandcha commented on openfisca_france/parameters/chomage/complement_are.yaml
> +      value: 0.57
@LucasDetre Je n'ai pas traité cette partie.

2022-09-01 02:08 UTC, sandcha commented on openfisca_france/parameters/chomage/allocation_retour_emploi/montant_minimum_hors_mayotte.yaml
> +    - href: https://www.ipp.eu/baremes-ipp/chomage/allocations_assurance_chomage/alloc_base/
@LucasDetre Je n'ai pas traité cette partie.

2022-09-01 02:15 UTC, sandcha approved these changes
Merci @LucasDetre pour tous les correctifs !
Avant rebase(s) j'ai également apporté quelques modifications qui en résumé ont concerné : 
* Comparaison à l’exonération : utilisation d'un signe strict comme sur la [fiche unédic](https://www.unedic.org/indemnisation/fiches-thematiques/retenues-sociales-sur-les-allocations)
* Seuil d’exonération : calculé automatiquement selon les évolutions du smic (peut poser question parce que dans le paramètre initiaux, les références législatives indiquaient des dates légèrement après les évolutions du smic
* Barème contribution : appliquation directe du barème pour la CRDS mais pas pour la CSG (barème formaté autrement)
* Contributions : conservation du principe où, par défaut, on ne connaît pas le RFR et on applique le taux plein
* CSG et CRDS chômage : correction de l'assiette pour en exclure la cotisation à la retraite complémentaire (conformément à la [fiche unédic](https://www.unedic.org/indemnisation/fiches-thematiques/retenues-sociales-sur-les-allocations) et en cohérence avec les cas de tests réels de la PR)

2022-09-01 09:52 UTC, sandcha commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/remplacement.py
> +        chomage_brut = individu('chomage_brut', period)
Pour info, @pzuldp les mises à jour d'assiettes de CSG / CRDS évoquées ensemble sont appliquées ici et dans les modifications suivantes de ce fichier. 🙂

2022-09-01 11:50 UTC, sandcha commented on openfisca_france/parameters/chomage/cotisation_retraite_complementaire.yaml
> +taux:
@benjello @pzuldp Auriez-vous un répertoire à conseiller pour cette cotisation ? 

Aujourd'hui, nous avons ce classement pour les prélèvements sociaux ; il est issu des barèmes IPP et il s'agirait de ne pas en altérer la cohérence 🙂 : 
[openfisca_france/parameters/prelevements_sociaux](https://github.com/openfisca/openfisca-france/tree/4f5cfe78ff4a02ea1a2be8357a6204d17119d70d/openfisca_france/parameters/prelevements_sociaux)
├── autres_taxes_participations_assises_salaires
├── contributions_assises_specifiquement_accessoires_salaire
├── contributions_sociales
├── cotisations_regime_assurance_chomage
├── cotisations_secteur_public
├── cotisations_securite_sociale_regime_general
├── cotisations_taxes_independants_artisans_commercants
├── cotisations_taxes_professions_liberales
├── hsup_exo.yaml
├── index.yaml
├── pss
├── reductions_cotisations_sociales
└── regimes_complementaires_retraite_secteur_prive

Ajouteriez-vous un répertoire cotisations_chomage ? Ou intégreriez-vous ce paramètre à un régime en particulier ? Le tout sachant qu'habituellement, les cotisations sont structurées en deux sous répertoires `employeur` et `salarie` qui ne semblent pas faire sens dans le cas du demandeur d'emploi 🤔

2022-09-01 11:53 UTC, benjello commented on openfisca_france/parameters/chomage/cotisation_retraite_complementaire.yaml
> +taux:
Dans prelevements-sociaux/regimes_complementaires_retraite_secteur_prive

2022-09-01 12:07 UTC, pzuldp commented on openfisca_france/parameters/chomage/cotisation_retraite_complementaire.yaml
> +taux:
tout à fait d'accord avec @benjello !

2022-09-01 12:10 UTC, pzuldp commented on openfisca_france/parameters/chomage/cotisation_retraite_complementaire.yaml
> +taux:
pour le coup c'est plutôt les chômeurs indemnisés que les demandeurs d'emploi... Mais effectivement, ça ne rentre pas dans la classification habituelle. étant donné qu'il faut retirer ces cotis de l'ARE pour avoir l'assiette de CSG, je les aurais plutôt rangées côté employeur, mais je ne suis pas sûr que ça soit utile de faire un tel rangement ?

2022-09-01 12:17 UTC, merged

2022-09-02 22:47 UTC, sandcha commented on openfisca_france/parameters/chomage/cotisation_retraite_complementaire.yaml
> +taux:
cc @LucasDetre

2022-09-06 15:44 UTC, sandcha commented on openfisca_france/parameters/chomage/cotisation_retraite_complementaire.yaml
> +taux:
@benjello Comme nous avons déjà des valeurs (un barème) pour https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters/prelevements_sociaux/regimes_complementaires_retraite_secteur_prive/agirc_arrco/employeur, on partirait sur un nouveau répertoire parameters/prelevements_sociaux/regimes_complementaires_retraite_secteur_prive/ cotisation_retraite_complementaire/employeur ? 🤔

2022-09-06 18:01 UTC, sandcha commented on openfisca_france/parameters/chomage/cotisation_retraite_complementaire.yaml
> +taux:
C'est maintenant traité par [cette PR](https://github.com/openfisca/openfisca-france/pull/1880).