Ajoute la prime exceptionnelle de pouvoir d'achat (Prime Macron)
openfisca/openfisca-france pull request #1850
Opened 2022-05-24 14:13 UTC by AhmedZemzami

* Évolution du système socio-fiscal
* Périodes concernées :  à partir du 24/12/2018
* Zones impactées :
   - `/model/revenus/activite/salarie.py`  
   - `/parameters/marche_travail/prime_pepa/`
* Détails :
   - Ajout de la prime exceptionnelle de pouvoir d'achat

---

- La prime exceptionnelle de pouvoir d'achat exonérée est la prime dont on est exonérée des charges sociales et IR
- La prime exceptionnelle de pouvoir d'achat non exonérée est la partie non exonérée de la prime et qui est calculé comme une prime classique 
- https://boss.gouv.fr/portail/accueil/mesures-exceptionnelles/instruction-du-19-aout-2021.html : conditions de la prime exceptionnelle de pouvoir d'achat 
- - - -

Ces changements  :

- Ajoutent une fonctionnalité (par exemple ajout d'une variable).

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [x] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [x] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

**edit sandcha :** Indentation de la description, retrait d'`openfisca-france` de la zone impactée et retrait des tests du détail.

2022-06-02 15:20 UTC, benoit-cty commented on openfisca_france/model/revenus/activite/salarie.py
> +        plafond_par_defaut = 1000 # parameters.x.y.z
Utiliser le paramètre.

2022-06-02 15:32 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat au plafond de 2000 euros sans accord d'interessement
La description ne correspond pas au test.

2022-06-17 07:34 UTC, benoit-cty commented on openfisca_france/reforms/parameters/Prime-PEPA
> +class pepa(Variable):
Il faut supprimer ce fichier, non ?

2022-06-17 07:35 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +#  test à faire :
Retirer ces commentaires si ces tests sont fait.

2022-06-17 07:37 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat d'un montant de 1500 euro sans accord d'interessement
Préciser que comme moins de 50 salariés, la prime est exonérée dans la limite de 2 000 €.

2022-06-17 07:39 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    salaire_super_brut: 1500
Comme il y a un salaire de base de 2 000 on s'attendrait à plus de 3500€ de salaire_super_brut.
Problème avec les périodes ?

2022-06-17 07:40 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat au plafond de 1000 euros (cas général)
Le montant de 1300 ne correspond pas au commentaire "1000 euros"

2022-06-17 07:41 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    effectif_entreprise: 37
Est-ce qu'il ne faut pas mettre un effectif de plus de 50 pour que le cas accord_interessement soit indispensable.
Idéalement il faut tester les deux cas.

2022-06-17 07:44 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    accord_interessement: false
Il faudrait préciser quel effectif prend OpenFisca par défaut comme ça rentre dans le calcul.

2022-06-17 07:45 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat à 3 fois le SMIC euros avec accord d'interessement
Ce n'est pas la PEPA qui est à 3x le SMIC mais le salaire.

2022-06-17 07:54 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +        plafond_max = 2000 # TODO: parameters.x.y.z
Salut, c'est fait ici openfisca_france/parameters/marche_travail/prime_pepa/plafond_effectif_entreprise.yaml

2022-06-17 07:55 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +        plafond_par_defaut = 1000 # parameters.x.y.z
C'est fait openfisca_france/parameters/marche_travail/prime_pepa/seuil_exoneration_avec_accord_interessement.yaml

2022-06-17 07:58 UTC, AhmedZemzami commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    # irpp_economique: 0
C'est fait, j'ai pu tester l'impot sur le revenu (irpp) pour le dispositif pepa

2022-06-17 08:08 UTC, benoit-cty commented
Ahmed, voici un code pour t'aider à vérifier la couverture de test:
```py
# Liste des possibilités
salaires = ["moins_3_smic", "plus_3_smic"]
primes = ["moins_1000", "entre_1000_et_2000", "plus_de_2000"]
effectifs = ["moins_de_50", "plus_de_50"]
interessements = ["oui", "non"]

def exonere(salaire, prime, effectif, interessement):
    if salaire == "plus_3_smic":
        return "cas 1 : Non exonérée"
    elif prime == "moins_1000":
        return "cas 2 : exonérée"
    elif prime == "entre_1000_et_2000":
        if effectif == "moins_de_50" or interessement == "oui":
            return "cas 3 : exonérée"
        else:
            return "cas 4 : exonérée jusqu'à 1000 seulement"
    elif prime == "plus_de_2000":
        if effectif == "moins_de_50" or interessement == "oui":
            return "cas 5 : exonérée jusqu'à 2000 seulement"
        else:
            return "cas 6 : exonérée jusqu'à 1000 seulement"

# Examen de toutes les possibilités
for salaire in salaires:
    for prime in primes:
        for effectif in effectifs:
            for interessement in interessements:
                print("Salaire", salaire, ", montant de la prime", prime, ", effectif", effectif, ", accord intéressement", interessement, "=>", exonere(salaire, prime, effectif, interessement))

```  

Ce qui donne :
```
Salaire moins_3_smic , montant de la prime moins_1000 , effectif moins_de_50 , accord intéressement oui => cas 2 : exonérée
Salaire moins_3_smic , montant de la prime moins_1000 , effectif moins_de_50 , accord intéressement non => cas 2 : exonérée
Salaire moins_3_smic , montant de la prime moins_1000 , effectif plus_de_50 , accord intéressement oui => cas 2 : exonérée
Salaire moins_3_smic , montant de la prime moins_1000 , effectif plus_de_50 , accord intéressement non => cas 2 : exonérée
Salaire moins_3_smic , montant de la prime entre_1000_et_2000 , effectif moins_de_50 , accord intéressement oui => cas 3 : exonérée
Salaire moins_3_smic , montant de la prime entre_1000_et_2000 , effectif moins_de_50 , accord intéressement non => cas 3 : exonérée
Salaire moins_3_smic , montant de la prime entre_1000_et_2000 , effectif plus_de_50 , accord intéressement oui => cas 3 : exonérée
Salaire moins_3_smic , montant de la prime entre_1000_et_2000 , effectif plus_de_50 , accord intéressement non => cas 4 : exonérée jusqu'à 1000 seulement
Salaire moins_3_smic , montant de la prime plus_de_2000 , effectif moins_de_50 , accord intéressement oui => cas 5 : exonérée jusqu'à 2000 seulement
Salaire moins_3_smic , montant de la prime plus_de_2000 , effectif moins_de_50 , accord intéressement non => cas 5 : exonérée jusqu'à 2000 seulement
Salaire moins_3_smic , montant de la prime plus_de_2000 , effectif plus_de_50 , accord intéressement oui => cas 5 : exonérée jusqu'à 2000 seulement
Salaire moins_3_smic , montant de la prime plus_de_2000 , effectif plus_de_50 , accord intéressement non => cas 6 : exonérée jusqu'à 1000 seulement
Salaire plus_3_smic , montant de la prime moins_1000 , effectif moins_de_50 , accord intéressement oui => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime moins_1000 , effectif moins_de_50 , accord intéressement non => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime moins_1000 , effectif plus_de_50 , accord intéressement oui => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime moins_1000 , effectif plus_de_50 , accord intéressement non => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime entre_1000_et_2000 , effectif moins_de_50 , accord intéressement oui => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime entre_1000_et_2000 , effectif moins_de_50 , accord intéressement non => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime entre_1000_et_2000 , effectif plus_de_50 , accord intéressement oui => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime entre_1000_et_2000 , effectif plus_de_50 , accord intéressement non => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime plus_de_2000 , effectif moins_de_50 , accord intéressement oui => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime plus_de_2000 , effectif moins_de_50 , accord intéressement non => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime plus_de_2000 , effectif plus_de_50 , accord intéressement oui => cas 1 : Non exonérée
Salaire plus_3_smic , montant de la prime plus_de_2000 , effectif plus_de_50 , accord intéressement non => cas 1 : Non exonérée
```

Mais comme il y a 6 return dans le code, 6 tests devraient suffire pour couvrir ta formule. Avec un 7° sur une période où la prime n'est pas en vigueur pour s'assurer que c'est bien le cas.

2022-06-17 10:04 UTC, benoit-cty requested changes
Retour sur commentaire.

2022-06-17 10:04 UTC, benoit-cty commented on openfisca_france/model/revenus/activite/salarie.py
> +        # eligibilite = effectif_entreprise < plafond_effectif_entreprise
Supprimer ce commentaire

2022-06-20 07:17 UTC, AhmedZemzami commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat à 3 fois le SMIC euros avec accord d'interessement
Merci pour ton retour, c'est fait :)

2022-06-20 07:21 UTC, AhmedZemzami commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    salaire_super_brut: 1500
Oui effectivement la période du test ne correspond pas à la date correspondant au salaire de base

2022-06-20 07:24 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +         si salaire < 3 SMIC
Merci beaucoup !

2022-06-20 07:30 UTC, AhmedZemzami commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    accord_interessement: false
Salut, en effet la valeur prise par défaut est de zéro  [https://legislation.fr.openfisca.org/effectif_entreprise?q=effectif] :)

2022-06-20 10:08 UTC, sandcha commented on openfisca_france/model/revenus/activite/salarie.py
> +         si salaire < 3 SMIC
> Ce type de commentaire a tendance à mal vieillir. Passée la phase de développement, nous pourrions le supprimer.

2022-06-20 12:07 UTC, AhmedZemzami commented on openfisca_france/parameters/marche_travail/Prime_Pepa/Prime_pepa_max_deux_mille_euros
> +metadata:
Effectivement c'est bien au 01/04/2022 merci

2022-06-23 14:41 UTC, benoit-cty commented on openfisca_france/reforms/parameters/Prime-PEPA
> +class pepa(Variable):
Je l'ai supprimé.

2022-06-23 14:42 UTC, benoit-cty commented on openfisca_france/parameters/marche_travail/Prime_Pepa/Prime_pepa_max_mille_euros
> +    value: 1000
Fait

2022-06-23 15:01 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      2021-04: 12616.575 #  8909.35 + 2000 #  17597.398
Les commentaires ne correspondent pas au montant. Les effacer ?
Par contre, ça peut être utile d'indiquer d'où sort ce montant. Salaire_super_brut + prime + taxe_prime ? Et indiquer les montants respectifs plutôt que le total : OpenFisca test sait faire les calculs.

2022-06-24 12:50 UTC, benoit-cty requested changes

2022-06-24 12:50 UTC, benoit-cty commented on openfisca_france/parameters/marche_travail/prime_pepa/seuil_exoneration_avec_accord_interessement.yaml
> +  ux_name: Pepa seuil avec conditions
L'ux-name sera affiché sur le site internet, il faut un nom bien lisible, je propose :
`ux_name: Deuxième seuil d'exonération sous condition`

2022-06-24 12:50 UTC, benoit-cty commented on openfisca_france/parameters/marche_travail/prime_pepa/seuil_exoneration.yaml
> +  ux_name: Pepa seuil
L'ux-name sera affiché sur le site internet, il faut un nom bien lisible, je propose :
`ux_name: Premier seuil d'exonération`

2022-06-24 12:50 UTC, benoit-cty commented on openfisca_france/parameters/marche_travail/prime_pepa/plafond_salaire.yaml
> +  ux_name: Salaire inférieur à 3 fois le SMIC
L'ux-name sera affiché sur le site internet, il faut un nom bien lisible, je propose :
`ux_name: Salaire maximal d'exonération, en nombre de SMIC`

2022-06-24 12:50 UTC, benoit-cty commented on openfisca_france/parameters/marche_travail/prime_pepa/plafond_effectif_entreprise.yaml
> +  ux_name: Pepa plafond effectif entreprise
L'ux-name sera affiché sur le site internet, il faut un nom bien lisible, je propose :
`ux_name: Seuil d'effectif de l'entreprise sans accord d'intéressement`

2022-06-24 12:50 UTC, benoit-cty commented on openfisca_france/model/prestations/visale.py
> +            'primes_salaires_non_exonerees',  # Sont prises en compte toutes les « primes récurrentes perçues dans le cadre d’une activité intégrée dans le calcul du salaire ou traitement ». Note : c
Vu avec Sandra

2022-06-24 12:51 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    #  salaire_super_brut_hors_allegements:
A effacer

2022-06-24 12:58 UTC, AhmedZemzami commented on openfisca_france/parameters/marche_travail/prime_pepa/plafond_effectif_entreprise.yaml
> +  ux_name: Pepa plafond effectif entreprise
Merci de ta contribution !

2022-06-27 12:37 UTC, benoit-cty requested changes
Tests à revoir:
- Il manque les cas 5 et 6
- Des descriptions ne correspondent pas au test fait
- Il faut préciser sur chaque test le cas couvert
- Il faut corriger les warning sur le YAML de test

2022-06-27 12:37 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat d'un montant de 1001 euros et un salaire mensuel de 5000 euros
```suggestion
- name: Prime exceptionnelle de pouvoir d'achat d'un montant de 1001 euros et un salaire mensuel de 5000 euros (cas 4 : exonérée jusqu'à 1000 seulement)
```

2022-06-27 12:37 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat d'un montant de 2200 euros sans accord d'interessement et > 50 salariés
La description du test ne correspond pas, que voulais-tu tester ?

2022-06-27 12:37 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat au plafond de 1300 euros
"au plafond de 1300 euros" 1300, n'est pas un plafond de PEPA, si ? Quel est le but de ce test ?
Salaire moins_3_smic , montant de la prime moins_1000 , effectif moins_de_50 => cas 2 : exonérée

2022-06-27 12:37 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat au plafond de 2000 euros (cas avec accord d'interessement)
```suggestion
- name: Prime exceptionnelle de pouvoir d'achat au plafond de 2000 euros (cas avec accord d’intéressement) (cas 2 : exonérée)
```

2022-06-27 12:37 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat pour une personne avec un salaire > 3 fois le SMIC euros avec accord d'interessement
```suggestion
- name: Prime exceptionnelle de pouvoir d'achat pour une personne avec un salaire > 3 fois le SMIC euros avec accord d’intéressement (cas 1 : Non exonérée)
```

2022-06-27 13:10 UTC, AhmedZemzami commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    effectif_entreprise: 37
Ligne 129 :)

2022-06-28 08:06 UTC, benoit-cty commented
La Loi parle aussi de _"ou pour les travailleurs de la deuxième ligne si des mesures de revalorisation sont engagées"_
Est-ce qu'il faut l'implémenter ?

2022-06-28 08:28 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    prime_exceptionnelle_pouvoir_achat_exoneree: [2000,2000]
Il faut ajouter le cas de non exonération avec un salaire > 3 x SMIC sur 12 mois glissant : 59 241€.

2022-06-28 08:40 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat au plafond de 1300 euros #  ( cas 6 exonération jusqu'à 1000)
```suggestion
- name: Prime exceptionnelle de pouvoir d'achat au dessus du plafond de 1000 euros #  ( cas 6 exonération jusqu'à 1000)
```

2022-06-28 16:20 UTC, AhmedZemzami commented
Bonjour @benjello, qui me conseilles-tu pour revoir ma PR sur la prime exceptionnelle de pouvoir d'achat ? Je te remercie d'avance !

2022-06-29 10:43 UTC, clallemand requested changes
Bonjour, 

Je n'ai pas relu les tests et ne les ai pas non plus adapté aux modifications que je demande.
Je n'ai pas non plus vérifié les liens mis dans les  paramètres.

J'ai repéré de nombreux cas de "doublon" c'est à dire qu'une des variables concernant la prime exceptionnelle a été ajoutée dans une variable (par exemple `prime_exceptionnelle_pouvoir_achat_non_exoneree` est comprise dans `primes_salaires_non_exonérées`) mais est également ajoutée en plus dans les variables qui appelle cette variable (voir par exemple salaire_imposable). A la fin la prime d'activité est donc comptée plusieurs fois.
C'est également le cas dans les différentes variables de revenus bruts ou super bruts qui ont été modifiées.

ATTENTION à être plus vigilant sur ce genre de cas, il ne faut pas rajouter la variable à chaque étape si elle est déjà comprise dans une variable en amont.

2022-06-29 10:43 UTC, clallemand commented on openfisca_france/model/revenus/activite/salarie.py
> +        prime_exceptionnelle_pouvoir_achat_exoneree = individu('prime_exceptionnelle_pouvoir_achat_exoneree', period)
Existe avant 2019?

2022-06-29 10:43 UTC, clallemand commented on openfisca_france/model/revenus/activite/salarie.py
> +        return salaire_super_brut_hors_allegements - exonerations_et_allegements + prime_exceptionnelle_pouvoir_achat
Pas cohérent avec ce qui a été mis dans `salaire_super_brut_hors_allegements` ? Puisque la partie non exonérée a déjà été incluse il me semble

2022-06-29 10:43 UTC, clallemand commented on openfisca_france/model/revenus/activite/salarie.py
> +        prime_exceptionnelle_pouvoir_achat_exoneree = individu('prime_exceptionnelle_pouvoir_achat_exoneree', period)
Déjà compris dans salaire super brut non ??

2022-06-30 13:09 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +        condition_salaire = salaire_de_base_moyenne < (smic_b_mensuel * plafond_salaire)
Bonjour, tu as raison la variable quotite_de_travail * plafond salaire c'est ce qui représente mieux la loi merci beaucoup

2022-06-30 13:13 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +        seuil_exoneration = parameters(period).marche_travail.prime_pepa.seuil_exoneration
Je suis d'accord ce sont des plafonds dont on parle :) je vais changer le nom

2022-06-30 13:18 UTC, AhmedZemzami commented on openfisca_france/model/prestations/visale.py
> +            'primes_salaires_non_exonerees',  # Sont prises en compte toutes les « primes récurrentes perçues dans le cadre d’une activité intégrée dans le calcul du salaire ou traitement ». Note : c
Nous avons vu avec @sandcha et normalement ça rentre bien dans le calcul du salaire mais nous ferons une autre vérification, merci !

2022-06-30 13:20 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +        prime_exceptionnelle_pouvoir_achat_non_exoneree = individu('prime_exceptionnelle_pouvoir_achat_non_exoneree', period)
T'as raison la pepa non exonérée ne doit pas être rajouter après avoir revu. Je l'ai supprimé je te remercie de ta remarque

2022-06-30 13:20 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +        prime_exceptionnelle_pouvoir_achat_exoneree = individu('prime_exceptionnelle_pouvoir_achat_exoneree', period)
Elle rentre en vigueur le 1/1/2019 tu as raison je l'ai donc supprimé

2022-06-30 13:35 UTC, AhmedZemzami commented
@clallemand Merci énormément pour le temps que t'as pris pour me faire des retours très utiles et précis

2022-07-04 15:24 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      month:2020-05:12: 8909.35 * 12
Pourquoi ce montant de "8909.35 * 12" ?
8 909.35 / 3 = 2 969,78 c'est loin du SMIC, non ?

2022-07-04 15:59 UTC, benoit-cty requested changes
Retours sur les tests.

2022-07-04 15:59 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      2020-01: 2000
Salaire pas versé à la même date que la prime, c'est volontaire ?

2022-07-04 15:59 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      month:2020-05:12: 8909.35 * 12
Est-ce qu'il n'y a pas un problème de période ?
Je trouve les charges très faibles pour un salaire si élevé.

2022-07-04 15:59 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      month:2020-05:12: 8909.35 * 12
Pourquoi ce montant de "8909.35 * 12" ?
8 909.35 / 3 = 2 969,78 c'est loin du SMIC, non ?

2022-07-04 15:59 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat de 2000 euros pour une personne à temps plein
Il faudrait un test avec un salaire > 3 x SMIC mais avec une _quotite_de_travail_ qui fait que son salaire réel est inférieur à 3 x SMIC.
Ca peut être dans le même test en exploitant le mode tableau.

2022-07-04 15:59 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    csg_imposable_salaire: -70.74
Les csg_imposable_salaire, csg_deductible_salaire, crds_salaire ne sont pas nécessaires dans tous les tests, comme c'est inclus dans salaire_super_brut.

2022-07-04 16:12 UTC, clallemand commented on openfisca_france/model/revenus/activite/salarie.py
> +        condition_salaire = salaire_de_base_moyenne < (smic_b_mensuel * plafond_salaire)
Oui c'est bien ça mais j'ai l'impression que ce n'est pas ce que tu as codé pourtant...

2022-07-05 09:48 UTC, benoit-cty commented
Bonjour @clallemand , actuellement la PEPA n'est pas intégrée au `salaire_super_brut_hors_allegements`, il faudrait qu'elle le soit ?

2022-07-05 09:50 UTC, benoit-cty commented on openfisca_france/model/revenus/activite/salarie.py
> +        salaire_de_base_moyenne = individu('salaire_de_base', annee_glissante, options=[ADD]) / 12
@sandcha  Dans ce calcul le mois en cours n'est pas pris en compte. Même un milliardaire se voit exonéré. Comment faire ?

2022-07-05 12:12 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    salaire_super_brut: 1500
Toutes les périodes ont été vérifiées.

2022-07-05 12:17 UTC, AhmedZemzami commented on openfisca_france/model/revenus/activite/salarie.py
> +        condition_salaire = salaire_de_base_moyenne < (smic_b_mensuel * plafond_salaire)
Maintenant j'ai l'impression que dans condition_salaire, le salaire de base dépend de quotité_de_travail. J'ai peut-être pas compris ce que tu voulais dire

2022-07-05 12:51 UTC, benoit-cty commented on openfisca_france/model/revenus/activite/salarie.py
> +        condition_salaire = salaire_de_base_moyenne < (smic_b_mensuel * plafond_salaire)
Bonjour Chloée,
Tu veux dire que ce sont les plafonds de 1000/2000€ qui doivent être proratisés, ou le plafond de 3*SMIC, ce qui est ce qu'Ahmed fait normalement par:
```
condition_salaire = salaire_de_base_moyenne < (smic_b_mensuel * plafond_salaire)
```

2022-07-05 14:36 UTC, benoit-cty commented on openfisca_france/model/revenus/activite/salarie.py
> +        condition_salaire = salaire_de_base_moyenne < (smic_b_mensuel * plafond_salaire)
Ah oui, c'est écrit "une rémunération inférieure à trois fois la valeur annuelle du salaire minimum de croissance __correspondant à la durée de travail prévue au contrat__" sur https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000043805912
Donc c'est bien ce qui est implémenté, non ?

2022-08-04 14:21 UTC, benoit-cty commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/contributions_sociales/activite.py
> +        prime_exceptionnelle_pouvoir_achat_exoneree = individu('prime_exceptionnelle_pouvoir_achat_exoneree', period)
OK, a été mis dans une formule datée.

2022-08-04 14:26 UTC, benoit-cty commented on openfisca_france/model/prestations/visale.py
> +            'primes_salaires_non_exonerees',  # Sont prises en compte toutes les « primes récurrentes perçues dans le cadre d’une activité intégrée dans le calcul du salaire ou traitement ». Note : c
'primes_salaires_non_exonerees' est un renommage de 'primes_salaires' pour expliciter que ces primes ne sont pas exonérées contrairement aux prime PEPA et PPV.

2022-08-04 14:28 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      2020-01: 2000
Vu

2022-08-04 14:37 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      month:2020-05:12: 8909.35 * 12
Supprimé

2022-08-04 14:43 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat de 2000 euros pour une personne à temps plein
@AhmedZemzami Il faudrait donc faire:
```yaml
- salaire_de_base: 1 670 * 3 *12 # pour être en dessous de 3 SMIC
- quotite_de_travail: 0.5 # pour être bien au dessus de 3 SMIC
```

2022-08-05 08:05 UTC, benoit-cty requested changes

2022-08-05 08:05 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      2020-01: 1670 * 3 * 12
```suggestion
      2020: 1670 * 3 * 12
```

2022-08-05 08:05 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    salaire_de_base: [2000, 1600]
```suggestion
    salaire_de_base: [24_000, 19_200]
```

2022-08-05 08:05 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +      # 2021-01: [500, 0]
Supprimer les commentaires inutiles.

2022-08-05 09:39 UTC, AhmedZemzami commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    salaire_de_base: [2000, 1600]
Ce test a été supprimé car c'est un doublon :)

2022-08-05 12:09 UTC, benoit-cty requested changes

2022-08-05 12:09 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +- name: Prime exceptionnelle de pouvoir d'achat pour un salarié  à temps partiel < 3*SMIC mais dont l'équivalent temps plein est > 3*SMIC
```suggestion
- name: Prime exceptionnelle de pouvoir d'achat pour un salarié à temps partiel < 3*SMIC mais dont l'équivalent temps plein est > 3*SMIC
```

2022-08-05 12:09 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    #  Ecart de 9 euros à partir de 50 salariés en raison de la participation_effort_construction
Commentaire plus utile dans ce context, non ?
```suggestion
```

2022-08-05 12:51 UTC, benoit-cty commented on tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml
> +    salaire_de_base: [20000, 35000, 20000, 25000]
Test changé

2022-08-05 14:11 UTC, benoit-cty approved these changes
C'est bon pour moi.

Nous avons été obligé de squash les commits car il y avait des problèmes d'embranchements  dupliquant les commits et générant des conflits lors du rebase. Ils sont visibles dans la branche `prime-partage-valeur`.

Bonjour @clallemand, pourrais-tu revoir ta demande de changement ?

2022-08-08 14:39 UTC, clallemand commented on openfisca_france/model/revenus/activite/salarie.py
> +                smic_annuel * plafond_salaire * quotite_de_travail
Cette ligne de code a déjà fait l'objet d'une discussion et a changé depuis mais j'ai l'impression qu'il y a toujours une erreur : le 29 juin lors de mon 1e commentaire la proratisation du smic n'était pas prise en compte mais maintenant j'ai l'impression qu'elle est prise en compte deux fois : la variable `smic_annuel` correspond ainsi à un smic proratisé. Mais celui-ci est proratisée une seconde fois avec la variable `quotite_de_travail`.

2022-08-08 15:37 UTC, clallemand commented on openfisca_france/model/revenus/activite/salarie.py
> +                smic_annuel * plafond_salaire * quotite_de_travail
J'ai l'impression que `quantité_de_travail` et `coefficient_de_proratisation` sont des variables très similaires, avec la seconde qui est plus précise dans le cadre spécifique du calcul des cotisations sociales et du smic proratisé. Donc je pense que l'on peut mettre directement `smic_proratise` sans utiliser `quantite_de_travail`. Désolée pour le mauvais conseil au mois de juin, je n'avais plus en tête qu'il existait déjà une variable de smic proratisé.

2022-08-08 16:20 UTC, benoit-cty commented on openfisca_france/model/revenus/activite/salarie.py
> +                smic_annuel * plafond_salaire * quotite_de_travail
D'après le test https://github.com/openfisca/openfisca-france/blob/82ff2200b7abe540a60f8888aae9e289c79eb60f/tests/formulas/prime_exceptionnelle_pouvoir_achat.yaml#L128 j'ai l'impression qu'il faut bien utiliser `quotite_de_travail`, non ?

2022-08-09 13:18 UTC, clallemand commented on openfisca_france/model/revenus/activite/salarie.py
> +                smic_annuel * plafond_salaire * quotite_de_travail
Oui quotité de travail c'est bien je pense

2022-08-09 16:00 UTC, merged