Met à jour allocation adulte handicapé
openfisca/openfisca-france pull request #1864
Opened 2022-07-07 07:41 UTC by DorineLam

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-08-22 11:29 UTC, sandcha requested changes
Merci @DorineLam 🙌 
Juste une demande de changement sur `montant_de_base.yaml` où la date de la référence est à mettre à la date de la valeur (le reste est optionnel).

2022-08-22 11:32 UTC, sandcha commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/ppa/pa_m/montant_de_base.yaml
> +    2022-04-26:
> @eraviart C'est ici que [le validateur YAML passe](https://control-center.tax-benefit.org/tasks/23922) alors qu'on s'attendrait à une erreur (sauf si la fonctionnalité a été désactivée).

2023-01-16 14:10 UTC, eraviart approved these changes

2023-01-16 17:00 UTC, sandcha approved these changes
Merci @DorineLam pour ces améliorations ! 
Voici aussi un retour rapide sur le CHANGELOG.

2023-01-16 17:11 UTC, sandcha commented
@DorineLam L'historique de cette branche ne semble pas linéaire. 
Au cas où, il faudrait retirer les commits de merge et rebaser avant de merger la PR.

2023-01-16 18:00 UTC, sandcha commented
Retrait des commits de merge en cours (force-push à venir).

2023-01-16 19:09 UTC, sandcha commented
Rebase en cours (était sur master v116.13.2 ; de l'harmonisation est intervenue entre-temps sur des fichiers de cette PR), bump et mise à jour du CHANGELOG.

2023-01-16 19:59 UTC, merged