Met à jour les paramètres de la taxe d'habitation
openfisca/openfisca-france pull request #1867
Opened 2022-07-26 10:22 UTC by lukas-puschnig

* Évolution du système socio-fiscal.
* Périodes concernées : 2022.
* Zones impactées : 
  - `openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev.yaml`
  - `openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev_degressif.yaml`
  - `openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/taux_sup_plaf.yaml`
  - `openfisca_france/parameters/taxation_indirecte/taxe_habitation/exon_plaf_rfr.yaml`
* Détails :
  - Met à jour les taux de la taxe d'habitation pour 2022.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Corrigent ou améliorent un calcul déjà existant.

2022-07-26 10:24 UTC, lukas-puschnig commented
Hello @sandcha et @benoit-cty , je vous ai mis en review, mais n'hésitez-pas de suggérer quelqu'un d'autre si vous connaissez quelqu'un pour qui ça serait plus pertinent.

2022-08-01 14:04 UTC, clallemand approved these changes

2022-08-02 08:24 UTC, benoit-cty requested changes
Bonjour,
Merci pour cette contribution, pourriez-vous ajouter la metadata `last_review` sur chaque paramètre ?
Voir https://github.com/openfisca/openfisca-france/wiki/Bonnes-pratiques-de-mod%C3%A9lisation#last_review pour plus d'information.
Cela permet de savoir quand le paramètre a été revu. Nous l'utilisons par exemple sur LexImpact pour indiquer si le paramètre est à jour.

2022-08-02 08:24 UTC, benoit-cty commented on openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/taux_sup_plaf.yaml
> +      title: art. 1414 C du CGI
```suggestion
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041465111/
      title: art. 1414 C du CGI
```

2022-08-02 08:24 UTC, benoit-cty commented on openfisca_france/parameters/taxation_indirecte/taxe_habitation/degrevement_d_office/plaf_rfr_degrev.yaml
>    metadata:
```suggestion
  metadata:
    last_review: "2022-08-01"
```

2022-08-03 11:51 UTC, benoit-cty approved these changes
Merci, c'est bon pour moi.

2022-08-03 12:29 UTC, merged