[plaf_GuadMarReu] Ajoute last_review et précise référence
openfisca/openfisca-france pull request #1874
Opened 2022-08-08 06:12 UTC by DorineLam

* Changement mineur.
* Périodes concernées : toutes.
* Zones impactées : `/parameters/impot_revenu.calcul_impot_revenu`.
* Détails :
  - Ajoute last_review
  - Précise les références
- - - -

Ces changements :
- Corrigent ou améliorent un calcul déjà existant.

2022-08-08 15:48 UTC, benoit-cty reviewed
Est-ce que les dates sont bonnes ?

2022-08-08 15:48 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/bareme_ir_depuis_1945/bareme.yaml
> +    - 0001-01-01:
```suggestion
    - 2022-01-01:
```

2022-08-08 15:48 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/celib.yaml
> +  - 0001-01-01:
```suggestion
  - 2022-01-01:
```

2022-08-08 15:48 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/celib_enf.yaml
> +  - 0001-01-01:
```suggestion
  - 2022-01-01:
```

2022-08-09 05:47 UTC, DorineLam commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/taux_GuadMarReu.yaml
> +    - 1979-07-01:
Hum je crois que c'est un reliquat de copier/coller ...
On peut remplacer par 0001-01-01 ou bien 2022.
Pour répondre à tes questions, je ne sais pas s'il faut que je mette la date du lien, du dernier paramètre ou la date de début du dispositif. 

- Si c'est la date du lien, alors il faudrait peut-être mettre 2022-08-08. 
- Si c'est la date du dernier paramètre, la date indiquée
- Autrement 2022-01-01

2022-08-11 12:45 UTC, DorineLam commented
@benoit-cty j'ai mis à jour le change.log mais je n'ai pas compris l'erreur indiquée au niveau de la version ...

2022-08-11 15:22 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/taux_GuyMay.yaml
> +      href: https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006069577&idArticle=LEGIARTI000006308322
```suggestion
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006308322
```

2022-08-11 15:22 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/decote/taux.yaml
> +      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042907517
Cette article à la date du 2020-01-01 ne contient pas le paramètre 45.25%

2022-08-11 15:22 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/general.yaml
> +      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042907517
Cet article n'a pas changé en 2021. C'est la bonne référence et la bonne valeur pour 2022.

2022-08-11 15:22 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/not31a.yaml
> +
Pas de référence, ni last_review ?

2022-08-11 15:22 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/enfant_marie/montant.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041464076/2022-08-08/
```suggestion
    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041464076/2022-01-01/
```

2022-08-11 16:46 UTC, DorineLam commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/enfant_marie/montant.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041464076/2022-01-01/
@eraviart @benoit-cty ici la date n'est pas décalée d'un an en arrière... étrange ... ?

2022-08-11 17:20 UTC, DorineLam commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/plaf_GuadMarReu.yaml
> +  - 0001-01-01:
@eraviart ici je ne suis pas sûre de comprendre d'où vient l'erreur de lint

2022-08-11 17:22 UTC, DorineLam commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/celib.yaml
> +  - 0001-01-01:
@eraviart ici aussi je ne sais pas comment résoudre le pb de lint

2022-08-12 10:59 UTC, benoit-cty approved these changes

2022-08-12 10:59 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/abat_dom/plaf_GuyMay.yaml
>    2018-01-01:
Ah oui, avec l'histoire du un an de décalage des paramètres IR OpenFisca !

2022-08-12 11:01 UTC, benoit-cty requested changes

2022-08-12 11:01 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/enfant_marie/montant.yaml
> +  2022-01-01:
Ah oui, c'est moi qui ai fait l'erreur !
```suggestion
  2021-01-01: 
```

2022-08-12 11:01 UTC, benoit-cty commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/enfant_marie/montant.yaml
> +    - href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041464076/2022-01-01/
Ah oui, c'est moi qui ai fait l'erreur !

2022-08-12 11:04 UTC, DorineLam commented
@benoit-cty j'ai corrigé

2022-08-12 12:21 UTC, benoit-cty approved these changes

2022-08-12 12:44 UTC, merged