Met en propre la réforme de l'abattement minimum pour les chomeurs de longue durée
openfisca/openfisca-france pull request #1895
Opened 2022-09-26 15:13 UTC by lukas-puschnig

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2018.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Améliore la prise en compte d'une réforme.
  - Ne devrait changer le calcul.
  - Met un end date à une variable (une case concrètement) qui n'existe plus.
  - Corrige des formules à partir de 2018.
  - Petit bug fix dans un autre fichier (met des guillemets).

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-09-26 15:45 UTC, lukas-puschnig commented
Hello @eraviart , est-ce que tu pourrais reviewer ce PR s'il te plaît ? C'est un petit PR alors ca ne devrait pas prendre longtemps. Merci!

2022-09-26 19:15 UTC, benjello requested changes
@eraviart ne pourra pas te faire une revue sur le fond donc je te fais un retour.
Sur le fond pas grand chose à part mes petites remarques.

2022-09-27 08:07 UTC, lukas-puschnig commented on openfisca_france/model/prestations/aides_logement.py
> +        hsup = individu('hsup', period.n_2, options = [ADD])
done, je l'ai aussi enlevée de la dernière définition alors.

2022-09-27 08:08 UTC, lukas-puschnig commented
> @eraviart ne pourra pas te faire une revue sur le fond donc je te fais un retour. Sur le fond pas grand chose à part mes petites remarques.

Merci @benjello ! Je pense que pour ce petit PR on pourrait se passer du review externe.

2022-09-27 08:09 UTC, benjello commented on openfisca_france/model/prestations/aides_logement.py
> +        hsup = individu('hsup', period.n_2, options = [ADD])
Je  n"ai pas regardé mais Il faut bien vérifier les périodes ...

2022-09-27 08:13 UTC, lukas-puschnig commented on openfisca_france/model/prestations/aides_logement.py
> +        hsup = individu('hsup', period.n_2, options = [ADD])
J'ai vérifié. La variable `hsup` a un end_date en 2013, je l'ai enlevée de la formule 2018 et aussi de la formule 2021 :+1:

2022-09-27 08:16 UTC, benjello commented
Je crois que comme on enlève une variable il faut que cela soit un montée de version majeure n'est-ce pas @sandcha ?

2022-09-27 08:17 UTC, benjello requested changes
Juste la montée de version si @sandcha est d'accord (elle m'a repris là-dessus dernièrement ....)

2022-09-27 08:22 UTC, lukas-puschnig commented
> Je crois que comme on enlève une variable il faut que cela soit un montée de version majeure n'est-ce pas @sandcha ?

Hm mais j'enlève pas de variable d'OpenFisca, je l'enlève d'une définition d'une autre variable, Alors je modifie une variable c'est tout - et étant donné le fait que la variable n'existe plus à ce date le calcul ne change pas. Ca me semble assez mineur comme changement mais je ferai comme vous proposez.

2022-09-27 08:25 UTC, benjello commented
> > Je crois que comme on enlève une variable il faut que cela soit un montée de version majeure n'est-ce pas @sandcha ?
> 
> Hm mais j'enlève pas de variable d'OpenFisca, je l'enlève d'une définition d'une autre variable, Alors je modifie une variable c'est tout - et étant donné le fait que la variable n'existe plus à ce date le calcul ne change pas. Ca me semble assez mineur comme changement mais je ferai comme vous proposez.

2022-09-27 08:26 UTC, benjello approved these changes

2022-09-27 08:28 UTC, merged