[WIP] PLFSS 2023: Réforme ASG + PAJE-CMG
openfisca/openfisca-france pull request #1899
Opened 2022-09-30 15:23 UTC by Sasha-Laniece

* Évolution du système socio-fiscal.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : 
 - Réforme ASF:
     - `prestations_sociales.prestations_familiales.education_presence_parentale.asf.montant_asf.orphelin_assimile_deux_parents`
     - `prestations_sociales.prestations_familiales.education_presence_parentale.asf.montant_asf.orphelin_assimile_seul_parent`
 - Réforme CMG:
    - `prestations_sociales.prestations_familiales.petite_enfance.paje.paje_cmg.limite_age.`
    - `paje.py`
* Détails :
  - Mise à jour suite PLFSS 2023

- - - -

Ces changements:
- Corrigent ou améliorent un calcul déjà existant.
- - - -

ATTENTION  ! Cette réforme n'est pas encore votée. Il faut encore:
- [  ] Vérifier qu'il n'y a pas eu de changements
- [  ] Ajouter les références législatives dans les paramètres pour justifier de leur évolution
-

2023-01-05 11:42 UTC, DorineLam requested changes
Revue des paramètres uniquement
Partie 1 jusqu'aux tabacs inclus

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/cigares.yaml
> +      - title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/cigarettes.yaml
> +      - title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/tabac_rouler.yaml
> +      - title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabac_rouler.yaml
> +      title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabacs_batonnets.yaml
> +      title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabacs_batonnets.yaml
> +      title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabacs_batonnets.yaml
> +      title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabacs_batonnets.yaml
> +      title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabacs_batonnets.yaml
> +      title: Code des impositions sur les biens et services, art L314-24
```suggestion
      title: Article L314-24 du Code des impositions sur les biens et services
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/autres_tabacs_a_fumer_apres_chauffer.yaml
> +  ux_name: Tabacs fumés après chauffe
```suggestion
  ux_name: Tabacs fumés/inhalés après chauffe
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/autres_tabacs_a_fumer_apres_chauffer.yaml
> +  ux_name: Tabacs fumés après chauffe
Il me semble que le terme "inhaler" fait partie de la caractéristique de cette catégorie

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/cigares.yaml
>    ipp_csv_id: tx_cigares
```suggestion
  ux_name: Cigares et cigarillos
  ipp_csv_id: tx_cigares
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/cigarettes.yaml
>    ipp_csv_id: tx_cigarettes
```suggestion
  ux_name: Cigarettes
  ipp_csv_id: tx_cigarettes
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/tabac_rouler.yaml
>    ipp_csv_id: tx_tabac_rouler
```suggestion
  ux_name: Tabac à rouler
  ipp_csv_id: tx_tabac_rouler
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/tabacs_chiquer.yaml
>    ipp_csv_id: tx_tabac_chiquer
```suggestion
  ipp_csv_id: tx_tabac_chiquer
  ux_name: Tabac à mâcher
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/tabacs_chiquer.yaml
>    ipp_csv_id: tx_tabac_chiquer
Changer aussi le terme chiquer dans la description

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taux_normal/tabacs_priser.yaml
>    ipp_csv_id: tx_tabac_priser
```suggestion
  ux_name: Tabac à priser
  ipp_csv_id: tx_tabac_priser
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/autres_tabacs_a_fumer_apres_chauffer.yaml
> +  ux_name: Tabacs fumés après chauffe
```suggestion
  ux_name: Tabacs fumés/inhalés après chauffe
```

2023-01-05 11:42 UTC, DorineLam commented on openfisca_france/parameters/taxation_indirecte/taxes_tabacs/taxes_specifiques/montants_apres_2015/tabac_rouler.yaml
>    ipp_csv_id: tx_spec_tabac_rouler
```suggestion
  ux_name: Tabac à rouler
  ipp_csv_id: tx_spec_tabac_rouler
```

2023-01-05 13:05 UTC, DorineLam reviewed
En fait, il ne restait que le test

2023-01-05 16:19 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cmg/limite_age/etendue.yaml
> +        title: LOI n° 2022-1616 du 23/12/2022 de financement de la sécurité sociale, art. 86, I-4ºb) et II-1º
Ok 👍

2023-01-05 16:20 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cmg/limite_age/etendue.yaml
> +        title: LOI n° 2022-1616 du 23/12/2022 de financement de la sécurité sociale, art. 86, I-4ºb) et II-1º
```suggestion
        title: Article 86, I.4.b et II.1 de la Loi n° 2022-1616 du 23/12/2022 de financement de la sécurité sociale
```

2023-01-05 17:25 UTC, DorineLam reviewed
Revue complète pour les paramètres ✅

2023-01-10 22:01 UTC, sandcha requested changes
Merci @Sasha-Laniece pour cette mise à jour !
Voici une revue de la CMG uniquement et quelques demandes de modification qui en découlent.

2023-01-10 22:01 UTC, sandcha commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +        salaire_horaire_brut = famille('remuneration_horaire_brute_employe', period)
Merci pour cette amélioration !

> Une note pour garder une trace du delta : sauf erreur, la condition de rémunération de la personne employée est antérieure à la LFSS 2023 qui modifie l'article L531-5 comme suit : 
> * en ajoutant au I. : `à la condition que la rémunération horaire de cette personne n'excède pas un plafond fixé par décret. Ce décret peut fixer des plafonds distincts selon que la personne employée est un assistant maternel agréé ou un salarié mentionné au même premier alinéa`
> * en supprimant au II. ceci pour (assistant maternel uniquement) : `à la condition que la rémunération correspondante de l'assistant maternel ne dépasse pas un taux de salaire horaire maximum fixé par décret.

2023-01-10 22:07 UTC, sandcha commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +                + 1.0 * parent_isole * (nb_enf(famille, period, paje.paje_cmg.limite_age.pleine, paje.paje_cmg.limite_age.etendue - 1) > 0)
S'il n'y a plus de taux réduit, retirer les deux `1.0 *` ? ^^

2023-01-11 11:32 UTC, sandcha commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cmg/limite_age/pleine.yaml
> +      title: LOI n° 2022-1616 du 23/12/2022 de financement de la sécurité sociale, art. 86, I-4ºb) et II-1º
A priori, le 6 ans étant antérieur à la LFSS 2023, on devrait avoir une référence de disponible mais elle n'a pas l'air simple à trouver 😅 
Il y a cette référence un peu indirecte qui décrit l'application de l'article L531-5 de la CMG emploi direct : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000039308946

2023-01-12 08:03 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cmg/limite_age/etendue.yaml
> +    value: null
Ceci vient de l'harmonisation, dans le doute où cela est utile à l'IPP, et comme ça ne coûte rien, on les a gardés systématiquement.

2023-01-12 15:03 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cmg/limite_age/etendue.yaml
> +description: Limite d'âge (stricte) pour une prestation réduite du Complément de libre choix de mode de garde (CMG) de la Prestation d'accueil du jeune enfant (PAJE)
Effectivement,
On passe de:
- 0-3 ans taux plein
- 3-6 ans taux réduit

À:
- 0-6: taux plein
- 6-12 ans & parents isolés: taux plein aussi (la limite de 12 ans et le taux (plein/réduit) seront confirmés par décret

2023-01-12 15:09 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cmg/limite_age/etendue.yaml
> +    value: 12
On est en attente de décret, en effet

2023-01-16 10:36 UTC, sandcha commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_cmg/limite_age/pleine.yaml
> +description: Limite d'âge (stricte) pour un montant plein du Complément de libre choix de mode de garde (CMG) de ka Prestation d'accueil du jeune enfant (PAJE)
```suggestion
description: Limite d'âge (stricte) pour un montant plein du Complément de libre choix de mode de garde (CMG) de la Prestation d'accueil du jeune enfant (PAJE)
```

2023-01-16 11:02 UTC, DorineLam approved these changes

2023-01-16 13:43 UTC, sandcha commented
Rebase en cours (était sur master v 137.0.0)

2023-01-16 15:51 UTC, merged