[Harmonisation] IR - calcul impot revenu - Plus Values
openfisca/openfisca-france pull request #1933
Opened 2022-12-02 11:47 UTC by Sasha-Laniece

* Amélioration technique
* Périodes concernées : toutes
* Zones impactées : `parameters.calcul_impot_revenu.pv`.
* Détails :
  - Ajout des paramètres issus du barème IPP
  - Ajout des références dans les paramètres existants

- - - -

Ces changements"

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

2022-12-06 14:16 UTC, eraviart approved these changes

2022-12-06 14:46 UTC, clallemand requested changes

2022-12-06 14:51 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/reduction_ss_condition_revenus/majoration_plafond_par_demi_parts_supp.yaml
> +  2019-12-31:
est ce que tu peux m'expliquer pourquoi tu as changé pour 31/12 ? Pour que je comprenne ce que j'ai mal expliqué. Surtout que tu avais bien mis 2019-01-01 au début me semble-t-il

2022-12-06 15:07 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/reduction_ss_condition_revenus/majoration_plafond_par_demi_parts_supp.yaml
> +  2019-12-31:
C'est '2019-01-01' côté IPP, mais si je mets cela on casse les tests. Tu disais que c'est intégré dans la décôte à partir de 2020, donc je mettrais plutôt '2020-01-01' ? Auquel cas on aurait une erreur côté IPP ?

2022-12-07 09:27 UTC, clallemand approved these changes

2022-12-07 09:28 UTC, clallemand commented
Je valide Sasha, désolée il y a des comentaires que j'ai fait hier et je n'avais pas vu qu'il étaient pas publiés en fait, mais comme on en a discuté entre temps c'est ok

2022-12-07 09:44 UTC, benjello commented
@clallemand : pourrais-tu corriger en amont sur les barèmes IPP aussi afin que l'on ne se repose pas la question lors de l'homogeneisation ?

Merci !

2022-12-07 10:38 UTC, merged