nettoyage des metadata de paramètres sur le minimum vieillesse
openfisca/openfisca-france pull request #1937
Opened 2022-12-08 17:09 UTC by clallemand

* Changement mineur.
* Périodes concernées : toutes.
* Zones impactées : `parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/`.
* Détails :
  - Nettoyage de certaines métadonnées

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

2022-12-09 15:05 UTC, benjello requested changes

2022-12-14 13:50 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/index.yaml
> +  (1) Ou lorsque un seul des conjoints bénéficie de l'ASPA.
@benjello j'ai plutôt choisi de reformuler les notes car en fait elles sont valables pour plusieurs séries de l'aspa. Est ce que cela te convient ?

2022-12-14 13:53 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/index.yaml
> +  (1) Ou lorsque un seul des conjoints bénéficie de l'ASPA.
Oui c'est très bien.

2022-12-14 13:53 UTC, benjello approved these changes

2022-12-14 14:19 UTC, benjello commented
@clallemand tu peux désormais "bumper" la version.

2022-12-14 15:08 UTC, benjello commented
@eraviart : peux-tu passer ton nettoyeur et on merge dans la foulée ?

2022-12-14 15:17 UTC, merged