Demarrage
openfisca/openfisca-france pull request #1951
Opened 2022-12-16 14:32 UTC by Sasha-Laniece

En réponse à cette issue: https://github.com/openfisca/openfisca-france/issues/1946

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2022-12-16 14:37 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
> +      href: https://www.anil.org/aj-plafonds-ressources-2018-logement-social/
Faudrait trouver le texte légifrance ...
J'ai mis des liens qui prouvait que ce n'était pas à jour mais je ne suis pas allé plus loin.

2022-12-16 14:40 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
> +      href: https://www.anil.org/aj-plafonds-ressources-2018-logement-social/
Yes ! De toute façon je suis en pause car je suis dans le train et j'ai besoin d'un 2e écran pour faire ça efficacement

2022-12-16 14:41 UTC, Sasha-Laniece commented
@benjello Si je me chauffe à faire en même temps les paramètres du PLUS, tu penses que la formule pourrait être codée par chez vous ?

2022-12-16 14:46 UTC, benjello commented
C'est juste une eligibilite donc je ne pense pas que cela intéresse plus que cela @openfisca/france-contrib-ipp mais peut être que @openfisca/france-contrib-mesaides ou @openfisca/france-contrib-mesaides seraient put-être intéressés.

Et puis je ne pense pas que cela sois très long et largement similaire à PLAI donc je peux rearder aussi si besoin.
Le plus long ce sont les paramètres ...

2022-12-16 14:49 UTC, Sasha-Laniece commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
> +      href: https://www.anil.org/aj-plafonds-ressources-2018-logement-social/
> C'est juste une éligibilité donc je ne pense pas que cela intéresse plus que cela @openfisca/france-contrib-ipp mais peut être que @openfisca/france-contrib-mesaides ou @openfisca/france-contrib-mesaides seraient put-être intéressés.
> 
> Et puis je ne pense pas que cela sois très long et largement similaire à PLAI donc je peux rearder aussi si besoin. Le plus long ce sont les paramètres ...

Top ! Je vais m'y pencher alors !

2022-12-18 17:03 UTC, Sasha-Laniece commented
J'ai aussi modifié le calcul en précisant les conditions d'éligibilité:

2022-12-18 21:52 UTC, benjello requested changes

2022-12-18 21:52 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/ile_de_france.yaml
> +description: Catégorie 1 / Île-de-France - Plafonds de ressources annuelles applicables aux logements financés avec un Prêt Locatif Aidé d'Intégration (PLAI)
```suggestion
description: Catégorie 1 / Île-de-France - Plafonds de ressources annuelles applicables aux logements financés avec un prêt locatif aidé d'intégration (PLAI)
```

2022-12-18 21:52 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
> +description: Catégorie 1 / Paris et communes limitrophes - Plafonds de ressources annuelles applicables aux logements financés avec un Prêt Locatif Aidé d'Intégration (PLAI)
```suggestion
description: Catégorie 1 / Paris et communes limitrophes - Plafonds de ressources annuelles applicables aux logements financés avec un prêt locatif aidé d'intégration (PLAI)
```

2022-12-18 21:52 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_2/autres_regions.yaml
> +description: Catégorie 2 / Autres régions - Plafonds de ressources annuelles applicables aux logements financés avec un Prêt Locatif Aidé d'Intégration (PLAI)
```suggestion
description: Catégorie 2 / Autres régions - Plafonds de ressources annuelles applicables aux logements financés avec un prêt locatif aidé d'intégration (PLAI)
```

2022-12-18 21:52 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/autres_regions.yaml
> +description: Catégorie 1 / Autres régions - Plafonds de ressources annuelles applicables aux logements financés avec un Prêt Locatif Aidé d'Intégration (PLAI)
```suggestion
description: Catégorie 1 / Autres régions - Plafonds de ressources annuelles applicables aux logements financés avec un prêt locatif aidé d'intégration (PLAI)
```

2022-12-18 21:52 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plai/plafond_ressources/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
> +description: Catégorie 1 / Paris et communes limitrophes - Plafonds de ressources annuelles applicables aux logements financés avec un Prêt Locatif Aidé d'Intégration (PLAI)
Retirer les majuscules dans toutes les descriptions.

2022-12-19 18:36 UTC, benjello approved these changes

2022-12-19 19:37 UTC, merged