Refactor credits impots - interets emprunt
openfisca/openfisca-france pull request #2007
Opened 2023-01-23 19:50 UTC by benjello

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2023-01-24 10:14 UTC, Sasha-Laniece requested changes

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +# Pcredit = P.credits_impotss
2 's' ?

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/cas_base/taux_applique_premiere_annuite_remboursement.yaml
> +description: Taux appliqué à la première annuité de remboursement pour le crédit d'impôt sur les intérêts d'emprunt pour l'habitation principale
Est-ce qu'on ne mettrait pas les infos "réforme Sarkozy" dans la documentation ? Pour les gens qui feraient leur recherche sous ce nom

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/logements_2011/taux_2.yaml
> -documentation: Taux appliqué aux intérêts payés au titre des cinq premières annuités de remboursement, à l'exclusion des frais d'emprunt et des cotisations d'assurances contractées en vue de garantir
Pourquoi enlever ces informations ?

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/logements_2010/taux_applique_premiere_annuite_remboursement.yaml
> -description: Taux appliqué à la première annuité de remboursement pour les logements neufs construits ou acquis en 2010 au titre du Crédit d'impôt - intérêts d'emprunt pour l'habitation principale (r
On ne perd pas de l'information ici ? La description doit être stand-alone

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/logements_2012/taux_2.yaml
> -description: Taux spécifique pour les logements neufs construits ou acquis en 2012 au titre du Crédit d'impôt - intérêts d'emprunt pour l'habitation principale (réforme Sarkozy)
Idem, il manque de l'info ici

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/logements_performants_energie/taux_unique.yaml
> +description: Taux unique
Idem, il manque de l'info ici

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/logements_performants_energie/taux_unique.yaml
> -documentation: Dans le cas de logement à performance énergétique globale élevée, les intérêts ouvrants droit au crédit d'impôt sont ceux des sept premières années d'annuité
Idem, pourquoi supprimer?

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/majoration_plafond_par_enfant_charge.yaml
> +description: Majoration du plafond par enfant à charge
Idem, il manque de l'info ici

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/plafond_base.yaml
> +description: Plafond de base
Idem, il manque de l'info ici

2023-01-24 10:14 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/plafond_handicap.yaml
> +description: Plafond handicap
Idem, il manque de l'info ici

2023-01-24 10:19 UTC, benjello commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/cas_base/taux_applique_premiere_annuite_remboursement.yaml
> +description: Taux appliqué à la première annuité de remboursement pour le crédit d'impôt sur les intérêts d'emprunt pour l'habitation principale
Oui je crois que je l'ai mis plus haut ans l'arborescence.

2023-01-24 11:09 UTC, benjello commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/cas_base/taux_applique_premiere_annuite_remboursement.yaml
> +description: Taux appliqué à la première annuité de remboursement pour le crédit d'impôt sur les intérêts d'emprunt pour l'habitation principale
Je préfère le laisser dans le champ documentation

2023-01-24 11:26 UTC, benjello commented
@Sasha-Laniece : j'ai rétabli pas mal de trucs, est-ce que cela te va ?

2023-01-24 16:20 UTC, benjello commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/logements_performants_energie/taux_unique.yaml
> -documentation: Dans le cas de logement à performance énergétique globale élevée, les intérêts ouvrants droit au crédit d'impôt sont ceux des sept premières années d'annuité
J'ai gardé plus haut dans l'arbre pour éviter les redite

2023-01-24 18:55 UTC, Sasha-Laniece approved these changes
Juste des questions/modifs et c'est bon !

2023-01-24 18:55 UTC, Sasha-Laniece commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> -# TODO: CSG, CRDS et prélèvements sociaux sur revenu du patrimione, d'activité et de remplacement
Tu supprimes parce que c'est fait ?

2023-01-24 18:55 UTC, Sasha-Laniece commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/plafond_handicap.yaml
> -documentation: Les plafonds (plafonds de base et handicap) sont ceux appliqués aux célibataires, veufs, divorcés. Ils sont multipliés par deux pour les couples
Pourquoi supprimer cette info ? C'est utile pour les calculs, non ?

2023-01-25 09:43 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> -# TODO: CSG, CRDS et prélèvements sociaux sur revenu du patrimione, d'activité et de remplacement
Je pense en partie mais ici cela n'aide pas. Donc oui.

2023-01-25 09:43 UTC, benjello commented on openfisca_france/parameters/impot_revenu/credits_impots/interets_emprunt_habitation_principale/plafond_handicap.yaml
> -documentation: Les plafonds (plafonds de base et handicap) sont ceux appliqués aux célibataires, veufs, divorcés. Ils sont multipliés par deux pour les couples
Je garde.

2023-01-25 10:35 UTC, merged