Correction mineure end param ir
openfisca/openfisca-france pull request #2041
Opened 2023-02-27 13:37 UTC by clallemand

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Changement mineur.
* Périodes concernées : à partir du 01/01/2014.
* Zones impactées : 
  - `/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/decote/seuil.yaml`
  - `/openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py`
* Détails :
  - Ajout d'une valeur nulle pour un paramètre qui est remplacé par d'autres paramètres à partir des revenus 2014

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Corrigent ou améliorent un calcul déjà existant.

2023-02-27 16:55 UTC, benjello requested changes
Voir commentaires

2023-02-27 16:55 UTC, benjello commented on openfisca_france/units.yaml
> +- name: part_qf
J'utiliserais plutôt un nom long et explicite.

2023-02-27 16:55 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/conj.yaml
> +description: Part supplémentaire de quotient familial pour le conjoint d'un couple marié ou pacsé - Impôt sur le revenu
Il me semblait que l'on avait dit que l'on retirait la mention Impôt sur le revenu en fin de description ?

2023-02-27 16:55 UTC, benjello commented on openfisca_france/reforms/plf2016.py
> +            nb_adult = foyer_fiscal('nb_adult', period)
Je ne sais pas s'il faut garder ce fichier réforme surtout si on ne le teste pas

2023-03-01 07:38 UTC, clallemand commented
@benjello j'ai fait les modifs que tu suggérais, est ce que cela te convient ?

2023-03-01 07:43 UTC, benjello requested changes
J'ai encore des objections sur les description.

Et au moins préciser ce qui change en 2008 pour nbptr.

2023-03-01 07:43 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf2.yaml
> +description: Part supplémentaire de quotient familial par enfant, à partir du 3ème enfant - Impôt sur le revenu
Retirer le Impôt sur le revenu en fin de description

2023-03-01 07:43 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf1.yaml
> +description: Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant - Impôt sur le revenu
Retirer le Impôt sur le revenu en fin de description

2023-03-01 08:08 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf1.yaml
> +description: Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant - Impôt sur le revenu
Pardon j'avais fait un commentaire sur ce point mais il était resté en brouillon. 

Je suis un peu perdue avec cette description parce que j'étais restée sur le fait qu'il fallait indiquer "tout le chemin" du paramètre dedans. Est ce que cela fait suite à la studieuse et notamment la phrase `Il est toléré de raccourcir un peu le label s'il est vraiment trop long et que certaines choses sont explicites`dans le wiki ?

Parce que n'étant pas dans le groupe de travail sur cet aspect là je ne trouve pas du tout évident ce qui est explicite ou pas. 

Peut être que ça vaut le coup de rajouter dans le wiki qu'il ne faut pas mettre impôt sur le revenu dans le label ?

2023-03-01 08:18 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf1.yaml
> +description: Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant - Impôt sur le revenu
@DorineLam est-ce que tu penses que ma remarque est valable ?
Je pense que Chloé a raison et qu'il faut expliciter mieux ce que l'on entend par trop long.
Personellement, je rajouterais que cela doit tenir en une phrase (éventuellement avec des éléments entre parenthèses).

2023-03-01 08:18 UTC, clallemand commented
> J'ai encore des objections sur les description.
> 
> Et au moins préciser ce qui change en 2008 pour nbptr.

J'ai changé la description de la PR

2023-03-01 09:25 UTC, DorineLam commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf1.yaml
> +description: Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant - Impôt sur le revenu
Je suis un peu partagée, ici, on fait référence uniquement à quotient familial, qui pour les initiés permet de savoir direction qu'il s'agit de l'IR.... Mais pour un non-initié ...
Une autre façon aurait été d'écrire : 

> Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant, entrant dans le calcul de l'impôt sur le revenu.

Mais c'est encore plus long...

2023-03-01 10:31 UTC, DorineLam commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf1.yaml
> +description: Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant - Impôt sur le revenu
Autre élément, il existe un autre type de quotient familial : le quotient familial de la CAF. Ce qui peut porter à confusion

2023-03-01 10:47 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf1.yaml
> +description: Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant - Impôt sur le revenu
Que pensez-vous de :

> Part supplémentaire de quotient familial (au sens de l'IR) par enfant, jusqu'au 2ème enfant.

> Part supplémentaire de quotient familial (IR) par enfant, jusqu'au 2ème enfant.

2023-03-01 12:59 UTC, DorineLam commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/quotient_familial/enf1.yaml
> +description: Part supplémentaire de quotient familial par enfant, jusqu'au 2ème enfant - Impôt sur le revenu
Deuxième version top 👍

2023-03-03 09:33 UTC, pzuldp commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        nb_pac = foyer_fiscal('nb_pac', period)
Pour les très longues formules comme ça, est-ce que ça ajouterait à la lisibilité du code de rajouter un petit commentaire expliquant la diff avec la formule d'avant ?
```suggestion
        '''
        Modification de la prise en compte des enfants à charge du conjoint décédé et du veuf.
        '''
        nb_pac = foyer_fiscal('nb_pac', period)
```

2023-03-03 10:19 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        nb_pac = foyer_fiscal('nb_pac', period)
Je me demande même si cela ne vaut pas le coup de factoriser le code.

2023-03-03 13:12 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        nb_pac = foyer_fiscal('nb_pac', period)
Je ne comprends pas ce que signifie factoriser le code

2023-03-03 16:20 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        nb_pac = foyer_fiscal('nb_pac', period)
Eviter d'avoir une grosse partie qui est copié-collé et donc ne l'avoir qu'à un seul endroit.
Cela suppose peut-être d'introduire une variable intermédiaire (qu'il faudra mettre dans la blacklist pour ne pas la conserver) ou une fonction ad hoc qu'on utilise au deux endroits (mais cela limite un peu la lisibilité du code pour des personnes non-spécialiste).

2023-03-03 18:20 UTC, pzuldp commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        nb_pac = foyer_fiscal('nb_pac', period)
je comprends l'idée mais vous ne pensez pas que factoriser réduirait la transparence de la formule ? au final, si on suit la brochure pratique de l'IR, le calcul est long...

2023-03-03 19:08 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        nb_pac = foyer_fiscal('nb_pac', period)
Moi je suis pour garder le changement de formule tel quel mais rajouter des explications comme le suggérait @pzuldp. Surtout que bon il n'y a pas des changements tous les ans non plus... Ça t'irait @benjello ?

2023-03-03 20:19 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        nb_pac = foyer_fiscal('nb_pac', period)
Tout me va.

2023-03-06 11:05 UTC, benjello approved these changes

2023-03-06 13:10 UTC, merged