Mise à jour barêmes 2023
openfisca/openfisca-france pull request #2049
Opened 2023-03-09 09:37 UTC by PhunkyBob

Bonjour,

Dans le but d'avoir des chiffres comparables à ceux retournés par le site du gouvernement, j'ai apporté les modifications suivantes. 

* Évolution du système socio-fiscal / Changement mineur.
* Périodes concernées : à partir du 01/01/2022.
* Zones impactées : 
`openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/min.yaml`
`openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/max.yaml`
`openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/min.yaml`
`openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml`
* Détails :
  - Barême de l'IR : Pension alimentaire perçue par un ex-conjoint
  - Barême de l'IR : Frais professionnels - forfait ou frais réels (déduction)

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2023-03-09 16:58 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/max.yaml
> +
```suggestion
```

2023-03-09 16:58 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/min.yaml
> +
```suggestion
```

2023-03-09 17:00 UTC, benjello requested changes
Merci pour votre contribution.
Les références recevables sont des liens vers la législation.

2023-03-09 17:35 UTC, PhunkyBob reviewed
Ok

2023-06-19 10:04 UTC, sylvainipp commented
Les textes de revalorisation ont été sortis, je les ai mis sur ma PR. Il est peut-être temps de fermer celle-ci par conséquent ?

2023-06-19 10:05 UTC, closed without merging