Règle de deconjugalisation du plafond de ressources pour l'aah
openfisca/openfisca-france pull request #2078
Opened 2023-04-04 12:28 UTC by robinguill

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/09/2023.
* Zones impactées : `tests\formulas\aah\aah_couple.yaml`, `openfisca_france\model\prestations\minima_sociaux\aah.py`.
* Détails :
  - Déconjugalisation des plafonds des ressources pour l'AAH

- - - -

Ces changements:

- Corrigent ou améliorent un calcul déjà existant.

2023-04-04 15:27 UTC, robinguill commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +            + 1
Python est si gentil de laisser passer ça ...

2023-04-05 09:20 UTC, JoDuGa requested changes

2023-04-05 09:20 UTC, JoDuGa commented on openfisca_france/reforms/aah_deconjugalisee.py
> +            plaf_ress_aah = individu('aah_plafond_ressources_deconjugalisee', period)
Où est définie cette classe ? S'agit-il de celle 'aah_plafond_ressources' qui a été ajoutée ligne 184 ?

2023-04-05 09:20 UTC, JoDuGa commented on openfisca_france/reforms/aah_deconjugalisee.py
> +class aah_plafond_ressources(Variable):
S'agit-il du bon nom de classe ?

2023-04-05 09:20 UTC, JoDuGa commented on openfisca_france/model/prestations/minima_sociaux/aah.py
> +            1
Pour toute cette méthode, est-ce-qu'on ne pourrait pas mettre parameters(period).prestations_sociales.prestations_etat_de_sante.invalidite.aah dans une variable ? Comme ça on n'aurait pas des appels de parameters à rallonge...

2023-04-05 10:56 UTC, merged