Corrections prelsoc
openfisca/openfisca-france pull request #2101
Opened 2023-05-15 08:42 UTC by pzuldp

* Évolution du système socio-fiscal.
* Périodes concernées : toutes.
* Zones impactées : `model/revenus/activite/salarie.py`.
* Détails :
  - Déplace les paramètres par défaut de taux de participation de l'employeur à la complémentaire santé et à la prévoyance obligatoire dans le dossier paramètres
  - Recode la participation employeur de telle sorte à être compatibles avec l'assiette de CSG non abattue.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2023-05-17 16:58 UTC, benjello requested changes
Surtout dees changements de code par souci d'homoénéisation.

2023-05-17 16:58 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +        estimation_abattue = switch(
Utiliser plutôt where

2023-05-17 16:58 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +            cotisation = switch(effectif_entreprise == 0, {
Utiliser plutôt where.

2023-05-17 16:58 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +        with np.errstate(invalid='ignore'):
Quelle est l'erreur que tu veux éviter ? Une division par zéro ?

2023-05-17 16:58 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
> +        part_emp = max_(complementaire_sante_part_employeur, minimum)
Utiliser plutôt part_employeur

2023-05-17 16:58 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/travail_prive.py
> +        part_emp = individu('complementaire_sante_part_employeur', period)
Utiliser plutôt part_employeur

2023-05-17 16:58 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +        estimation_reduite = np.select(conditions, results)
Tu peux utiliser le select d'openfisca. Il y a plein d'exemples dans france.

2023-05-19 14:08 UTC, pzuldp commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +        with np.errstate(invalid='ignore'):
je n'ai pas modifié ce morceau de code, donc je ne sais pas répondre à cette question

2023-05-19 14:50 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +        with np.errstate(invalid='ignore'):
Ok, les `+` m'ont induit en erreur.

2023-05-19 14:50 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/taxes_salaires_main_oeuvre.py
> +        estimation_abattue = np.where(
Utiliser `where` au lieu de `np.where`. il y en a plusieurs comme cela.

2023-05-19 15:38 UTC, benjello approved these changes
Super taf. Merci Paul !

2023-05-19 17:04 UTC, merged