Corrige la liste des pays de l'union europeene
openfisca/openfisca-france pull request #2113
Opened 2023-05-31 09:26 UTC by Nodraak

Corrige la liste des pays de l'Union Européenne : "SV" correspond au Salvador (SV/SLV), et non pas à la Slovenie (SI/SVN).

---

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Amélioration technique.
* Périodes concernées : toutes.
* Zones impactées : `openfisca_france/parameters/geopolitique/ue.yaml`.
* Détails :
  - Corrige la liste des pays de l'Union Européenne : "SV" correspond au Salvador (SV/SLV), et non pas à la Slovenie (SI/SVN).

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2023-05-31 09:29 UTC, benjello approved these changes

2023-06-03 14:31 UTC, Nodraak commented
> Top, il ne manque qu'une mise à jour du CHANGELOG slightly_smiling_face

Fait :)

2023-06-03 15:02 UTC, MattiSG requested changes
Merci @Nodraak ! Je vais prendre les correctifs du CHANGELOG en charge 🙂 

Pour faciliter la revue, dans le futur, merci de privilégier les push successifs plutôt que des force push 🙂 
Cela permet aux reviewers de revoir uniquement ce qui a changé depuis leur dernière revue et de préserver les liens dans les notifications par mail et l'historique de la CI 🙂

2023-06-03 15:02 UTC, MattiSG commented on CHANGELOG.md
> +* Périodes concernées : toutes.
Seulement depuis l'entrée de la Slovénie dans l'UE 🙂 
```suggestion
* Périodes concernées : à partir de 2004.
```

2023-06-03 15:02 UTC, MattiSG commented on CHANGELOG.md
> +* Changement mineur.
```suggestion
* Correction du système socio-fiscal.
```

2023-06-03 15:02 UTC, MattiSG commented on CHANGELOG.md
> +  - Corrige la liste des pays de l'Union Europeenne
```suggestion
  - Corrige le code pays de la Slovénie dans l'Union Européenne
```

2023-06-03 15:04 UTC, MattiSG approved these changes
Merci beaucoup ! 🙏 🇸🇮

2023-06-03 15:10 UTC, merged