Corrige le forfait asf pris en compte dans le calcul du rsa et de la pa
openfisca/openfisca-france pull request #2118
Opened 2023-06-09 07:50 UTC by clallemand

* Amélioration technique.
* Périodes concernées : à partir du 01/04/2014
* Zones impactées : 
    - `/openfisca_france/model/prestations/minima_sociaux/rsa.py`.
    - `/openfisca_france/model/prestations/minima_sociaux/ppa.py`.
    - `/openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml`
    - `/openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux2.yaml`
* Détails :
  - Correction de la prise en compte de l'asf dans la base ressource du RSA et de la prime d'activité. Pour le calcul de ces dispositifs le montant d'asf est pris en compte est plafonné et ce montant plafonné était mal calculé.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Corrigent ou améliorent un calcul déjà existant.

2023-06-09 07:58 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/rsa.py
> +        taux_max_par_enfant = bmaf * minima_sociaux.rsa.rsa_maj.forfait_asf.taux1
Y'a pas un pb ici. On risque de compter deux fois la bmaf

2023-06-09 08:09 UTC, clallemand commented on openfisca_france/model/prestations/minima_sociaux/rsa.py
> +        taux_max_par_enfant = bmaf * minima_sociaux.rsa.rsa_maj.forfait_asf.taux1
oui effectivement, merci !

2023-06-09 10:29 UTC, benjello requested changes

2023-06-09 10:29 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/rsa.py
> +        montant_max_retenu_rsa_par_enfant = (
Je mettrais plutot un `where` ici pour montrer que c'est bien une condition (avec un booléen).

2023-06-09 10:54 UTC, benjello approved these changes

2023-06-12 08:46 UTC, DorineLam approved these changes

2023-06-12 08:46 UTC, DorineLam commented on openfisca_france/model/prestations/minima_sociaux/rsa.py
> +        'Article R844-4 du code de la sécurité sociale, pour la PA',
Détail : Mettre en premier la Ref pour le RSA ?

2023-06-12 08:46 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
>  description: "Orphelin de père ou de mère (un seul parent manquant) ou situation assimilée: beaux parents ou pension alimentaire non versée"
```suggestion
description: "Taux du montant de l'ASF pris en compte dans le calcul de la base de ressources du revenu de solidarité active (RSA) pour les ménages composé d'un orphelin d'un seul des deux parents, ou situations assimilées telles qu'un parent hors d'état de faire face à ses obligations ou ne versant pas la pension alimentaire."
```

2023-06-12 08:46 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +  last_value_still_valid_on: "2023-06-08"
```suggestion
  short_label: "Taux de l'ASF pris en compte dans la base ressources du RSA pour les orphelins d'un seul parent ou situations assimilées
  last_value_still_valid_on: "2023-06-08"
```

2023-06-12 08:46 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
> +    - title: Article R262-10-1 du code de l'action sociale et des familles
Ajouter une documentation à la suite pour expliquer ce que sont les situations assimilées : 
L'article  L523-1 du Code de la sécurité sociale (https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000044629511) décrit les situations assimilées.

2023-06-12 08:46 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux2.yaml
>  description: Orphelin (de père et de mère), ou situation assimilée
```suggestion
description: "Taux du montant de l'ASF pris en compte dans le calcul de la base de ressources du revenu de solidarité active (RSA) pour les ménages composé d'un orphelin des deux parents, ou situations assimilées telles qu'un parent hors d'état de faire face à ses obligations ou ne versant pas la pension alimentaire."
```

2023-06-12 08:46 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux2.yaml
> +  last_value_still_valid_on: "2023-06-08"
```suggestion
  short_label: "Taux de l'ASF pris en compte dans la base ressources du RSA pour les orphelins des deux parents ou situations assimilées"
  last_value_still_valid_on: "2023-06-08"
  
```

2023-06-12 08:46 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/rsa/rsa_maj/forfait_asf/taux1.yaml
>  description: "Orphelin de père ou de mère (un seul parent manquant) ou situation assimilée: beaux parents ou pension alimentaire non versée"
@clallemand je profite de ta PR pour rendre plus clair les labels.

Du coup, il me semble qu'il n'est pas utile de garder la mention "père et mère" mais que simplement "parent" suffit et inclut toutes les situations possibles.

2023-06-13 08:32 UTC, merged