Synchro ir
openfisca/openfisca-france pull request #2121
Opened 2023-06-14 14:48 UTC by benjello

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2023-08-03 12:36 UTC, clallemand requested changes
Petit récapitulatif général de mes commentaires : 
- Je veux bien une explication de `currency_next_year` et des implications qui en découlent
- A quoi correspond la métadonnée `documentation_start` ? Il ne me semble pas qu'elle existe dans openfisca jusquèà maintenant.
- Il y a pleins de value null qui ont été rajoutée avant la première valeur, c'est-à-dire avant la date de création du paramètre. Je suppose que ça découle de la structure des barèmes IPP organisés en tableau mais je ne pense pas que ce soit une bonne chose de les mettre dans openfisca car cela n'a pas de sens, d'autant plus que les dates ne sont pas toutes les mêmes. De plus des références ont été rajoutées en lien avec ces dates, elles ne concernent donc pas le paramètre en question a priori mais un autre paramètre qui était sur la même feuille dans les barèmes IPP.
- Il y a plusieurs descriptions qui ont été ajoutées qui correspondent plus à des short label qu'à des descriptions, je ne l'ai pas signalé à chaque fois.

Je n'ai pas lu le contenu de la documentation ajoutée ou déplacée, c'était trop d'info pour moi. Pour les prochaines PR équivalentes n'hésite pas à découper davantage !

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/accueil_personne_agee/plafond.yaml
> +    value: null
Cette valeur nulle me paraît suspecte

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/plafond.yaml
> +    value: null
cette valeur nulle me paraît suspecte

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_ba/montant_minimum.yaml
> +    value: 305
Est ce que ce n'est pas un doublon du paramètre `openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/montant_minimum.yaml` suite à un déplacement dans la loi ?

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/microsocial/servi.yaml
> +    1979-01-01:
a priori cette référence ne concerne pas ce paramètre

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/microsocial/bnc.yaml
> +    1979-01-01:
a priori cette référence ne concerne pas ce paramètre

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/contributions_exceptionnelles/minorations_exceptionnelles/seuil_impot_1.yaml
> -  short_label: Seuil 1
je trouve que "Seuil 1" est plus compréhensible que "1"

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/contributions_exceptionnelles/minorations_exceptionnelles/seuil_impot_2.yaml
> -  short_label: Seuil 2
je trouve que "Seuil 2" est plus compréhensible que "2"

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/contributions_exceptionnelles/minorations_exceptionnelles/seuil_impot_3.yaml
> -  short_label: Seuil 3
idem

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/contributions_exceptionnelles/minorations_exceptionnelles/taux_1.yaml
> +  short_label: "1"
ancien short label plus compréhensible

2023-08-03 12:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/credits_impots/plaf_nich/plafonnement_des_niches/majoration_om.yaml
> -description: Majoration du plafond global des avantages fiscaux pour les investissements d'outre-mer
L'ancienne description est plus complète je trouve

2023-08-03 12:41 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_reductions_impots/compte_epargne_co_developpement/plafond/plafond_par_personne.yaml
> +  2009-01-01:
Yep. Traité dans commit qui va venir

2023-08-03 12:41 UTC, benjello commented on openfisca_france/parameters/impot_revenu/contributions_exceptionnelles/minorations_exceptionnelles/taux_1.yaml
> +  short_label: "1"
Ok

2023-08-03 12:41 UTC, benjello commented on openfisca_france/parameters/impot_revenu/contributions_exceptionnelles/minorations_exceptionnelles/seuil_impot_3.yaml
> -  short_label: Seuil 3
Ok

2023-08-03 12:42 UTC, benjello commented on openfisca_france/parameters/impot_revenu/contributions_exceptionnelles/minorations_exceptionnelles/seuil_impot_1.yaml
> -  short_label: Seuil 1
Ok

2023-08-03 12:45 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_reductions_impots/cotisations_syndicales/taux.yaml
> +  1987-01-01:
Je crois que l'on avait mis cela, car cela nous permettait soit de dater le début, soit de s'assurer que cela n'existait pas avant. Mais oui, il faut améliorer cela, mais c'est orthogonal à cette PR. Mais je ne veux pas jetter cette info qui était dans les barèmes.

2023-08-03 12:46 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_impot_revenu/plaf_qf/index.yaml
> +  documentation_start: true
Pour construire la doc sans redondance, il doit agréger la doc pour une série/feuille de l'arbre des paramètres en remontant jusqu'à ce noeud.

2023-08-03 12:47 UTC, benjello commented on openfisca_france/parameters/impot_revenu/anciens_baremes_igr/bareme_igr_1917_1918/seuils/tranche_1.yaml
> +  unit: currency_next_year
C'est l'unité monétaire de l'année suivante car comme on est en année revenus pour les variables IR cela peut poser problème au changement de monnaie.

2023-08-03 13:41 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_reductions_impots/divers/intemp/deduction_des_charges/plafond.yaml
> +description: Plafond
Ce sont des vieilles valeurs en provenance des barèmes et je n'ai pas plus d'infos.

2023-08-03 13:41 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_reductions_impots/divers/intemp/deduction_des_charges/increment.yaml
> +description: Incrément
Ce sont des vieilles valeurs en provenance des barèmes et je n'ai pas plus d'infos.

2023-08-05 07:54 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_ba/montant_minimum.yaml
> +    value: 305
Oui, je le retire

2023-08-05 08:00 UTC, benjello commented on openfisca_france/parameters/impot_revenu/credits_impots/plaf_nich/plafonnement_des_niches/majoration_om.yaml
> -description: Majoration du plafond global des avantages fiscaux pour les investissements d'outre-mer
Je ne trouve pas une description plus complète

2023-08-05 08:53 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_reductions_impots/divers/intemp/interets_d_emprunts/increment.yaml
> +description: Incrément
Je ne sais pas quoi mettre, je garde en attendant mieux

2023-08-05 08:55 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_reductions_impots/divers/intemp/interets_d_emprunts/index.yaml
> +description: Intérêts d'emprunts
Corrigé à minima

2023-08-05 13:30 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/accueil_personne_agee/plafond.yaml
> +    value: null
Rétabli

2023-08-05 13:31 UTC, benjello commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/charges_deductibles/pensions_alimentaires/plafond.yaml
> +    value: null
Rétabli

2023-08-08 12:21 UTC, eraviart approved these changes

2023-08-08 20:57 UTC, merged