Revalorisations des R0, RLS, AF, CF et Taux LEP + correction de référence ARS à partir de 01/01/2022
openfisca/openfisca-france pull request #2134
Opened 2023-06-28 13:37 UTC by frtomas

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2022.
* Zones impactées :
 -  `openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_param_r0/r0`
     - `/taux1pac.yaml`
     - `/taux2pac.yaml`
     - `/taux3pac.yaml`
     - `/taux4pac.yaml`
     - `/taux5pac.yaml`
     - `/taux6pac.yaml`
     - `/taux_couple.yaml`
     - `/taux_pac_supp.yaml`
     - `/taux_seul.yaml`
 - `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_1`
     - `/couples.yaml`
     - `/famille_1.yaml`
     - `/majoration_par_pac_supp.yaml`
     - `/personnes_seules.yaml`
- `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_2`
     - `/couples.yaml`
     - `/famille_1.yaml`
     - `/majoration_par_pac_supp.yaml`
     - `/personnes_seules.yaml`
 - `openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant/par_zone/zone_3`
     - `/couples.yaml`
     - `/famille_1.yaml`
     - `/majoration_par_pac_supp.yaml`
     - `/personnes_seules.yaml`
 - `openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/ars/ars_plaf/plafond_ressources.yaml`
 - `openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cond_ress`
      - `/majoration_plafond_par_enfant_supplementaire.yaml`
      - `/plafond_tranche_1.yaml`
      - `/plafond_tranche_1_base.yaml`
      - `/plafond_tranche_2.yaml`
      - `/plafond_tranche_2_base.yaml`
 - `openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_0_enfant.yaml`
 - `openfisca_france/parameters/taxation_capital/epargne/livret_a`
     - `/majoration_base.yaml`
     - `/taux.yaml`
* Détails :
  - Revalorisation du R0 pour 01/01/2022
  - Revalorisation du RLS pour 01/01/2022
  - Revalorisation des plafonds AF pour 01/01/2022
  - Revalorisation des plafonds CF pour 01/01/2022
  - Revalorisation du Taux LEP pour 01/02/2022
  - Correction de la référence pour le plafond de ressources de l'ARS pour 01/01/2022

- - - -

Ces changements :

- Corrigent ou améliorent un calcul déjà existant.

2023-07-03 10:56 UTC, benjello requested changes
La MR est encore en Draft et il reste des TODO

2023-08-31 09:34 UTC, bfabre01 commented
Hello, @frtomas : merci pour cette PR ! Que manque-t-il pour la merger ?
@benjello : tu mentionnes des choses restant à faire. De quoi s'agit-il ?

2023-09-28 12:55 UTC, robinguill commented
@benjello @bfabre01 @DorineLam j'ai rebase la PR de @frtomas, dites moi si cous voyez encore des choses à changer. Sinon @benjello, si tu peux valider les changes requested de la PR et la valider, nous pourront la merger.

2023-09-28 12:59 UTC, benjello approved these changes

2023-09-28 14:30 UTC, merged

2023-10-09 10:19 UTC, bfabre01 commented
Merci @robinguill !