Ajoute l'unité ratio au taux d'incapacité pris en compte pour l'AAH
openfisca/openfisca-france pull request #2149
Opened 2023-07-20 11:41 UTC by DorineLam

* Changement mineur
* Périodes concernées : toutes
* Zones impactées :
  - `/model/caracteristiques_socio_demographiques/capacite_travail.py`
* Détails :
  - Ajoute unité ratio à cette variable taux d'incapacité prise en compte dans l'AAH, permet d'éviter d'entrer une valeur telle que 80 alors que la valeur doit être entre 0 et 1.

2023-07-20 11:45 UTC, benjello requested changes

2023-07-20 11:45 UTC, benjello commented on openfisca_france/model/caracteristiques_socio_demographiques/capacite_travail.py
> +    unit == '/1'
```suggestion
    unit = '/1'
```

Mais je ne suis pas sûr que l'on peut mettre des unités pour les variables (comme on peut le faire pour les variabels).

2023-07-20 12:09 UTC, DorineLam commented
@benjello j'ai l'impression qu'on le fait ici => 
![image](https://github.com/openfisca/openfisca-france/assets/46896006/387fdb5b-4762-4c0c-a38f-e96d2942477c)

2023-07-20 12:35 UTC, benjello commented
Oui tu as raison @DorineLam j'ai trouvé aussi d'autres occurrences. Mais ce n'est pas systématique et pas utilisé par openfisca-core à ma connaissance. Mais cela ne ne pose pas de problème donc go.

2023-07-20 12:39 UTC, DorineLam commented
> Oui tu as raison @DorineLam j'ai trouvé aussi d'autres occurrences. Mais ce n'est pas systématique et pas utilisé par openfisca-core à ma connaissance. Mais cela ne ne pose pas de problème donc go.

Ok, merci :) je te redemande une review, comme ça je merge :)

2023-07-21 07:58 UTC, benjello approved these changes

2023-07-21 09:02 UTC, merged