feat(css): ajout arrete du 2023-03-31 a effet le 2023-04-01
openfisca/openfisca-france pull request #2153
Opened 2023-07-28 09:10 UTC by GerEaton

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/04/2023.
* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml`.
* Détails :
  - Changement du plafind de base de la css

- - - -

- Corrigent ou améliorent un calcul déjà existant.

- - - -

2023-07-28 15:43 UTC, benjello requested changes
2 changements cosmétiques

2023-08-01 09:40 UTC, robinguill approved these changes

2023-08-01 11:19 UTC, DorineLam approved these changes
Merci ! Même proposition que pour la PR précédente : ajouter aussi la référence législative.

2023-08-01 11:19 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml
> +      - title: Décret n° 2023-236 31/03/2023
```suggestion
      - title: Article L861-1, 1° du Code de la Sécurité sociale
         href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037950247
      - title: Décret n° 2023-236 31/03/2023
```

2023-08-02 07:21 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml
> +      - title: Décret n° 2023-236 31/03/2023
La référence législative est-elle utile à cet endroit alors qu'elle est déjà référencée dans le champ documentation ?

2023-08-02 11:37 UTC, DorineLam commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/cmu/plafond_base.yaml
> +      - title: Décret n° 2023-236 31/03/2023
Bonjour, Oui, car elle est exploitable avec un title et un href structuré.

2023-09-18 07:14 UTC, merged