Fix is
openfisca/openfisca-france pull request #2169
Opened 2023-08-10 09:55 UTC by benjello

* Correction de paramètres.
* Périodes concernées : toutes.
* Zones impactées : `parameters/taxation_societe`.
* Détails :
  - Correction de la valeur du taux réduit qui a été prolongée au delà de la période initialement prévue.
  - Pas d'impact sur les variabele car non affectées par ces paramètres.
  - Voir aussi [Barèmes IPP](https://gitlab.com/ipp/partage-public-ipp/baremes-ipp/baremes-ipp-yaml/-/merge_requests/424).

2023-08-10 12:27 UTC, MattiSG requested changes
[L'article 219 du CGI](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000046868562#:~:text=Le%20montant%20net%20des%20plus,séparée%20au%20taux%20de%2010%20%25.) donné en référence est très long et mentionne de nombreux taux différents. En l'état, je ne peux pas confirmer par la référence législative le changement indiqué ici.

Si ce que l'on décrit dans le paramètre `taux_reduit` est « Le montant net des plus-values à long terme fait l'objet d'une imposition séparée au taux de 15 %. » (et non « Le résultat net bénéficiaire déterminé en application de l'article 238 est soustrait du résultat soumis au taux normal et fait l'objet d'une imposition séparée au taux de 10 % », par exemple), alors il me semble nécessaire d'indiquer dans la description « Taux réduit sur le montant net des plus-values à long terme » et non simplement « Taux réduit », qui est ambigu.

2023-08-10 12:27 UTC, MattiSG commented on CHANGELOG.md
> +* Périodes concernées : toutes.
```suggestion
* Périodes concernées : à partir de 2020.
```

2023-08-10 12:27 UTC, MattiSG commented on CHANGELOG.md
> +  - Pas d'impact sur les variabele car non affectées par ces paramètres.
```suggestion
  - Pas d'impact sur les variables car non affectées par ces paramètres.
```

2023-08-10 12:47 UTC, benjello commented
> [L'article 219 du CGI](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000046868562#:~:text=Le%20montant%20net%20des%20plus,s%C3%A9par%C3%A9e%20au%20taux%20de%2010%20%25.) donné en référence est très long et mentionne de nombreux taux différents. En l'état, je ne peux pas confirmer par la référence législative le changement indiqué ici.
> 
> Si ce que l'on décrit dans le paramètre `taux_reduit` est « Le montant net des plus-values à long terme fait l'objet d'une imposition séparée au taux de 15 %. » (et non « Le résultat net bénéficiaire déterminé en application de l'article 238 est soustrait du résultat soumis au taux normal et fait l'objet d'une imposition séparée au taux de 10 % », par exemple), alors il me semble nécessaire d'indiquer dans la description « Taux réduit sur le montant net des plus-values à long terme » et non simplement « Taux réduit », qui est ambigu.

Je pense que c'est cette partie qui justifie le taux de 15 %

```
b. Par exception au deuxième alinéa du présent I et au premier alinéa du a, pour les redevables ayant réalisé un chiffre d'affaires n'excédant pas 10 millions d'euros au cours de l'exercice ou de la période d'imposition, ramené s'il y a lieu à douze mois, le taux de l'impôt applicable au bénéfice imposable est fixé, dans la limite de 42 500 € de bénéfice imposable par période de douze mois, à 25 % pour les exercices ouverts en 2001 et à 15 % pour les exercices ouverts à compter du 1er janvier 2002.
```

2023-08-15 10:42 UTC, MattiSG commented
Merci @benjello pour cette précision. Peut-on la refléter dans le titre, la description et la référence de ce paramètre ? :)

2023-08-16 10:07 UTC, MattiSG requested changes

2023-08-16 10:07 UTC, MattiSG commented on CHANGELOG.md
> +  - Pas d'impact sur les variables actuelles, car elles ne sont  affectées par ces paramètres.
```suggestion
  - Pas d'impact sur les variables actuelles, car elles ne sont pas affectées par ces paramètres.
```

2023-08-16 10:07 UTC, MattiSG commented on CHANGELOG.md
> +* Périodes concernées : toutes.
Il semblerait que https://github.com/openfisca/openfisca-france/pull/2169/commits/ceb9e5cc1eae6aba80a347fe61167207b8f98e32 ait annulé https://github.com/openfisca/openfisca-france/pull/2169/commits/358f89daf16fc3663cc58907a3d2da709b962a93

2023-08-16 11:23 UTC, benjello commented on CHANGELOG.md
> +* Périodes concernées : toutes.
J'ai rebasé et utilisé `git push --force-wuth-lease`

2023-08-17 08:56 UTC, benjello commented
@MattiSG : est-ce que je peux te laisser corriger et merger stp ? J'ai fait cette PR qui concerne des paramètres largement orthogonaux à ce que fait openfisca-france aujourd'hui pour répondre à une personne qui nous a sollicité sur contact@openfisca.fr en sollicitant une source côté IPP, pour apporter une correction. Je ne peux pas y consacrer beauoup plus de temps.

2023-08-17 08:57 UTC, MattiSG commented
Ok !

2023-08-17 09:05 UTC, MattiSG approved these changes
J'ai :
- corrigé les erreurs apportées dans le changelog au rebase
- clarifié la description pour qu'elle ne soit plus ambigüe
- précisé les références légales

2023-08-17 09:50 UTC, merged