Ajoute la variable crous_repas_tarif_non_boursiers_eligibilite
openfisca/openfisca-france pull request #2181
Opened 2023-09-01 13:30 UTC by Allan-CodeWorks

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 07/2021.
* Zones impactées : `openfisca_france/model/prestations/alimentation.py`.
* Détails :
  - Ajoute le dispositif permettant aux étudiant du supérieur de béneficier de repas à 3,30 euros dans les restaurant du crous.

- - - -

Ces changements:

- Ajoutent une fonctionnalité (par exemple ajout d'une variable).

2023-09-01 14:01 UTC, baptou12 reviewed
Je suis ok avec ces changements, cependant il manque pas la partie prix à 3.3 euros ? Enfin sinon comment vois-tu la suite ?

2023-09-01 15:14 UTC, Allan-CodeWorks commented
> Je suis ok avec ces changements, cependant il manque pas la partie prix à 3.3 euros ? Enfin sinon comment vois-tu la suite ?

C'est une bonne remarque, il me semble pertinent de reprendre la logique utilisée pour le repas à **1 euro**, c'est à dire, est-ce qu'on est éligible ou pas.
Le problème c'est que je ne vois pas bien comment intégrer le prix actuel du repas (3,30 euros) dans ce context.
Je me suis dit que, le mettre dans le nom de la variable comme pour le repas à un euro serait problématique si demain le prix change.

Pour la suite, on en reste là côté openfisca, on réplique le fonctionnement de la variable du repas à un euro.

2023-09-04 08:46 UTC, Allan-CodeWorks commented
> D'un point de vu strictement* "aides jeunes" avoir un cout du repas qui est 1, 3.3, ou bien 0 si pas éligible ça marcherait. Mais du point de vu Openfisca c'est bizarre en effet. Si on a deux notion sur eligibilité puis sur prix (qui ne veut rien dire si pas eligible) ça peut déjà se rapprocher d'une solution.
> 
> On a pas des cas similaire finalement ? Pour une aides permis si on est pas dans la region par exemple, l'aide renvoi 0 ? c'est un peu le même cas non ? (je me trompe p.e.)
> 
> *Même sur local je pense pas qu'il faille qu'on adopte un point de vu strictement aides-jeunes pour info, encore moins ici

Tout à fait d'accord sur ton premier point, avec la nuance que ça "tomberait en marche" selon moi. Ça ne serait pas vraiment cohérent avec ce que l'on fait pour le moment, CF mon deuxième point.

Pour moi, c'est une situation un peu spéciale. Nos aides se divisent à priori en trois catégories (mais j'en oublie surement) : 
- Les prestations de service (On donne accès a une carte qui donne tel ou tel avantage)
- les subventions (aides permis ou on finance tout ou parti de la formation)
- les réductions (exemple transport solidaire ou on réduit le prix du service avec un pourcentage) 

Ce qui rend le dispositif des repas du crous particulier de mon point de vue c'est qu'on a du mal à savoir dans quelle catégorie la mettre.
Les aides au permis sont des subventions, les collectivités donnent de l'argent a une personne pour que celle-ci se forme à la conduite. D'un point de vue modélisation c'est assez simple, soit on est éligible et on reçoit un montant, soit on ne l'est pas et le montant est 0, dans le cas du simulateur, il est incohérent d'afficher une aide à "0 euro". 
Pour moi, nous ne sommes pas dans ce cas-là avec le repas crous à 1 ou 3,30 euros.

On peut avoir l'impression que c'est une réduction mais ce n'en est pas vraiment une car le prix à payer n'est pas en fonction d'un prix de base. si on reprend l'exemple des tarifications solidaire, on offre une réduction en pourcentage sur un service particulier. Ici, le prix des resto'U pour les externes n'est pas légiféré. Nous ne pouvons techniquement pas calculer cette réduction, et ce ne serait pas métier.

Pour moi, il s'agit d'une prestation de service. Soit on a le droit au prix de 3,30 euros, soit on y a pas droit.

J'aurai peut-être dû te poser des questions pour préciser ta pensée avant d'écrire tout ça... :D 
Dans ton message, j'ai l'impression que tes deux paragraphes disent deux choses opposées.

Pour résumer, je ne vois pas comment modéliser ça autrement sans modifier profondément le simulateur et/ou openfisca et plus je réfléchis, plus je me dis que voir la chose comme étant une prestation à laquelle on a le droit ou non est la bonne manière.

2023-09-08 08:34 UTC, Allan-CodeWorks commented on openfisca_france/parameters/prestations_sociales/education/alimentation/montant_repas_non_boursier.yaml
J'aurai aimé retracer l'évolution du montant mais je ne trouve aucune source correctes.

2023-09-14 13:30 UTC, baptou12 commented on openfisca_france/model/prestations/alimentation.py
> +        montant_repas = eligibilite_repas_un_euro + (etudiant_non_boursier * tarif_repas_non_boursier)
Un truc qui m'embête dans cette formule c'est que le fait que pour les étudiant boursier le fait que l'output soit "1 euros" utilise le raccourci `True + 0 == 1` 

Dans l'idéal on devrait avoir un paramètre `parameters(period).prestations_sociales.education.alimentation. montant_repas_boursier` à 1 euro non ?

2023-09-14 13:31 UTC, baptou12 requested changes
cf formule `crous_repas_montant`

2023-09-15 08:25 UTC, baptou12 commented on openfisca_france/model/prestations/alimentation.py
> +        montant_repas = eligibilite_repas_un_euro + (etudiant_non_boursier * tarif_repas_non_boursier)
Dis moi si c'est une norme openfisca

2023-09-15 09:07 UTC, Allan-CodeWorks commented on openfisca_france/model/prestations/alimentation.py
> +        montant_repas = eligibilite_repas_un_euro + (etudiant_non_boursier * tarif_repas_non_boursier)
Je vois le problème.

L'idée des paramètres et de pouvoir suivre l'évolution des montants et des références législatives.
Dans ce cas précis, je trouve qu'on peut s'en passer dans le but de simplifier la lecture et le code.

Cette variable `crous_repas_un_euro_eligibilite` contient la valeur en question dans son nom. Le jour où le montant change, il faudra supprimer la variable. Faire un paramètre pour cette valeur me semble inutilement lourd.

Par contre, je suis tout à fait d'accord que `True + 0 == 1` est problématique
Je vois trois solutions : 
- Ta suggestion avec un paramètre -> je trouve ça lourd
- `True * 1 + 0 == 1` -> Efficace mais pas explicite
-
```
montant_repas_boursier = 1
True * montant_repas_boursier + 0 == 1
```
-> compromis entre les deux ?

2023-09-15 09:10 UTC, baptou12 commented on openfisca_france/model/prestations/alimentation.py
> +        montant_repas = eligibilite_repas_un_euro + (etudiant_non_boursier * tarif_repas_non_boursier)
Perso je préfère ça : `True * 1 + 0 == 1` que le compromis 😅

2023-09-15 12:20 UTC, baptou12 approved these changes
LGTM

2023-09-15 12:53 UTC, merged

2023-09-15 13:10 UTC, benjello commented on openfisca_france/model/prestations/alimentation.py
> +        montant_repas = eligibilite_repas_un_euro * 1 + (etudiant_non_boursier * tarif_repas_non_boursier)
@Allan-CodeWorks @baptou12 : désolé si jarrive un peu après la bataille mais il y a les fonctions `where` et `select` qui peuvent être très utile pour rendre plus explicite le code.