Synchro presta 1
openfisca/openfisca-france pull request #2184
Opened 2023-09-20 16:42 UTC by benjello

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2023-11-10 10:47 UTC, clallemand requested changes
Je remets ici les deux gros points : 
- Plusieurs ajouts de valeurs nulles à des dates antérieures à la 1e date renseignée dans le paramètre. Cela n'a a priori pas de sens

- Plusieurs valeurs de paramètres rajoutées alors qu'elle sont identiques à la valeur précédente dans la série


J'ai mis un commentaire sur le moment dans la plupart des cas mais il se peut que j'en ai sauté un ou deux !
Sinon ça me semble pas mal, quelques autres commentaires de forme. 
Le n'ai pas cliqué sur les liens

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +            (nombre_enfants == 1) * paje.plaf_cmg.premier_plafond_ne_adopte_apres_04_2014.enfant
Pourquoi ce paramètre (idem pour les suivant) n'est mis qu'à partir de 2017 alors qu'il existe depuis le 1e janvier 2015 ?

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aes/complement_allocation/4e_categorie.yaml
> +  1976-08-01:
Est on obligé de mettre cette valeur nulle ? Je comprends que c'est dans le processus d'homogénéisation mais si on peut éviter, même temporairement, cela me semble grandement préférable. Ce commentaire est donc vrai pour toute les situations similaires qui suivent

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aes/complement_allocation/4e_categorie.yaml
> +    1976-08-01:
Mon commentaire précédent est d'autant plus justifier que cela rajoute des références qui a priori ne concernent pas ce paramètre

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/beneficiaires_enfant_ne_adopte_apres_04_2014/taux_partiel_50.yaml
> +    value: 0.6246
Doublon de valeur avec 2004, pourquoi le répéter ?

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/beneficiaires_enfant_ne_adopte_apres_04_2014/taux_partiel_50_80.yaml
> +    value: 0.3603
Idem doublon avec valeur précédente

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/beneficiaires_enfant_ne_adopte_apres_04_2014/taux_partiel_50.yaml
> +    value: 0.6246
Vu le titre du paramètre je dirais que c'est la valeur 2004 qui n'est pas valide ?

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/colca/taux_plein_duree_arret_predeterminee.yaml
> +    value: 1.5793
Idem date 2004 non pertinente ?

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/non_beneficiaires_enfant_ne_adopte_avant_04_2014/taux_partiel_50.yaml
> +    value: 0.6246
doublon avec valeur précédente

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/non_beneficiaires_enfant_ne_adopte_avant_04_2014/taux_plein.yaml
> +    value: 0.9662
idem doublon

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/majorations_enfants/premier_2eme_enfant.yaml
> +    value: 0.25
doublon avec valeur précédente

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_prepare/periode_ref_8_trimestres_cotis_vieillesse/deux_enfants.yaml
> +    value: 4
doublon avec la valeur précédente

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_prepare/periode_ref_8_trimestres_cotis_vieillesse/un_enfant.yaml
> +    value: 2
idem doublon

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/premier_plafond_ne_adopte_apres_04_2014/deux_enfants.yaml
> +    value: null
valeur nulle à éviter

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/premier_plafond_ne_adopte_apres_04_2014/enfant.yaml
> +    value: null
idem valeur nulle à éviter

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/plaf_cmg/premier_plafond_ne_adopte_apres_04_2014/majoration_enfant_supp.yaml
> +    value: null
idem

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_2.yaml
> +    value: null
idem

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_cm/modulation/taux_tranche_1.yaml
> +    value: null
idem

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/af/af_maj/maj_age_deux_enfants/taux2.yaml
> +description: Taux de la 2ème majoration pour âge (14 ans pour les enfants nés > 30/04/97)
c'est mieux de garder les mots non ?

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm_dom/index.yaml
> +description: "Complément familial (CF) : majorations dans les DOM"
guillemets en trop ?

2023-11-10 10:47 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_cf_majore.yaml
> +  short_label: Pour avoir le droit au complément familial majoré
```suggestion
  short_label: Plafond de ressources
```

2023-11-10 14:12 UTC, benjello commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +            if period.start >= Instant((2018, 1, 1)):
C'est pour retourner une valeur pour le plafond qui de toute façon ne sera pas utilisé et qu'il évite de passer par les paramètres qui vont bugger car n'existant plus au delà de la date.

2023-11-10 14:12 UTC, benjello commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +            if period.start < Instant((2014, 4, 1)) or period.start >= Instant((2021, 4, 1)):
Idem

2023-11-10 14:13 UTC, benjello commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +            if period.start < Instant((2014, 4, 1)) or period.start >= Instant((2021, 4, 1)):
idem

2023-11-10 14:18 UTC, benjello commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +            (nombre_enfants == 1) * paje.plaf_cmg.premier_plafond_ne_adopte_apres_04_2014.enfant
Parce qu'il  y a un chevauchement entre date de naissance (cela s'applique dès janvier 2015 pour les enfants nés cette année là) et date de la prestation (on considère que 3 ans après tout le monde est passé aux nouveaux paramètres.

2023-11-10 14:25 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_cm_dom/index.yaml
> +description: "Complément familial (CF) : majorations dans les DOM"
Les deux points fon bugger je crois.

2023-11-10 14:42 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_cf_majore.yaml
> +  short_label: Pour avoir le droit au complément familial majoré
Je propose une autre modif

2023-11-14 10:51 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aes/complement_allocation/4e_categorie.yaml
> +  1976-08-01:
Je préfère gérer cela indépendamment dans une seconde passe où on les repèrera tous.

2023-11-14 10:53 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/beneficiaires_enfant_ne_adopte_apres_04_2014/taux_partiel_50.yaml
> +    value: 0.6246
Bon si je les vire cela casse la `paje_clca` qu'il faudrait recoder. Je te propose d'ouvrir un ticket et que l'on traite cela séparément. Je peux aussi juste retirer le doublon.
Et si t'as un quick fix sur la `paje_clca` je prends aussi.

2023-11-14 14:03 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aes/complement_allocation/4e_categorie.yaml
> +  1976-08-01:
Cela te va @clallemand ?

2023-11-14 17:29 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/education_presence_parentale/aes/complement_allocation/4e_categorie.yaml
> +  1976-08-01:
disons que oui

2023-11-14 17:33 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_clca/beneficiaires_enfant_ne_adopte_apres_04_2014/taux_partiel_50.yaml
> +    value: 0.6246
ok ok

2023-11-14 17:34 UTC, clallemand approved these changes

2023-11-15 10:56 UTC, benjello commented on openfisca_france/model/prestations/prestations_familiales/paje.py
> +            if period.start >= Instant((2018, 1, 1)):
Yep. Et la valeur était à zéro dans les paramètres.

2023-11-15 14:38 UTC, merged