Revalorisations annuelles aides au logement 2023
openfisca/openfisca-france pull request #2208
Opened 2023-11-22 09:50 UTC by JoDuGa

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/10/2023.
* Zones impactées :
  - openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_charge
  - openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_loc2
  - openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_plaf_logement_foyer
  - openfisca_france/parameters/prestations_sociales/aides_logement/reduction_loyer_solidarite/montant
* Détails :
  - Mise à jour des paramètres pour le calcul de l'aide au logement et de la réduction de loyer de solidarité.

- - - -

Ces changements :

- Corrigent ou améliorent un calcul déjà existant.

2023-11-22 15:17 UTC, benjello requested changes
Revoir le format et préciser le titre de la référence.
Merci !

2023-11-22 15:17 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_charge/majoration_par_enfant.yaml
> +      title: Arrêté du 22 septembre 2023 relatif au calcul des aides personnelles au logement et de l'aide à l'accession sociale et à la sortie de l'insalubrité spécifique à l'outre-mer
Changer la date en DD/MM/YY et préciser si possible article et alinéa comme référence précdédente.
Idem pour les autres mises à jour.
Par avance, merci pour ce travail de mise à jour !

2023-11-23 09:30 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_charge/majoration_par_enfant.yaml
> +      title: Arrêté du 22 septembre 2023 relatif au calcul des aides personnelles au logement et de l'aide à l'accession sociale et à la sortie de l'insalubrité spécifique à l'outre-mer
Le format de la date a été changé et le titre ne contient maintenant plus que la date de l'arrêté et le numéro de l'article. Et ce sur tous les fichiers de la PR.

2023-12-18 16:45 UTC, JoDuGa commented
Ajout des revalorisations des aides au logement et la réduction de loyer de solidarité pour janvier 2024.

Parce que nous n'avons pas encore les références législatives pour ces revalorisations, nous passons la PR en Draft.

2024-01-08 16:15 UTC, JoDuGa commented
Les références législatives ont été ajoutées, nous enlevons le draft.

2024-01-08 16:52 UTC, sylvainipp reviewed
Merci beaucoup pour cette mise à jour ! Tout me semble bon. Je suis juste un peu étonné des dates de journaux officiels, qui sont présentes sur les premiers paramètres mais pas sur les plafonds_ressources et ressources.

2024-01-08 16:53 UTC, sylvainipp approved these changes
(Et je voulais approuver, mais j'ai mal cliqué)

2024-01-16 13:18 UTC, clallemand commented
Bonjour, merci beaucoup pour cette contibution ! Nous serions très intéressés pour qu'elle soit intégrée rapidement. Est ce que cela vous semble envisageable ? Je suis disponible si vous avez besoin d'aide !

2024-01-25 10:38 UTC, robinguill commented
@clallemand la PR est prête, en attente de @benjello pour le resolve sur les requested changes.

2024-01-25 11:32 UTC, benjello approved these changes

2024-01-25 11:33 UTC, benjello commented
Désolé @clallemand et @robinguill pour le délai dans la réponse

2024-01-25 13:42 UTC, merged