Suppression CGA 2023
openfisca/openfisca-france pull request #2230
Opened 2024-01-03 10:19 UTC by sylvainipp

* Évolution du système socio-fiscal. 
* Périodes concernées :  à partir du 01/01/2023.
* Zones impactées : `model/prelevements_obligatoires/impot_revenu/ir`.
* Détails :
  - La pénalité pour absence de CGA pour les revenus non-salariaux prend fin en 2023. Le taux associé prend donc fin, et de nombreuses formules sont reformulées dans une version 2023 un peu allégée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2024-01-03 12:50 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +            min_(f5rn + f5ro + f5rp + f5rq + f5rr + f5rw, aacc_impn + macc_pvct + macc_timp )
```suggestion
            min_(f5rn + f5ro + f5rp + f5rq + f5rr + f5rw, aacc_impn + macc_pvct + macc_timp)
```

2024-01-03 12:50 UTC, benjello requested changes
Des suggestions de forme.
Un petit test serait peut-être utile.

2024-01-03 15:35 UTC, sylvainipp commented
Merci de ta review ! Je pense approfondir encore les conséquences de cette suppression en vérifiant les impacts sur les cases fiscales notamment, il m'a semblé en voir certaines qui n'étaient plus d'actualité. Comme il s'agit d'un sujet qui n'est je pense pas central pour la communauté openfisca à court terme (j'avais modifié les taux de 2021 cet été), je me permet de reporter le merge de l'information dont je suis sûr : la fin de la pénalité pour absence de CGA, pour bien vérifier ce dont je ne suis pas sûr (soit tout le reste). Je te redemanderai peut-être une revue dans quelques semaines, quand j'aurais regardé plus précisément (et en espérant que la DGFIP sorte la brochure 2023 et leur simulateur rapidement).

2024-01-05 14:54 UTC, sylvainipp commented on openfisca_france/model/prelevements_obligatoires/isf.py
> +class rag(Variable):
J'ai fait passer dans l'isf quatre catégories de revenus qui ne sont utilisées que là (ou pas du tout).

2024-02-05 08:23 UTC, sylvainipp commented
Le [calculateur d'impôts](https://simulateur-ir-ifi.impots.gouv.fr/calcul_impot/2024/) sur revenus 2023 est sorti, même si je n'ai pas encore vu la brochure, confirmant bien la disparition des cases sans CGA.

2024-02-06 14:48 UTC, clallemand requested changes
Quelques questionnements sur les dates de fin des variables, merci pour cette contribution !

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    def formula_2023_01_01(foyer_fiscal, period, parameters):
Si je comprends bien la variable nbnc_pvce a une date de fin en 2015 d'où ma suggestion de changement de date de formule

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    def formula_2008_01_01(individu, period, parameters):
Je ne comprends pourquoi spécifier cette année 2008 ? Car d'autres variables de cette liste on de dates de débuts ultérieurs. Il me semble qu'il faut soit spécifier année par année les changements soit n'en garder qu'une générique pour toutes les années ?

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    def formula_2023_01_01(individu, period, parameters):
Tu supprimes plusieurs variables pour 2023 mais si je comprends il s'agit de variables qui sont éteintes depuis plusieurs années - par exemple `frag_exon` s'arrête en 2016. 
Ce qui me surprend d'ailleurs c'est qu'il n'y ait pas d'erreur du fait qu'on laisse ces variables pour des années ultérieur à leur "end". Cela est sans doute dû au fait qu'il s'agisse d'input_variable sans formule. 
L'idéal serait donc de faire une formule par année où il y a des suppressions pour que ce soit bien clair pour l'oeil humain. A minima je pense que cela peut être bien de documenter en commentaire la vraie date de fin de ces variables

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    def formula_2023_01_01(foyer_fiscal, period, parameters):
Supprimer `frag_impo` dès la formule de 2016 ?

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    def formula_2023_01_01(foyer_fiscal, period, parameters):
Ajouter une end_date dans la variable `nrag_impg` ?

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        # frag_fore est remplacé par coupe_bois, frag_pvct par mrag_pvct
```suggestion
```

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        # frag_fore est remplacé par coupe_bois, frag_pvct par mrag_pvct
ce commentaire ne concerne pas cette année là a priori

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        # frag_fore est remplacé par coupe_bois, frag_pvct par mrag_pvct
j'ai un doute pour la suppression de la variable `mrag_pvct` en 2023, as tu une source ?

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
>      definition_period = YEAR
Ajout d'une end date ?

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    label = 'Revenus des professions non salariées individuels sans abattement CGA (régime contrôlé)'
Ajout d'une end date ?

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    def formula_2023_01_01(individu, period, parameters):
Ajout d'une end date pour la variable `ntimp` ?

2024-02-06 14:48 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +    def formula_2023_01_01(foyer_fiscal, period, parameters):
Mettre le changement de formule à 2018 ?

2024-02-06 15:01 UTC, sylvainipp commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        # frag_fore est remplacé par coupe_bois, frag_pvct par mrag_pvct
Tu as raison, 5HW semble encore exister dans le calculateur dgfip, mais par conséquent il était probablement mal calculé auparavant (il n'y a aucune raison pour qu'on applique la pénalité pour absence de CGA à une plus-value)

2024-02-09 14:19 UTC, clallemand approved these changes
Merci pour les changements !

2024-02-09 16:41 UTC, sylvainipp commented
@benjello, juste pour te signaler que je n'ai pas mis de test car il n'y a que des suppressions de cases, je ne vois pas trop quoi mettre de nouveau.

2024-02-09 16:58 UTC, benjello commented
Peut-être prolonger un test existant aujourd'hui. Mais je te laisse juge.

2024-02-09 17:01 UTC, sylvainipp commented
Je peux merger selon toi sinon ?

2024-02-09 17:02 UTC, benjello approved these changes

2024-02-12 09:52 UTC, merged