Met à jour les montants d'aspa pour 2024
openfisca/openfisca-france pull request #2234
Opened 2024-01-05 16:52 UTC by clallemand

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/01/2024.
* Zones impactées : `openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa`.
* Détails :
  - Met à jour les montant de l'aspa à partir du 01/01/2024

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Corrigent ou améliorent un calcul déjà existant.

2024-01-05 20:43 UTC, benjello requested changes
Quelques suggestions de forme

2024-01-05 20:43 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/personnes_seules.yaml
> +      title: Circulaire Cnav 2023-34 du 29/12/2023 p10.
```suggestion
      title: Circulaire Cnav 2023-34 du 29/12/2023 (page 10).
```

2024-01-05 20:43 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/montant_maximum_annuel/couples.yaml
> +      title: Circulaire Cnav 2023-34 du 29/12/2023 p10.
```suggestion
      title: Circulaire Cnav 2023-34 du 29/12/2023 (page 10).
```

2024-01-05 20:43 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/couples.yaml
> +      title: Circulaire Cnav 2023-34 du 29/12/2023 p10.
```suggestion
      title: Circulaire Cnav 2023-34 du 29/12/2023 (page 10).
```

2024-01-05 20:43 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/solidarite_insertion/minimum_vieillesse/aspa/plafond_ressources/personnes_seules.yaml
> +      title: Circulaire Cnav 2023-34 du 29/12/2023 p10.
```suggestion
      title: Circulaire Cnav 2023-34 du 29/12/2023 (page 10).
```

2024-01-08 08:57 UTC, clallemand commented
> Quelques suggestions de forme

merci, @benjello je les ai prises en compte, ok pour toi ?

2024-01-08 09:04 UTC, benjello approved these changes

2024-01-08 11:57 UTC, merged