Revalorisation janvier 2024 PAJE et CF
openfisca/openfisca-france pull request #2243
Opened 2024-01-24 16:11 UTC by robinguill

* Évolution du système socio-fiscal.
* Périodes concernées :à partir du 01/01/2024.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Revalorisation des plafinds de la Prestation d'Accueil du Jeune Enfant (PAJE)
  - Revalorisation des plafonds du Complément Familial (CF)

- - - -

Ces changements :
- Corrigent ou améliorent un calcul déjà existant.

2024-01-26 15:15 UTC, frtomas approved these changes

2024-01-26 16:36 UTC, benjello requested changes
Merci de respecter l'indentation.
Les `-` sont alignés avec l'entrée de niveau supérieur.

2024-01-31 14:32 UTC, JoDuGa requested changes

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/biactifs_parents_isoles.yaml
> +      - title: Instruction no DSS/2B/2021/247 du 14/12/2021
De la ligne 46 à la 49, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/biactifs_parents_isoles.yaml
> +      - title: Le Décret 2018-331 spécifie que les plafonds sont majorés dans les conditions définies aux deuxième et troisième alinéas de l'article R. 522-2. C'est dans ces alinéas que figurent les
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
> +      - title: Décret 2018-312 du 26 avril 2018, art. 2
De la ligne 30 à la 35, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
> +      - title: Instruction no DSS/2B/2021/247 du 14/12/2021
De la ligne 46 à la 49, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
> +      - title: "Création de la PAJE. Mais entrée en vigueur progressive : de janvier 2004 à décembre 2006 inclus (cf. art. 60, VIII de la loi 2003-1199)"
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_partiel/plafond_ressources_0_enfant.yaml
> +      - title: Le Décret 2018-331 spécifie que les plafonds sont majorés dans les conditions définies aux deuxième et troisième alinéas de l'article R. 522-2. C'est dans ces alinéas que figurent les
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/biactifs_parents_isoles.yaml
> +      - title: Décret 2018-312 du 26 avril 2018, art. 2
De la ligne 30 à la 35, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/biactifs_parents_isoles.yaml
> +      - title: Instruction no DSS/2B/2021/247 du 14/12/2021
De la ligne 46 à la 49, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/biactifs_parents_isoles.yaml
> +      - title: "Création de la PAJE. Mais entrée en vigueur progressive : de janvier 2004 à décembre 2006 inclus (cf. art. 60, VIII de la loi 2003-1199)"
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/petite_enfance/paje/paje_plaf/ne_adopte_apres_04_2018/taux_plein/biactifs_parents_isoles.yaml
> +      - title: Le Décret 2018-331 spécifie que les plafonds sont majorés dans les conditions définies aux deuxième et troisième alinéas de l'article R. 522-2. C'est dans ces alinéas que figurent les
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Circulaire DSS/SD2B/2013/416
De la ligne 74 à la 76, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Circulaire DSS/SD2B/2017/352 du 22/12/2017
De la ligne 82 à la 84, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Circulaire DSS/SD2B/2018/279 du 17/12/2018
De la ligne 86 à la 88, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Arrêté du 14/12/2020, art. 3
De la ligne 93 à la 96, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Article R522-2 du Code de la sécurité sociale
De la ligne 98 à la 103, revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: "art. R222-2 : la réglementation des plafonds est la même que pour l'APJE"
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Suppression de l'APJE => le renvoi à la réglementation des plafonds de l'APJE n'est plus possible.; => règlementation propre au CF
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Ne pas confondre la circulaire pour la France métropolitaine avec celle pour les départements d'Outre-mer
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Pas de modification en 2017 cf. circulaire DSS/SD2B/2016/396 du 21/12/2016
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Arrêté du 21/12/2018, Revalorisation des plafonds de 0,2%
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/majoration/biactifs_isoles.yaml
> +      - title: Revalorisation des plafonds de 0,2%
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/biactifs_isoles.yaml
> +    value: 4380
Pourquoi a-t-on changé la valeur pour cette date ?

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/biactifs_isoles.yaml
> +      title: Arrêté du 21 décembre 2022 relatif aux plafonds de ressources de certaines prestations familiales
Mettre la date de l'arrêté au format "dd/MM/yyyy".

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
> +    - title: Arrêté du 21 décembre 2022 relatif aux plafonds de ressources de certaines prestations familiales
Mettre la date de l'arrêté au format "dd/MM/yyyy".

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
> +      - title: "art. R222-2 : la réglementation des plafonds est la même que pour l'APJE"
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
> +      - title: Ne pas confondre la circulaire pour la France métropolitaine avec celle pour les départements d'Outre-mer
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
> +      - title: Pas de modification en 2017 cf. circulaire DSS/SD2B/2016/396 du 21/12/2016
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
> +      - title: Arrêté du 21/12/2018, Revalorisation des plafonds de 0,2%
Revenir à l'indentation d'avant.

2024-01-31 14:32 UTC, JoDuGa commented on openfisca_france/parameters/prestations_sociales/prestations_familiales/prestations_generales/cf/cf_plaf/plafond_ressources_majoration/couple_avec_1_revenu.yaml
> +      - title: Revalorisation des plafonds de 0,2%
Revenir à l'indentation d'avant.

2024-02-06 09:23 UTC, merged