Actualisations diverses sur l'IR
openfisca/openfisca-france pull request #2286
Opened 2024-04-25 13:11 UTC by bfabre01

* Évolution du système socio-fiscal et corrections.
* Périodes concernées : toutes.
* Détails :
  - Actualise des paramètres monétaires existants (n'ai regardé ni les paramètres non monétaires, ni s'il y avait de nouveaux paramètres créés). Critère d'investigation d'un fichier :
     - (1) le paramètre est existant (ne regarde pas si nouveaux paramètres)
     - (2) il est monétaire
     - (3) sa dernière valeur n'est pas `null`
     - (4) sa dernière valeur est à une date antérieure à `2023-01-01`.
  - Champ des fichiers checkés : `parameters/impot_revenu/calcul_impot_revenu` (tout était bon), `parameters/impot_revenu/calcul_revenus_imposables` (cette partie n'était pas actualisée) ; taxes sur le salaire et les boissons et limite de réduction d'impôt pour don. qui étaient mis à jour dans le décret correspondant aux paramètres précédents.
  - Redéfinit et réagence certains paramètres et corrige certaines erreurs des dates passées (sans pour autant faire une vérification systématique de l'historique), au sein de ceux remplissant les critères susmentionnés.

2024-05-21 13:19 UTC, clallemand requested changes

2024-05-21 13:19 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/montant_1.yaml
> +    - title: Référence non encore publiée au 24/04/2024 (valeur prise dans la brochure pratique de l'IR, et issue de la règle de revalorisation inscrite dans l'art. 157 bis du CGI)
Merci Brice pour ces mises à jour. 
Je mets ici un commentaire valable pour toutes les mises à jour que tu as faite avec la brochure pratique. Ce format de référence me semble trop loin des standards openfisca france même si je comprends pourquoi tu as fait cela.- Je te propose deux alternatives :
- Le plus propre serait d'attendre les décrets pour faire cette mise à jour afin d'avoir les textes de lois faisant foi. Ils devraient arriver d'ici un mois.
- Si attendre un mois avant de merger est bloquant de ton côté ou pour tout autre raison pour laquelle tu voudrais merger : je te proposer de renseigner la brochure pratique comme référence en bon et dû forme, notamment en mettant son lien dans `href`. En parallèle de ça on pourrait faire une issue qui liste toutes les valeurs pour lesquelles il faudra changer la référence le moment venu, comme ça c'est plus facile de s'en rappeler.

Je suis disponible si tu as besoin de plus discuter de cela

2024-05-27 15:13 UTC, bfabre01 commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/montant_1.yaml
> +    - title: Référence non encore publiée au 24/04/2024 (valeur prise dans la brochure pratique de l'IR, et issue de la règle de revalorisation inscrite dans l'art. 157 bis du CGI)
Bonjour Chloé, merci pour ton retour. Cela n'urge pas. J'attends donc les décrets.

2024-05-27 15:17 UTC, bfabre01 commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/abat_rni/personne_agee_ou_invalide/montant_1.yaml
> +    - title: Référence non encore publiée au 24/04/2024 (valeur prise dans la brochure pratique de l'IR, et issue de la règle de revalorisation inscrite dans l'art. 157 bis du CGI)
Sur le recensement des paramètres concernés, je ne pense pas que ça soit la peine d'en faire une liste. Ça se voit très bien dès qu'on fait l'actualisation, étant donné qu'il y a dans les références l'article de loi, dont la temporalité d'actualisation sur legifrance est très claire.

2024-06-10 15:39 UTC, sylvainipp approved these changes
Tout me semble bon avec ces références !

2024-06-10 18:31 UTC, bfabre01 commented
@clallemand : les décrets sont parus et on a donc toutes les références (en ayant ajouté d'autres actualisations qui étaient contenus dans lesdits décrets ; merci @sylvainipp !). Peux-tu stp, si tout est ok pour toi, valider pour que je puisse merger ? Merci !

2024-06-11 10:36 UTC, clallemand approved these changes
Merci @bfabre01 et @sylvainipp pour l'ajout des références !
J'ai fait quelques suggestions de corrections / ajouts : 
- Des liens qui pointaient vers des versions anciennes des textes
- L'ajout de quelques références du CGI 
- La mise à jour / ajout de quelques `last_value_still_valid_on`

Si cela vous paraît ok je veux bien que vous les ajoutiez avant de merger, mais je valide quand même comme ça je ne vous bloque plus !

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml
> +      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032701943/2016-06-13
```suggestion
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032701943
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml
> +      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032701943/2016-06-13
Idem, version ancienne de l'article comme lien

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/min.yaml
> +      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032701943/2016-06-13
```suggestion
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032701943
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/min.yaml
> +      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032701943/2016-06-13
idem le lien renvoit vers une version ancienne de l'article

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_ba/plafond_recettes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000048727447
```suggestion
    - title: Article 69, I. du Code général des impôts
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000028447731
    2024-01-01:
    - title: Loi n° 2023-1322 du 29 décembre 2023 de finances pour 2024, art. 94
      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000048727447
    - title: Article 69, I. du Code général des impôts
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000028447731
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/microentreprise/regime_micro_ba/plafond_recettes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000048727447
Il me semble que c'est bien dans l'article 69 du CGI qu'est défini ce paramètre. Si c'est bien cela je laisserai cette référence en plus de la référence de la modification

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/taxsal/abattement_special.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000049629765
```suggestion
    - title: Décret n° 2024-496 du 30/05/2024, art. 1
      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000049629765
    - title: Article 1679-A du CGI
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042160214
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/taxsal/taux_maj.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000049629765
```suggestion
    - title: Décret n° 2024-496 du 30/05/2024, art. 1
      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000049629765
    - title: Article 231 du CGI
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000047622885
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/taxation_indirecte/alcools_autres_boissons/boissons_sucrees_energisantes/boissons_edulcorees_y_compris_mayotte.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000049629765
```suggestion
    - title: Décret n° 2024-496 du 30/05/2024, art. 1
      href: https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000049629765
    - title: Article 1613 ter du CGI
      href: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000038686585
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpen/min.yaml
>    last_value_still_valid_on: "2023-07-05"
```suggestion
  last_value_still_valid_on: "2024-06-11"
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/max.yaml
>    last_value_still_valid_on: "2023-07-05"
```suggestion
  last_value_still_valid_on: "2024-06-11"
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/deductions/abatpro/min.yaml
>    last_value_still_valid_on: "2023-07-05"
```suggestion
  last_value_still_valid_on: "2024-06-11"
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/impot_revenu/calcul_revenus_imposables/rpns/micro/plafond_imputation_deficits_agricoles_sur_revenu_global.yaml
>    ipp_csv_id: plaf_defba
```suggestion
  last_value_still_valid_on: "2024-06-11"
  ipp_csv_id: plaf_defba
```

2024-06-11 10:36 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/autres_taxes_participations_assises_salaires/taxsal/abattement_special.yaml
>    unit: currency
```suggestion
  last_value_still_valid_on: "2024-06-11"
  unit: currency
```

2024-06-11 16:55 UTC, merged