Revalorisations APL étudiants
openfisca/openfisca-france pull request #2287
Opened 2024-04-25 14:22 UTC by benoit-cty

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/10/2023.
* Zones impactées : `prestations_sociales.aides_logement.allocations_logement.al_etudiant`.
* Détails :
  - Mise à jour des équivalences de loyer
- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2024-04-29 16:39 UTC, JoDuGa requested changes

2024-04-30 06:45 UTC, benoit-cty commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/autres_etudiants_en_chambres_rehabilitees_de_ru/menages.yaml
> +  2023-09-28:
Merci beaucoup @JoDuGa, j'ai changé les dates des valeurs ainsi que celles des références législatives.

2024-05-03 12:37 UTC, benoit-cty commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/autres_etudiants_en_chambres_rehabilitees_de_ru/personnes_isolees.yaml
> +  2023-09-28:
Merci beaucoup @JoDuGa, j'ai changé les dates des valeurs ainsi que celles des références législatives.

2024-05-03 12:37 UTC, benoit-cty commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/loyer_considere_comme_paye_etudiants_logeant_en_ru/menages.yaml
> +  2023-09-28:
Merci beaucoup @JoDuGa, j'ai changé les dates des valeurs ainsi que celles des références législatives.

2024-05-03 12:37 UTC, benoit-cty commented on openfisca_france/parameters/prestations_sociales/aides_logement/allocations_logement/al_etudiant/loyer_considere_comme_paye_etudiants_logeant_en_ru/personnes_isolees.yaml
> +  2023-09-28:
Merci beaucoup @JoDuGa, j'ai changé les dates des valeurs ainsi que celles des références législatives.

2024-05-06 08:18 UTC, JoDuGa commented
J'ai marqué mes demandes comme résolues.

2024-05-06 12:51 UTC, benoit-cty commented
> J'ai marqué mes demandes comme résolues.

Merci beaucoup @JoDuGa , peux-tu approuver la PR car elle est en mode "1 review requesting changes by reviewers" ?

2024-05-06 12:53 UTC, JoDuGa approved these changes

2024-05-06 13:24 UTC, merged