Ajout de l'aide Pass colo pour les enfants né(e) en 2013
openfisca/openfisca-france pull request #2299
Opened 2024-05-07 14:29 UTC by jenovateurs

* Changement mineur.
* Périodes concernées : à partir du 2024-01-01.
* Zones impactées : `prestations_sociales.education.pass_colo`.
* Détails :
  - Ajout de l'aide pass colo à destination des enfants né(e) en 2013 souhaitant aller en colonie de vacances

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2024-05-08 17:21 UTC, Shamzic reviewed
Sur Légifrance on peut lire :

> Si le mineur n'a pas bénéficié de l'aide pendant l'année au cours de laquelle il a atteint l'âge de onze ans, cette aide peut être mobilisée au cours de l'année durant laquelle il atteint ses douze ans selon les mêmes modalités.

Ce qui me laisse penser qu'il faudrait modéliser l'éligibilité plutôt sur l'âge des enfants (11 et 12 ans?) que sur leur année de naissance

2024-05-08 19:31 UTC, jenovateurs commented
> Sur Légifrance on peut lire :
> 
> > Si le mineur n'a pas bénéficié de l'aide pendant l'année au cours de laquelle il a atteint l'âge de onze ans, cette aide peut être mobilisée au cours de l'année durant laquelle il atteint ses douze ans selon les mêmes modalités.
> 
> Ce qui me laisse penser qu'il faudrait modéliser l'éligibilité plutôt sur l'âge des enfants (11 et 12 ans?) que sur leur année de naissance

Je me questionne sur cette citation, si j'ai un enfant qui a eu 12 ans en Janvier, il n'a pas pu bénéficier de l'aide car elle n'existait pas au moment de ses 11 ans. Peut-il donc y avoir droit ? Ou c'est plutôt pour l'année prochaine et donc on reste sur des enfants dont l'année de naissance est 2013.

De mon côté, j'ai aussi regardé le simulateur du site [jeune.gouv](https://www.jeunes.gouv.fr/evaluez-le-montant-de-votre-pass-colo-2067) pour lequel on peut lire : 
> Enfants bénéficiaires : Nés entre le 1er janvier 2013 et le 31 décembre 2013

J'ai pu tester le simulateur avec comme date de naissance le 01/01/2012 ainsi que 01/06/2012 et le résultat est négatif : 
<img width="831" alt="Screenshot 2024-05-08 at 21 24 58" src="https://github.com/openfisca/openfisca-france/assets/3491729/924a945f-7d13-4b96-bf0f-66f8191869ca">

Doit-on être cohérent avec l'autre simulateur existant d'un site du Ministère de l'éducation nationale et de la jeunesse ou du décret Légifrance ?

2024-05-09 09:05 UTC, yasmine-glitch commented
Je pense qu'il faut suivre Légifrance et proposer l'aide aux parents dont l'enfant est né en 2013 ou en 2012.

2024-05-13 14:34 UTC, yasmine-glitch commented
Suite à une discussion avec jeunes.gouv nous avons obtenu des précisions :
"Pour cette année, ce sont les enfants nés en 2013.
L'an prochain, ce seront les enfants nés en 2014 et ceux nés en 2013 qui n'ont pas sollicité leur pass en 2024."
Cette PR est donc juste sur le fond.

2024-05-13 14:37 UTC, jenovateurs commented
> Suite à une discussion avec jeunes.gouv nous avons obtenu des précisions : "Pour cette année, ce sont les enfants nés en 2013. L'an prochain, ce seront les enfants nés en 2014 et ceux nés en 2013 qui n'ont pas sollicité leur pass en 2024." Cette PR est donc juste sur le fond.

Merci pour ton retour @yasmine-glitch .
@Shamzic , je replace donc la PR en état de review.

2024-06-11 13:02 UTC, Shamzic commented
Même si les ajouts semble cohérents et sans remettre en cause l'explication de jeunes.gouv, le texte de Légifrance reste assez explicite dans l'article 2 car il est bien question d'âge et non pas d'année de naissance => cela permet de reconduire l'aide plus facilement sur les années suivantes, c'est plus facilement maintenable

2024-06-11 13:04 UTC, Shamzic requested changes
Même si les ajouts semble cohérents et sans remettre en cause l'explication de jeunes.gouv, le texte de Légifrance reste assez explicite dans l'article 2 car il est bien question d'âge et non pas d'année de naissance => cela permet de reconduire l'aide plus facilement sur les années suivantes, c'est ainsi plus facilement maintenable.

2024-06-13 10:21 UTC, Shamzic approved these changes

2024-06-13 12:35 UTC, merged