Rattrapage de l'historique de prestations_sociales.aides_logement.logement_social.plu.par_categorie_de_menage
openfisca/openfisca-france pull request #2308
Opened 2024-05-23 16:28 UTC by benoit-cty

Sous-partie de https://github.com/openfisca/openfisca-france/pull/2297

2024-05-23 16:59 UTC, benjello commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +  2020-01-02:
Valeur bizarre ...

2024-05-24 09:50 UTC, benoit-cty commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +  2020-01-02:
Bien vu, c'est parceque j'utilise la description pour faire la recherche et ici elle est erronée :` description: Catégorie 1 `alors que l'on est dans le fichier `categorie_5` !

2024-05-30 12:48 UTC, clallemand requested changes
Je n'ai pas fini la PR, je la finis dans l'après midi

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_1/autres_regions.yaml
> +    value: 20870
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_1/autres_regions.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_1/ile_de_france.yaml
> +    value: 24006
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_1/ile_de_france.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
> +    value: 24006
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_1/paris_communes_limitrophes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_2/autres_regions.yaml
> +    value: 27870
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_2/autres_regions.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 12:48 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +    value: 22642
```suggestion
    value:  51641
```

2024-05-30 13:54 UTC, clallemand requested changes
@benoit-cty je suis remontée jusque 2012 pour le moment. Je n'ai pas non plus relue les paramètres en doublon pour lesquels j'avais fait la revue dans la #2297

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_4/ile_de_france.yaml
>      value: 518897
```suggestion
    value: 51897
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +    value: 26300
```suggestion
    value: 47818
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_personne_supplementaire/paris_communes_limitrophes.yaml
> +    value: 8377
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_personne_supplementaire/paris_communes_limitrophes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_personne_supplementaire/ile_de_france.yaml
> +    value: 7668
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_personne_supplementaire/ile_de_france.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_personne_supplementaire/autres_regions.yaml
>    2021-01-01:
```suggestion
  2021-01-01:
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_personne_supplementaire/autres_regions.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_6/paris_communes_limitrophes.yaml
> +    value: 75177
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_6/paris_communes_limitrophes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_6/ile_de_france.yaml
> +    value: 68817
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_6/ile_de_france.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_6/autres_regions.yaml
> +    value: 53644
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_6/autres_regions.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/paris_communes_limitrophes.yaml
> +    value: 66809
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/paris_communes_limitrophes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/ile_de_france.yaml
> +    value: 61154
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/ile_de_france.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +    value: 47599
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_4/paris_communes_limitrophes.yaml
> +    value: 56152
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_4/paris_communes_limitrophes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_4/ile_de_france.yaml
> +    value: 51659
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_4/ile_de_france.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_4/autres_regions.yaml
> +    value: 40462
```suggestion
  2020-01-02:
    value: 40462
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_4/autres_regions.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_3/paris_communes_limitrophes.yaml
> +    value: 47031
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_3/paris_communes_limitrophes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_3/ile_de_france.yaml
> +    value: 43127
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_3/ile_de_france.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_3/autres_regions.yaml
> +    value: 33516
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_3/autres_regions.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_2/paris_communes_limitrophes.yaml
> +    value: 35877
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_2/paris_communes_limitrophes.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_2/ile_de_france.yaml
> +    value: 35877
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_2/ile_de_france.yaml
> +      href: https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000039728497
```suggestion
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +    value: 25870
```suggestion
    value: 47035
```

2024-05-30 13:54 UTC, clallemand commented on openfisca_france/parameters/prestations_sociales/aides_logement/logement_social/plu/par_categorie_de_menage/categorie_5/autres_regions.yaml
> +    value: 25470
```suggestion
    value: 46308
```

2024-06-04 13:36 UTC, clallemand approved these changes

2024-06-04 14:26 UTC, merged