Pour les aides RSA et PPA passage à la period M-2 M-4
openfisca/openfisca-france pull request #2337
Opened 2024-07-31 12:42 UTC by Martin-Billard-iMSA

Prise en compte du passe M-1 M-3 à M-2 à M-4 pour les aides PPA et RSA

Modification des règles de calcul pour le RSA et PPA
Périodes concernées : Après 2024/10/01.
Zones impactées : openfisca_france/model/prestations/minima_sociaux/ppa.py.
openfisca_france/model/prestations/minima_sociaux/rsa.py.
Détails :
Selon ces articles: (pas encore sorti)

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

Corrigent ou améliorent un calcul déjà existant.
- - - -

Quelques conseils à prendre en compte :

- [x ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x ] Documentez votre contribution avec des références législatives.
- [x ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [x ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [x ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2024-08-27 08:28 UTC, humbleCraftman requested changes

2024-08-27 14:36 UTC, Martin-Billard-iMSA commented on CHANGELOG.md
> +
Par rapport à master j'ai mis 168.0.14

2024-08-28 08:14 UTC, sylvainipp approved these changes
Merci pour la modification !

2024-09-09 11:56 UTC, humbleCraftman approved these changes

2024-09-16 08:13 UTC, merged