Nettoie CSG
openfisca/openfisca-france pull request #2342
Opened 2024-08-05 13:56 UTC by benjello

* Changement mineur.
* Périodes concernées : toutes.
* Zones impactées : `parameters/prelevemenst_sociaux`.
* Détails :
  - Nettoyage des notes et documentation doublonnées.

2024-08-06 06:40 UTC, clallemand requested changes
@benjello il y quelques jours nous avons fait une PR de nettoyage de la csg/crds dans laquelle nous avons enlevé des doublons et inifier et complété les index. Ta PR annulent certaines de ces modifications. Je pense que c'est plutôt du côté des barèmes qu'il faut faire les modifs.

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/deductible/index.yaml
> +  - abattement
```suggestion
```

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/deductible/index.yaml
> +  - abattement
@benjello j'ai remonté les paramètres d'abattement de la csg dans une PR récente car ils étaient en doublon par rapport à la loi. Le paramètre abattement n'est plus dans ce dossier du coup. Il faut supprimer côté barèmes ipp

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/index.yaml
> +  - abattement
```suggestion
```

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/imposable/index.yaml
> +  - abattement
Comme au dessus

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  - deductible
Idem ici @benjello nous avons changé l'index avec les nouvelles modifications. Il faut garder les lignes que tu as supprimé

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/allocations_chomage/deductible/index.yaml
> +  - taux_reduit
Idem si tu pouvais laisser l'ordre que l'on a changé. On a fait en sorte d'unifier l'ordre entre les sous noeuds de la csg / crds pour notre affichage.

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/deductible/index.yaml
> -  - taux_plein
Pareil si tu pouvais laisser l'ordre existant

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/index.yaml
> +  - taux_reduit
Idem garder l'ordre et les items existants

2024-08-06 06:40 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/index.yaml
> -  - imposable
Idem à garder

2024-08-06 07:00 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/deductible/index.yaml
> +  - abattement
Oui j'ai vu. Je voulais d'abord nettoyer les docs, mais il y a eu des ratés.

2024-08-06 07:04 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  - deductible
La CSG imposable n'existe pas dans la loi. Elle est le résultat de la CSG totale et de la déductible. C'est pour cela que je la vire des index pour qu'elle ne s'affiche pas.

2024-08-06 07:05 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/allocations_chomage/deductible/index.yaml
> +  - taux_reduit
Je pense qu'il vaut mieux mettre le taux plein qui est la situation générique et mettre les taux réduit et médian ensuite. Est-ce que cela pose un problème pour vous ?

2024-08-06 07:05 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/deductible/index.yaml
> -  - taux_plein
Je pense qu'il vaut mieux mettre le taux plein qui est la situation générique et mettre les taux réduit et médian ensuite. Est-ce que cela pose un problème pour vous ?

2024-08-06 07:05 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/index.yaml
> +  - taux_reduit
Je pense qu'il vaut mieux mettre le taux plein qui est la situation générique et mettre les taux réduit et médian ensuite. Est-ce que cela pose un problème pour vous ?

2024-08-06 07:06 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  - deductible
Oui je sais qu'elle n'existe pas mais nous on veut l'afficher tant qu'on n'a pas corrigé openfisca france

2024-08-06 07:06 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/index.yaml
> -  - imposable
Imposable n'est pas dans la loi. Je laisse les paramètres, mais je ne veux pas les afficher.

2024-08-06 07:06 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  - deductible
et en plus je pense que dans ce cas tu veux afficher l'abattement sur les revenus d'activité qui existe lui

2024-08-06 07:07 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/index.yaml
> +  - taux_reduit
Non tant que l'ordre est le même partout

2024-08-06 07:09 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  - deductible
Donc l'objectif est bien de virer imposable à terme ?

2024-08-06 07:11 UTC, benjello commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/remplacement/pensions_retraite_invalidite/imposable/index.yaml
> +  - taux_reduit
Ok je le change partout alors.

2024-08-06 07:14 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  - deductible
Oui mais ça demande pas mal de changements donc je ne sais pas quand on va le faire. Mais je demande si on a vraiment besoin des index pour nous affichage, ce n'est pas certain.

2024-08-06 07:26 UTC, clallemand commented on openfisca_france/parameters/prelevements_sociaux/contributions_sociales/csg/activite/index.yaml
> +  - deductible
@benjello tu peux supprimer `imposable` des index sans problème pour nous ! Mais attention à `abattement` dans ce cas-ci

2024-08-07 07:49 UTC, clallemand approved these changes

2024-08-07 09:08 UTC, merged

2024-12-10 10:56 UTC, sandcha commented
ℹ️ L'`abattement` de CSG retiré de l'index par cette PR résulte de la suppression du paramètre par la PR https://github.com/openfisca/openfisca-france/pull/2331.