Ajoute taux indémnité compensatrice
openfisca/openfisca-france pull request #2344
Opened 2024-08-12 10:13 UTC by DorineLam

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2024-08-13 12:05 UTC, clallemand requested changes

2024-08-13 13:35 UTC, DorineLam commented on openfisca_france/parameters/prelevements_sociaux/reductions_cotisations_sociales/exonerations_geographiques_cotis/zrr/plafond_exoneration_integrale_part_remuneration.yaml
> +  2009-01-01:
Oui bien vu. J'ai préféré garder plusieurs dates, je ne sais pas si ça se fait mais ça nous permet de retrouver les références

2024-08-13 14:15 UTC, DorineLam commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
> +        seuil_max = 2.4 if period.start.year < 2009 else seuils.plafond_part_remuneration
Pris en compte avant 2008

2024-08-13 14:18 UTC, DorineLam commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
> +        taux_max = .281 if period.start.year < 2015 else .2655 if period.start.year < 2019 else (t_max_parameters.cotisations_securite_sociale_regime_general.mmid.employeur.maladie.rates[0] - t_max_p
J'ai changé la syntaxe mais par contre j'ai laissé les taxu avant, car je me dis que sinon faut vraiment qu'on vérifie toutes les cotis prises en compte. À voir ensemble si tu penses qu'on peut aller plus loin.

2024-08-13 14:27 UTC, DorineLam commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
> +        seuil_min = 1.4 if period.start.year < 2009 else seuils.plafond_exoneration_integrale_part_remuneration
Oui ! Merci, tu as raison ce sera bien plus simple !

2024-08-13 14:35 UTC, DorineLam commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
> +    def formula_2011_01_01(individu, period, parameters):
Fait :)

2024-08-13 15:11 UTC, DorineLam commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
> +        taux_max = .281 if period.start.year < 2019 else (t_max_parameters.cotisations_securite_sociale_regime_general.mmid.employeur.maladie.rates[0] - t_max_parameters.reductions_cotisations_social
Je viens de réessayer et du coup j'ai compris pourquoi j'avais laissé cette info : le paramètre `reductions_cotisations_sociales.alleg_gen.mmid.taux` n'a pas de valeur avant 2019. Et donc le système socio-fiscal de 2012 plante.
L'allègement général vient en remplacement du cice. Mais cela va prendre beaucoup de temps de tout revérifier.

2024-08-14 11:41 UTC, clallemand commented on openfisca_france/model/prelevements_obligatoires/prelevements_sociaux/cotisations_sociales/exonerations.py
> +        taux_max = .281 if period.start.year < 2019 else (t_max_parameters.cotisations_securite_sociale_regime_general.mmid.employeur.maladie.rates[0] - t_max_parameters.reductions_cotisations_social
ok ça me va

2024-08-14 11:41 UTC, clallemand approved these changes

2024-08-14 12:56 UTC, merged