application des abattements pour le calcul de la CSS
openfisca/openfisca-france pull request #2361
Opened 2024-10-02 16:09 UTC by humbleCraftman

Fiabilisation du calcul des ressources pour l'éligibilité a la CSS par application des abattements prévus dans les circulaires ministérielles suivantes:
 - https://sante.gouv.fr/fichiers/bo/2021/2021.6.sante.pdf#page=75
 - https://sante.gouv.fr/fichiers/bo/2023/2023.24.sante.pdf#page=82

Évolution du système socio-fiscal.

Périodes concernées : à partir du 01/04/2021.

Zones impactées :
 - openfisca_france/model/prestations/minima_sociaux/cs/ressources.py.
 - openfisca_france/parameters/prestations_sociales/solidarite_insertion/minima_sociaux/cs/css/

Détails :
Afin que les revalorisations exceptionnelles de l’allocation aux adultes handicapés (AAH), de l’allocation de solidarité aux personnes âgées (ASPA), de l’allocation supplémentaire vieillesse (ASV) et de l’allocation supplémentaire d’invalidité (ASI) ne conduisent à rendre inéligibles certains de leurs allocataires à la complémentaire santé solidaire (C2S), l’article 40 de la loi de financement de la sécurité sociale pour 2018 a introduit un abattement sur le montant de ces allocations pris en compte dans l’éligibilité à la CSS.
La présente PR prend en compte ces abattements dans le calcul des ressources pour l'éligibilité à la CSS

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [x] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france/blob/master/setup.py).
- [x] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2024-10-02 16:35 UTC, benjello commented on CHANGELOG.md
> +* Zones impactées :
```suggestion
* Zones impactées :
```

2024-10-02 16:35 UTC, benjello commented on CHANGELOG.md
> +* Amélioration technique.
```suggestion
* Amélioration technique.
```

2024-10-02 16:35 UTC, benjello commented on CHANGELOG.md
> +* Amélioration technique.
```suggestion
* Amélioration technique.
```

2024-10-02 16:36 UTC, benjello commented on CHANGELOG.md
> +* Zones impactées :
```suggestion
* Zones impactées :
```

2024-10-02 16:48 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        return 0
Utiliser  `individu.empty_array()` plutôt que 0

2024-10-02 16:49 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +            [aspa > 0 and aspa_couple, aspa > 0],
```suggestion
            [(aspa > 0) * aspa_couple, aspa > 0],
```

2024-10-02 16:51 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        adulte_ayant_asi = where(and_(
Utiliser des vecteurs booléens et `*` pour AND

2024-10-02 16:52 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +            [aah > 0, appliquer_abattement_couple and adulte_ayant_asi, adulte_ayant_asi],
```suggestion
            [aah > 0, appliquer_abattement_couple * adulte_ayant_asi, adulte_ayant_asi],
```

2024-10-02 16:54 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        appliquer_abattement_couple = sum_(adulte_ayant_asi) > 1
Sur quelle entité faut-il sommer ? Là, on risque de sommer sur toutes la population si on a des données qui ne se réduisent pas à un cas type.

2024-10-02 16:55 UTC, benjello requested changes
J'ai mis pas mal de suggestions et une remarque assez importante.

2024-10-03 12:15 UTC, humbleCraftman commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        appliquer_abattement_couple = sum_(adulte_ayant_asi) > 1
@benjello @sylvainipp en réfléchissant sur ce commentaire je me suis posé la question de savoir si la variable "asi" est vraiment une variable "Individu". Ne devrait t-elle pas être une variable "famille" comme l'aspa ?  En effet, elle dépend comme l'aspa de la composition et des ressources des autres membres (conjoint en l'occurrence) du foyer.
Merci de me donner votre avis car je connais pas très bien openFisca je débute

2024-10-03 12:40 UTC, humbleCraftman commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        appliquer_abattement_couple = sum_(adulte_ayant_asi) > 1
en regardant les définitions de l'ASI et de l'ASPA je me dis qu'elles se ressemblent beaucoup quand même. Elles dépendent toutes deux du fait d'être en couple ou pas:
- ASI: https://www.service-public.fr/particuliers/vosdroits/F16940
- ASPA: https://www.service-public.fr/particuliers/vosdroits/F16871

2024-10-03 13:38 UTC, benjello commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        appliquer_abattement_couple = sum_(adulte_ayant_asi) > 1
Je ne connais pas (ou ne me souviens pas) des raisons ayant présidé à ce choix. Mais l'idée n'est pas que le choix de l'entité soit lié aux ressources que l'on considère, mais à qui elle est versée et si elle peut être considérée comme une prestation collective ou individuelle.

2024-10-03 14:31 UTC, sandcha commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        appliquer_abattement_couple = sum_(adulte_ayant_asi) > 1
Il semble que l'ASI soit passée de l'entité Famille à l'Individu à la version 25.0.0 d'openfisca-france : https://github.com/openfisca/openfisca-france/pull/1156
cc @guillett @Morendil au cas où vous auriez encore la mémoire de ce choix

> La question des performances a aussi été discutée dans une PR référencée sur la précédente : https://github.com/openfisca/openfisca-france/pull/991

2024-10-04 12:03 UTC, Morendil commented on openfisca_france/model/prestations/minima_sociaux/cs/ressources.py
> +        appliquer_abattement_couple = sum_(adulte_ayant_asi) > 1
C'est loin: je ne me souviens plus du raisonnement… de ce que je peux comprendre en lisant les commits de #1156 c'était une amélioration de modélisation par rapport à la version précédente (cf. le commentaire `TODO: Faute de mieux, on verse l'asi à la famille plutôt qu'aux individus`), effectivement l'ASI semble bien être une prestation individuelle.

2024-10-30 15:29 UTC, sylvainipp approved these changes
Merci de ces ajouts ! Tout me semble bon

2024-10-31 09:03 UTC, humbleCraftman commented
> Merci de ces ajouts ! Tout me semble bon

Ok super ! @benjello manque juste la validation de tes changes requested

2024-10-31 10:40 UTC, benjello approved these changes

2024-10-31 14:44 UTC, merged