Impôt sur le revenu : ajoute le paramètre couple manquant pour l'abattement d'assurance-vie
openfisca/openfisca-france pull request #2377
Opened 2024-10-24 16:45 UTC by DorineLam

Merci de contribuer à OpenFisca ! Effacez cette ligne ainsi que, pour chaque ligne ci-dessous, les cas ne correspondant pas à votre contribution :)

* Évolution du système socio-fiscal. | Amélioration technique. | Correction d'un crash. | Changement mineur.
* Périodes concernées : toutes. | jusqu'au JJ/MM/AAAA. | à partir du JJ/MM/AAAA.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :

- Modifient l'API publique d'OpenFisca France (par exemple renommage ou suppression de variables).
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.
- Modifient des éléments non fonctionnels de ce dépôt (par exemple modification du README).

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`pyproject.toml`](https://github.com/openfisca/openfisca-france/blob/master/pyproject.toml).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2024-11-04 16:52 UTC, dusylvain approved these changes
Merci pour la clarification ! Je crois que le numéro de version ne fonctionne pas, mais le reste me semble bon !

2024-11-04 16:52 UTC, dusylvain commented on pyproject.toml
> +version = "169.4.1"
```suggestion
version = "169.4.0"
``` ou 169.3.2, j'ai l'impression qu'il n'y a pas encore de 169.4.0 si je ne m'abuse. Idem dans le Changelog.

2024-11-05 08:45 UTC, DorineLam commented
> Merci pour la clarification ! Je crois que le numéro de version ne fonctionne pas, mais le reste me semble bon !

J'ai modifié, peux-tu approuver la PR si c'est bon pour toi ? :)

2024-11-05 08:49 UTC, sylvainipp approved these changes
Merci !

2024-11-05 09:09 UTC, benjello commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        P = parameters(period).impot_revenu.calcul_revenus_imposables.rvcm
L'usage du `P` majuscule est à proscrire. C'est un reste d'un vieux code.
L'idéal est de remplacer par parameters et/ou de faire des sous-branches de paramètres.

La ligne du dessus faisait le taf.
On peut la remplacer par `parameters_rvcm` pour être plus explicite.

2024-11-05 09:10 UTC, benjello requested changes
Retirer les `P` voir commentaire.

2024-11-06 07:51 UTC, DorineLam commented on openfisca_france/model/prelevements_obligatoires/impot_revenu/ir.py
> +        P = parameters(period).impot_revenu.calcul_revenus_imposables.rvcm
Merci @benjello c'est pris en compte :)

2024-11-06 07:52 UTC, DorineLam commented
@benjello j'ai modifié les P par parameters_rvcm, si ça te convient je veux bien que tu approuves pour que je puisse merger :)

2024-11-06 08:03 UTC, benjello approved these changes

2024-11-06 08:28 UTC, merged

2024-11-06 14:53 UTC, sandcha commented
Cette PR fait suite au fix de CI conda (#2381) et on peut voir que [la publication de la librairie 169.4.0 a bien eu lieu](https://anaconda.org/openfisca/openfisca-france/files?version=169.4.0) sur le channel `openfisca` de conda.