Ajoute l'aide à l'alimentation pour les étudiants éloignés
openfisca/openfisca-france pull request #2395
Opened 2024-11-29 12:25 UTC by Shamzic

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/02/2025.
* Zones impactées:
    - `model/prestations/aide_alimentation_etudiants_eloignes.py`
    - `model/base/localisation.py`
    - `parameters/prestations_sociales/aide_alimentation_etudiants_eloignes/`
* Détails :
  - Ajoute l'aide financière pour les étudiants éloignés des restaurants universitaires

- - - -

Ces changements :
- Ajoutent une fonctionnalité (par exemple ajout d'une variable).
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [x] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`pyproject.toml`](https://github.com/openfisca/openfisca-france/blob/master/pyproject.toml).
- [x] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2024-11-29 21:48 UTC, jenovateurs requested changes
Merci pour l'ajout @Shamzic.
Tout est bon pour moi et testé avec AJ sans bug apparent à l'usage.
Juste une vérification sur la grille des montants.

2024-11-29 21:48 UTC, jenovateurs commented on openfisca_france/parameters/prestations_sociales/aide_alimentation_etudiants_eloignes/montant_etudiant_drom_non_boursier.yaml
> +    value: 30
Je n'ai pas trouvé la source pour les montants, même en lisant la page legifrance.

2024-11-29 22:50 UTC, benjello commented on openfisca_france/model/prestations/aide_alimentation_etudiants_eloignes.py
> +        P = parameters(period).prestations_sociales.aide_alimentation_etudiants_eloignes
L'usage des majuscules est à proscrire (même s'il en reste dans le code ...)

2024-11-29 22:53 UTC, benjello commented on openfisca_france/model/prestations/aide_alimentation_etudiants_eloignes.py
> +            resident_drom & boursier,
Il faut suivre les règles de calcul vectoriel énoncées [dans la doc](https://openfisca.org/doc/coding-the-legislation/25_vectorial_computing.html#boolean-operations)

2024-11-29 22:57 UTC, benjello commented on openfisca_france/model/base/localisation.py
> +class localisation_DROM_aide_alimentation_etudiants_eloignes(Variable):
Il existe déjà une variable residence_dom.

2024-11-29 23:14 UTC, benjello commented
Et il y a des problèmes avec les paramètres : https://control-center.tax-benefit.org/parameters/56585/github.com/openfisca/openfisca-france/aide-alimentation-etudiants-eloignes/raw_unprocessed_parameters/errors

2024-12-02 09:12 UTC, Shamzic commented
> Merci pour l'ajout @Shamzic. Tout est bon pour moi et testé avec AJ sans bug apparent à l'usage. Juste une vérification sur la grille des montants.

Les montants sont dans le lien mentionné en références

2024-12-02 09:14 UTC, Shamzic commented
> Merci pour l'ajout @Shamzic. Tout est bon pour moi et testé avec AJ sans bug apparent à l'usage. Juste une vérification sur la grille des montants.

Les montants sont dans le lien mentionné en références dans le 2e lien, article 1.

2024-12-02 14:11 UTC, Shamzic commented on openfisca_france/model/base/localisation.py
> +class localisation_DROM_aide_alimentation_etudiants_eloignes(Variable):
Bien vu, je ne l'avais pas remarquée. Elle utilise, en partie, l'ancienne appellation `DOM-TOM`, on pourrait refacto `residence_dom `=> `residence_drom`.

2024-12-02 14:37 UTC, Shamzic commented
@benjello Merci pour tous ces retours. Je n'avais pas connaissance de l'outil Tax-benefit Control System. L'erreur qui persiste semble lié à des modification précédentes : https://control-center.tax-benefit.org/tasks/56634

2024-12-02 15:33 UTC, benjello commented on openfisca_france/model/base/localisation.py
> +class localisation_DROM_aide_alimentation_etudiants_eloignes(Variable):
Tou à fait. Mais il faudra alors un changement de version majeure.

2024-12-02 15:35 UTC, benjello commented
> @benjello Merci pour tous ces retours. Je n'avais pas connaissance de l'outil Tax-benefit Control System. L'erreur qui persiste semble liée à des modifications précédentes : https://control-center.tax-benefit.org/tasks/56634

@openfisca/france-contrib-leximpact est-ce que cela vient de vous ?

2024-12-02 17:02 UTC, eraviart commented
> @openfisca/france-contrib-leximpact est-ce que cela vient de vous ?

Oui ça été développé initialement pour les besoins de LexImpact.

2024-12-02 17:30 UTC, benjello approved these changes

2024-12-03 10:31 UTC, Shamzic commented
@jenovateurs Est-ce que c'est bon pour toi ?

2024-12-03 11:00 UTC, jenovateurs approved these changes
Tout est bon pour moi @Shamzic

2024-12-03 14:02 UTC, Shamzic commented
J'ai du rebase à cause de l'upgrade du numéro de version entre temps.

2024-12-03 14:09 UTC, merged