Ajout du Bail Réel Solidaire
openfisca/openfisca-france pull request #2404
Opened 2024-12-19 19:05 UTC by Shamzic

* Évolution du système socio-fiscal.
* Périodes concernées : à partir du 01/07/2024.
* Zones impactées : 
  - `openfisca_france/parameters/prestations_sociales/bail_reel_solidaire/plafonds_par_zones`
  - `openfisca_france/model/prestations/bail_reel_solidaire.py`
  - `tests/formulas/bail_reel_solidaire.yaml`
* Détails :
  - Ajout du dispositif Bail Réel Solidaire
  - Ajout des plafonds de ressources selon la zone et le nombre de personnes du foyer
  - Ajout du fichier csv de zones pour le BRS

- - - -

Ces changements :

- Ajoutent une fonctionnalité (ajout d'une variable).

- - - -

Quelques conseils à prendre en compte :

- [x] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france/blob/master/CONTRIBUTING.md).
- [x] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france/pulls).
- [x] Documentez votre contribution avec des références législatives.
- [x] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [x] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`pyproject.toml`](https://github.com/openfisca/openfisca-france/blob/master/pyproject.toml).
- [x] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france/blob/master/CHANGELOG.md).
- [x] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2024-12-30 14:46 UTC, Shamzic commented
Après des recherches infructueuses, je n'arrive pas à trouver les plafonds sur Légifreance, je suis donc contraint de conserver la source de service-public.fr ...

2025-01-06 16:17 UTC, jenovateurs requested changes
Quelques petites questions, sinon tout me paraît plutôt correcte.

2025-01-06 16:17 UTC, jenovateurs commented on openfisca_france/model/prestations/bail_reel_solidaire.py
> +        rfr = menage.sum(menage.members.foyer_fiscal('rfr', period.n_2), role = FoyerFiscal.DECLARANT_PRINCIPAL)[0]
Pareil sais-tu pourquoi il y a plusieurs valeurs ?

2025-01-06 17:24 UTC, Shamzic commented on openfisca_france/model/prestations/bail_reel_solidaire.py
> +        nb_personnes = menage.nb_persons()[0]
Parce que `menage.nb_persons()` renvoie un tableau qui contient le nombre de personnes du ménage dans un entier sur le premier élément du tableau

2025-01-06 18:04 UTC, benjello commented on openfisca_france/model/prestations/bail_reel_solidaire.py
> +    with open(ZONAGE_ABC, 'r', encoding='latin1') as csvfile:
C'est normal d'avoir un tableau. 
Je rappelle que l'on travaille sur des vecteurs : https://openfisca.org/doc/coding-the-legislation/25_vectorial_computing.html

2025-01-06 18:04 UTC, benjello commented on openfisca_france/model/prestations/bail_reel_solidaire.py
> +        rfr = menage.sum(menage.members.foyer_fiscal('rfr', period.n_2), role = FoyerFiscal.DECLARANT_PRINCIPAL)[0]
C'est normal d'avoir un tableau. 
Je rappelle que l'on travaille sur des vecteurs : https://openfisca.org/doc/coding-the-legislation/25_vectorial_computing.html

2025-01-06 18:15 UTC, Shamzic commented on openfisca_france/model/prestations/bail_reel_solidaire.py
> +    with open(ZONAGE_ABC, 'r', encoding='latin1') as csvfile:
J'ai testé de convertir le fichier en encodage utf-8, j'ai modifié le code en conséquence et ajouté un print du type sur `depcom[0]` mais ça m'affiche `Type de depcom[0]: <class 'numpy.bytes_'>, valeur: b'01401'` donc ça me semble compliqué de se passer d'un decode ici. 

Tu avais une idée plus précise en tête ?

2025-01-07 14:06 UTC, jenovateurs commented on openfisca_france/model/prestations/bail_reel_solidaire.py
> +    with open(ZONAGE_ABC, 'r', encoding='latin1') as csvfile:
Pas d'autres idées en tête. Donc pas de soucis.

2025-01-07 14:06 UTC, jenovateurs approved these changes
Tout me semble donc bon.

2025-01-13 09:44 UTC, jenovateurs reviewed
Petite suggestion.

2025-01-13 13:11 UTC, Shamzic commented on openfisca_france/model/prestations/bail_reel_solidaire.py
> +NB_PERSONNES_MAX = 6
C'est pertinent, j'ai fait un refacto en conséquence!

2025-02-03 09:39 UTC, jenovateurs approved these changes
LGTM :-)

2025-02-04 11:31 UTC, jenovateurs approved these changes
Tout me semble bon :-). Merci @Shamzic

2025-02-04 12:52 UTC, merged